AccelerometerControl.h File Reference
Controls the accelerometer driver.
Functions
void AccControl_Init (void)
void AccControl_SetConfig (uint8_t value)
void AccControl_ReadAcc (void)
Detailed Description
Controls the accelerometer driver. Project 1814 IOLab Remote Sensor Application
Description Controls the accelerometer driver and controls the configuration for it.
Definition in file AccelerometerControl.h.
Function Documentation
void AccControl_Init (void)
Initializes the accelerometer controller.
Definition at line 58 of file AccelerometerControl.c.
Referenced by ConMan_Init().
void AccControl_ReadAcc (void)
Gets a reading from the accelerometer.
Definition at line 195 of file AccelerometerControl.c.
Referenced by _ProcessEvents_DEFAULT().
void AccControl_SetConfig (uint8_t keyValue)
Sets a configuration value to the accelerometer
Parameters
in keyValue - the key/value pair with the configuration information
Definition at line 71 of file AccelerometerControl.c.
Referenced by ConMan_SetSensorConfig().