AccelerometerControl.c File Reference
Controls the accelerometer driver.
#include <ProjectTypes.h>
*
#include `AccelerometerControl.h`
*
#include <Accelerometer.h>
*
#include <EventQueue.h>
*
#include <DataBuffer.h>
*
#include <SensorId.h>
*
#include <KeyValue.h>
*
#include <Assert.h>
*
#include <Serial.h>
*
#include <Debug.h>
*
Macros
#define MAX_DATA_BYTES (6u)
Functions
static void _AccDataReadyIsr (void)
void AccControl_Init (void)
void AccControl_SetConfig (uint8_t keyValue)
void AccControl_ReadAcc (void)
Variables
static bool _initialized = false
static AccConfig_t _accConfig
Detailed Description
Controls the accelerometer driver. Project 1814 IOLab Remote Sensor Application
Description Controls the accelerometer driver and controls the configuration for it.
Definition in file AccelerometerControl.c.
Function Documentation
static void _AccDataReadyIsr (void) [static]
The data ready ISR handles the accelerometer data ready interrupt and will add an event to the event queue to notify the system to read the accelerometer.
Definition at line 229 of file AccelerometerControl.c.
Referenced by AccControl_Init().
void AccControl_Init (void)
Initializes the accelerometer controller.
Definition at line 58 of file AccelerometerControl.c.
Referenced by ConMan_Init().
void AccControl_ReadAcc (void)
Gets a reading from the accelerometer.
Definition at line 195 of file AccelerometerControl.c.
Referenced by _ProcessEvents_DEFAULT().
void AccControl_SetConfig (uint8_t keyValue)
Sets a configuration value to the accelerometer
Parameters
in keyValue - the key/value pair with the configuration information
Definition at line 71 of file AccelerometerControl.c.
Referenced by ConMan_SetSensorConfig().
Variable Documentation
AccConfig_t _accConfig [static]
Initial value:
=
{
        AccOdr_100,
        AccResolution_14bit,
        AccFullScaleRange_4g,
        AccOverSample_HighRes
}
Stores the settings for the accelerometer
Definition at line 45 of file AccelerometerControl.c.
bool _initialized = false [static]
tracks if the controller has been initialized
Definition at line 42 of file AccelerometerControl.c.