Accelerometer.c File Reference
Accelerometer sensor interface module.
#include <ProjectTypes.h>
*
#include `Accelerometer.h`
*
#include <Assert.h>
*
#include <Debug.h>
*
#include <Serial.h>
*
#include <I2c.h>
*
#include <Gpio.h>
*
#include <Board.h>
*
#include <Device.h>
*
Macros
#define WHO_AM_I ((uint8_t)0x1A)
#define ACC_PORT I2cPort_0
#define ACC_ADDRESS ((uint8_t)0x1C)
#define BYTES_PER_SAMPLE 6
Enumerations
enum AccReg_t {
*
AccReg_STATUS = 0x00,
*
AccReg_OUT_X_MSB = 0x01,
*
AccReg_OUT_X_LSB = 0x02,
*
AccReg_OUT_Y_MSB = 0x03,
*
AccReg_OUT_Y_LSB = 0x04,
*
AccReg_OUT_Z_MSB = 0x05,
*
AccReg_OUT_Z_LSB = 0x06,
*
AccReg_FIFO_SETUP = 0x09,
*
AccReg_TRIG_CONFIG = 0x0A,
*
AccReg_SYSMOD = 0x0B,
*
AccReg_INT_SOURCE_STAT = 0x0C,
*
AccReg_WHO_AM_I = 0x0D,
*
AccReg_XYZ_DATA_CONFIG = 0x0E,
*
AccReg_HP_FILTER_CUTOFF = 0x0F,
*
AccReg_PL_STATUS = 0x10,
*
AccReg_PL_CONFIG = 0x11,
*
AccReg_PL_COUNT = 0x12,
*
AccReg_PL_BF_ZCOMP = 0x13,
*
AccReg_PL_THS_REG = 0x14,
*
AccReg_FF_MT_CONFIG = 0x15,
*
AccReg_FF_MT_SOURCE = 0x16,
*
AccReg_FF_MT_THS = 0x17,
*
AccReg_FF_MT_COUNT = 0x18,
*
AccReg_TRANSIENT_CONFIG = 0x1D,
*
AccReg_TRANSIENT_SOURCE = 0x1E,
*
AccReg_TRANSIENT_THS = 0x1F,
*
AccReg_TRANSIENT_COUNT = 0x20,
*
AccReg_PULSE_CONFIG = 0x21,
*
AccReg_PULSE_SOURCE = 0x22,
*
AccReg_PULSE_THS_X = 0x23,
*
AccReg_PULSE_THS_Y = 0x24,
*
AccReg_PULSE_THS_Z = 0x25,
*
AccReg_PULSE_TMLT = 0x26,
*
AccReg_PULSE_LTCY = 0x27,
*
AccReg_PULSE_WIND = 0x28,
*
AccReg_ASLP_COUNT = 0x29,
*
AccReg_CTRL_REG1 = 0x2A,
*
AccReg_CTRL_REG2 = 0x2B,
*
AccReg_CTRL_REG3 = 0x2C,
*
AccReg_CTRL_REG4 = 0x2D,
*
AccReg_CTRL_REG5 = 0x2E,
*
AccReg_OFF_X = 0x2F,
*
AccReg_OFF_Y = 0x30,
*
AccReg_OFF_Z = 0x31
 }
enum Status_t {
*
Status_ZYXOW = 0x80,
*
Status_ZOW = 0x40,
*
Status_YOW = 0x20,
*
Status_XOW = 0x10,
*
Status_ZYXDR = 0x08,
*
Status_ZDR = 0x04,
*
Status_YDR = 0x02,
*
Status_XDR = 0x01
 }
enum FifoStatus_t {
*
FifoStatus_F_OVF = 0x80,
*
FifoStatus_F_WMRK_FLAG = 0x40,
*
FifoStatus_F_CNT5 = 0x20,
*
FifoStatus_F_CNT4 = 0x10,
*
FifoStatus_F_CNT3 = 0x08,
*
FifoStatus_F_CNT2 = 0x04,
*
FifoStatus_F_CNT1 = 0x02,
*
FifoStatus_F_CNT0 = 0x01,
*
FifoStatus_F_CNT
 }
enum FifoSetup_t {
*
FifoSetup_F_MODE1 = 0x80,
*
FifoSetup_F_MODE0 = 0x40,
*
FifoSetup_F_MODE = FifoSetup_F_MODE1 | FifoSetup_F_MODE0,
*
FifoSetup_F_WMRK5 = 0x20,
*
FifoSetup_F_WMRK4 = 0x10,
*
FifoSetup_F_WMRK3 = 0x08,
*
FifoSetup_F_WMRK2 = 0x04,
*
FifoSetup_F_WMRK1 = 0x02,
*
FifoSetup_F_WMRK0 = 0x01,
*
FifoSetup_F_WMRK
 }
enum TriggerConfig_t {
*
TriggerConfig_TRANS = 0x20,
*
TriggerConfig_LNDPRT = 0x10,
*
TriggerConfig_PULSE = 0x08,
*
TriggerConfig_FF_MT = 0x04
 }
enum SysMod_t {
*
SysMod_FGERR = 0x80,
*
SysMod_FGT_4 = 0x40,
*
SysMod_FGT_3 = 0x20,
*
SysMod_FGT_2 = 0x10,
*
SysMod_FGT_1 = 0x08,
*
SysMod_FGT_0 = 0x04,
*
SysMod_FGT,
*
SysMod_SYSMOD1 = 0x02,
*
SysMod_SYSMOD0 = 0x01,
*
SysMod_SYSMOD = SysMod_SYSMOD1 | SysMod_SYSMOD0,
*
SysMod_STNDBY = 0x00,
*
SysMod_WAKE = 0x01,
*
SysMod_SLEEP = 0x02
 }
enum IntSourceStatus_t {
*
IntSourceStatus_ASLP = 0x80,
*
IntSourceStatus_FIFO = 0x40,
*
IntSourceStatus_TRANS = 0x20,
*
IntSourceStatus_LNDPRT = 0x10,
*
IntSourceStatus_PULSE = 0x08,
*
IntSourceStatus_FF_MT = 0x04,
*
IntSourceStatus_DRDY = 0x01
 }
enum XyzDataConfig_t {
*
XyzDataConfig_HPF_OUT = 0x10,
*
XyzDataConfig_FS1 = 0x02,
*
XyzDataConfig_FS0 = 0x01,
*
XyzDataConfig_FS = XyzDataConfig_FS1 | XyzDataConfig_FS0,
*
XyzDataConfig_2g = 0x00,
*
XyzDataConfig_4g = 0x01,
*
XyzDataConfig_8g = 0x02
 }
enum HpFilterCutoff_t {
*
HpFilterCutoff_HPF_BYP = 0x20,
*
HpFilterCutoff_LPF_EN = 0x10,
*
HpFilterCutoff_SEL1 = 0x02,
*
HpFilterCutoff_SEL0 = 0x01,
*
HpFilterCutoff_SEL = HpFilterCutoff_SEL1 | HpFilterCutoff_SEL0
 }
enum PlStatus_t {
*
PlStatus_NEWLP = 0x80,
*
PlStatus_LO = 0x40,
*
PlStatus_LAPO1 = 0x04,
*
PlStatus_LAPO0 = 0x02,
*
PlStatus_LAPO = PlStatus_LAPO1 | PlStatus_LAPO0,
*
PlStatus_BAFRO = 0x01
 }
enum PlConfig_t {
*
PlConfig_DBCNTM = 0x80,
*
PlConfig_PL_EN = 0x40
 }
enum PlBfComp_t {
*
PlBfComp_BKFR = 0xC0,
*
PlBfComp_ZLOCK = 0x07
 }
enum PlThreshold_t {
*
PlThreshold_THS = 0xF8,
*
PlThreshold_HYST = 0x07
 }
enum CtrlRegOne_t {
*
CtrlRegOne_ASLP_RATE1 = 0x80,
*
CtrlRegOne_ASLP_RATE0 = 0x40,
*
CtrlRegOne_ASLP_RATE = CtrlRegOne_ASLP_RATE1 | CtrlRegOne_ASLP_RATE0,
*
CtrlRegOne_ODR2 = 0x20,
*
CtrlRegOne_ODR1 = 0x10,
*
CtrlRegOne_ODR0 = 0x08,
*
CtrlRegOne_ODR = CtrlRegOne_ODR2 | CtrlRegOne_ODR1 | CtrlRegOne_ODR0,
*
CtrlRegOne_LNOISE = 0x04,
*
CtrlRegOne_F_READ = 0x02,
*
CtrlRegOne_ACTIVE = 0x01,
*
CtrlRegOne_ODR_800 = 0x00,
*
CtrlRegOne_ODR_400 = CtrlRegOne_ODR0,
*
CtrlRegOne_ODR_200 = CtrlRegOne_ODR1,
*
CtrlRegOne_ODR_100 = CtrlRegOne_ODR1 | CtrlRegOne_ODR0,
*
CtrlRegOne_ODR_50 = CtrlRegOne_ODR2,
*
CtrlRegOne_ODR_12_5 = CtrlRegOne_ODR2 | CtrlRegOne_ODR0,
*
CtrlRegOne_ODR_6_25 = CtrlRegOne_ODR2 | CtrlRegOne_ODR1,
*
CtrlRegOne_ODR_1_56 = CtrlRegOne_ODR2 | CtrlRegOne_ODR1 | CtrlRegOne_ODR0,
*
CtrlRegOne_ODR1 = 0x80,
*
CtrlRegOne_ODR0 = 0x40,
*
CtrlRegOne_ODR = CtrlRegOne_ODR1 | CtrlRegOne_ODR0,
*
CtrlRegOne_BW1 = 0x20,
*
CtrlRegOne_BW0 = 0x10,
*
CtrlRegOne_BW = CtrlRegOne_BW1 | CtrlRegOne_BW0,
*
CtrlRegOne_PD = 0x08,
*
CtrlRegOne_Zen = 0x04,
*
CtrlRegOne_Yen = 0x02,
*
CtrlRegOne_Xen = 0x01,
*
CtrlRegOne_ODR_760 = CtrlRegOne_ODR1 | CtrlRegOne_ODR0,
*
CtrlRegOne_ODR_380 = CtrlRegOne_ODR1,
*
CtrlRegOne_ODR_190 = CtrlRegOne_ODR0,
*
CtrlRegOne_ODR_95 = 0x00
 }
enum CtrlRegTwo_t {
*
CtrlRegTwo_ST_EN = 0x80,
*
CtrlRegTwo_RST = 0x40,
*
CtrlRegTwo_SMODS1 = 0x10,
*
CtrlRegTwo_SMODS0 = 0x08,
*
CtrlRegTwo_SMODS = CtrlRegTwo_SMODS1 | CtrlRegTwo_SMODS0,
*
CtrlRegTwo_SMODS_NRML = 0x00,
*
CtrlRegTwo_SMODS_LNLP = CtrlRegTwo_SMODS0,
*
CtrlRegTwo_SMODS_HRES = CtrlRegTwo_SMODS1,
*
CtrlRegTwo_SMODS_LPWR = CtrlRegTwo_SMODS1 | CtrlRegTwo_SMODS0,
*
CtrlRegTwo_SLPE = 0x04,
*
CtrlRegTwo_MODS1 = 0x02,
*
CtrlRegTwo_MODS0 = 0x01,
*
CtrlRegTwo_MODS = CtrlRegTwo_MODS1 | CtrlRegTwo_MODS0,
*
CtrlRegTwo_MODS_NRML = 0x00,
*
CtrlRegTwo_MODS_LNLP = CtrlRegTwo_MODS0,
*
CtrlRegTwo_MODS_HRES = CtrlRegTwo_MODS1,
*
CtrlRegTwo_MODS_LPWR = CtrlRegTwo_MODS1 | CtrlRegTwo_MODS0,
*
CtrlRegTwo_HPM1 = 0x20,
*
CtrlRegTwo_HPM0 = 0x10,
*
CtrlRegTwo_HPM = CtrlRegTwo_HPM1 | CtrlRegTwo_HPM0,
*
CtrlRegTwo_HPCF3 = 0x08,
*
CtrlRegTwo_HPCF2 = 0x04,
*
CtrlRegTwo_HPCF1 = 0x02,
*
CtrlRegTwo_HPCF0 = 0x01,
*
CtrlRegTwo_HPCF = CtrlRegTwo_HPCF3 | CtrlRegTwo_HPCF3 | CtrlRegTwo_HPCF1 | CtrlRegTwo_HPCF0
 }
enum CtrlRegThree_t {
*
CtrlRegThree_FIFO_GATE = 0x80,
*
CtrlRegThree_WAKE_TRANS = 0x40,
*
CtrlRegThree_WAKE_LNDPRT = 0x20,
*
CtrlRegThree_WAKE_PULSE = 0x10,
*
CtrlRegThree_WAKE_FF_MT = 0x08,
*
CtrlRegThree_IPOL = 0x02,
*
CtrlRegThree_PP_OD = 0x01,
*
CtrlRegThree_I1_Int1 = 0x80,
*
CtrlRegThree_I1_Boot = 0x40,
*
CtrlRegThree_H_Lactive = 0x20,
*
CtrlRegThree_PP_OD = 0x10,
*
CtrlRegThree_I2_DRDY = 0x08,
*
CtrlRegThree_I2_WTM = 0x04,
*
CtrlRegThree_I2_ORun = 0x02,
*
CtrlRegThree_I2_Empty = 0x01
 }
enum CtrlRegFour_t {
*
CtrlRegFour_INT_EN_ASLP = 0x80,
*
CtrlRegFour_INT_EN_FIFO = 0x40,
*
CtrlRegFour_INT_EN_TRANS = 0x20,
*
CtrlRegFour_INT_EN_LNDPRT = 0x10,
*
CtrlRegFour_INT_EN_PULSE = 0x80,
*
CtrlRegFour_INT_EN_FF_MT = 0x40,
*
CtrlRegFour_INT_EN_DRDY = 0x01,
*
CtrlRegFour_BDU = 0x80,
*
CtrlRegFour_BLE = 0x40,
*
CtrlRegFour_FS1 = 0x20,
*
CtrlRegFour_FS0 = 0x10,
*
CtrlRegFour_FS = CtrlRegFour_FS1 | CtrlRegFour_FS0,
*
CtrlRegFour_SIM = 0x01,
*
CtrlRegFour_RES_250 = 0x00,
*
CtrlRegFour_RES_500 = CtrlRegFour_FS0,
*
CtrlRegFour_RES_2000 = CtrlRegFour_FS1
 }
enum CtrlRegFive_t {
*
CtrlRegFive_INT_CFG_ASLP = 0x80,
*
CtrlRegFive_INT_CFG_FIFO = 0x40,
*
CtrlRegFive_INT_CFG_TRANS = 0x20,
*
CtrlRegFive_INT_CFG_LNDPRT = 0x10,
*
CtrlRegFive_INT_CFG_PULSE = 0x08,
*
CtrlRegFive_INT_CFG_FF_MT = 0x04,
*
CtrlRegFive_INT_CFG_DRDY = 0x01,
*
CtrlRegFive_BOOT = 0x80,
*
CtrlRegFive_FIFO_EN = 0x40,
*
CtrlRegFive_HPen = 0x10,
*
CtrlRegFive_INT1_Sel1 = 0x08,
*
CtrlRegFive_INT1_Sel0 = 0x04,
*
CtrlRegFive_INT1_Sel = CtrlRegFive_INT1_Sel1 | CtrlRegFive_INT1_Sel0,
*
CtrlRegFive_Out_Sel1 = 0x02,
*
CtrlRegFive_Out_Sel0 = 0x01,
*
CtrlRegFive_Out_Sel = CtrlRegFive_INT1_Sel1 | CtrlRegFive_INT1_Sel0
 }
Functions
static void _HandleDataReadyInterrupt (void)
static void _HandleOtherInterrupt (void)
static uint8_t _AccReadSingleRegister (AccReg_t)
static void _AccReadMultipleRegisters (AccReg_t startReg, uint8_t numRegisters, uint8_t registers[])
static I2cError_t _AccWriteSingleRegister (AccReg_t reg, uint8_t value)
void Accelerometer_Init (void)
bool Accelerometer_Config (const AccConfig_t *config)
void Accelerometer_Start (void)
void Accelerometer_Stop (void)
void Accelerometer_TriggerSampleBlocking (AccSample_t *sample)
void Accelerometer_SetCalibration (const AccSample_t *calibration)
bool Accelerometer_ReadSample (AccSample_t *sample)
void Accelerometer_ReadSampleArray (uint16_t maxLength, uint16_t *actualLength, uint8_t data[])
void Accelerometer_RegisterIsr (AccIsrPointer_t isr)
void Accelerometer_UnregisterIsr (void)
Variables
static bool _initialized = false
static bool _configured = false
static AccIsrPointer_t _accIsrPointer = NULL
static AccConfig_t _parameters
static volatile uint8_t _ctrlRegOne = 0u
static volatile uint8_t _ctrlRegTwo = 0u
static volatile uint8_t _ctrlRegThree = 0u
static volatile uint8_t _ctrlRegFour = 0u
static volatile uint8_t _ctrlRegFive = 0u
static volatile uint8_t _xyzDataConfig = 0u
static bool _active = false
static volatile bool _dataReady = false
Detailed Description
Accelerometer sensor interface module. Project 1814 IOLab Remote Sensor Application
Description This module provides logic to interface with the 3-axis accelerometer. This logic assumes that the accelerometer in use is the Freescale MMA8451Q I2C digital accelerometer.
Link to Product Webpage
Link to Product Datasheet
Definition in file Accelerometer.c.
Macro Definition Documentation
#define ACC_ADDRESS ((uint8_t)0x1C)
Defines the accelerometer's I2C address. The primary address is 0x1C and the alternate address is 0x1D
Definition at line 476 of file Accelerometer.c.
Referenced by _AccReadMultipleRegisters(), _AccReadSingleRegister(), and _AccWriteSingleRegister().
#define ACC_PORT I2cPort_0
Defines the port the accelerometer is attached to
Definition at line 472 of file Accelerometer.c.
Referenced by _AccReadMultipleRegisters(), _AccReadSingleRegister(), and _AccWriteSingleRegister().
#define BYTES_PER_SAMPLE 6
Defines the number of bytes per sample reading in normal 14-bit mode
Definition at line 482 of file Accelerometer.c.
Referenced by Accelerometer_ReadSample(), Accelerometer_ReadSampleArray(), and Accelerometer_Start().
#define WHO_AM_I ((uint8_t)0x1A)
Define the expected value of the WHO_AM_I query
Definition at line 212 of file Accelerometer.c.
Referenced by Accelerometer_Init().
Enumeration Type Documentation
enum AccReg_t
Defines the possible registers that can be read from or written to on the accelerometer.
Enumerator
AccReg_OUT_X_MSB
 (R) Real time status
AccReg_OUT_X_LSB
 (R) MSB of X sample, root pointer to XYZ FIFO
AccReg_OUT_Y_MSB
 (R) LSB of X sample
AccReg_OUT_Y_LSB
 (R) MSB of Y sample
AccReg_OUT_Z_MSB
 (R) LSB of Y sample
AccReg_OUT_Z_LSB
 (R) MSB of Z sample
AccReg_FIFO_SETUP
 (R) LSB of Z sample 0x07 - 0x08 are reserved
AccReg_TRIG_CONFIG
 (R/W) FIFO setup
AccReg_SYSMOD
 (R/W) Map of FIFO data capture events
AccReg_INT_SOURCE_STAT
 (R) Current system mode
AccReg_WHO_AM_I
 (R) Interrupt status
AccReg_XYZ_DATA_CONFIG
 (R) Device ID (0x1A)
AccReg_HP_FILTER_CUTOFF
 (R/W) Dynamic range settings
AccReg_PL_STATUS
 (R/W) Cutoff frequency is 16Hz @ 800 Hz
AccReg_PL_CONFIG
 (R) Landscape/Portrait orientation status
AccReg_PL_COUNT
 (R/W) Landscape/Portrait configuration
AccReg_PL_BF_ZCOMP
 (R/W) Landscape/Portrait debounce counter
AccReg_PL_THS_REG
 (R/W) Back/Front Z-Lock trip threshold
AccReg_FF_MT_CONFIG
 (R/W) Portrait to Landscape trip angle is 29 deg
AccReg_FF_MT_SOURCE
 (R/W) Freefall/Motion functional block config
AccReg_FF_MT_THS
 (R) Freefall/Motion event source
AccReg_FF_MT_COUNT
 (R/W) Freefall/Motion threshold
AccReg_TRANSIENT_CONFIG
 (R/W) Freefall/Motion debounce counter 0x19 - 0x1C are reserved
AccReg_TRANSIENT_SOURCE
 (R/W) Transient functional block configuration
AccReg_TRANSIENT_THS
 (R) Transient event status register
AccReg_TRANSIENT_COUNT
 (R/W) Transient event threshold
AccReg_PULSE_CONFIG
 (R/W) Transient debounce counter
AccReg_PULSE_SOURCE
 (R/W) ELE, Double_XYZ or Single_XYZ
AccReg_PULSE_THS_X
 (R) EA, Double_XYZ or Single_XYZ
AccReg_PULSE_THS_Y
 (R/W) X pulse threshold
AccReg_PULSE_THS_Z
 (R/W) Y pulse threshold
AccReg_PULSE_TMLT
 (R/W) Z pulse threshold
AccReg_PULSE_LTCY
 (R/W) Time limit for pulse
AccReg_PULSE_WIND
 (R/W) Latency time for 2nd pulse
AccReg_ASLP_COUNT
 (R/W) Window time for 2nd pulse
AccReg_CTRL_REG1
 (R/W) Counter setting for auto-sleep
AccReg_CTRL_REG2
 (R/W) ODR = 800Hz, STANDBY Mode
AccReg_CTRL_REG3
 (R/W) Sleep Enable, OS Modes, RST, ST
AccReg_CTRL_REG4
 (R/W) Wake from Sleep, IPOL, PP_OD
AccReg_CTRL_REG5
 (R/W) Interrupt enable register
AccReg_OFF_X
 (R/W) Interrupt pin (INT1/INT2) map
AccReg_OFF_Y
 (R/W) X-axis offset adjust
AccReg_OFF_Z
 (R/W) Y-axis offset adjust
Definition at line 47 of file Accelerometer.c.
enum CtrlRegFive_t
Defines the bitmask for hte Control register 5 AccReg_CTRL_REG5 of AccReg_t. This register control which pin the interrupt are routed to. A value of '0' routes to INT2 pin and a value of '1' routes to INT1 pin.
Enumerator
CtrlRegFive_INT_CFG_FIFO
 auto sleep/wake interrupt routing
CtrlRegFive_INT_CFG_TRANS
 FIFO interrupt routing.
CtrlRegFive_INT_CFG_LNDPRT
 Transient interrupt routing.
CtrlRegFive_INT_CFG_PULSE
 Landscape/portrait interrupt routing.
CtrlRegFive_INT_CFG_FF_MT
 Pulse interrupt routing.
CtrlRegFive_INT_CFG_DRDY
 Freefall/motion interrupt routing.
CtrlRegFive_FIFO_EN
 reboot memory content
CtrlRegFive_HPen
 FIFO enable.
CtrlRegFive_INT1_Sel1
 high-pass filter enable
CtrlRegFive_Out_Sel1
 INT1 selection configuration.
Definition at line 460 of file Accelerometer.c.
enum CtrlRegFour_t
Defines the bitmask for the Control register 4 AccReg_CTRL_REG4 of AccReg_t. This register controls the interrupt enables.
Enumerator
CtrlRegFour_INT_EN_FIFO
 auto sleep/wake interrupt enable
CtrlRegFour_INT_EN_TRANS
 FIFO interrupt enable.
CtrlRegFour_INT_EN_LNDPRT
 Transient interrupt enable.
CtrlRegFour_INT_EN_PULSE
 Landscape/portrait interrupt enable.
CtrlRegFour_INT_EN_FF_MT
 Pulse detection interrupt enable.
CtrlRegFour_INT_EN_DRDY
 Freefall/motion interrupt enable.
CtrlRegFour_BLE
 block data update
CtrlRegFour_FS1
 big/little endian data selection
CtrlRegFour_SIM
 full scale selection
CtrlRegFour_RES_250
 SPI serial interface mode selection.
Definition at line 445 of file Accelerometer.c.
enum CtrlRegOne_t
Defines the bitmask for the control register one AccReg_CTRL_REG_1 of the AccReg_t.
ASLP_RATE - 00: 50 Hz 01: 12.5 Hz 10: 6.25 Hz 11: 1.56 Hz
Frequency (Hz) Period (ms) ODR - 000: 800 1.25 001: 400 2.5 010: 200 5 011: 100 10 100: 50 20 101: 12.5 80 110: 6.25 160 111: 1.56 640
Note
except for active/standby, the device must be in standby mode to change any fields within this register.
Enumerator
CtrlRegOne_ASLP_RATE0
 bit 1 of the autowake sample frequency
CtrlRegOne_ASLP_RATE
 bit 0 of the autowake sample frequency
CtrlRegOne_ODR2
 Configures the autowake sample frequency.
CtrlRegOne_LNOISE
 output data rate selection
CtrlRegOne_F_READ
 reduced noise enabled
CtrlRegOne_ACTIVE
 fast read mode enable
CtrlRegOne_ODR_800
 active mode enable
CtrlRegOne_BW1
 output data rate selection
CtrlRegOne_PD
 bandwidth selection
CtrlRegOne_Zen
 power-down mode enable
CtrlRegOne_Yen
 Z axis enable.
CtrlRegOne_Xen
 Y axis enable.
CtrlRegOne_ODR_760
 X axis enable.
Definition at line 372 of file Accelerometer.c.
enum CtrlRegThree_t
Defines the bitmask for the Control register 3 AccReg_CTRL_REG3 of AccReg_t.
Enumerator
CtrlRegThree_WAKE_TRANS
 Enable the gate to block the FIFO once full.
CtrlRegThree_WAKE_LNDPRT
 Transient function interrupt can wake up system.
CtrlRegThree_WAKE_PULSE
 Orientation interrupt can wake system.
CtrlRegThree_WAKE_FF_MT
 Pulse interrupt can wake system.
CtrlRegThree_IPOL
 Freefall/motion interrupt can wake system.
CtrlRegThree_PP_OD
 Interrupt polarity active high enable.
CtrlRegThree_I1_Boot
 interrupt enable on INT1 pin
CtrlRegThree_H_Lactive
 boot status available on INT1
CtrlRegThree_PP_OD
 interrupt active configuration on INT1
CtrlRegThree_I2_DRDY
 push-pull/ open drain
CtrlRegThree_I2_WTM
 data ready on DRDY/INT2
CtrlRegThree_I2_ORun
 FIFO watermark interrupt on DRDY/INT2.
CtrlRegThree_I2_Empty
 FIFO overrun interrupt on DRDY/INT2.
Definition at line 431 of file Accelerometer.c.
enum CtrlRegTwo_t
Defines the bitmask for the Control register 2 AccReg_CTRL_REG2 of AccReg_t.
The software reset can be activated in standby or active mode. Resetting the device causes all registers to immediately be cleared.
          Mode
 (S)MODS - 00: Normal 01: Low Noise, Low Power 10: High Resolution 11: Low Power
Note
Low noise and high resolution modes only work for 2g and 4g range, not 8g.
Enumerator
CtrlRegTwo_RST
 Self test enable.
CtrlRegTwo_SMODS1
 Software Reset enable.
CtrlRegTwo_SMODS0
 Sleep mode power scheme bit 1.
CtrlRegTwo_SMODS
 Sleep mode power scheme bit 0.
CtrlRegTwo_SMODS_NRML
 Sleep mode power scheme selection.
CtrlRegTwo_MODS1
 Auto sleep mode enable.
CtrlRegTwo_MODS0
 Active mode power scheme bit 1.
CtrlRegTwo_MODS
 Active mode power scheme bit 0.
CtrlRegTwo_MODS_NRML
 Active mode power scheme selection.
CtrlRegTwo_HPCF3
 high-pass filter mode selection
Definition at line 407 of file Accelerometer.c.
enum FifoSetup_t
Defines the bitmasks for the bits in the AccReg_FIFO_SETUP register of AccReg_t.
F_MODE - 00: FIFO is disabled 01: FIFO is circular buffer 10: FIFO stops when full 11: FIFO will take WMRK samples then stop
Enumerator
FifoSetup_F_MODE0
 FIFO mode bit 1.
FifoSetup_F_MODE
 FIFO mode bit 0.
FifoSetup_F_WMRK4
 Bit 5 of the watermark setpoint.
FifoSetup_F_WMRK3
 Bit 4 of the watermark setpoint.
FifoSetup_F_WMRK2
 Bit 3 of the watermark setpoint.
FifoSetup_F_WMRK1
 Bit 2 of the watermark setpoint.
FifoSetup_F_WMRK0
 Bit 1 of the watermark setpoint.
FifoSetup_F_WMRK
 Bit 0 of the watermark setpoint.
Definition at line 147 of file Accelerometer.c.
enum FifoStatus_t
Defines the bitmasks for the bits in the AccReg_Status register of AccReg_t when using the FIFO (F_MODE > 0 in AccReg_FIFO_SETUP).
Note
These bits are only correct when USING THE FIFO! This register has a different meaning when not using the FIFO.
See Also
See Status.
Enumerator
FifoStatus_F_WMRK_FLAG
 Set when the fifo overflows.
FifoStatus_F_CNT5
 Set when the FIFO hits the watermark.
FifoStatus_F_CNT4
 Bit 5 of the FIFO counter (how many samples are in the FIFO)
FifoStatus_F_CNT3
 Bit 4 of the FIFO counter.
FifoStatus_F_CNT2
 Bit 3 of the FIFO counter.
FifoStatus_F_CNT1
 Bit 2 of the FIFO counter.
FifoStatus_F_CNT0
 Bit 1 of the FIFO counter.
FifoStatus_F_CNT
 Bit 0 of the FIFO counter.
Definition at line 126 of file Accelerometer.c.
enum HpFilterCutoff_t
Defines the bitmasks for the high pass filter cutoff settings.
Enumerator
HpFilterCutoff_LPF_EN
 Bypass the high pass filter for pulse processing.
HpFilterCutoff_SEL1
 Enable the low pass filter for pulse processing.
HpFilterCutoff_SEL0
 High Pass cutoff frequency selection. See datasheet Table 22.
Definition at line 237 of file Accelerometer.c.
enum IntSourceStatus_t
Defines the bitmasks for the interrupt source status register AccReg_INT_SOURCE_STAT of the AccReg_t.
Enumerator
IntSourceStatus_FIFO
 WAKE to SLEEP or SLEEP to WAKE interrupt occurred.
IntSourceStatus_TRANS
 FIFO overflow or watermark occurred.
IntSourceStatus_LNDPRT
 Acceleration transient value > THRESH occurred.
IntSourceStatus_PULSE
 Device orientation change occurred.
IntSourceStatus_FF_MT
 A single or double pulse occurred.
IntSourceStatus_DRDY
 A freefall or motion event occurred.
Definition at line 200 of file Accelerometer.c.
enum PlBfComp_t
Defines the bitmasks for the back to front z-lockout compensation register AccReg_PL_BF_COMP of the AccReg_t.
       Back/Front Transistion(deg)   Front/Back Transistion(deg)
 BKFR = 00: Z < 80 or Z > 280 Z > 100 and Z < 260 01: Z < 75 or Z > 285 Z > 105 and Z < 255 10: Z < 70 or Z > 290 Z > 110 and Z < 250 11 Z < 65 or Z > 295 Z > 115 and Z < 245
  Threshold Angle (deg)
 ZLOCK = 0x00: 14 0x01: 18 0x02: 21 0x03: 25 0x04: 29 0x05: 33 0x06: 37 0x07: 42
Enumerator
PlBfComp_ZLOCK
 Back to front transition setpoint.
Definition at line 293 of file Accelerometer.c.
enum PlConfig_t
Defines the bitmasks for the portrait landscape configuration register AccReg_PL_CONFIG of the AccReg_t.
Enumerator
PlConfig_PL_EN
 0 - decrement counter, 1 - clear counter on event
Definition at line 267 of file Accelerometer.c.
enum PlStatus_t
Defines the bitmasks for the portrait landscape status register AccReg_PL_STATUS of the AccReg_t.
LAPO - 00: Portrait up 01: Portrait down 10: Landscape right 11: Landscape left
Enumerator
PlStatus_LO
 Landscape/Portrait status has changed.
PlStatus_LAPO1
 Z-tilt lockout angle has been exceeded.
PlStatus_LAPO0
 Landscape/Portrait orientation bit 1.
PlStatus_LAPO
 Landscape/Portrait orientation bit 0.
Definition at line 254 of file Accelerometer.c.
enum PlThreshold_t
Defines the bit masks for the portrait to landscape threshold and hysteresis settings for the AccReg_PL_THS_REG of the AccReg_t. The default trip angle is 45 deg (0x10) and the default hysteresis is +/-14 deg.
5-bit register Threshold Angle (degrees) THS - 0x07: 15 0x09: 20 0x0C: 30 0x0D: 35 0x0F: 40 0x10: 45 0x13: 55 0x14: 60 0x17: 70 0x19: 75
3-bit register Hysteresis L->P P->L HYST - 0x00: 0 45 45 0x01: 4 49 41 0x02: 7 52 38 0x03: 11 56 34 0x04: 14 59 31 0x05: 17 62 28 0x06: 21 66 24 0x07: 24 69 21
Note
THS+HYST > 0 and THS + HYST < 32 for Landscape/Portrait detection to work correctly. All angles accurate to +/- 2 degrees.
Enumerator
PlThreshold_HYST
 Portrait/Landscape trip threshold.
Definition at line 328 of file Accelerometer.c.
enum Status_t
Defines the bitmasks for the bits in the AccReg_Status register of AccReg_t when not using the FIFO (F_MODE = 0 in AccReg_FIFO_SETUP).
Note
These bits are only correct when NOT USING THE FIFO! This register has a different meaning when using the FIFO.
See Also
See FifoStatus.
Enumerator
Status_ZOW
 XYX-axis data overwrite occurred.
Status_YOW
 Z-axis data overwrite occurred.
Status_XOW
 Y-axis data overwrite occurred.
Status_ZYXDR
 X-axis data overwrite occurred.
Status_ZDR
 ZYX-axis new data ready (cleared when ALL axis MSBs are read)
Status_YDR
 Z-axis new data ready.
Status_XDR
 Y-axis new data ready.
Definition at line 106 of file Accelerometer.c.
enum SysMod_t
Defines the bitmasks for the system mode AccReg_SYS_MOD of the AccReg_t.
SYSMOD - 00: STANDBY mode 01: WAKE mode 10: SLEEP mode
Enumerator
SysMod_FGT_4
 FIFO gate error. Emptying the FIFO clears the error.
SysMod_FGT_3
 Number of ODR time units since FGERR was asserted. Reset when FGERR is cleared.
SysMod_SYSMOD0
 Bit 1 of the system mode.
SysMod_SYSMOD
 Bit 0 of the system mode.
SysMod_WAKE
 Value of the SYSMOD bits when system is in standby.
SysMod_SLEEP
 Value of the SYSMOD bits when the system is active.
Definition at line 179 of file Accelerometer.c.
enum TriggerConfig_t
Defines the bitmasks for the interrupt trigger configuration AccReg_TRIG_CONFIG register of the AccReg_t.
Enumerator
TriggerConfig_LNDPRT
 Transient interrupt trigger.
TriggerConfig_PULSE
 Landscape/Portrait orientation interrupt trigger.
TriggerConfig_FF_MT
 Pulse interrupt trigger.
Definition at line 165 of file Accelerometer.c.
enum XyzDataConfig_t
Defines the bitmasks for the XYZ configuration register that sets the dynamic range and the high pass filter for the output data.
Full scale range: FS - 00: 2g 01: 4g 10: 8g 11: reserved
Note
8g mode will not work with low noise or high resolution modes.
Enumerator
XyzDataConfig_FS1
 Enable high pass output data.
XyzDataConfig_FS0
 Full scale range bit 1.
XyzDataConfig_FS
 Full scale range bit 0.
XyzDataConfig_4g
 FS value when range is 2g.
XyzDataConfig_8g
 FS value when range is 4g.
Definition at line 225 of file Accelerometer.c.
Function Documentation
static void _AccReadMultipleRegisters (AccReg_t startReg, uint8_t numRegisters, uint8_t registers[]) [static]
Reads a multiple consecutive registers from the accelerometer.
Parameters
in startReg - the first register to read of the consecutive registers
in numRegisters - The number of consecutive registers to read
in registers[] - the array in which the register values will be stored.
Note
Make sure that registers[] has at least numRegisters elements to hold the register data.
Definition at line 966 of file Accelerometer.c.
Referenced by Accelerometer_ReadSample(), Accelerometer_ReadSampleArray(), and Accelerometer_Start().
static uint8_t _AccReadSingleRegister (AccReg_t reg) [static]
Reads a single register from the accelerometer.
Parameters
in reg- the register to read
Returns
The value read from the accelerometer register
Definition at line 936 of file Accelerometer.c.
Referenced by Accelerometer_Config(), and Accelerometer_Init().
static I2cError_t _AccWriteSingleRegister (AccReg_t reg, uint8_t value) [static]
Writes a single register to the accelerometer.
Parameters
in reg - the register to write to
in value - The value to write to the register
Returns
I2cError_OK if the register could be written successfully. Otherwise return an I2cError.
Definition at line 1006 of file Accelerometer.c.
Referenced by Accelerometer_Config(), Accelerometer_Start(), and Accelerometer_Stop().
static void _HandleDataReadyInterrupt (void) [static]
Handles the GPIO event that indicates that data is ready on the accelerometer.
Definition at line 910 of file Accelerometer.c.
Referenced by Accelerometer_Init().
void _HandleOtherInterrupt (void) [static]
Handles the GPIO event that indicates that a special event on the accelerometer.
Definition at line 924 of file Accelerometer.c.
Referenced by Accelerometer_Init().
bool Accelerometer_Config (const AccConfig_t * config)
Configures the accelerometer, but does not start the sampling.
Parameters
in config - Structure of selected accelerometer settings.
Returns
True if the configuration was successful, false otherwise. The configuration will fail if the accelerometer is not in standby when configured.
Definition at line 556 of file Accelerometer.c.
Referenced by AccControl_SetConfig(), and Accelerometer_TriggerSampleBlocking().
void Accelerometer_Init (void)
Initializes the accelerometer, but does not configure or start sampling
Definition at line 527 of file Accelerometer.c.
Referenced by AccControl_Init().
bool Accelerometer_ReadSample (AccSample_t * sample)
Reads a sample from the accelerometer if a sample was ready.
Parameters
out sample - structure to hold the sample data once it is collected
Returns
True if the sample was ready, false otherwise
Definition at line 818 of file Accelerometer.c.
Referenced by AccControl_ReadAcc(), and Accelerometer_TriggerSampleBlocking().
void Accelerometer_ReadSampleArray (uint16_t maxLength, uint16_t * actualLength, uint8_t data[])
Reads a sample from the accelerometer if a sample was ready.
Parameters
in maxLength - the maximum length of bytes data[] can hold
out actualLength - the actual number of bytes written to data[]
in data - an array to hold the data from the accelerometer reading
Definition at line 855 of file Accelerometer.c.
Referenced by AccControl_ReadAcc().
void Accelerometer_RegisterIsr (AccIsrPointer_t isr)
Sets a function that will be ran when the data ready interrupt occurs.
Parameters
in isr - pointer to the accelerometer data ready ISR
Definition at line 890 of file Accelerometer.c.
Referenced by AccControl_Init().
void Accelerometer_Start (void)
Starts the accelerometer sampling at its configured data rate.
Definition at line 717 of file Accelerometer.c.
Referenced by AccControl_SetConfig(), and Accelerometer_TriggerSampleBlocking().
void Accelerometer_Stop (void)
Stops the data collecting of the accelerometer.
Definition at line 752 of file Accelerometer.c.
Referenced by AccControl_SetConfig(), and Accelerometer_TriggerSampleBlocking().
void Accelerometer_TriggerSampleBlocking (AccSample_t * sample)
Triggers the accelerometer to take a sample and block until the sample is returned.
Parameters
out sample - the result of the accelerometer sample.
Definition at line 772 of file Accelerometer.c.
Referenced by _HandleHumanAccCommand().
void Accelerometer_UnregisterIsr (void)
Clears the custom ISR for the accelerometer.
Definition at line 901 of file Accelerometer.c.
Variable Documentation
AccIsrPointer_t _accIsrPointer = NULL [static]
Stores the ISR pointer
Definition at line 492 of file Accelerometer.c.
Referenced by _HandleDataReadyInterrupt(), Accelerometer_RegisterIsr(), and Accelerometer_UnregisterIsr().
bool _active = false [static]
Tracks if the accelerometer is actively collecting data
Definition at line 509 of file Accelerometer.c.
Referenced by Accelerometer_Start(), Accelerometer_Stop(), and Accelerometer_TriggerSampleBlocking().
bool _configured = false [static]
Tracks if the accelerometer has ever been configured before
Definition at line 489 of file Accelerometer.c.
Referenced by Accelerometer_Config(), Accelerometer_Start(), and Accelerometer_TriggerSampleBlocking().
volatile uint8_t _ctrlRegOne = 0u [static]
Store the values written to the control registers so they don't have to be read back.
Definition at line 501 of file Accelerometer.c.
Referenced by Accelerometer_Config(), Accelerometer_Start(), and Accelerometer_Stop().
volatile bool _dataReady = false [static]
Tracks if data is ready to be read from the accelerometer
Definition at line 512 of file Accelerometer.c.
Referenced by _HandleDataReadyInterrupt(), Accelerometer_ReadSample(), and Accelerometer_ReadSampleArray().
bool _initialized = false [static]
Tracks if the accelerometer has been initialized.
Definition at line 486 of file Accelerometer.c.
AccConfig_t _parameters [static]
Initial value:
= {AccOdr_100, AccResolution_14bit, AccFullScaleRange_4g,
                                  AccOverSample_HighRes}
Stores the configuration parameters for the initialized accelerometer
Definition at line 495 of file Accelerometer.c.