Accelerometer.h File Reference
Accelerometer interface header.
Data Structures
struct AccConfig_t
struct AccSample_t
Typedefs
typedef void(* AccIsrPointer_t)(void)
Enumerations
enum AccOdr_t {
*
AccOdr_800,
*
AccOdr_400,
*
AccOdr_200,
*
AccOdr_100,
*
AccOdr_50,
*
AccOdr_12_5,
*
AccOdr_6_25,
*
AccOdr_1_56
 }
enum AccResolution_t {
*
AccResolution_14bit,
*
AccResolution_8bit
 }
enum AccFullScaleRange_t {
*
AccFullScaleRange_8g,
*
AccFullScaleRange_4g,
*
AccFullScaleRange_2g
 }
enum AccOverSample_t {
*
AccOverSample_Normal,
*
AccOverSample_LNLP,
*
AccOverSample_HighRes,
*
AccOverSample_LowPower
 }
Functions
void Accelerometer_Init (void)
bool Accelerometer_Config (const AccConfig_t *config)
void Accelerometer_Start (void)
void Accelerometer_Stop (void)
void Accelerometer_TriggerSampleBlocking (AccSample_t *sample)
void Accelerometer_SetCalibration (const AccSample_t *calibration)
bool Accelerometer_ReadSample (AccSample_t *sample)
void Accelerometer_ReadSampleArray (uint16_t maxLength, uint16_t *actualLength, uint8_t data[])
void Accelerometer_RegisterIsr (AccIsrPointer_t isr)
void Accelerometer_UnregisterIsr (void)
Detailed Description
Accelerometer interface header. Project 1814 IOLab Remote Sensor Application
Description Header file for the 3-axis accelerometer sensor interface logic.
Definition in file Accelerometer.h.
Data Structure Documentation
struct AccConfig_t
Defines a structure to hold the accelerometer configuration data in.
Definition at line 70 of file Accelerometer.h.
Data Fields
AccOdr_t
odr
AccOverSample_t
overSampleMode
AccFullScaleRange_t
range
AccResolution_t
resolution
struct AccSample_t
Defines a structure to hold the accelerometer data in.
Definition at line 79 of file Accelerometer.h.
Data Fields
int16_t
xData
int16_t
yData
int16_t
zData
Typedef Documentation
typedef void(* AccIsrPointer_t)(void)
Defines an accelerometer ISR function pointer
Definition at line 88 of file Accelerometer.h.
Enumeration Type Documentation
enum AccFullScaleRange_t
Defines the full scale range output from the accelerometer in g
Definition at line 51 of file Accelerometer.h.
enum AccOdr_t
Defines the output data rates that the accelerometer can run at. Lower sample rates consume less power.
Definition at line 29 of file Accelerometer.h.
enum AccOverSample_t
Defines the over sampling mode for the accelerometer. The higher resolution uses more power.
Enumerator
AccOverSample_LNLP
 High resolution.
AccOverSample_HighRes
 Low noise, but also low power.
AccOverSample_LowPower
 Highest resolution, especially at lower ODR. lowest power, but highest noise
Definition at line 61 of file Accelerometer.h.
enum AccResolution_t
Defines the resolution setting for the accelerometer Lower resolution allows for lower bus traffic
Definition at line 44 of file Accelerometer.h.
Function Documentation
bool Accelerometer_Config (const AccConfig_t * config)
Configures the accelerometer, but does not start the sampling.
Parameters
in config - Structure of selected accelerometer settings.
Returns
True if the configuration was successful, false otherwise. The configuration will fail if the accelerometer is not in standby when configured.
Definition at line 556 of file Accelerometer.c.
Referenced by AccControl_SetConfig(), and Accelerometer_TriggerSampleBlocking().
void Accelerometer_Init (void)
Initializes the accelerometer, but does not configure or start sampling
Definition at line 527 of file Accelerometer.c.
Referenced by AccControl_Init().
bool Accelerometer_ReadSample (AccSample_t * sample)
Reads a sample from the accelerometer if a sample was ready.
Parameters
out sample - structure to hold the sample data once it is collected
Returns
True if the sample was ready, false otherwise
Definition at line 818 of file Accelerometer.c.
Referenced by AccControl_ReadAcc(), and Accelerometer_TriggerSampleBlocking().
void Accelerometer_ReadSampleArray (uint16_t maxLength, uint16_t * actualLength, uint8_t data[])
Reads a sample from the accelerometer if a sample was ready.
Parameters
in maxLength - the maximum length of bytes data[] can hold
out actualLength - the actual number of bytes written to data[]
in data - an array to hold the data from the accelerometer reading
Definition at line 855 of file Accelerometer.c.
Referenced by AccControl_ReadAcc().
void Accelerometer_RegisterIsr (AccIsrPointer_t isr)
Sets a function that will be ran when the data ready interrupt occurs.
Parameters
in isr - pointer to the accelerometer data ready ISR
Definition at line 890 of file Accelerometer.c.
Referenced by AccControl_Init().
void Accelerometer_Start (void)
Starts the accelerometer sampling at its configured data rate.
Definition at line 717 of file Accelerometer.c.
Referenced by AccControl_SetConfig(), and Accelerometer_TriggerSampleBlocking().
void Accelerometer_Stop (void)
Stops the data collecting of the accelerometer.
Definition at line 752 of file Accelerometer.c.
Referenced by AccControl_SetConfig(), and Accelerometer_TriggerSampleBlocking().
void Accelerometer_TriggerSampleBlocking (AccSample_t * sample)
Triggers the accelerometer to take a sample and block until the sample is returned.
Parameters
out sample - the result of the accelerometer sample.
Definition at line 772 of file Accelerometer.c.
Referenced by _HandleHumanAccCommand().
void Accelerometer_UnregisterIsr (void)
Clears the custom ISR for the accelerometer.
Definition at line 901 of file Accelerometer.c.