AdcManager.h File Reference
Analog to digital conversion manager header file.
#include <Adc.h>
*
Typedefs
typedef void(* AdcDataCallback_t)(uint16_t)
Enumerations
enum AdcManChannel_t {
*
AdcManChannel_INVALID = -1,
*
AdcManChannel_FIRST = AdcInputChannel_A0,
*
AdcManChannel_HEADER_06 = AdcInputChannel_A0,
*
AdcManChannel_HEADER_07 = AdcInputChannel_A1,
*
AdcManChannel_HEADER_08 = AdcInputChannel_A2,
*
AdcManChannel_FORCE_GAUGE = AdcInputChannel_A4,
*
AdcManChannel_ECG_1 = AdcInputChannel_A5,
*
AdcManChannel_ECG_2 = AdcInputChannel_A6,
*
AdcManChannel_ECG_3 = AdcInputChannel_A7,
*
AdcManChannel_TEMPERATURE = AdcInputChannel_TEMP,
*
AdcManChannel_AMBIENT_LIGHT = AdcInputChannel_A12,
*
AdcManChannel_HIGH_GAIN = AdcInputChannel_A13,
*
AdcManChannel_MICROPHONE = AdcInputChannel_A14,
*
AdcManChannel_BATTERY = AdcInputChannel_A15,
*
AdcManChannel_LAST
 }
enum AdcManSampleRate_t {
*
AdcManSampleRate_INVALID = -1,
*
AdcManSampleRate_FIRST = 0u,
*
AdcManSampleRate_0001HZ = 0u,
*
AdcManSampleRate_0010HZ = 1u,
*
AdcManSampleRate_0050HZ = 2u,
*
AdcManSampleRate_0100HZ = 3u,
*
AdcManSampleRate_0200HZ = 4u,
*
AdcManSampleRate_0400HZ = 5u,
*
AdcManSampleRate_0800HZ = 6u,
*
AdcManSampleRate_2400HZ = 7u,
*
AdcManSampleRate_4800HZ = 8u,
*
AdcManSampleRate_6000HZ = 9u,
*
AdcManSampleRate_LAST
 }
enum AdcManRef_t {
*
AdcManRef_INVALID = -1,
*
AdcManRef_FIRST = 0u,
*
AdcManRef_DEFAULT = AdcManRef_FIRST,
*
AdcManRef_VREF = AdcManRef_DEFAULT,
*
AdcManRef_VCC,
*
AdcManRef_LAST
 }
Functions
void AdcManager_Init (void)
void AdcManager_EnableChannel (AdcManChannel_t channel, AdcManSampleRate_t rate, AdcManRef_t reference, AdcDataCallback_t callback)
void AdcManager_DisableChannel (AdcManChannel_t channel)
uint16_t AdcManager_SingleSampleBlocking (AdcManChannel_t channel)
void AdcManager_ProcessConversion (void)
uint16_t AdcManager_GetGainFactor (void)
uint16_t AdcManager_GetOffset (void)
void AdcManager_PoweredChannelControl (AdcManChannel_t channel, bool enable)
AdcReference_t AdcManager_AdcManRefToAdcRef (AdcManRef_t adcManRef)
Detailed Description
Analog to digital conversion manager header file. Project 1814 IOLab Remote Sensor Application
Description The analog to digital conversion manager will provide configuration functions and macros for accessing analog conversion samples.
Definition in file AdcManager.h.
Typedef Documentation
typedef void(* AdcDataCallback_t)(uint16_t)
Defines a callback for function pointer for handling the conversion data.
Note
The callback must be in the form of:
void callback(uint16_t sample);
Where sample with be the ADC value that was sampled.
Definition at line 92 of file AdcManager.h.
Enumeration Type Documentation
enum AdcManChannel_t
Defines the available ADC Channels by their purpose
Note
The enum value for the AdcManChannel must match the AdcInputChannel value for the particular input channel
Definition at line 33 of file AdcManager.h.
enum AdcManRef_t
Defines the analog reference options
Definition at line 74 of file AdcManager.h.
enum AdcManSampleRate_t
Defines the ADC sample rate options
Definition at line 56 of file AdcManager.h.
Function Documentation
AdcReference_t AdcManager_AdcManRefToAdcRef (AdcManRef_t adcManRef)
Takes an ADC manager reference and converts it to an ADC reference
This function should only be used internally to the ADC manager, except for board level test and debugging purposes.
Parameters
in adcManRef - the AdcManRef_t ADC Manager analog reference selection
Returns
The AdcReference_t reference for the ADC driver
Definition at line 844 of file AdcManager.c.
Referenced by _SetupAdcForNormalMode(), and AdcManager_EnableChannel().
void AdcManager_DisableChannel (AdcManChannel_t channel)
Disables an ADC channel and clears its callback pointer. Also disables the ADC module if this was the last/only active channel.
Parameters
in channel - the desired sample channel to stop
Definition at line 455 of file AdcManager.c.
Referenced by AmbientLightControl_SetConfig(), Analog7Control_SetConfig(), Analog8Control_SetConfig(), Analog9Control_SetConfig(), BatteryControl_SetConfig(), EcgControl_SetConfig(), FgControl_SetConfig(), HighGainControl_SetConfig(), MicrophoneControl_SetConfig(), and ThermometerControl_SetConfig().
void AdcManager_EnableChannel (AdcManChannel_t channel, AdcManSampleRate_t rate, AdcManRef_t reference, AdcDataCallback_t callback)
Enables an ADC channel and starts sampling it at the given rate. The data from each sample will be passed into the callback function. Also enables the ADC module if this was the first/only active channel.
Parameters
in channel - the desired sample channel
in rate - the rate at which to pass a sample into the callback function
in callback - the function to call to pass the ADC sample data to
Definition at line 300 of file AdcManager.c.
Referenced by AmbientLightControl_SetConfig(), Analog7Control_SetConfig(), Analog8Control_SetConfig(), Analog9Control_SetConfig(), BatteryControl_SetConfig(), EcgControl_SetConfig(), FgControl_SetConfig(), HighGainControl_SetConfig(), MicrophoneControl_SetConfig(), and ThermometerControl_SetConfig().
uint16_t AdcManager_GetGainFactor (void)
Gets the ADC gain factor that can be used to scale the ADC readings for higher accuracy.
Returns
The ADC gain factor
Definition at line 594 of file AdcManager.c.
Referenced by BatteryControl_ReadCalibration().
uint16_t AdcManager_GetOffset (void)
Gets the ADC offset that can be used to shift the ADC readings for higher accuracy.
Returns
The ADC offset
Definition at line 606 of file AdcManager.c.
Referenced by BatteryControl_ReadCalibration().
void AdcManager_Init (void)
Initializes the ADC manager
Definition at line 265 of file AdcManager.c.
Referenced by main().
void AdcManager_PoweredChannelControl (AdcManChannel_t channel, bool enable)
Takes an ADC channel and if it is a powered channel will enable or disable the power rail for the channel.
This function should only be used internally to the ADC manager, except for board level test and debugging purposes.
Parameters
in channel - the channel that should be enabled or disabled
in enable - true to enable, false to disable
Definition at line 788 of file AdcManager.c.
Referenced by AdcManager_DisableChannel(), AdcManager_EnableChannel(), and SelfTest_Process().
void AdcManager_ProcessConversion (void)
Should be called by the event handler for processing the ADC conversion complete event. This function will take the converted ADC data from the buffer and call the ADC sample callback functions at the desired rate.
Definition at line 559 of file AdcManager.c.
Referenced by _ProcessEvents_DEFAULT().
uint16_t AdcManager_SingleSampleBlocking (AdcManChannel_t channel)
Takes a single sample of an ADC channel and returns the raw ADC counts
Parameters
in channel - the ADC channel which to sample
Returns
the value in raw ADC counts of the ADC channel.
Definition at line 509 of file AdcManager.c.
Referenced by _HandleHumanAdc1Command().