AdcManager.c File Reference
Analog to digital conversion manager.
#include <ProjectTypes.h>
*
#include <Device.h>
*
#include <Adc.h>
*
#include `AdcManager.h`
*
#include <Timer.h>
*
#include <Board.h>
*
#include <Gpio.h>
*
#include <Assert.h>
*
#include <Serial.h>
*
#include <Debug.h>
*
Data Structures
struct AdcChannelData_t
Macros
#define ADC_REFERENCE (AdcReference_eVREFp_VREFm)
#define ADC_THERMOMETER_REFERENCE (AdcReference_VREFp_AVSS)
#define ADC_THERMOMETER_REFERENCE_VOLTAGE (AdcReferenceLevel_1p5_VOLTS)
Enumerations
enum EveryXSamples_t {
*
EveryXSamples_INVLALID = -1,
*
EveryXSamples_0001 = 400u,
*
EveryXSamples_0010 = 40u,
*
EveryXSamples_0050 = 8u,
*
EveryXSamples_0100 = 4u,
*
EveryXSamples_0200 = 2u,
*
EveryXSamples_0400 = 1u,
*
EveryXSamples_0800 = 1u,
*
EveryXSamples_2400 = 1u,
*
EveryXSamples_4800 = 1u,
*
EveryXSamples_6000 = 1u
 }
enum AdcPoweredChannel_t {
*
AdcPoweredChannel_NONE = 0u,
*
AdcPoweredChannel_FORCE_GAUGE = 0x01,
*
AdcPoweredChannel_AMBIENT_LIGHT = 0x02,
*
AdcPoweredChannel_MICROPHONE = 0x04
 }
enum AdcTimerRate_t {
*
AdcTimerRate_INVALID = -1,
*
AdcTimerRate_FIRST = 0u,
*
AdcTimerRate_0400HZ = AdcTimerRate_FIRST,
*
AdcTimerRate_0800HZ,
*
AdcTimerRate_2400HZ,
*
AdcTimerRate_4800HZ,
*
AdcTimerRate_6000HZ,
*
AdcTimerRate_LAST
 }
enum AdcSamplesNeeded_t {
*
AdcSamplesNeeded_0400HZ = AdcInputChannel_LAST,
*
AdcSamplesNeeded_0800HZ = 2u,
*
AdcSamplesNeeded_2400HZ = 6u,
*
AdcSamplesNeeded_4800HZ = 12u,
*
AdcSamplesNeeded_6000HZ = 15u
 }
enum AdcManSampleMode_t {
*
AdcManSampleMode_INVALID = -1,
*
AdcManSampleMode_FIRST = 0u,
*
AdcManSampleMode_NORMAL = AdcManSampleMode_FIRST,
*
AdcManSampleMode_FAST,
*
AdcManSampleMode_LAST
 }
Functions
static EveryXSamples_t _GetSamplesToSkip (AdcManSampleRate_t sampleRate)
static bool _AllChannelsDisabled (void)
static __inline void _InitialzeXAdcChannels (uint16_t x)
static void _SetupTimerConfig (void)
static __inline void _AdcStart (void)
static __inline void _AdcStop (void)
static __inline void _SetupAdcForNormalMode (AdcManRef_t reference)
static __inline void _SetupAdcSingleChannel (AdcManChannel_t channel, AdcManRef_t reference)
void AdcManager_Init (void)
void AdcManager_EnableChannel (AdcManChannel_t channel, AdcManSampleRate_t rate, AdcManRef_t reference, AdcDataCallback_t callback)
void AdcManager_DisableChannel (AdcManChannel_t channel)
uint16_t AdcManager_SingleSampleBlocking (AdcManChannel_t channel)
void AdcManager_ProcessConversion (void)
uint16_t AdcManager_GetGainFactor (void)
uint16_t AdcManager_GetOffset (void)
void AdcManager_PoweredChannelControl (AdcManChannel_t channel, bool enable)
AdcReference_t AdcManager_AdcManRefToAdcRef (AdcManRef_t adcManRef)
Variables
static const AdcConfig_t _fastAdcConfig = { AdcConSeq_SEQ_OF_CHAN, AdcSht_0008, false }
static const AdcConfig_t _normAdcConfig = { AdcConSeq_SEQ_OF_CHAN, AdcSht_0384, true }
static const AdcConfig_t _fastMultiAdcConfig = { AdcConSeq_SEQ_OF_CHAN, AdcSht_0008, true }
static bool _initialized = false
static AdcChannelConfig_t _adcAllChannelConfig [AdcManChannel_LAST]
static bool _active = false
static AdcPoweredChannel_t _poweredSensorsEnabled = AdcPoweredChannel_NONE
static AdcTimerRate_t _timerRate = AdcTimerRate_0400HZ
static AdcManSampleMode_t _sampleMode = AdcManSampleMode_NORMAL
static uint16_t _highSpeedActiveChannels = 1u
static AdcChannelData_t _channels [AdcManChannel_LAST]
Detailed Description
Analog to digital conversion manager. Project 1814 IOLab Remote Sensor Application
Description The analog to digital conversion manager will provide configuration functions and macros for accessing analog conversion samples.
Definition in file AdcManager.c.
Data Structure Documentation
struct AdcChannelData_t
Defines a structure that will hold all the necessary data for a channel to be sampled
Definition at line 56 of file AdcManager.c.
Data Fields
AdcDataCallback_t
callback
Store the callback that knows how to handle the data
uint16_t
sampleData
Stores the last ADC value that was kept
uint16_t
skippedSamples
Store the number of samples that have been skipped since the last one was kept.
EveryXSamples_t
skipSamples
Store the number of samples to skip to achieve the data rate
Macro Definition Documentation
#define ADC_REFERENCE (AdcReference_eVREFp_VREFm)
Defines the reference to use for all of the adc channels
Definition at line 71 of file AdcManager.c.
Referenced by AdcManager_AdcManRefToAdcRef(), AdcManager_Init(), and AdcManager_SingleSampleBlocking().
#define ADC_THERMOMETER_REFERENCE (AdcReference_VREFp_AVSS)
Defines the reference to use for the thermometer
Definition at line 73 of file AdcManager.c.
Referenced by _SetupAdcForNormalMode(), AdcManager_EnableChannel(), and AdcManager_Init().
#define ADC_THERMOMETER_REFERENCE_VOLTAGE (AdcReferenceLevel_1p5_VOLTS)
Defines the reference voltage for the thermometer
Definition at line 75 of file AdcManager.c.
Referenced by _InitialzeXAdcChannels(), and AdcManager_SingleSampleBlocking().
Enumeration Type Documentation
enum AdcManSampleMode_t
Defines the sampling modes of the ADC Manager
Definition at line 110 of file AdcManager.c.
enum AdcPoweredChannel_t
Defines the number of powered sensors. This must be a binary flag enum
Definition at line 78 of file AdcManager.c.
enum AdcSamplesNeeded_t
Defines how many channels need to be used for different sample rates
Definition at line 100 of file AdcManager.c.
enum AdcTimerRate_t
Enum for the ADC timer rate that triggers the conversions
Definition at line 87 of file AdcManager.c.
enum EveryXSamples_t
Defines how many ADC samples to drop to achieve `slower` sample rates assuming a 400Hz sample rate
Definition at line 39 of file AdcManager.c.
Function Documentation
static __inline void _AdcStart (void) [static]
Starts the ADC and its timer.
Definition at line 870 of file AdcManager.c.
Referenced by AdcManager_EnableChannel().
static __inline void _AdcStop (void) [static]
Stops the ADC and its timer.
Definition at line 881 of file AdcManager.c.
Referenced by AdcManager_DisableChannel(), and AdcManager_EnableChannel().
bool _AllChannelsDisabled (void) [static]
Checks to see if all of the ADC channels are disabled.
Returns
True if all channels are disabled, False otherwise
Definition at line 678 of file AdcManager.c.
Referenced by AdcManager_DisableChannel(), and AdcManager_EnableChannel().
EveryXSamples_t _GetSamplesToSkip (AdcManSampleRate_t sampleRate) [static]
Accepts an ADC sample rate and converts that rate into the number of ADC samples that must be skipped in able to achieve that sample rate.
Parameters
in sampleRate - The desired ADC sample rate
Returns
The number of samples to skip to get the desired sample rate
Definition at line 620 of file AdcManager.c.
Referenced by AdcManager_EnableChannel().
static __inline void _InitialzeXAdcChannels (uint16_t x) [static]
Initializes all of the ADC channels to be used in the ADC driver.
Parameters
in x - the number of channels to initialize the ADC to sample
Definition at line 700 of file AdcManager.c.
Referenced by _SetupTimerConfig().
static __inline void _SetupAdcForNormalMode (AdcManRef_t reference) [static]
Sets the proper variables, timers, and ADC settings for the normal sampling mode.
Definition at line 893 of file AdcManager.c.
Referenced by AdcManager_DisableChannel(), AdcManager_EnableChannel(), and AdcManager_Init().
void _SetupTimerConfig (void) [static]
Sets up the array of channel configs with the proper settings for the current mode.
Definition at line 710 of file AdcManager.c.
Referenced by _SetupAdcForNormalMode(), AdcManager_EnableChannel(), and AdcManager_SingleSampleBlocking().
AdcReference_t AdcManager_AdcManRefToAdcRef (AdcManRef_t adcManRef)
Takes an ADC manager reference and converts it to an ADC reference
This function should only be used internally to the ADC manager, except for board level test and debugging purposes.
Parameters
in adcManRef - the AdcManRef_t ADC Manager analog reference selection
Returns
The AdcReference_t reference for the ADC driver
Definition at line 844 of file AdcManager.c.
Referenced by _SetupAdcForNormalMode(), and AdcManager_EnableChannel().
void AdcManager_DisableChannel (AdcManChannel_t channel)
Disables an ADC channel and clears its callback pointer. Also disables the ADC module if this was the last/only active channel.
Parameters
in channel - the desired sample channel to stop
Definition at line 455 of file AdcManager.c.
Referenced by AmbientLightControl_SetConfig(), Analog7Control_SetConfig(), Analog8Control_SetConfig(), Analog9Control_SetConfig(), BatteryControl_SetConfig(), EcgControl_SetConfig(), FgControl_SetConfig(), HighGainControl_SetConfig(), MicrophoneControl_SetConfig(), and ThermometerControl_SetConfig().
void AdcManager_EnableChannel (AdcManChannel_t channel, AdcManSampleRate_t rate, AdcManRef_t reference, AdcDataCallback_t callback)
Enables an ADC channel and starts sampling it at the given rate. The data from each sample will be passed into the callback function. Also enables the ADC module if this was the first/only active channel.
Parameters
in channel - the desired sample channel
in rate - the rate at which to pass a sample into the callback function
in callback - the function to call to pass the ADC sample data to
Definition at line 300 of file AdcManager.c.
Referenced by AmbientLightControl_SetConfig(), Analog7Control_SetConfig(), Analog8Control_SetConfig(), Analog9Control_SetConfig(), BatteryControl_SetConfig(), EcgControl_SetConfig(), FgControl_SetConfig(), HighGainControl_SetConfig(), MicrophoneControl_SetConfig(), and ThermometerControl_SetConfig().
uint16_t AdcManager_GetGainFactor (void)
Gets the ADC gain factor that can be used to scale the ADC readings for higher accuracy.
Returns
The ADC gain factor
Definition at line 594 of file AdcManager.c.
Referenced by BatteryControl_ReadCalibration().
uint16_t AdcManager_GetOffset (void)
Gets the ADC offset that can be used to shift the ADC readings for higher accuracy.
Returns
The ADC offset
Definition at line 606 of file AdcManager.c.
Referenced by BatteryControl_ReadCalibration().
void AdcManager_Init (void)
Initializes the ADC manager
Definition at line 265 of file AdcManager.c.
Referenced by main().
void AdcManager_PoweredChannelControl (AdcManChannel_t channel, bool enable)
Takes an ADC channel and if it is a powered channel will enable or disable the power rail for the channel.
This function should only be used internally to the ADC manager, except for board level test and debugging purposes.
Parameters
in channel - the channel that should be enabled or disabled
in enable - true to enable, false to disable
Definition at line 788 of file AdcManager.c.
Referenced by AdcManager_DisableChannel(), AdcManager_EnableChannel(), and SelfTest_Process().
void AdcManager_ProcessConversion (void)
Should be called by the event handler for processing the ADC conversion complete event. This function will take the converted ADC data from the buffer and call the ADC sample callback functions at the desired rate.
Definition at line 559 of file AdcManager.c.
Referenced by _ProcessEvents_DEFAULT().
uint16_t AdcManager_SingleSampleBlocking (AdcManChannel_t channel)
Takes a single sample of an ADC channel and returns the raw ADC counts
Parameters
in channel - the ADC channel which to sample
Returns
the value in raw ADC counts of the ADC channel.
Definition at line 509 of file AdcManager.c.
Referenced by _HandleHumanAdc1Command().
Variable Documentation
bool _active = false [static]
Tracks if the ADC is active or not
Definition at line 135 of file AdcManager.c.
Referenced by _AdcStart(), _AdcStop(), and AdcManager_SingleSampleBlocking().
AdcChannelConfig_t _adcAllChannelConfig[AdcManChannel_LAST] [static]
Stores the configuration information for all the ADC channels
Definition at line 132 of file AdcManager.c.
AdcChannelData_t _channels[AdcManChannel_LAST] [static]
Stores the data from the ADC conversion
Definition at line 149 of file AdcManager.c.
const AdcConfig_t _fastAdcConfig = { AdcConSeq_SEQ_OF_CHAN, AdcSht_0008, false } [static]
This configuration will set the ADC to sample for the high speed settings
Definition at line 121 of file AdcManager.c.
const AdcConfig_t _fastMultiAdcConfig = { AdcConSeq_SEQ_OF_CHAN, AdcSht_0008, true } [static]
This configuration will set the ADC to sample for the multi-channel high speed settings
Definition at line 125 of file AdcManager.c.
uint16_t _highSpeedActiveChannels = 1u [static]
tracks how many unique high speed channels are currently active
Definition at line 146 of file AdcManager.c.
Referenced by _SetupAdcForNormalMode(), _SetupTimerConfig(), AdcManager_DisableChannel(), and AdcManager_EnableChannel().
bool _initialized = false [static]
tracks if the ADC manager is initialized
Definition at line 129 of file AdcManager.c.
const AdcConfig_t _normAdcConfig = { AdcConSeq_SEQ_OF_CHAN, AdcSht_0384, true } [static]
This configuration will set the ADC to sample for the normal modes
Definition at line 123 of file AdcManager.c.
AdcManSampleMode_t _sampleMode = AdcManSampleMode_NORMAL [static]
tracks the current sample mode of the ADC Manager
Definition at line 143 of file AdcManager.c.
Referenced by _SetupAdcForNormalMode(), AdcManager_DisableChannel(), and AdcManager_EnableChannel().
AdcTimerRate_t _timerRate = AdcTimerRate_0400HZ [static]
tracks the timer rate which the ADC uses for sampling
Definition at line 140 of file AdcManager.c.
Referenced by _SetupAdcForNormalMode(), _SetupTimerConfig(), and AdcManager_EnableChannel().