Adc.h File Reference
Analog to digital conversion module header file.
Data Structures
struct AdcChannelConfig_t
struct AdcConfig_t
Macros
#define ADC_NUM_CONVERSION_MEMORY_REGISTERS (16u)
#define ADC_SEQUENCE_MAX_LENGTH (ADC_NUM_CONVERSION_MEMORY_REGISTERS)
Enumerations
enum AdcReference_t {
*
AdcReference_AVCC_AVSS = 0u,
*
AdcReference_VREFp_AVSS = 1u,
*
AdcReference_eVREFp_AVSS = 2u,
*
AdcReference_AVCC_VREFm = 4u,
*
AdcReference_VREFp_VREFm = 5u,
*
AdcReference_eVREFp_VREFm = 6u
 }
enum AdcInputChannel_t {
*
AdcInputChannel_INVALID = -1,
*
AdcInputChannel_FIRST = 0u,
*
AdcInputChannel_A0 = 0u,
*
AdcInputChannel_A1 = 1u,
*
AdcInputChannel_A2 = 2u,
*
AdcInputChannel_A3 = 3u,
*
AdcInputChannel_A4 = 4u,
*
AdcInputChannel_A5 = 5u,
*
AdcInputChannel_A6 = 6u,
*
AdcInputChannel_A7 = 7u,
*
AdcInputChannel_eVREFp = 8u,
*
AdcInputChannel_VREFm = 9u,
*
AdcInputChannel_TEMP = 10u,
*
AdcInputChannel_AVCC_AVSS = 11u,
*
AdcInputChannel_A12 = 12u,
*
AdcInputChannel_A13 = 13u,
*
AdcInputChannel_A14 = 14u,
*
AdcInputChannel_A15 = 15u,
*
AdcInputChannel_LAST
 }
enum AdcConSeq_t {
*
AdcConSeq_SING_CHAN_SING_CONV = 0x00u,
*
AdcConSeq_SEQ_OF_CHAN = 0x01u,
*
AdcConSeq_REPEAT_SING_CHAN = 0x02u,
*
AdcConSeq_REPEAT_SEQ_CHAN = 0x03u
 }
enum AdcSht_t {
*
AdcSht_INVALID = -1,
*
AdcSht_FIRST = 0x0u,
*
AdcSht_0004 = 0x0u,
*
AdcSht_0008 = 0x01u,
*
AdcSht_0016 = 0x02u,
*
AdcSht_0032 = 0x03u,
*
AdcSht_0064 = 0x04u,
*
AdcSht_0096 = 0x05u,
*
AdcSht_0128 = 0x06u,
*
AdcSht_0192 = 0x07u,
*
AdcSht_0256 = 0x08u,
*
AdcSht_0384 = 0x09u,
*
AdcSht_0512 = 0x0Au,
*
AdcSht_0768 = 0x0Bu,
*
AdcSht_1024 = 0x0Cu,
*
AdcSht_LAST
 }
enum AdcCorrection_t {
*
AdcCorrection_GAIN_OFFSET,
*
AdcCorrection_REF,
*
AdcCorrection_REF_GAIN_OFFSET
 }
enum AdcReferenceLevel_t {
*
AdcReferenceLevel_1p5_VOLTS = 0,
*
AdcReferenceLevel_2p0_VOLTS,
*
AdcReferenceLevel_2p5_VOLTS,
*
AdcReferenceLevel_DONT_CARE
 }
Functions
void Adc_Init (void)
void Adc_Config (const AdcConfig_t *config)
bool Adc_IsConversionInProgress (void)
void Adc_SetChannelSequence (const AdcChannelConfig_t config[], uint16_t numChannels, AdcReferenceLevel_t refLevel)
void Adc_StartConversionSequenceOfChannels (void)
void Adc_SingleConversionSequenceBlocking (void)
void Adc_StopConversion (void)
uint16_t Adc_GetNumberOfConversions (void)
uint16_t Adc_GetGainFactor (void)
uint16_t Adc_GetOffset (void)
void Adc_GetTempCalib (uint16_t *cal85C, uint16_t *cal30C)
int16_t Adc_ConvertValueToTemp (uint16_t value)
void Adc_ApplyCorrection (AdcCorrection_t correction, uint16_t numValuesToCorrect, const uint16_t rawValues[], uint16_t correctedValues[])
Detailed Description
Analog to digital conversion module header file. Project 1814 IOLab Remote Sensor Application
Description Header file for the 12-bit ADC module.
Definition in file Adc.h.
Data Structure Documentation
struct AdcChannelConfig_t
Struct that contains the configuration for a channel in conversion sequence.
Definition at line 72 of file Adc.h.
Data Fields
uint16_t *
destination
AdcInputChannel_t
inputChannel
AdcReference_t
reference
struct AdcConfig_t
Struct that contains the configurable settings of the ADC module
Definition at line 129 of file Adc.h.
Data Fields
AdcConSeq_t
conSeq
bool
multipleSampleConversion
AdcSht_t
sampleHoldTime
Macro Definition Documentation
#define ADC_NUM_CONVERSION_MEMORY_REGISTERS (16u)
Number of conversion memory registers in the ADC module.
Definition at line 26 of file Adc.h.
Referenced by _AdcIsr(), _MoveSamplesToUserLocation(), and Adc_SetChannelSequence().
#define ADC_SEQUENCE_MAX_LENGTH (ADC_NUM_CONVERSION_MEMORY_REGISTERS)
Maximum number of channels in a conversion sequence.
Definition at line 28 of file Adc.h.
Referenced by Adc_SetChannelSequence(), Adc_SingleConversionSequenceBlocking(), and Adc_StartConversionSequenceOfChannels().
Enumeration Type Documentation
enum AdcConSeq_t
Enum for the ADC Conversion Sequence options.
Definition at line 80 of file Adc.h.
enum AdcCorrection_t
Available ADC corrections that can be performed using the available calibration information.
Definition at line 112 of file Adc.h.
enum AdcInputChannel_t
Possible ADC input channels. Enumeration values are defined to equal ADC register values.
Definition at line 46 of file Adc.h.
enum AdcReference_t
Possible ADC conversion references. Enumeration values are defined to equal ADC register values.
Definition at line 33 of file Adc.h.
enum AdcReferenceLevel_t
Possible ADC interval voltage reference levels.
Definition at line 120 of file Adc.h.
enum AdcSht_t
Enum for the ADC sample and hold time options in # clock cycles
Definition at line 89 of file Adc.h.
Function Documentation
void Adc_ApplyCorrection (AdcCorrection_t correction, uint16_t numValuesToCorrect, const uint16_t rawValues[], uint16_t correctedValues[])
Applies the given correction to ADC raw values. These corrections are based on the ADC and internal voltage reference (REF) calibration values.
Parameters
in correction - Correction to perform.
in numValuesToCorrect - Number of values to correct.
in rawValues - Raw ADC values to correct.
out correctedValues - Corrected ADC values.
Definition at line 645 of file Adc.c.
void Adc_Config (const AdcConfig_t * config)
Configures the ADC module to use the specific ADC global configuration settings
Parameters
in config - Configuration information for the ADC module
Definition at line 195 of file Adc.c.
Referenced by _SetupAdcForNormalMode(), Adc_Init(), and AdcManager_EnableChannel().
int16_t Adc_ConvertValueToTemp (uint16_t value)
Converts an ADC raw value to a temperature in degrees Celsius.
The raw ADC value should not be corrected in any way before being passed to this function, as the calibration values used to perform the conversion take the other corrections into account.
Parameters
in value - Raw ADC value to convert.
Returns
The temperature in degrees Celsius.
Definition at line 557 of file Adc.c.
uint16_t Adc_GetGainFactor (void)
Gets the ADC gain factor that can be used to scale the ADC readings for higher accuracy.
Returns
The ADC gain factor
Definition at line 492 of file Adc.c.
Referenced by AdcManager_GetGainFactor().
uint16_t Adc_GetNumberOfConversions (void)
Returns the number of conversions that have occurred since this function was last called.
Definition at line 443 of file Adc.c.
Referenced by AdcManager_ProcessConversion().
uint16_t Adc_GetOffset (void)
Gets the ADC offset that can be used to shift the ADC readings for higher accuracy.
Returns
The ADC offset
Definition at line 505 of file Adc.c.
Referenced by AdcManager_GetOffset().
void Adc_GetTempCalib (uint16_t * cal85C, uint16_t * cal30C)
Gets the ADC calibration that is used for temperature conversion for more accurate readings.
Parameters
out cal85C - the calibration value at 85°C
out cal30C - the calibration value at 30°C
Definition at line 519 of file Adc.c.
Referenced by ThermometerControl_ReadCalibration().
void Adc_Init (void)
This function initializes the ADC variables.
Each channel is sampled for about 3 microseconds. Each conversion (sample time + conversion time) takes about 6 microseconds.
Note
The reference voltage takes 75 microseconds to settle (typical) and the temperature sensor, which is sourced by the reference voltage, requires a minimum sampling time of 30 microseconds.
Definition at line 144 of file Adc.c.
Referenced by AdcManager_Init().
bool Adc_IsConversionInProgress (void)
Returns
True if a conversion is in progress, false otherwise.
Definition at line 253 of file Adc.c.
void Adc_SetChannelSequence (const AdcChannelConfig_t config[], uint16_t numChannels, AdcReferenceLevel_t refLevel)
Configures the ADC module to sample the given sequence of channels.
Parameters
in config - Configuration information for each channel in the sequence.
in numChannels - Number of channels in the sequence.
Definition at line 265 of file Adc.c.
Referenced by _InitialzeXAdcChannels(), and AdcManager_SingleSampleBlocking().
void Adc_SingleConversionSequenceBlocking (void)
Starts the conversion of a sequence of channels and blocks until they are finished.
Definition at line 387 of file Adc.c.
Referenced by AdcManager_SingleSampleBlocking().
void Adc_StartConversionSequenceOfChannels (void)
Starts the conversion of a sequence of channels.
Definition at line 371 of file Adc.c.
Referenced by _AdcStart().
void Adc_StopConversion (void)
Stops the ADC from sampling.
Definition at line 433 of file Adc.c.
Referenced by _AdcStop().