AmbientLightControl.c File Reference
Controls reading the ambient light sensor.
#include <ProjectTypes.h>
*
#include `AmbientLightControl.h`
*
#include <SensorId.h>
*
#include <DataBuffer.h>
*
#include <KeyValue.h>
*
#include <AdcManager.h>
*
#include <Assert.h>
*
#include <Serial.h>
*
Functions
static void _AmbientLightDataCallback (uint16_t data)
void AmbientLightControl_Init (void)
void AmbientLightControl_SetConfig (uint8_t config)
Variables
static bool _initialized = false
static AmbientLightSampleRate_t _sampleRate = DEFAULT_AMBIENT_LIGHT_SAMPLE_RATE
Detailed Description
Controls reading the ambient light sensor. Project 1814 IOLab Remote Sensor Application
Description Controls the ambient light sensor and manages the configurations and settings associated with the ambient light sensor.
Definition in file AmbientLightControl.c.
Function Documentation
static void _AmbientLightDataCallback (uint16_t data) [static]
Takes the ambient light sensor data and stores it in the proper location. This function is designed to be called every time there is data for the ambient light sensor.
Parameters
in data - The sample from the ambient light sensor that should be stored in the proper location.
Definition at line 164 of file AmbientLightControl.c.
Referenced by AmbientLightControl_SetConfig().
void AmbientLightControl_Init (void)
Initializes the ambient light sensor reading control.
Definition at line 51 of file AmbientLightControl.c.
Referenced by ConMan_Init().
void AmbientLightControl_SetConfig (uint8_t config)
Takes a configuration and sets it for the ambient light sensor reading.
Parameters
in config - the KeyValue configuration setting for the ambient light sensor reading.
Definition at line 63 of file AmbientLightControl.c.
Referenced by ConMan_SetSensorConfig().
Variable Documentation
bool _initialized = false [static]
Tracks if the module has been initialized
Definition at line 39 of file AmbientLightControl.c.
AmbientLightSampleRate_t _sampleRate = DEFAULT_AMBIENT_LIGHT_SAMPLE_RATE [static]
Stores the desired sample rate of the ambient light sensor voltage reading
Definition at line 42 of file AmbientLightControl.c.
Referenced by AmbientLightControl_SetConfig().