Analog9Control.c File Reference
Controls reading analog input in header pin 9.
#include <ProjectTypes.h>
*
#include `Analog9Control.h`
*
#include <SensorId.h>
*
#include <DataBuffer.h>
*
#include <KeyValue.h>
*
#include <AdcManager.h>
*
#include <Board.h>
*
#include <Gpio.h>
*
#include <Device.h>
*
#include <Assert.h>
*
#include <Serial.h>
*
Functions
static AdcManRef_t _Analog9_RefVoltToAdcManRef (Analog9RefVolt_t refVolt)
static void _Analog9DataCallback (uint16_t data)
void Analog9Control_Init (void)
void Analog9Control_SetConfig (uint8_t config)
Variables
static bool _initialized = false
static Analog9SampleRate_t _sampleRate = DEFAULT_ANALOG9_SAMPLE_RATE
static Analog9RefVolt_t _refVolt = DEFAULT_ANALOG9_REF_VOLT
Detailed Description
Controls reading analog input in header pin 9. Project 1814 IOLab Remote Sensor Application
Description Controls the analog input on header pin 9 and manages the configurations and settings associated with it.
Definition in file Analog9Control.c.
Function Documentation
static AdcManRef_t _Analog9_RefVoltToAdcManRef (Analog9RefVolt_t refVolt) [static]
Converts from an Analog9RefVolt_t to an AdcManRef_t.
Parameters
in refVolt - the voltage reference selection to match
Returns
The AdcManRef_t value corresponding to the refVolt value
Definition at line 178 of file Analog9Control.c.
Referenced by Analog9Control_SetConfig().
static void _Analog9DataCallback (uint16_t data) [static]
Takes the analog input data from header pin 9 and stores it in the proper location. This function is designed to be called every time there is data for the analog header pin 9.
Parameters
in data - The sample from header pin 9 that should be stored in the proper location.
Definition at line 208 of file Analog9Control.c.
Referenced by Analog9Control_SetConfig().
void Analog9Control_Init (void)
Initializes the header pin 9 reading control.
Definition at line 57 of file Analog9Control.c.
Referenced by ConMan_Init().
void Analog9Control_SetConfig (uint8_t config)
Takes a configuration and sets it for the header pin.
Parameters
in config - the KeyValue configuration setting for the header pin.
Definition at line 68 of file Analog9Control.c.
Referenced by ConMan_SetSensorConfig().
Variable Documentation
bool _initialized = false [static]
Tracks if the module has been initialized
Definition at line 41 of file Analog9Control.c.
Analog9RefVolt_t _refVolt = DEFAULT_ANALOG9_REF_VOLT [static]
Stores the desired analog reference voltage of the header pin
Definition at line 47 of file Analog9Control.c.
Referenced by Analog9Control_SetConfig().
Analog9SampleRate_t _sampleRate = DEFAULT_ANALOG9_SAMPLE_RATE [static]
Stores the desired sample rate of the header pin
Definition at line 44 of file Analog9Control.c.
Referenced by Analog9Control_SetConfig().