BarometerControl.h File Reference
Controls the barometer driver.
Functions
void BarometerControl_Init (void)
void BarometerControl_SetConfig (uint8_t value)
void BarometerControl_ReadBar (void)
void BarometerControl_ReadCalibration (uint16_t maxCalibrationLength, uint16_t *actualCalibrationLength, uint8_t calibration[])
Detailed Description
Controls the barometer driver. Project 1814 IOLab Remote Sensor Application
Description Controls the barometer driver and controls the configuration for it.
Definition in file BarometerControl.h.
Function Documentation
void BarometerControl_Init (void)
Initializes the barometer controller.
Definition at line 86 of file BarometerControl.c.
Referenced by ConMan_Init().
void BarometerControl_ReadBar (void)
Gets a reading from the Barometer.
Definition at line 190 of file BarometerControl.c.
Referenced by BarometerControl_SetConfig().
void BarometerControl_ReadCalibration (uint16_t maxCalibrationLength, uint16_t * actualCalibrationLength, uint8_t calibration[])
Reads the calibration values from the barometer.
Parameters
in maxCalibrationLength - the maximum number of bytes allocated for calibration[]
out actualCalibrationLength - the number of bytes of calibration data placed in calibration[]
out calibration[] - the calibration data from the barometer.
Definition at line 244 of file BarometerControl.c.
Referenced by ConMan_GetCalibration().
void BarometerControl_SetConfig (uint8_t keyValue)
Sets a configuration value to the Barometer
Parameters
in keyValue - the key/value pair with the configuration information
Definition at line 98 of file BarometerControl.c.
Referenced by ConMan_SetSensorConfig().