Barometer.c File Reference
Driver for the barometer sensor.
#include <ProjectTypes.h>
*
#include `Barometer.h`
*
#include <Clock.h>
*
#include <Gpio.h>
*
#include <Device.h>
*
#include <Board.h>
*
#include <SpiMaster.h>
*
#include <Assert.h>
*
Macros
#define CONVERSION_US 5000u
#define BAROMETER_START_SPI_XFER GPIO_CLEAR(CS_BAROMETER_PORT, CS_BAROMETER_PIN);
#define BAROMETER_END_SPI_XFER GPIO_SET(CS_BAROMETER_PORT, CS_BAROMETER_PIN);
#define BLANK_BYTE 0u
#define BYTES_PER_SAMPLE 4u
#define NUM_COEFF_BYTES 8u
#define SPI_CS_DELAY_US 1u
Enumerations
enum BarometerReg_t {
*
BarometerReg_PADC_MSB = 0x00<<1,
*
BarometerReg_PADC_LSB = 0x01<<1,
*
BarometerReg_TADC_MSB = 0x02<<1,
*
BarometerReg_TADC_LSB = 0x03<<1,
*
BarometerReg_A0_MSB = 0x04<<1,
*
BarometerReg_A0_LSB = 0x05<<1,
*
BarometerReg_B1_MSB = 0x06<<1,
*
BarometerReg_B1_LSB = 0x07<<1,
*
BarometerReg_B2_MSB = 0x08<<1,
*
BarometerReg_B2_LSB = 0x09<<1,
*
BarometerReg_C12_MSB = 0x0A<<1,
*
BarometerReg_C12_LSB = 0x0B<<1,
*
BarometerReg_CONVERT = 0x12<<1
 }
Functions
uint8_t _BarReadRegister (BarometerReg_t regAddress)
void _BarWriteRegister (BarometerReg_t regAddress, uint8_t regValue)
void _BarReadMultipleRegisters (BarometerReg_t regStartAddress, uint8_t numberOfRegisters, uint8_t values[])
void Barometer_Init (void)
void Barometer_Config (const BarometerConfig_t *config)
void Barometer_Start (void)
void Barometer_Stop (void)
void Barometer_TriggerSampleBlocking (BarometerSample_t *sample)
void Barometer_StartSampleConversion (void)
bool Barometer_ReadSample (BarometerSample_t *sample)
bool Barometer_ReadSampleArray (uint16_t maxLength, uint16_t *actualLength, uint8_t data[])
void Barometer_ReadCoefficients (BarometerCoef_t *coefficients)
void Barometer_ReadCoeffArray (uint16_t maxLength, uint16_t *actualLength, uint8_t coefficients[])
Variables
static volatile bool _conversionInProgress = false
Detailed Description
Driver for the barometer sensor. Project 1814 IOLab Remote Sensor Application
Description This module interfaces to a SPI barometer sensor to read the barometric pressure and temperature data. This driver is designed to work with a Freescale MPL115A1 SPI Barometer.
Definition in file Barometer.c.
Macro Definition Documentation
#define BAROMETER_START_SPI_XFER GPIO_CLEAR(CS_BAROMETER_PORT, CS_BAROMETER_PIN);
Defines the chip select enable and disable for the barometer
Definition at line 63 of file Barometer.c.
Referenced by _BarReadMultipleRegisters(), _BarReadRegister(), and _BarWriteRegister().
#define BLANK_BYTE 0u
Defines the value of a `Blank Byte` to write to the barometer
Definition at line 67 of file Barometer.c.
Referenced by _BarReadMultipleRegisters(), and Barometer_StartSampleConversion().
#define BYTES_PER_SAMPLE 4u
Defines the number of registers to read a sample
Definition at line 70 of file Barometer.c.
Referenced by Barometer_ReadSample(), and Barometer_ReadSampleArray().
#define CONVERSION_US 5000u
defines how long the Barometer conversion takes in microseconds
Definition at line 60 of file Barometer.c.
Referenced by Barometer_TriggerSampleBlocking().
#define NUM_COEFF_BYTES 8u
Defines the number of registers to read the coefficients
Definition at line 73 of file Barometer.c.
Referenced by Barometer_ReadCoeffArray(), and Barometer_ReadCoefficients().
#define SPI_CS_DELAY_US 1u
Defines the number of microseconds to delay between de/asserting the chip select line and ending/starting the SPI communication to allow the chip to become ready
Definition at line 78 of file Barometer.c.
Referenced by _BarReadMultipleRegisters(), _BarReadRegister(), and _BarWriteRegister().
Enumeration Type Documentation
enum BarometerReg_t
Defines the valid register addresses for the barometer registers
Note
The values in the barometer are shifted left 1 bit from the datasheet definition (<<1).
Enumerator
BarometerReg_PADC_LSB
 pressure ADC MSB
BarometerReg_TADC_MSB
 pressure ADC LSB
BarometerReg_TADC_LSB
 temperature ADC MSB
BarometerReg_A0_MSB
 temperature ADC LSB
BarometerReg_A0_LSB
 pressure offset coefficient MSB
BarometerReg_B1_MSB
 pressure offset coefficient LSB
BarometerReg_B1_LSB
 pressure sensitivity coefficient MSB
BarometerReg_B2_MSB
 pressure sensitivity coefficient LSB
BarometerReg_B2_LSB
 temperature offset coefficient MSB
BarometerReg_C12_MSB
 temperature offset coefficient LSB
BarometerReg_C12_LSB
 temperature sensitivity coefficient MSB
BarometerReg_CONVERT
 temperature sensitivity coefficient LSB
Definition at line 41 of file Barometer.c.
Function Documentation
void _BarReadMultipleRegisters (BarometerReg_t regStartAddress, uint8_t numberOfRegisters, uint8_t values[])
Reads from consecutive registers using the SPI port.
Parameters
in regStartAddress - the register address to read from the device
in numberOfRegisters - the number of consecutive registers to read
in values[] - the location to store the register values
Note
The length of values >= numberOfRegisters
Definition at line 288 of file Barometer.c.
Referenced by Barometer_ReadCoeffArray(), Barometer_ReadCoefficients(), Barometer_ReadSample(), and Barometer_ReadSampleArray().
uint8_t _BarReadRegister (BarometerReg_t regAddress)
Reads from a specific register using the SPI port.
Parameters
in regAddress - the register address to read from the device
Returns
The value read from the register.
Definition at line 250 of file Barometer.c.
void _BarWriteRegister (BarometerReg_t regAddress, uint8_t regValue)
Writes a value to a specific register using the SPI port.
Parameters
in regAddress - the register address to write at on device
in regValue - the value at regAddress
Definition at line 269 of file Barometer.c.
Referenced by Barometer_StartSampleConversion().
void Barometer_ReadCoeffArray (uint16_t maxLength, uint16_t * actualLength, uint8_t coefficients[])
Reads in the conversion coefficients from the barometer
Parameters
in maxLength - the number of bytes allocated for coefficients[]
out actualLength - the actual number of bytes that were put in coefficients[]
out coefficients[] - the coefficient data from the barometer
Definition at line 230 of file Barometer.c.
Referenced by BarometerControl_ReadCalibration().
void Barometer_ReadCoefficients (BarometerCoef_t * coefficients)
Reads in the value of the conversion coefficients from the barometer
Parameters
in coefficients - the location to store the coefficients
Definition at line 205 of file Barometer.c.
Referenced by _HandleHumanBarcCommand().
bool Barometer_ReadSample (BarometerSample_t * sample)
Reads in the value of the conversion from the barometer
Parameters
in sample- the location to store the sample data.
Returns
True if a sample conversion was already in progress and the data could be read, false otherwise. True does NOT mean the sample was ready, just that the conversion was started before the reading.
Definition at line 147 of file Barometer.c.
Referenced by Barometer_TriggerSampleBlocking(), and BarometerControl_ReadBar().
bool Barometer_ReadSampleArray (uint16_t maxLength, uint16_t * actualLength, uint8_t data[])
Reads in the value of the conversion from the barometer
Parameters
in maxLength - the number of bytes allocated for data[]
out actualLength - the actual number of bytes that were put in data[]
out data[] - the pressure and temperature data from the barometer
Returns
True if a sample conversion was already in progress and the data could be read, false otherwise. True does NOT mean the sample was ready, just that the conversion was started before the reading.
Definition at line 184 of file Barometer.c.
Referenced by BarometerControl_ReadBar().
void Barometer_StartSampleConversion (void)
Starts a barometer conversion on the sensor.
Definition at line 131 of file Barometer.c.
Referenced by Barometer_TriggerSampleBlocking(), BarometerControl_ReadBar(), and BarometerControl_SetConfig().
void Barometer_TriggerSampleBlocking (BarometerSample_t * sample)
Starts a sample conversion on the Barometer and blocks until it is complete and returns the data from that conversion.
Parameters
in sample - the location to store the result of the sample conversion
Definition at line 107 of file Barometer.c.
Referenced by _HandleHumanBarCommand().
Variable Documentation
volatile bool _conversionInProgress = false [static]
Define a variable that will track if the barometer conversion is in progress
Definition at line 82 of file Barometer.c.
Referenced by Barometer_ReadSample(), and Barometer_StartSampleConversion().