Barometer.h File Reference
Header file for Barometer (and temperature)sensor driver.
Data Structures
struct BarometerConfig_t
struct BarometerSample_t
struct BarometerCoef_t
Enumerations
enum BarSampleRate_t { BarSampleRate_10
 }
Functions
void Barometer_Init (void)
void Barometer_Config (const BarometerConfig_t *config)
void Barometer_Start (void)
void Barometer_Stop (void)
void Barometer_TriggerSampleBlocking (BarometerSample_t *sample)
void Barometer_StartSampleConversion (void)
bool Barometer_ReadSample (BarometerSample_t *sample)
bool Barometer_ReadSampleArray (uint16_t maxLength, uint16_t *actualLength, uint8_t data[])
void Barometer_ReadCoefficients (BarometerCoef_t *coefficients)
void Barometer_ReadCoeffArray (uint16_t maxLength, uint16_t *actualLength, uint8_t coefficients[])
Detailed Description
Header file for Barometer (and temperature)sensor driver. Project 1814 IOLab Remote Sensor Application
Description The barometer sensor driver accesses the pressure and temperature readings from the barometer sensor.
Definition in file Barometer.h.
Data Structure Documentation
struct BarometerConfig_t
Defines a structure to hold the barometer configuration settings
Definition at line 33 of file Barometer.h.
Data Fields
BarSampleRate_t
sampleRate
struct BarometerSample_t
Defines a structure to hold the barometer sample data in
Definition at line 39 of file Barometer.h.
Data Fields
uint16_t
pressure
uint16_t
temperature
struct BarometerCoef_t
Definition at line 45 of file Barometer.h.
Data Fields
uint16_t
a0
uint16_t
b1
Pressure offset coefficient.
uint16_t
b2
Pressure sensitivity coefficient.
uint16_t
c12
temperature coefficient of offset
Enumeration Type Documentation
enum BarSampleRate_t
Defines the options for the barometer sample rates in Hz
Definition at line 27 of file Barometer.h.
Function Documentation
void Barometer_ReadCoeffArray (uint16_t maxLength, uint16_t * actualLength, uint8_t coefficients[])
Reads in the conversion coefficients from the barometer
Parameters
in maxLength - the number of bytes allocated for coefficients[]
out actualLength - the actual number of bytes that were put in coefficients[]
out coefficients[] - the coefficient data from the barometer
Definition at line 230 of file Barometer.c.
Referenced by BarometerControl_ReadCalibration().
void Barometer_ReadCoefficients (BarometerCoef_t * coefficients)
Reads in the value of the conversion coefficients from the barometer
Parameters
in coefficients - the location to store the coefficients
Definition at line 205 of file Barometer.c.
Referenced by _HandleHumanBarcCommand().
bool Barometer_ReadSample (BarometerSample_t * sample)
Reads in the value of the conversion from the barometer
Parameters
in sample- the location to store the sample data.
Returns
True if a sample conversion was already in progress and the data could be read, false otherwise. True does NOT mean the sample was ready, just that the conversion was started before the reading.
Definition at line 147 of file Barometer.c.
Referenced by Barometer_TriggerSampleBlocking(), and BarometerControl_ReadBar().
bool Barometer_ReadSampleArray (uint16_t maxLength, uint16_t * actualLength, uint8_t data[])
Reads in the value of the conversion from the barometer
Parameters
in maxLength - the number of bytes allocated for data[]
out actualLength - the actual number of bytes that were put in data[]
out data[] - the pressure and temperature data from the barometer
Returns
True if a sample conversion was already in progress and the data could be read, false otherwise. True does NOT mean the sample was ready, just that the conversion was started before the reading.
Definition at line 184 of file Barometer.c.
Referenced by BarometerControl_ReadBar().
void Barometer_StartSampleConversion (void)
Starts a barometer conversion on the sensor.
Definition at line 131 of file Barometer.c.
Referenced by Barometer_TriggerSampleBlocking(), BarometerControl_ReadBar(), and BarometerControl_SetConfig().
void Barometer_TriggerSampleBlocking (BarometerSample_t * sample)
Starts a sample conversion on the Barometer and blocks until it is complete and returns the data from that conversion.
Parameters
in sample - the location to store the result of the sample conversion
Definition at line 107 of file Barometer.c.
Referenced by _HandleHumanBarCommand().