BatteryControl.c File Reference
Controls reading the battery voltage.
#include <ProjectTypes.h>
*
#include `BatteryControl.h`
*
#include <SensorId.h>
*
#include <DataBuffer.h>
*
#include <KeyValue.h>
*
#include <AdcManager.h>
*
#include <Board.h>
*
#include <Gpio.h>
*
#include <Device.h>
*
#include <Assert.h>
*
#include <Serial.h>
*
Macros
#define NUM_BATTERY_CALIBRATION_BYTES (4u)
Functions
static void _BatteryVoltageDataCallback (uint16_t data)
void BatteryControl_Init (void)
void BatteryControl_SetConfig (uint8_t config)
BatteryCounts_t BatteryControl_GetCounts (void)
void BatteryControl_ReadCalibration (uint16_t maxCalibrationLength, uint16_t *actualCalibrationLength, uint8_t calibration[])
Variables
static bool _initialized = false
static BatterySampleRate_t _sampleRate = DEFAULT_BATTERY_SAMPLE_RATE
Detailed Description
Controls reading the battery voltage. Project 1814 IOLab Remote Sensor Application
Description Controls the force gauge and manages the configurations and settings associated with the force gauge.
Definition in file BatteryControl.c.
Function Documentation
static void _BatteryVoltageDataCallback (uint16_t data) [static]
Takes the battery voltage data and stores it in the proper location. This function is designed to be called every time there is data for the battery voltage.
Parameters
in data - The sample from the battery that should be stored in the proper location.
Definition at line 214 of file BatteryControl.c.
Referenced by BatteryControl_SetConfig().
void BatteryControl_Init (void)
Initializes the battery voltage reading control.
Definition at line 53 of file BatteryControl.c.
Referenced by ConMan_Init().
void BatteryControl_ReadCalibration (uint16_t maxCalibrationLength, uint16_t * actualCalibrationLength, uint8_t calibration[])
Reads the calibration values from the battery.
Parameters
in maxCalibrationLength - the maximum number of bytes allocated for calibration[]
out actualCalibrationLength - the number of bytes of calibration data placed in calibration[]
out calibration[] - the calibration data from the battery.
Definition at line 180 of file BatteryControl.c.
Referenced by ConMan_GetCalibration().
void BatteryControl_SetConfig (uint8_t config)
Takes a configuration and sets it for the battery voltage reading.
Parameters
in config - the KeyValue configuration setting for the battery reading.
Definition at line 64 of file BatteryControl.c.
Referenced by ConMan_SetSensorConfig().
Variable Documentation
bool _initialized = false [static]
Tracks if the module has been initialized
Definition at line 41 of file BatteryControl.c.
BatterySampleRate_t _sampleRate = DEFAULT_BATTERY_SAMPLE_RATE [static]
Stores the desired sample rate of the battery voltage reading
Definition at line 44 of file BatteryControl.c.
Referenced by BatteryControl_SetConfig().