BatteryControl.h File Reference
Controls the battery voltage readings.
Typedefs
typedef uint16_t BatteryCounts_t
Functions
void BatteryControl_Init (void)
void BatteryControl_SetConfig (uint8_t config)
BatteryCounts_t BatteryControl_GetCounts (void)
void BatteryControl_ReadCalibration (uint16_t maxCalibrationLength, uint16_t *actualCalibrationLength, uint8_t calibration[])
Detailed Description
Controls the battery voltage readings. Project 1814 IOLab Remote Sensor Application
Description Controls reading the battery voltage.
Definition in file BatteryControl.h.
Function Documentation
void BatteryControl_Init (void)
Initializes the battery voltage reading control.
Definition at line 53 of file BatteryControl.c.
Referenced by ConMan_Init().
void BatteryControl_ReadCalibration (uint16_t maxCalibrationLength, uint16_t * actualCalibrationLength, uint8_t calibration[])
Reads the calibration values from the battery.
Parameters
in maxCalibrationLength - the maximum number of bytes allocated for calibration[]
out actualCalibrationLength - the number of bytes of calibration data placed in calibration[]
out calibration[] - the calibration data from the battery.
Definition at line 180 of file BatteryControl.c.
Referenced by ConMan_GetCalibration().
void BatteryControl_SetConfig (uint8_t config)
Takes a configuration and sets it for the battery voltage reading.
Parameters
in config - the KeyValue configuration setting for the battery reading.
Definition at line 64 of file BatteryControl.c.
Referenced by ConMan_SetSensorConfig().