Buzzer.h File Reference
Driver for the buzzer.
#include <PitchToFrequency.h>
*
Macros
#define BUZZER_DUTY_MAX_VOLUME (50u)
Functions
void Buzzer_Init (void)
void Buzzer_Enable (void)
void Buzzer_Disable (void)
void Buzzer_SetFrequency (PitchFrequency_t freq)
void Buzzer_SetDuty (uint8_t duty)
Detailed Description
Driver for the buzzer. Description Driver for the buzzer.
Definition in file Buzzer.h.
Macro Definition Documentation
#define BUZZER_DUTY_MAX_VOLUME (50u)
Define the duty setting that gives maximum buzzer volume. 50% gives the maximum volume because the sounder is moving the maximum amount in both directions. The duty cycle is represented in percent (%).
Definition at line 28 of file Buzzer.h.
Referenced by UiManager_PlaySequence().
Function Documentation
void Buzzer_Disable (void)
Disables the Buzzer
Definition at line 70 of file Buzzer.c.
Referenced by _PlaySequence(), and UiManager_StopSequence().
void Buzzer_Enable (void)
Enables the Buzzer
Definition at line 62 of file Buzzer.c.
Referenced by _PlaySequence().
void Buzzer_Init (void)
Initialized the Buzzer and PWM driver.
Definition at line 52 of file Buzzer.c.
Referenced by UiManager_Init().
void Buzzer_SetDuty (uint8_t duty)
Sets the duty cycle of the buzzer of the buzzer
Parameters
in duty - Duty cycle for the buzzer in percent (0 to 100)
Definition at line 90 of file Buzzer.c.
Referenced by UiManager_PlaySequence().
void Buzzer_SetFrequency (PitchFrequency_t freq)
Sets the frequency of the buzzer
Parameters
in freq - Frequency in HzX10 (37.6 Hz = 376)
Definition at line 80 of file Buzzer.c.
Referenced by _PlaySequence().