CommProtocol.c File Reference
Communications protocol module.
#include <ProjectTypes.h>
*
#include <EventQueue.h>
*
#include `CommProtocol.h`
*
#include <SpiSlave.h>
*
#include <Assert.h>
*
#include <Serial.h>
*
#include <Debug.h>
*
#include <DataBuffer.h>
*
#include <LedControl.h>
*
#include <SensorId.h>
*
#include <BatteryControl.h>
*
#include <ConfigurationManager.h>
*
#include <System.h>
*
#include <TimerTick.h>
*
#include <Version.h>
*
Macros
#define DATA_PACKET_SIZE (114u)
#define MESSAGE_PACKET_SIZE (30u)
#define START_OF_MESSAGE (0x02u)
#define START_OF_MESSAGE_INDEX (0u)
#define END_OF_PACKET (0x0Au)
#define END_OF_DATA_PACKET_INDEX (DATA_PACKET_SIZE - 1u)
#define END_OF_MESSAGE_PACKET_INDEX (MESSAGE_PACKET_SIZE - 1u)
#define COMMAND_INDEX (1u)
#define TX_PACKET_DATA_START_INDEX (COMMAND_INDEX + 1u)
#define VALID_DATA_LENGTH_INDEX (TX_PACKET_DATA_START_INDEX)
#define RX_PACKET_DATA_START_INDEX (VALID_DATA_LENGTH_INDEX + 1u)
#define BYTES_PACKET_OVERHEAD (3u)
#define TX_REMOTE_ID_INDEX (VALID_DATA_LENGTH_INDEX + 1u)
#define RX_REMOTE_ID_INDEX (0u)
#define MAX_NO_CONNECT_TIME_MSEC ((uint32_t)(1000u * 60u)) /* 60 seconds in msec */
#define STATUS_PACKET_EXPECTED_LENGTH (3u)
#define FIRMWARE_MAJOR_INDEX (0u)
#define FIRMWARE_MINOR_INDEX (1u)
#define CONNECTION_STATUS_INDEX (2u)
#define OUTPUT_CONFIG_USEFUL_DATA_OFFSET (2u)
#define FIXED_CONFIG_USEFUL_DATA_OFFSET (1u)
#define LENGTH_STATUS_REPLY (6u)
Enumerations
enum CommCommand_t {
*
CommCommand_INVALID = 0u,
*
CommCommand_FIRST = 0x10u,
*
CommCommand_RF_PACKET = CommCommand_FIRST,
*
CommCommand_STATUS = 0x11u,
*
CommCommand_START_DATA = 0x20u,
*
CommCommand_STOP_DATA = 0x21u,
*
CommCommand_SET_SENSOR_CONFIG = 0x22u,
*
CommCommand_GET_SENSOR_CONFIG = 0x23u,
*
CommCommand_SET_OUTPUT_CONFIG = 0x24u,
*
CommCommand_GET_OUTPUT_CONFIG = 0x25u,
*
CommCommand_SET_FIXED_CONFIG = 0x26u,
*
CommCommand_GET_FIXED_CONFIG = 0x27u,
*
CommCommand_GET_PACKET_CONFIG = 0x28u,
*
CommCommand_GET_CALIBRATION = 0x29u,
*
CommCommand_GET_STATUS = 0x2Au,
*
CommCommand_POWER_DOWN = 0x2Bu,
*
CommCommand_LAST
 }
Functions
static void _HandleRfPacket (uint8_t messageData[], uint8_t messageLength)
static void _HandleStatusPacket (uint8_t messageData[], uint8_t messageLength)
static void _HandleSetSensorConfigPacket (uint8_t messageData[], uint8_t messageLength)
static void _HandleGetSensorConfigPacket (uint8_t messageData[], uint8_t messageLength)
static void _HandleSetOutputConfigPacket (uint8_t messageData[], uint8_t messageLength)
static void _HandleGetOutputConfigPacket (uint8_t messageData[], uint8_t messageLength)
static void _HandleSetFixedConfigPacket (uint8_t messageData[], uint8_t messageLength)
static void _HandleGetFixedConfigPacket (uint8_t messageData[], uint8_t messageLength)
static void _HandleGetPacketConfigPacket (uint8_t messageData[], uint8_t messageLength)
static void _HandleGetCalibrationPacket (uint8_t messageData[], uint8_t messageLength)
static void _HandleGetStatusPacket (uint8_t messageData[], uint8_t messageLength)
static void _HandlePowerDownPacket (uint8_t messageData[], uint8_t messageLength)
static void _SetTxCommand (CommCommand_t command)
static bool _WriteMessageData (uint8_t messageStartIndex, uint8_t messageLength, const uint8_t messageData[])
static void _HandleRfStatusISR (void)
void CommProtocol_Init ()
void CommProtocol_RxHandler (void)
void CommProtocol_TxHandler (void)
void CommProtocol_GetRfStatus (RfStatus_t *status)
void CommProtocol_HandleStartDataPacket (uint8_t messageData[], uint8_t messageLength)
void CommProtocol_HandleStopDataPacket (uint8_t messageData[], uint8_t messageLength)
Variables
static uint8_t _bufferTxZero [DATA_PACKET_SIZE] = { 0u }
static uint8_t _bufferTxOne [DATA_PACKET_SIZE] = { 0u }
static uint8_t _messageBuffer [MESSAGE_PACKET_SIZE] = { 0u }
static uint8_t * _activeWriteArray = _bufferTxZero
static uint8_t _bufferRx [DATA_PACKET_SIZE] = { 0u }
static bool _dataMode = false
static RfStatus_t _rfStatus = { RfConnectionStatus_INVLALID, 0u, 0u }
Detailed Description
Communications protocol module. Project 1814 IOLab Remote Sensor Application
Description The communications protocol module manages the data coming in and going out from the other microcontroller.
Definition in file CommProtocol.c.
Macro Definition Documentation
#define BYTES_PACKET_OVERHEAD (3u)
Defines how many bytes of the packet is overhead
Definition at line 119 of file CommProtocol.c.
Referenced by CommProtocol_Init().
#define COMMAND_INDEX (1u)
Defines where in the packet the command value is located
Definition at line 110 of file CommProtocol.c.
Referenced by _SetTxCommand(), CommProtocol_HandleStartDataPacket(), CommProtocol_HandleStopDataPacket(), CommProtocol_Init(), and CommProtocol_RxHandler().
#define DATA_PACKET_SIZE (114u)
Defines the size of the packets used in the protocol.
Definition at line 43 of file CommProtocol.c.
Referenced by CommProtocol_Init(), CommProtocol_RxHandler(), and CommProtocol_TxHandler().
#define END_OF_DATA_PACKET_INDEX (DATA_PACKET_SIZE - 1u)
Defines where in the data packet the end message is located
Definition at line 55 of file CommProtocol.c.
Referenced by CommProtocol_Init().
#define END_OF_MESSAGE_PACKET_INDEX (MESSAGE_PACKET_SIZE - 1u)
Defines where in the message packet the end message is located
Definition at line 57 of file CommProtocol.c.
Referenced by CommProtocol_Init().
#define END_OF_PACKET (0x0Au)
Defines the value for the end of message byte
Definition at line 53 of file CommProtocol.c.
Referenced by CommProtocol_Init().
#define MAX_NO_CONNECT_TIME_MSEC ((uint32_t)(1000u * 60u)) /* 60 seconds in msec */
Defines the maximum amount of time the system is allowed to be `not connected`
Definition at line 127 of file CommProtocol.c.
Referenced by _HandleRfStatusISR().
#define MESSAGE_PACKET_SIZE (30u)
Defines the size of the packets used for the non-data messages
Definition at line 45 of file CommProtocol.c.
Referenced by _WriteMessageData().
#define RX_PACKET_DATA_START_INDEX (VALID_DATA_LENGTH_INDEX + 1u)
Defines where in the packet the start of the RX data is
Definition at line 116 of file CommProtocol.c.
Referenced by CommProtocol_RxHandler().
#define RX_REMOTE_ID_INDEX (0u)
Defines where the remote ID index in on the message data received by the message handlers
Definition at line 124 of file CommProtocol.c.
Referenced by _HandleGetCalibrationPacket(), _HandleGetFixedConfigPacket(), _HandleGetPacketConfigPacket(), and _HandleGetStatusPacket().
#define START_OF_MESSAGE (0x02u)
Defines the value for the start of message byte
Definition at line 48 of file CommProtocol.c.
Referenced by CommProtocol_Init().
#define START_OF_MESSAGE_INDEX (0u)
Defines where in the packet the start message is located
Definition at line 50 of file CommProtocol.c.
Referenced by CommProtocol_Init().
#define TX_PACKET_DATA_START_INDEX (COMMAND_INDEX + 1u)
Defines where in the packet the start of the TX data is
Definition at line 112 of file CommProtocol.c.
Referenced by CommProtocol_Init().
#define TX_REMOTE_ID_INDEX (VALID_DATA_LENGTH_INDEX + 1u)
Defines where the remote ID index belongs in a transmitted message
Definition at line 122 of file CommProtocol.c.
Referenced by _HandleGetCalibrationPacket(), _HandleGetFixedConfigPacket(), _HandleGetPacketConfigPacket(), and _HandleGetStatusPacket().
#define VALID_DATA_LENGTH_INDEX (TX_PACKET_DATA_START_INDEX)
Defines where in the packet the valid data length value is located
Definition at line 114 of file CommProtocol.c.
Referenced by _HandleGetCalibrationPacket(), _HandleGetFixedConfigPacket(), _HandleGetOutputConfigPacket(), _HandleGetPacketConfigPacket(), _HandleGetSensorConfigPacket(), _HandleGetStatusPacket(), _HandlePowerDownPacket(), _HandleSetSensorConfigPacket(), CommProtocol_HandleStartDataPacket(), CommProtocol_HandleStopDataPacket(), CommProtocol_Init(), and CommProtocol_RxHandler().
Enumeration Type Documentation
enum CommCommand_t
Defines the possible command values
Definition at line 61 of file CommProtocol.c.
Function Documentation
void _HandleGetCalibrationPacket (uint8_t messageData[], uint8_t messageLength) [static]
Handles the packet data for the Get Calibration Command.
Parameters
in messageData[] - array of the data contained in the message
in messageLength - the number of valid bytes in the message data
Definition at line 646 of file CommProtocol.c.
Referenced by CommProtocol_RxHandler().
void _HandleGetFixedConfigPacket (uint8_t messageData[], uint8_t messageLength) [static]
Handles the packet data for the Get Fixed Configuration Command.
Parameters
in messageData[] - array of the data contained in the message
in messageLength - the number of valid bytes in the message data
Definition at line 581 of file CommProtocol.c.
Referenced by CommProtocol_RxHandler().
void _HandleGetOutputConfigPacket (uint8_t messageData[], uint8_t messageLength) [static]
Handles the packet data for the Get Output Configuration Command.
Parameters
in messageData[] - array of the data contained in the message
in messageLength - the number of valid bytes in the message data
Definition at line 545 of file CommProtocol.c.
Referenced by CommProtocol_RxHandler().
void _HandleGetPacketConfigPacket (uint8_t messageData[], uint8_t messageLength) [static]
Handles the packet data for the Get Packet Configuration Command.
Parameters
in messageData[] - array of the data contained in the message
in messageLength - the number of valid bytes in the message data
Definition at line 607 of file CommProtocol.c.
Referenced by CommProtocol_RxHandler().
void _HandleGetSensorConfigPacket (uint8_t messageData[], uint8_t messageLength) [static]
Handles the packet data for the Get Sensor Configuration Command.
Parameters
in messageData[] - array of the data contained in the message
in messageLength - the number of valid bytes in the message data
Definition at line 509 of file CommProtocol.c.
Referenced by CommProtocol_RxHandler().
void _HandleGetStatusPacket (uint8_t messageData[], uint8_t messageLength) [static]
Handles the packet data for the Get Status Command.
Parameters
in messageData[] - array of the data contained in the message
in messageLength - the number of valid bytes in the message data
Definition at line 695 of file CommProtocol.c.
Referenced by CommProtocol_RxHandler().
static void _HandlePowerDownPacket (uint8_t messageData[], uint8_t messageLength) [static]
Handles the packet data for the Power Down Command.
Parameters
in messageData[] - array of the data contained in the message
in messageLength - the number of valid bytes in the message data
Definition at line 730 of file CommProtocol.c.
Referenced by CommProtocol_RxHandler().
void _HandleRfPacket (uint8_t messageData[], uint8_t messageLength) [static]
Handles the packet data for the RF Command.
Parameters
in messageData[] - array of the data contained in the message
in messageLength - the number of valid bytes in the message data
Definition at line 354 of file CommProtocol.c.
Referenced by CommProtocol_RxHandler().
static void _HandleRfStatusISR (void) [static]
Processes system tasks based on the state of the RF connection and the time spent in that state. This should be called by the timer tick at regular intervals.
Definition at line 795 of file CommProtocol.c.
Referenced by CommProtocol_Init().
void _HandleSetFixedConfigPacket (uint8_t messageData[], uint8_t messageLength) [static]
Handles the packet data for the Set Fixed Configuration Command.
Parameters
in messageData[] - array of the data contained in the message
in messageLength - the number of valid bytes in the message data
Definition at line 562 of file CommProtocol.c.
Referenced by CommProtocol_RxHandler().
void _HandleSetOutputConfigPacket (uint8_t messageData[], uint8_t messageLength) [static]
Handles the packet data for the Set Output Configuration Command.
Parameters
in messageData[] - array of the data contained in the message
in messageLength - the number of valid bytes in the message data
Definition at line 526 of file CommProtocol.c.
Referenced by CommProtocol_RxHandler().
void _HandleSetSensorConfigPacket (uint8_t messageData[], uint8_t messageLength) [static]
Handles the packet data for the Set Sensor Configuration Command.
Parameters
in messageData[] - array of the data contained in the message
in messageLength - the number of valid bytes in the message data
Definition at line 492 of file CommProtocol.c.
Referenced by CommProtocol_RxHandler().
void _HandleStatusPacket (uint8_t messageData[], uint8_t messageLength) [static]
Handles the packet data for the Status Command.
Parameters
in messageData[] - array of the data contained in the message
in messageLength - the number of valid bytes in the message data
Definition at line 369 of file CommProtocol.c.
Referenced by CommProtocol_RxHandler().
static void _SetTxCommand (CommCommand_t command) [static]
Sets the command byte to the proper value based on the type of command.
Parameters
in command - the type of command to set for the TX Packet
Definition at line 749 of file CommProtocol.c.
Referenced by _HandleGetCalibrationPacket(), _HandleGetFixedConfigPacket(), _HandleGetOutputConfigPacket(), _HandleGetPacketConfigPacket(), _HandleGetSensorConfigPacket(), _HandleGetStatusPacket(), _HandlePowerDownPacket(), _HandleRfPacket(), _HandleSetFixedConfigPacket(), _HandleSetOutputConfigPacket(), _HandleSetSensorConfigPacket(), _HandleStatusPacket(), CommProtocol_HandleStartDataPacket(), and CommProtocol_HandleStopDataPacket().
bool _WriteMessageData (uint8_t messageStartIndex, uint8_t messageLength, const uint8_t messageData[]) [static]
Takes message data and writes it to the active write array.
Parameters
in messageStartIndex - the array index where the data should start at
in messageLength - the number of bytes of the message to write
in messageData - the data of the message to write to the array
Returns
True if the data would fit, false otherwise
Definition at line 765 of file CommProtocol.c.
Referenced by _HandleGetCalibrationPacket(), and _HandleGetPacketConfigPacket().
void CommProtocol_GetRfStatus (RfStatus_t * status)
Gets the RF Status information.
Parameters
out status - structure to hold the RF status in
Definition at line 342 of file CommProtocol.c.
Referenced by _HandleHumanRfCommand(), and _ProcessEvents_RUN().
void CommProtocol_HandleStartDataPacket (uint8_t messageData[], uint8_t messageLength)
Handles the packet data for the Start Data Command.
Parameters
in messageData[] - array of the data contained in the message
in messageLength - the number of valid bytes in the message data
Definition at line 424 of file CommProtocol.c.
Referenced by CommProtocol_RxHandler(), and SelfTest_Process().
void CommProtocol_HandleStopDataPacket (uint8_t messageData[], uint8_t messageLength)
Handles the packet data for the Stop Data Command.
Parameters
in messageData[] - array of the data contained in the message
in messageLength - the number of valid bytes in the message data
Definition at line 458 of file CommProtocol.c.
Referenced by CommProtocol_RxHandler(), and SelfTest_Process().
void CommProtocol_Init ()
Initialized the comm protocol.
Definition at line 198 of file CommProtocol.c.
Referenced by main().
void CommProtocol_RxHandler (void)
Handles the events related to the received events for the Comm Protocol.
Definition at line 228 of file CommProtocol.c.
Referenced by _ProcessEvents_DEFAULT().
void CommProtocol_TxHandler (void)
Handles the events related to the transmitted events for the Comm Protocol.
Definition at line 307 of file CommProtocol.c.
Referenced by _ProcessEvents_DEFAULT().
Variable Documentation
uint8_t* _activeWriteArray = _bufferTxZero [static]
A pointer to the active write array
Definition at line 137 of file CommProtocol.c.
Referenced by _HandleGetCalibrationPacket(), _HandleGetFixedConfigPacket(), _HandleGetOutputConfigPacket(), _HandleGetPacketConfigPacket(), _HandleGetSensorConfigPacket(), _HandleGetStatusPacket(), _HandlePowerDownPacket(), _HandleSetSensorConfigPacket(), _SetTxCommand(), _WriteMessageData(), CommProtocol_HandleStartDataPacket(), CommProtocol_HandleStopDataPacket(), CommProtocol_Init(), and CommProtocol_TxHandler().
uint8_t _bufferRx[DATA_PACKET_SIZE] = { 0u } [static]
A buffer to store the received data in
Definition at line 139 of file CommProtocol.c.
Referenced by CommProtocol_Init(), and CommProtocol_RxHandler().
uint8_t _bufferTxOne[DATA_PACKET_SIZE] = { 0u } [static]
A buffer to store the protocol data in
Definition at line 133 of file CommProtocol.c.
Referenced by CommProtocol_HandleStartDataPacket(), CommProtocol_HandleStopDataPacket(), CommProtocol_Init(), and CommProtocol_TxHandler().
uint8_t _bufferTxZero[DATA_PACKET_SIZE] = { 0u } [static]
A buffer to store the protocol data in
Definition at line 131 of file CommProtocol.c.
Referenced by CommProtocol_HandleStartDataPacket(), CommProtocol_HandleStopDataPacket(), CommProtocol_Init(), and CommProtocol_TxHandler().
bool _dataMode = false [static]
Tracks if the protocol is in data mode or not
Definition at line 142 of file CommProtocol.c.
Referenced by CommProtocol_HandleStartDataPacket(), CommProtocol_HandleStopDataPacket(), and CommProtocol_TxHandler().
uint8_t _messageBuffer[MESSAGE_PACKET_SIZE] = { 0u } [static]
A buffer to store the non-data messages
Definition at line 135 of file CommProtocol.c.
Referenced by CommProtocol_HandleStartDataPacket(), CommProtocol_HandleStopDataPacket(), CommProtocol_Init(), and CommProtocol_TxHandler().
RfStatus_t _rfStatus = { RfConnectionStatus_INVLALID, 0u, 0u } [static]
Stores the current RF Status
Definition at line 145 of file CommProtocol.c.
Referenced by CommProtocol_GetRfStatus().