CommProtocol.h File Reference
Header for the communications protocol module.
Data Structures
struct RfStatus_t
Enumerations
enum RfConnectionStatus_t {
*
RfConnectionStatus_INVLALID = 0u,
*
RfConnectionStatus_NOT_PAIRED = 0x20u,
*
RfConnectionStatus_FIRST = RfConnectionStatus_NOT_PAIRED,
*
RfConnectionStatus_PAIRING = 0x21u,
*
RfConnectionStatus_PAIRED_NOT_CONNECTED = 0x22u,
*
RfConnectionStatus_CONNECTED = 0x23u,
*
RfConnectionStatus_DATA = 0x24u,
*
RfConnectionStatus_LAST
 }
Functions
void CommProtocol_Init ()
void CommProtocol_RxHandler (void)
void CommProtocol_TxHandler (void)
void CommProtocol_GetRfStatus (RfStatus_t *status)
void CommProtocol_HandleStartDataPacket (uint8_t messageData[], uint8_t messageLength)
void CommProtocol_HandleStopDataPacket (uint8_t messageData[], uint8_t messageLength)
Detailed Description
Header for the communications protocol module. Project 1814 IOLab Remote Sensor Application
Description Header for the communications protocol module that will manage the protocol and data for the communications to the other micro.
Definition in file CommProtocol.h.
Data Structure Documentation
struct RfStatus_t
Defines a structure to hold the RF Status information in
Definition at line 40 of file CommProtocol.h.
Data Fields
RfConnectionStatus_t
connectionStatus
uint8_t
fwMajor
uint8_t
fwMinor
Enumeration Type Documentation
enum RfConnectionStatus_t
Defines the valid states for the RF Connection Status
Definition at line 27 of file CommProtocol.h.
Function Documentation
void CommProtocol_GetRfStatus (RfStatus_t * status)
Gets the RF Status information.
Parameters
out status - structure to hold the RF status in
Definition at line 342 of file CommProtocol.c.
Referenced by _HandleHumanRfCommand(), and _ProcessEvents_RUN().
void CommProtocol_HandleStartDataPacket (uint8_t messageData[], uint8_t messageLength)
Handles the packet data for the Start Data Command.
Parameters
in messageData[] - array of the data contained in the message
in messageLength - the number of valid bytes in the message data
Definition at line 424 of file CommProtocol.c.
Referenced by CommProtocol_RxHandler(), and SelfTest_Process().
void CommProtocol_HandleStopDataPacket (uint8_t messageData[], uint8_t messageLength)
Handles the packet data for the Stop Data Command.
Parameters
in messageData[] - array of the data contained in the message
in messageLength - the number of valid bytes in the message data
Definition at line 458 of file CommProtocol.c.
Referenced by CommProtocol_RxHandler(), and SelfTest_Process().
void CommProtocol_Init ()
Initialized the comm protocol.
Definition at line 198 of file CommProtocol.c.
Referenced by main().
void CommProtocol_RxHandler (void)
Handles the events related to the received events for the Comm Protocol.
Definition at line 228 of file CommProtocol.c.
Referenced by _ProcessEvents_DEFAULT().
void CommProtocol_TxHandler (void)
Handles the events related to the transmitted events for the Comm Protocol.
Definition at line 307 of file CommProtocol.c.
Referenced by _ProcessEvents_DEFAULT().