ConfigurationManager.h File Reference
The configuration manager keeps track of all the sensor configurations.
#include <FixedConfigList.h>
*
Functions
void ConMan_Init ()
void ConMan_SetSensorConfig (uint16_t configLength, const uint8_t config[])
void ConMan_SetFixedConfig (uint16_t configLength, const uint8_t config[])
FixedConfigList_t ConMan_GetFixedConfig (void)
void ConMan_SetOutputConfig (uint16_t configLength, const uint8_t config[])
const uint8_t * ConMan_GetPacketConfig (uint16_t *packetLength)
void ConMan_GetCalibration (SensorId_t sensorId, uint16_t maxLength, uint16_t *actualLength, uint8_t calibration[])
void ConMan_StartData ()
void ConMan_StopData ()
Detailed Description
The configuration manager keeps track of all the sensor configurations. Project 1814 IOLab Remote Sensor Application
Description The configuration manager is the module that will keep track of configuration all the sensors to be in the proper sensor mode based on the setup commands.
Definition in file ConfigurationManager.h.
Function Documentation
void ConMan_GetCalibration (SensorId_t sensorId, uint16_t maxLength, uint16_t * actualLength, uint8_t calibration[])
Returns the configuration data for a specific sensor.
Parameters
in sensorId - the sensor the configuration is for
in maxLength - the number of bytes allocation fro the calibration array
out actualLength - the number of bytes put in the calibration array
out calibration[] - the calibration data for sensor
Definition at line 574 of file ConfigurationManager.c.
Referenced by _HandleGetCalibrationPacket().
FixedConfigList_t ConMan_GetFixedConfig (void)
Fetches and returns the current fixed configuration setting.
Returns
The setting for the current fixed configuration.
Definition at line 306 of file ConfigurationManager.c.
Referenced by _HandleGetFixedConfigPacket().
const uint8_t* ConMan_GetPacketConfig (uint16_t * packetLength)
Returns the current configuration of the data packet.
Parameters
out packetLength - the number of bytes in the packet config array
Returns
Pointer to a static constant array containing the packet config
Definition at line 394 of file ConfigurationManager.c.
Referenced by _HandleGetPacketConfigPacket().
void ConMan_Init ()
Initializes the configuration manager. The initialization include initializing all the sensors for which the configuration manager manages.
Definition at line 101 of file ConfigurationManager.c.
Referenced by main().
void ConMan_SetFixedConfig (uint16_t configLength, const uint8_t config[])
Selects the fixed configuration and sends the configuration data to the appropriate sensors to manage the settings.
Parameters
in configLength - the number of valid bytes in the configuration data
in config[] - array of the data contained in the configuration
Definition at line 276 of file ConfigurationManager.c.
Referenced by _HandleSetFixedConfigPacket(), and SelfTest_Start().
void ConMan_SetOutputConfig (uint16_t configLength, const uint8_t config[])
Parses the output configuration command and sends the configuration data to the appropriate sensors to manage the settings.
Parameters
in configLength - the number of valid bytes in the configuration data
in config[] - array of the data contained in the configuration
Definition at line 319 of file ConfigurationManager.c.
Referenced by _HandleSetOutputConfigPacket().
void ConMan_SetSensorConfig (uint16_t configLength, const uint8_t config[])
Parses the sensor configuration command sends the configuration data to the appropriate sensors to manage the settings.
Parameters
in configLength - the number of valid bytes in the configuration data
in config[] - array of the data contained in the configuration
Definition at line 144 of file ConfigurationManager.c.
Referenced by ConMan_StartData(), and ConMan_StopData().
void ConMan_StartData ()
Sets the previously or default configured sensors to active mode to begin collecting data.
Definition at line 695 of file ConfigurationManager.c.
Referenced by CommProtocol_HandleStartDataPacket().
void ConMan_StopData ()
Stops the enabled sensors from collecting data.
Definition at line 932 of file ConfigurationManager.c.
Referenced by CommProtocol_HandleStopDataPacket().