DacControl.c File Reference
Controls the hardware DAC.
#include <ProjectTypes.h>
*
#include `DacControl.h`
*
#include <Dac.h>
*
#include <KeyValue.h>
*
#include <Assert.h>
*
#include <Serial.h>
*
#include <Debug.h>
*
Functions
static void _DacControl_SetAmplitude (void)
void DacControl_Init ()
void DacControl_SetConfig (uint8_t config)
Variables
DacMode_t _dacMode = DacMode_INVALID
DacAmplitude_t _dacAmplitude = DEFAULT_DAC_AMPLITUDE
Detailed Description
Controls the hardware DAC. Project 1814 IOLab Remote Sensor Application
Description Controls and manages the settings for the hardware DAC.
Definition in file DacControl.c.
Function Documentation
static void _DacControl_SetAmplitude (void) [static]
Sets the output of the DAC to the amplitude stored in _dacAmplitude.
Definition at line 113 of file DacControl.c.
Referenced by DacControl_SetConfig().
void DacControl_Init ()
Initialized the DAC and driver.
Definition at line 46 of file DacControl.c.
Referenced by ConMan_Init().
void DacControl_SetConfig (uint8_t config)
Sets a configuration value to the DAC
Parameters
in config - the key/value pair with the configuration information
Definition at line 57 of file DacControl.c.
Referenced by ConMan_SetOutputConfig().
Variable Documentation
DacAmplitude_t _dacAmplitude = DEFAULT_DAC_AMPLITUDE
Tracks what amplitude the DAC is set at
Definition at line 38 of file DacControl.c.
Referenced by _DacControl_SetAmplitude(), and DacControl_SetConfig().
DacMode_t _dacMode = DacMode_INVALID
Tracks what mode the DAC is in
Definition at line 36 of file DacControl.c.
Referenced by _DacControl_SetAmplitude(), and DacControl_SetConfig().