Dac.c File Reference
Driver for the DAC.
#include <ProjectTypes.h>
*
#include `Dac.h`
*
#include <Clock.h>
*
#include <Gpio.h>
*
#include <Device.h>
*
#include <Board.h>
*
#include <SpiMaster.h>
*
#include <Assert.h>
*
Macros
#define DAC_START_SPI_XFER GPIO_CLEAR(CS_DAC_PORT, CS_DAC_PIN);
#define DAC_END_SPI_XFER GPIO_SET(CS_DAC_PORT, CS_DAC_PIN);
#define SPI_CS_DELAY_US 1u
Functions
void DacInit (void)
void DacConfig (void)
void DacSetVoltage (uint8_t voltage)
Detailed Description
Driver for the DAC. Project 1814 IOLab Remote Sensor Application
Description This module interfaces to a SPI DAC to set the output voltage. This driver is designed to work with a TI DAC5311 SPI DAC.
Definition in file Dac.c.
Macro Definition Documentation
#define DAC_START_SPI_XFER GPIO_CLEAR(CS_DAC_PORT, CS_DAC_PIN);
Defines the chip select enable and disable for the gyroscope
Definition at line 38 of file Dac.c.
Referenced by DacSetVoltage().
#define SPI_CS_DELAY_US 1u
Defines the number of microseconds to delay between de/asserting the chip select line and ending/starting the SPI communication to allow the chip to become ready
Definition at line 44 of file Dac.c.
Referenced by DacSetVoltage().
Function Documentation
void DacSetVoltage (uint8_t voltage)
Writes a value to a specific register using the SPI port.
Parameters
in voltage - the decimal equivalent of binary code used to set the voltage, given by the equation voltage = Vout/AVDD*2^8
Definition at line 65 of file Dac.c.
Referenced by _DacControl_SetAmplitude(), _HandleHumanDacCommand(), and DacControl_SetConfig().