Dac.h File Reference
Header file for DAC driver.
Functions
void DacInit (void)
void DacConfig (void)
void DacSetVoltage (uint8_t voltage)
Detailed Description
Header file for DAC driver. Project 1814 IOLab Remote Sensor Application
Description The DAC driver sets the voltage level out of the DAC
Definition in file Dac.h.
Function Documentation
void DacSetVoltage (uint8_t voltage)
Writes a value to a specific register using the SPI port.
Parameters
in voltage - the decimal equivalent of binary code used to set the voltage, given by the equation voltage = Vout/AVDD*2^8
Definition at line 65 of file Dac.c.
Referenced by _DacControl_SetAmplitude(), _HandleHumanDacCommand(), and DacControl_SetConfig().