DataBuffer.h File Reference
Data buffer is the memory space reserved to store sensor data.
Macros
#define MAX_NUM_SUB_ARRAYS (33u)
#define MIN_BUFFER_SIZE (100u)
Functions
void DataBuffer_Init (uint8_t array0[], uint8_t array1[], uint16_t arraySize)
bool DataBuffer_SetData (uint16_t startIndex, uint16_t length, const uint8_t data[])
void DataBuffer_GetIdleBuffer (uint16_t *bufferLength, uint8_t **buffer)
uint16_t DataBuffer_RotateBuffer (void)
bool DataBuffer_CreateSubarray (uint8_t subArrayId, uint16_t length)
bool DataBuffer_AddToSubarray8Bit (uint8_t subArrayId, uint16_t length, const uint8_t data[])
bool DataBuffer_AddToSubarray16Bit (uint8_t subArrayId, uint16_t length, const uint16_t data[])
void DataBuffer_ClearSubarrays (void)
bool DataBuffer_SubarrayExists (uint8_t subArrayId)
Detailed Description
Data buffer is the memory space reserved to store sensor data. Project 1814 IOLab Remote Sensor Application
Description The data buffer contains memory space to store sensor data and can be written to and read from. The buffer contains locking mechanisms to ensure that data is not compromised and is valid.
Definition in file DataBuffer.h.
Macro Definition Documentation
#define MAX_NUM_SUB_ARRAYS (33u)
Defines the maximum number of subarrays that can be handled
Definition at line 28 of file DataBuffer.h.
Referenced by DataBuffer_CreateSubarray().
#define MIN_BUFFER_SIZE (100u)
Defines the minimum size acceptable for the buffer arrays
Definition at line 30 of file DataBuffer.h.
Referenced by DataBuffer_Init().
Function Documentation
bool DataBuffer_AddToSubarray16Bit (uint8_t subArrayId, uint16_t length, const uint16_t data[])
If there is room, it adds length of data to subarrayId.
Parameters
in subarrayId- the identifier for the subarray.
in length - the actual number of pieces of data to add to the subarray.
Return values
- True if the data could be added and would fit. False otherwise. Will return false if the length would cause an out of bounds array access. Or if the subarray Id is not found.
Definition at line 343 of file DataBuffer.c.
Referenced by _AmbientLightDataCallback(), _Analog7DataCallback(), _Analog8DataCallback(), _Analog9DataCallback(), _BatteryVoltageDataCallback(), _EcgAddToDataBuffer(), _ForceGaugeDataCallback(), _HighGainDataCallback(), _MicrophoneDataCallback(), _thermometerDataCallBack(), and EncControl_ReadEnc().
bool DataBuffer_AddToSubarray8Bit (uint8_t subArrayId, uint16_t length, const uint8_t data[])
If there is room, it adds length of data to subarrayId.
Parameters
in subarrayId- the identifier for the subarray.
in length - the actual number of pieces of data to add to the subarray.
Return values
- True if the data could be added and would fit. False otherwise. Will return false if the length would cause an out of bounds array access. Or if the subarray Id is not found.
Definition at line 289 of file DataBuffer.c.
Referenced by _ReadPins(), AccControl_ReadAcc(), BarometerControl_ReadBar(), GyroControl_ReadGyro(), and MagControl_ReadMag().
void DataBuffer_ClearSubarrays (void)
Deletes all the subarrays from the data arrays.
Definition at line 394 of file DataBuffer.c.
Referenced by ConMan_StartData(), and ConMan_StopData().
bool DataBuffer_CreateSubarray (uint8_t subArrayId, uint16_t length)
If there is room, it creates a subarray of length spaces. The subarray will always be appended to the end of the active subarrays.
Parameters
in subarrayId- the identifier for the subarray.
in length - the maximum number of pieces of data to store in the subarray.
Return values
- True if the subarray could be created. False otherwise. Will return false if the length would cause an out of bounds array access. Or if the subarray Id is already used.
Definition at line 220 of file DataBuffer.c.
Referenced by _ConMan_AllocateBuffer().
void DataBuffer_GetIdleBuffer (uint16_t * bufferLength, uint8_t ** buffer)
Gets a reference to the idle buffer.
Parameters
out bufferLength - the length of the returned buffer
out buffer - the pointer to the array of data in the buffer.
Definition at line 160 of file DataBuffer.c.
void DataBuffer_Init (uint8_t array0[], uint8_t array1[], uint16_t arraySize)
Initialized the data buffer and points this module to the memory to use as the data buffers.
Parameters
in array0 - the first array to be used to pingpong between.
in array1 - the second array to be used to pingpong between.
in arraySize - the size of the array0 and array1 in bytes.
Note
array0 and array1 must be the same size.
Definition at line 104 of file DataBuffer.c.
Referenced by CommProtocol_Init().
uint16_t DataBuffer_RotateBuffer (void)
Rotates which buffer the new data is going to and resets the old buffer.
Return values
The value of the now active buffer, 0 or 1.
Note
DO NOT CALL FROM INTERRUPT CONTEXT!!! There is currently no way to rotate the buffers from interrupt context and guarantee data integrity of the data within the buffers.
Definition at line 187 of file DataBuffer.c.
Referenced by CommProtocol_TxHandler().
bool DataBuffer_SetData (uint16_t startIndex, uint16_t length, const uint8_t data[])
Sets the memory to the values in data starting at startIndex and ending at startIndex+length.
Parameters
in startIndex- the index of the array to start inserting data at.
in length - the number of pieces of data in data[].
in data - the array of data to set in the data buffer array.
Return values
- True if the data could be set. False otherwise. Will return false if the index or length would cause an out of bounds array access.
Definition at line 129 of file DataBuffer.c.
bool DataBuffer_SubarrayExists (uint8_t subArrayId)
Checks if a subarray by the name of subArrayId exists.
Parameters
in subarrayId- the identifier for the subarray.
Return values
- True if the subarray ID exists. False otherwise.
Definition at line 412 of file DataBuffer.c.