Dma.h File Reference
Configuration and control functions and macros for the DMA.
Data Structures
struct DmaConfig_t
Macros
#define DMA_CHANNEL_0 0
#define DMA_CHANNEL_1 1
#define DMA_CHANNEL_2 2
DMA enable and disable macros.
#define DMA_ENABLE(channel) DMA_ENABLE_PREP(channel)
Enables DMA channel.
#define DMA_DISABLE(channel) DMA_DISABLE_PREP(channel)
Disables DMA channel.
#define DMA_INT_ENABLE(channel) DMA_INT_ENABLE_PREP(channel)
Enables interrupts for a DMA channel.
#define DMA_INT_DISABLE(channel) DMA_INT_DISABLE_PREP(channel)
Disables interrupts for a DMA channel.
Internal DMA enable and disable macros.
#define DMA_ENABLE_PREP(channel) (DMA##channel##CTL = DMA##channel##CTL | DMAEN)
#define DMA_DISABLE_PREP(channel) (DMA##channel##CTL = DMA##channel##CTL & ~DMAEN)
#define DMA_INT_ENABLE_PREP(channel) (DMA##channel##CTL = DMA##channel##CTL | DMAIE)
#define DMA_INT_DISABLE_PREP(channel) (DMA##channel##CTL = DMA##channel##CTL & ~DMAIE)
Typedefs
typedef void(* DmaIsrPointer_t)(void)
Enumerations
enum DmaChannel_t {
*
DmaChannel_0 = 0u,
*
DmaChannel_1 = 1u,
*
DmaChannel_2 = 2u
 }
enum DmaTrigger_t {
*
DmaTrigger_DMAREQ = 0u,
*
DmaTrigger_TA0CCR0 = 1u,
*
DmaTrigger_TA0CCR2 = 2u,
*
DmaTrigger_TA1CCR0 = 3u,
*
DmaTrigger_TA1CCR2 = 4u,
*
DmaTrigger_TA2CCR0 = 5u,
*
DmaTrigger_TA2CCR2 = 6u,
*
DmaTrigger_TB0CCR0 = 7u,
*
DmaTrigger_TB0CCR2 = 8u,
*
DmaTrigger_UCA0RXIFG = 16u,
*
DmaTrigger_UCA0TXIFG = 17u,
*
DmaTrigger_UCB0RXIFG = 18u,
*
DmaTrigger_UCB0TXIFG = 19u,
*
DmaTrigger_UCA1RXIFG = 20u,
*
DmaTrigger_UCA1TXIFG = 21u,
*
DmaTrigger_UCB1RXIFG = 22u,
*
DmaTrigger_UCB1TXIFG = 23u,
*
DmaTrigger_ADC12IFGx = 24u,
*
DmaTrigger_MPY_READY = 29u,
*
DmaTrigger_DMAxIFG = 30u,
*
DmaTrigger_DMAEO = 31u
 }
enum DmaIncr_t {
*
DmaIncr_NONE = 1u,
*
DmaIncr_DECREMENT = 2u,
*
DmaIncr_INCREMENT = 3u
 }
enum DmaMode_t {
*
DmaMode_SINGLE = 0x0000,
*
DmaMode_BLOCK = 0x1000,
*
DmaMode_BURST_BLOCK = 0x2000,
*
DmaMode_SINGLE_REPEATING = 0x4000,
*
DmaMode_BLOCK_REPEATING = 0x5000,
*
DmaMode_BURST_BLOCK_REPEATING = 0x6000
 }
enum DmaBitWidth_t {
*
DmaBitWidth_WORD = 0x00,
*
DmaBitWidth_BYTE = 0x01
 }
Functions
void Dma_Init (void)
void Dma_Configure (DmaChannel_t channel, const DmaConfig_t *config)
void Dma_Arm (DmaChannel_t channel, void *sourceAddress, void *destinationAddress, uint16_t dmaTransferSize)
void Dma_Enable (DmaChannel_t channel)
void Dma_Disable (DmaChannel_t channel)
void Dma_Trigger (DmaChannel_t channel)
void Dma_RegisterIsr (DmaChannel_t channel, DmaIsrPointer_t isrPtr)
void Dma_UnregisterIsr (DmaChannel_t channel)
void Dma_EnableIsr (DmaChannel_t channel)
void Dma_DisableIsr (DmaChannel_t channel)
Detailed Description
Configuration and control functions and macros for the DMA. Project 1814 IOLab Remote Sensor Application
Description Provides configuration and control for the direct memory access (DMA) controller on the MSP430F5xx family.
Definition in file Dma.h.
Data Structure Documentation
struct DmaConfig_t
Defines a structure that holds all the configuration information to set up a DMA channel.
Definition at line 92 of file Dma.h.
Data Fields
DmaBitWidth_t
destinationBitWidth
DmaIncr_t
destinationIncr
DmaMode_t
mode
DmaBitWidth_t
sourceBitWidth
DmaIncr_t
sourceIncr
DmaTrigger_t
trigger
Macro Definition Documentation
#define DMA_CHANNEL_0 0
Define the number for each of the DMA channels
Definition at line 107 of file Dma.h.
#define DMA_DISABLE(channel) DMA_DISABLE_PREP(channel)
Disables DMA channel.
Parameters
in channel - DMA channel number
Definition at line 126 of file Dma.h.
#define DMA_ENABLE(channel) DMA_ENABLE_PREP(channel)
Enables DMA channel.
Parameters
in channel - DMA channel number
Definition at line 119 of file Dma.h.
#define DMA_INT_DISABLE(channel) DMA_INT_DISABLE_PREP(channel)
Disables interrupts for a DMA channel.
Parameters
in channel - DMA channel number
Definition at line 140 of file Dma.h.
#define DMA_INT_ENABLE(channel) DMA_INT_ENABLE_PREP(channel)
Enables interrupts for a DMA channel.
Parameters
in channel - DMA channel number
Definition at line 133 of file Dma.h.
Typedef Documentation
typedef void(* DmaIsrPointer_t)(void)
Defines a DMA ISR function pointer
Definition at line 103 of file Dma.h.
Enumeration Type Documentation
enum DmaBitWidth_t
Defines the bit width of the DMA transfer
Definition at line 83 of file Dma.h.
enum DmaChannel_t
Defines the available DMA channels
Definition at line 27 of file Dma.h.
enum DmaIncr_t
Defines the ways that the DMA can increment after a transfer
Definition at line 64 of file Dma.h.
enum DmaMode_t
Defines the transfer modes that the DMA can perform
Definition at line 72 of file Dma.h.
enum DmaTrigger_t
Defines the possible DMA triggers for any DMA channel. The are usually part specific and these are defined for the MSP430F532x
Definition at line 36 of file Dma.h.
Function Documentation
void Dma_Arm (DmaChannel_t channel, void * sourceAddress, void * destinationAddress, uint16_t dmaTransferSize)
Arms the DMA to make a DMA transaction as soon as it is enabled and triggered.
Parameters
in channel - the DMA channel to arm
in sourceAddress - the address that is the source of the DMA transfer
in destinationAddress - the address that is the destination of the DMA transfer
in dmaTransferSize - the number of DMA transfers to make in a transaction
Note
This function does not enable the DMA. Use Dma_Enable or the enable macro to enable the DMA.
Definition at line 180 of file Dma.c.
Referenced by SpiSlave_LoadPacket(), and SpiSlave_ReadPacket().
void Dma_Configure (DmaChannel_t channel, const DmaConfig_t * config)
Configures the DMA to be ready to use.
Parameters
in channel - the DMA channel to configure
in config - the configuration struct of configuration options
Definition at line 120 of file Dma.c.
Referenced by SpiSlave_Init().
void Dma_Disable (DmaChannel_t channel)
Disables the DMA.
Parameters
in channel - the DMA channel to disable
Note
This function provides better safety checking (verifying that the DMA channel is valid) than the macro but the disable macro takes fewer clock cycles.
Definition at line 225 of file Dma.c.
Referenced by SpiSlave_FlushRead(), and SpiSlave_UnloadPacket().
void Dma_DisableIsr (DmaChannel_t channel)
Disables the ISR for a DMA channel.
Parameters
in channel - the DMA channel for the ISR
Note
This function provides better safety checking (verifying that the DMA channel is valid) than the macro but the macro takes fewer clock cycles.
Definition at line 307 of file Dma.c.
Referenced by SpiSlave_FlushRead(), and SpiSlave_UnloadPacket().
void Dma_Enable (DmaChannel_t channel)
Enables the DMA to perform a transaction as soon as it is triggered.
Parameters
in channel - the DMA channel to enable
Note
This function provides better safety checking (verifying that the DMA is configured and armed) than the macro but the enable macro takes fewer clock cycles.
Definition at line 206 of file Dma.c.
Referenced by SpiSlave_LoadPacket(), and SpiSlave_ReadPacket().
void Dma_EnableIsr (DmaChannel_t channel)
Enables the ISR for a DMA channel.
Parameters
in channel - the DMA channel for the ISR
Note
This function provides better safety checking (verifying that the DMA channel is valid) than the macro but the macro takes fewer clock cycles.
Definition at line 291 of file Dma.c.
Referenced by SpiSlave_LoadPacket(), and SpiSlave_ReadPacket().
void Dma_Init (void)
Initializes the DMA.
Definition at line 103 of file Dma.c.
Referenced by main().
void Dma_RegisterIsr (DmaChannel_t channel, DmaIsrPointer_t isrPtr)
Register an ISR for a DMA channel.
Parameters
in channel - the DMA channel for the ISR
in isrPtr - pointer to the ISR
Definition at line 253 of file Dma.c.
Referenced by SpiSlave_Init().
void Dma_Trigger (DmaChannel_t channel)
Triggers the DMA to start a transaction.
Parameters
in channel - the DMA channel to trigger
Definition at line 237 of file Dma.c.
void Dma_UnregisterIsr (DmaChannel_t channel)
Unregister an ISR for a DMA channel.
Parameters
in channel - the DMA channel for the ISR to unregister
Definition at line 271 of file Dma.c.