EcgControl.c File Reference
Controls reading the 6-channel ECG.
#include <ProjectTypes.h>
*
#include `EcgControl.h`
*
#include <SensorId.h>
*
#include <DataBuffer.h>
*
#include <KeyValue.h>
*
#include <AdcManager.h>
*
#include <Board.h>
*
#include <Gpio.h>
*
#include <Device.h>
*
#include <Assert.h>
*
#include <Serial.h>
*
Macros
#define HIGH_NIBBLE 0xF000
#define NUM_ADC_CHANNELS 3u
Functions
static AdcManRef_t _Ecg_RefVoltToAdcManRef (EcgRefVolt_t refVolt)
static void _Ecg1DataCallback (uint16_t data)
static void _Ecg2DataCallback (uint16_t data)
static void _Ecg3DataCallback (uint16_t data)
static void _EcgAddToDataBuffer (void)
void EcgControl_Init (void)
void EcgControl_SetConfig (uint8_t config)
Variables
static bool _initialized = false
static EcgSampleRate_t _sampleRate = DEFAULT_ECG_SAMPLE_RATE
static uint16_t _dataSamples [NUM_ADC_CHANNELS] = {HIGH_NIBBLE, HIGH_NIBBLE, HIGH_NIBBLE}
static EcgRefVolt_t _refVolt = DEFAULT_ECG_REF_VOLT
Detailed Description
Controls reading the 6-channel ECG. Controls reading the ECG.
Project 1814 IOLab Remote Sensor Application
Description Controls the 6-channel ECG and manages the configurations and settings associated with the ECG.
Project 1814 IOLab Remote Sensor Application
Description Controls the ECG and manages the configurations and settings associated with the ECG.
Definition in file EcgControl.c.
Macro Definition Documentation
#define HIGH_NIBBLE 0xF000
The most significant nibble should always be 0 since the A to D is 12 bits
Definition at line 39 of file EcgControl.c.
Referenced by _Ecg1DataCallback(), _Ecg2DataCallback(), and _Ecg3DataCallback().
#define NUM_ADC_CHANNELS 3u
Number of ADC channels for ECG
Definition at line 42 of file EcgControl.c.
Function Documentation
static void _Ecg1DataCallback (uint16_t data) [static]
Takes the ECG data and stores it in the data array. This function is designed to be called every time there is data for the first ECG channel.
Parameters
in data - The sample from the ECG that should be stored in the proper location.
Definition at line 222 of file EcgControl.c.
Referenced by EcgControl_SetConfig().
static void _Ecg2DataCallback (uint16_t data) [static]
Takes the ECG data and stores it in the data array. This function is designed to be called every time there is data for the second ECG channel.
Parameters
in data - The sample from the ECG that should be stored in the proper location.
Definition at line 244 of file EcgControl.c.
Referenced by EcgControl_SetConfig().
static void _Ecg3DataCallback (uint16_t data) [static]
Takes the ECG data and stores it in the data array. This function is designed to be called every time there is data for the third ECG channel.
Parameters
in data - The sample from the ECG that should be stored in the proper location.
Definition at line 266 of file EcgControl.c.
Referenced by EcgControl_SetConfig().
static AdcManRef_t _Ecg_RefVoltToAdcManRef (EcgRefVolt_t refVolt) [static]
Converts from an EcgRefVolt_t to an AdcManRef_t.
Parameters
in refVolt - the voltage reference selection to match
Returns
The AdcManRef_t value corresponding to the refVolt value
Definition at line 192 of file EcgControl.c.
Referenced by EcgControl_SetConfig().
static void _EcgAddToDataBuffer (void) [static]
Takes the ECG data and stores it in the proper location. This function is designed to be called every time there is data for the ECG.
Definition at line 285 of file EcgControl.c.
Referenced by _Ecg1DataCallback(), _Ecg2DataCallback(), and _Ecg3DataCallback().
void EcgControl_Init (void)
Initializes the ECG reading control.
Definition at line 67 of file EcgControl.c.
Referenced by ConMan_Init().
void EcgControl_SetConfig (uint8_t config)
Takes a configuration and sets it for the ECG reading.
Parameters
in config - the KeyValue configuration setting for the ECG reading.
Definition at line 78 of file EcgControl.c.
Referenced by ConMan_SetSensorConfig().
Variable Documentation
uint16_t _dataSamples[NUM_ADC_CHANNELS] = {HIGH_NIBBLE, HIGH_NIBBLE, HIGH_NIBBLE} [static]
array containing latest samples from all 3 analog inputs for the ECG
Definition at line 52 of file EcgControl.c.
Referenced by _Ecg1DataCallback(), _Ecg2DataCallback(), _Ecg3DataCallback(), and _EcgAddToDataBuffer().
bool _initialized = false [static]
Tracks if the module has been initialized
Definition at line 46 of file EcgControl.c.
EcgRefVolt_t _refVolt = DEFAULT_ECG_REF_VOLT [static]
Stores the desired analog reference voltage of the header pin
Definition at line 55 of file EcgControl.c.
Referenced by EcgControl_SetConfig().
EcgSampleRate_t _sampleRate = DEFAULT_ECG_SAMPLE_RATE [static]
Stores the desired sample rate of the ECG reading
Definition at line 49 of file EcgControl.c.
Referenced by EcgControl_SetConfig().