EncoderControl.h File Reference
Controls the driver for the Quadrature Encoder.
Functions
void EncControl_Init (void)
void EncControl_SetConfig (uint8_t control)
void EncControl_ReadEnc (void)
Detailed Description
Controls the driver for the Quadrature Encoder. Project 1814 IOLab Remote Sensor Application
Description Controls the driver for the Quadrature Encoder and manages the settings and configuration.
Definition in file EncoderControl.h.
Function Documentation
void EncControl_Init (void)
Initializes the encoder controller.
Definition at line 62 of file EncoderControl.c.
Referenced by ConMan_Init().
void EncControl_ReadEnc (void)
Gets a reading from the accelerometer.
Definition at line 151 of file EncoderControl.c.
Referenced by EncControl_SetConfig().
void EncControl_SetConfig (uint8_t control)
Sets a configuration value to the encoder
Parameters
in keyValue - the key/value pair with the configuration information
Definition at line 74 of file EncoderControl.c.
Referenced by ConMan_SetSensorConfig().