EncoderControl.c File Reference
Controls the Quadrature Encoder driver.
#include <ProjectTypes.h>
*
#include `EncoderControl.h`
*
#include <Encoder.h>
*
#include <TimerTick.h>
*
#include <DataBuffer.h>
*
#include <SensorId.h>
*
#include <KeyValue.h>
*
#include <Assert.h>
*
#include <Serial.h>
*
Macros
#define NUM_ENCODER_ITEMS (2u)
#define TIMEOUT_100HZ (10u)
#define TIMEOUT_50HZ (20u)
Functions
void EncControl_Init (void)
void EncControl_SetConfig (uint8_t control)
void EncControl_ReadEnc (void)
Variables
static bool _initialized = false
static TickTimeoutHandle_t _tickHandle
static bool _tickInUse = false
static EncoderSampleRate_t _sampleRate = DEFAULT_ENCODER_SAMPLE_RATE
Detailed Description
Controls the Quadrature Encoder driver. Project 1814 IOLab Remote Sensor Application
Description Controls the quadrature encoder driver and manages the configuration settings, and timing of the encoder.
Definition in file EncoderControl.c.
Macro Definition Documentation
#define NUM_ENCODER_ITEMS (2u)
Defines how many items are in an encoder sample
Definition at line 37 of file EncoderControl.c.
Referenced by EncControl_ReadEnc().
#define TIMEOUT_100HZ (10u)
defines how many milliseconds to wait between samples for a 100 Hz rate
Definition at line 40 of file EncoderControl.c.
Referenced by EncControl_SetConfig().
#define TIMEOUT_50HZ (20u)
defines how many milliseconds to wait between samples for a 50 Hz rate
Definition at line 43 of file EncoderControl.c.
Referenced by EncControl_SetConfig().
Function Documentation
void EncControl_Init (void)
Initializes the encoder controller.
Definition at line 62 of file EncoderControl.c.
Referenced by ConMan_Init().
void EncControl_ReadEnc (void)
Gets a reading from the accelerometer.
Definition at line 151 of file EncoderControl.c.
Referenced by EncControl_SetConfig().
void EncControl_SetConfig (uint8_t control)
Sets a configuration value to the encoder
Parameters
in keyValue - the key/value pair with the configuration information
Definition at line 74 of file EncoderControl.c.
Referenced by ConMan_SetSensorConfig().
Variable Documentation
bool _initialized = false [static]
Tracks if the module is initialized or not
Definition at line 47 of file EncoderControl.c.
EncoderSampleRate_t _sampleRate = DEFAULT_ENCODER_SAMPLE_RATE [static]
Stores the encoder sample rate setting
Definition at line 55 of file EncoderControl.c.
Referenced by EncControl_SetConfig().
TickTimeoutHandle_t _tickHandle [static]
Handle to the timer tick timeout for the encoder
Definition at line 50 of file EncoderControl.c.
Referenced by EncControl_SetConfig().
bool _tickInUse = false [static]
tracks if the tick handle is in use to make sure not to use an invalid tick handle
Definition at line 52 of file EncoderControl.c.
Referenced by EncControl_SetConfig().