Encoder.h File Reference
Hardware driver for the Quadrature Encoder.
Enumerations
enum EncoderStatus_t {
*
EncoderStatus_INVALID,
*
EncoderStatus_OKAY,
*
EncoderStatus_CAPTURE_OVERFLOW,
*
EncoderStatus_SW_CAPTURE_OVERFLOW,
*
EncoderStatus_BUFFER_OVERFLOW,
*
EncoderStatus_OTHER_ERROR
 }
Functions
void Encoder_Init (void)
void Encoder_Start (void)
void Encoder_Stop (void)
EncoderStatus_t Encoder_Read (int16_t counts[], uint16_t *elements, uint16_t maxElements)
Detailed Description
Hardware driver for the Quadrature Encoder. Project 1814 IOLab Remote Sensor Application
Description The quadrature encoder uses a a direction and count input to count how many pulses and in which direction a specially designed encoder moved.
Definition in file Encoder.h.
Enumeration Type Documentation
enum EncoderStatus_t
Defines the status options for the encoder
Definition at line 28 of file Encoder.h.
Function Documentation
void Encoder_Init (void)
Initializes the encoder module.
Definition at line 75 of file Encoder.c.
Referenced by EncControl_Init().
EncoderStatus_t Encoder_Read (int16_t counts[], uint16_t * elements, uint16_t maxElements)
Read the value of the encoder counts.
Parameters
out counts - the counts and direction of the encoder.
out elements - the actual number of samples that were put in counts
in maxElements - the maximum number of samples that fit into counts
Returns
The status of the encoder over the last sample.
Definition at line 138 of file Encoder.c.
Referenced by _HandleHumanEncoderCommand(), and EncControl_ReadEnc().
void Encoder_Start (void)
Starts the counting of the encoder.
Definition at line 97 of file Encoder.c.
Referenced by _HandleHumanEncoderCommand(), and EncControl_SetConfig().
void Encoder_Stop (void)
Stops the counting of the encoder.
Definition at line 117 of file Encoder.c.
Referenced by EncControl_SetConfig().