Encoder.c File Reference
The hardware driver for the quadrature encoder.
#include <ProjectTypes.h>
*
#include `Encoder.h`
*
#include <Device.h>
*
#include <Board.h>
*
#include <Gpio.h>
*
#include <Timer.h>
*
#include <Assert.h>
*
Macros
#define NUM_DIRECTION_CHANGE (2u)
Enumerations
enum EncoderDirection_t {
*
EncoderDirection_INVALID,
*
EncoderDirection_FORWARD,
*
EncoderDirection_BACKWARD
 }
Functions
static void _Encoder_AddSample (uint16_t counts, EncoderDirection_t direction)
static void _Encoder_ClearBuffer (void)
__interrupt void _TimerA2CC0Isr (void)
__interrupt void _TimerA2CCxIsr (void)
void Encoder_Init (void)
void Encoder_Start (void)
void Encoder_Stop (void)
EncoderStatus_t Encoder_Read (int16_t counts[], uint16_t *elements, uint16_t maxElements)
Variables
static bool _initialized = false
static uint16_t _previousCount
static EncoderDirection_t _previousDirection
static EncoderStatus_t _currentStatus = EncoderStatus_OKAY
static int16_t _encoderCounts [NUM_DIRECTION_CHANGE] = { 0u }
static uint16_t _encoderCountIndex = 0u
Detailed Description
The hardware driver for the quadrature encoder. Project 1814 IOLab Remote Sensor Application
Description The quadrature encoder uses a a direction and count input to count how many pulses and in which direction a specially designed encoder moved.
The encoder module uses timer A2 of for hardware counting and direction checking.
Definition in file Encoder.c.
Macro Definition Documentation
#define NUM_DIRECTION_CHANGE (2u)
Defines how many previous direction changes to store
Definition at line 47 of file Encoder.c.
Referenced by _Encoder_AddSample(), _Encoder_ClearBuffer(), and Encoder_Read().
Enumeration Type Documentation
enum EncoderDirection_t
Defines the direction options for the timer
Definition at line 39 of file Encoder.c.
Function Documentation
static void _Encoder_AddSample (uint16_t counts, EncoderDirection_t direction) [static]
Adds an encoder sample to the buffer.
Parameters
in counts - the value of the encoder HW counter
in direction - the current direction of the encoder
Definition at line 206 of file Encoder.c.
Referenced by _TimerA2CC0Isr(), and _TimerA2CCxIsr().
static void _Encoder_ClearBuffer (void) [static]
Clears the storage buffer for the encoder.
Definition at line 254 of file Encoder.c.
Referenced by Encoder_Read(), and Encoder_Start().
__interrupt void _TimerA2CC0Isr (void)
Interrupt service routine for the timer A2 compare/capture 0 interrupt. The interrupt flag is cleared in hardware when the ISR is called.
Read the value of the counter when the direction change occurred and start counting in the other direction.
Definition at line 274 of file Encoder.c.
__interrupt void _TimerA2CCxIsr (void)
Interrupt service routine for the timer A2 compare/capture 1-4 interrupt. The interrupt flag is cleared in hardware when the ISR is called.
Read the value of the counter and store the value.
Definition at line 312 of file Encoder.c.
void Encoder_Init (void)
Initializes the encoder module.
Definition at line 75 of file Encoder.c.
Referenced by EncControl_Init().
EncoderStatus_t Encoder_Read (int16_t counts[], uint16_t * elements, uint16_t maxElements)
Read the value of the encoder counts.
Parameters
out counts - the counts and direction of the encoder.
out elements - the actual number of samples that were put in counts
in maxElements - the maximum number of samples that fit into counts
Returns
The status of the encoder over the last sample.
Definition at line 138 of file Encoder.c.
Referenced by _HandleHumanEncoderCommand(), and EncControl_ReadEnc().
void Encoder_Start (void)
Starts the counting of the encoder.
Definition at line 97 of file Encoder.c.
Referenced by _HandleHumanEncoderCommand(), and EncControl_SetConfig().
void Encoder_Stop (void)
Stops the counting of the encoder.
Definition at line 117 of file Encoder.c.
Referenced by EncControl_SetConfig().
Variable Documentation
EncoderStatus_t _currentStatus = EncoderStatus_OKAY [static]
Current Encoder Status
Definition at line 59 of file Encoder.c.
Referenced by _Encoder_AddSample(), _TimerA2CC0Isr(), _TimerA2CCxIsr(), and Encoder_Read().
uint16_t _encoderCountIndex = 0u [static]
Stores the index of hte encoder counts
Definition at line 64 of file Encoder.c.
Referenced by _Encoder_AddSample(), _Encoder_ClearBuffer(), and Encoder_Read().
int16_t _encoderCounts[NUM_DIRECTION_CHANGE] = { 0u } [static]
Stores the encoder counts
Definition at line 62 of file Encoder.c.
Referenced by _Encoder_AddSample(), _Encoder_ClearBuffer(), and Encoder_Read().
bool _initialized = false [static]
Tracks if the module has been initialized
Definition at line 51 of file Encoder.c.
uint16_t _previousCount [static]
Tracks the count on the timer the last time it was captured.
Definition at line 54 of file Encoder.c.
Referenced by _Encoder_AddSample(), and Encoder_Start().
EncoderDirection_t _previousDirection [static]
Tracks the direction of the timer
Definition at line 56 of file Encoder.c.
Referenced by _Encoder_AddSample(), and Encoder_Start().