EventQueue.c File Reference
Event queue module.
#include <ProjectTypes.h>
*
#include `EventQueue.h`
*
#include <Interrupt.h>
*
#include <Assert.h>
*
Macros
#define QUEUE_SIZE (32u)
#define NUM_PRIORITIES (((int8_t) EventPriority_HIGHEST) + 1)
Functions
static void _CheckQueueLength (EventPriority_t priority)
void EventQueue_Init (void)
void EventQueue_Add (Event_t newEvent, EventPriority_t priority)
bool EventQueue_GetNext (Event_t *nextEvent)
bool EventQueue_IsEmpty (void)
uint16_t EventQueue_GetMaxLength (EventPriority_t priority)
Variables
static Event_t _eventQueue [NUM_PRIORITIES][QUEUE_SIZE]
static volatile uint16_t _queueIndexHead [NUM_PRIORITIES]
static volatile uint16_t _queueIndexTail [NUM_PRIORITIES]
static uint16_t _queueMaxLength [NUM_PRIORITIES]
Detailed Description
Event queue module. Project 1814 IOLab Remote Sensor Application
Description The event queue module provides a FIFO buffer for enqueueing events in the system.
Definition in file EventQueue.c.
Macro Definition Documentation
#define NUM_PRIORITIES (((int8_t) EventPriority_HIGHEST) + 1)
The number of priority levels
Definition at line 34 of file EventQueue.c.
#define QUEUE_SIZE (32u)
The maximum number of events minus one that the queue can store
Definition at line 31 of file EventQueue.c.
Referenced by _CheckQueueLength(), EventQueue_Add(), and EventQueue_GetNext().
Function Documentation
static void _CheckQueueLength (EventPriority_t priority) [static]
Checks the queue length at the given priority level.
Parameters
in priority - Selected priority level.
Definition at line 205 of file EventQueue.c.
Referenced by EventQueue_GetNext().
void EventQueue_Add (Event_t newEvent, EventPriority_t priority)
Adds an event to the queue at a given priority.
Parameters
in newEvent - Event to add to the queue.
in priority - Priority of the event.
Note
This does disable interrupts so that if it events are added in interrupt context and general application context then there won't be a race condition.
Definition at line 78 of file EventQueue.c.
Referenced by _AccDataReadyIsr(), _AdcIsr(), _GyroDataReadyIsr(), _HandleDmaRxIsr(), _HandleDmaTxIsr(), _HandlePowerDownPacket(), _HandleRfStatusISR(), _MagDataReadyIsr(), _PlaySequence(), _ProcessEvents_RUN(), _ProcessPushButtons(), _TimerA1CC0Isr(), _UnlatchPower(), SelfTest_Process(), SelfTest_Start(), and Serial_ProcessReceivedBytes().
uint16_t EventQueue_GetMaxLength (EventPriority_t priority)
Get the maximum length of the queue at the given priority level.
Parameters
in priority - Selected priority level.
Returns
The maximum length of the queue.
Definition at line 195 of file EventQueue.c.
bool EventQueue_GetNext (Event_t * nextEvent)
Gets the next event on the queue.
Parameters
out nextEvent - The event removed from the queue.
Returns
True if an event was retrieved. False if the entire queue was empty.
Definition at line 125 of file EventQueue.c.
Referenced by StateMachine_ProcessEvents().
void EventQueue_Init (void)
Initializes the queue.
Definition at line 57 of file EventQueue.c.
Referenced by main().
bool EventQueue_IsEmpty (void)
Determines if the event queue is empty.
Returns
True if the entire event queue is empty. Otherwise false.
Definition at line 168 of file EventQueue.c.
Referenced by main().
Variable Documentation
Event_t _eventQueue[NUM_PRIORITIES][QUEUE_SIZE] [static]
Array to store the events, grouped by priority
Definition at line 38 of file EventQueue.c.
Referenced by EventQueue_Add(), and EventQueue_GetNext().
volatile uint16_t _queueIndexHead[NUM_PRIORITIES] [static]
Stores the index of the next available spot in the queue for each priority
Definition at line 41 of file EventQueue.c.
Referenced by _CheckQueueLength(), EventQueue_Add(), EventQueue_GetNext(), EventQueue_Init(), and EventQueue_IsEmpty().
volatile uint16_t _queueIndexTail[NUM_PRIORITIES] [static]
Stores the index of the next event to process from the queue for each priority
Definition at line 44 of file EventQueue.c.
Referenced by _CheckQueueLength(), EventQueue_Add(), EventQueue_GetNext(), EventQueue_Init(), and EventQueue_IsEmpty().
uint16_t _queueMaxLength[NUM_PRIORITIES] [static]
Stores the maximum length the queue has reached at priority levels. This is used for load leveling to check how close the queue has been to being compeletely full
Definition at line 49 of file EventQueue.c.
Referenced by _CheckQueueLength(), EventQueue_GetMaxLength(), and EventQueue_Init().