EventQueue.h File Reference
Event queue module header file.
Enumerations
enum Event_t {
*
Event_INVALID = -1,
*
Event_FIRST = 0,
*
Event_TIMEOUT = Event_FIRST,
*
Event_ADC_CONVERSION_SEQUENCE_COMPLETE,
*
Event_SERIAL_RECEIVED_PACKET,
*
Event_LED_CONTROL_TIMEOUT,
*
Event_STATE_MACHINE_TIMEOUT,
*
Event_SPI_SLAVE_TX_COMPLETE,
*
Event_SPI_SLAVE_RX_COMPLETE,
*
Event_ACCELEROMETER_DATA_READY,
*
Event_MAGNETOMETER_DATA_READY,
*
Event_GYROSCOPE_DATA_READY,
*
Event_BAROMETER_DATA_READY,
*
Event_SYSTEM_TICK,
*
Event_SHUTDOWN,
*
Event_BUTTON_0_PRESSED,
*
Event_BUTTON_0_RELEASED,
*
Event_BUTTON_1_PRESSED,
*
Event_BUTTON_1_RELEASED,
*
Event_START_SELF_TEST,
*
Event_SELF_TEST,
*
Event_SELF_TEST_COMPLETE,
*
EventApplication_SEQUENCE_COMPLETE,
*
Event_LAST
 }
enum EventPriority_t {
*
EventPriority_LOWEST = 0,
*
EventPriority_NORMAL,
*
EventPriority_HIGH,
*
EventPriority_HIGHEST = EventPriority_HIGH
 }
Functions
void EventQueue_Init (void)
void EventQueue_Add (Event_t newEvent, EventPriority_t priority)
bool EventQueue_GetNext (Event_t *nextEvent)
bool EventQueue_IsEmpty (void)
uint16_t EventQueue_GetMaxLength (EventPriority_t priority)
Detailed Description
Event queue module header file. Project 1814 IOLab Remote Sensor Application
Description The event queue module provides a FIFO buffer for enqueueing events in the system.
Definition in file EventQueue.h.
Enumeration Type Documentation
enum Event_t
List of all possible events
Definition at line 27 of file EventQueue.h.
enum EventPriority_t
The possible event priorities
Enumerator
EventPriority_NORMAL
 Lowest priority should be used by most events
EventPriority_HIGH
Lowest priority.
EventPriority_HIGHEST
 High priority events should only be used by a Serial Messages
Definition at line 56 of file EventQueue.h.
Function Documentation
void EventQueue_Add (Event_t newEvent, EventPriority_t priority)
Adds an event to the queue at a given priority.
Parameters
in newEvent - Event to add to the queue.
in priority - Priority of the event.
Note
This does disable interrupts so that if it events are added in interrupt context and general application context then there won't be a race condition.
Definition at line 78 of file EventQueue.c.
Referenced by _AccDataReadyIsr(), _AdcIsr(), _GyroDataReadyIsr(), _HandleDmaRxIsr(), _HandleDmaTxIsr(), _HandlePowerDownPacket(), _HandleRfStatusISR(), _MagDataReadyIsr(), _PlaySequence(), _ProcessEvents_RUN(), _ProcessPushButtons(), _TimerA1CC0Isr(), _UnlatchPower(), SelfTest_Process(), SelfTest_Start(), and Serial_ProcessReceivedBytes().
uint16_t EventQueue_GetMaxLength (EventPriority_t priority)
Get the maximum length of the queue at the given priority level.
Parameters
in priority - Selected priority level.
Returns
The maximum length of the queue.
Definition at line 195 of file EventQueue.c.
bool EventQueue_GetNext (Event_t * nextEvent)
Gets the next event on the queue.
Parameters
out nextEvent - The event removed from the queue.
Returns
True if an event was retrieved. False if the entire queue was empty.
Definition at line 125 of file EventQueue.c.
Referenced by StateMachine_ProcessEvents().
void EventQueue_Init (void)
Initializes the queue.
Definition at line 57 of file EventQueue.c.
Referenced by main().
bool EventQueue_IsEmpty (void)
Determines if the event queue is empty.
Returns
True if the entire event queue is empty. Otherwise false.
Definition at line 168 of file EventQueue.c.
Referenced by main().