ForceGaugeControl.c File Reference
Controls the force gauge.
#include <ProjectTypes.h>
*
#include `ForceGaugeControl.h`
*
#include <SensorId.h>
*
#include <DataBuffer.h>
*
#include <KeyValue.h>
*
#include <AdcManager.h>
*
#include <Assert.h>
*
#include <Serial.h>
*
Functions
static void _ForceGaugeDataCallback (uint16_t data)
void FgControl_Init (void)
void FgControl_SetConfig (uint8_t config)
Variables
bool _initialized = false
static ForceGaugeSampleRate_t _sampleRate = DEFAULT_FORCE_GAUGE_SAMPLE_RATE
Detailed Description
Controls the force gauge. Project 1814 IOLab Remote Sensor Application
Description Controls the force gauge and manages the configurations and settings associated with the force gauge.
Definition in file ForceGaugeControl.c.
Function Documentation
static void _ForceGaugeDataCallback (uint16_t data) [static]
Takes the force gauge data and stores it in the proper location. This function is designed to be called every time there is data for the force gauge.
Parameters
in data - The sample from the force gauge that should be stored in the proper location.
Definition at line 159 of file ForceGaugeControl.c.
Referenced by FgControl_SetConfig().
void FgControl_Init (void)
Initializes the force gauge control.
Definition at line 50 of file ForceGaugeControl.c.
Referenced by ConMan_Init().
void FgControl_SetConfig (uint8_t config)
Takes a configuration and set its for the force gauge.
Parameters
in config - the KeyValue configuration setting for the force gauge.
Definition at line 61 of file ForceGaugeControl.c.
Referenced by ConMan_SetSensorConfig().
Variable Documentation
bool _initialized = false
Tracks if the module has been initialized
Definition at line 38 of file ForceGaugeControl.c.
Referenced by FgControl_Init(), and FgControl_SetConfig().
ForceGaugeSampleRate_t _sampleRate = DEFAULT_FORCE_GAUGE_SAMPLE_RATE [static]
Stores the desired sample rate of the force gauge
Definition at line 41 of file ForceGaugeControl.c.
Referenced by FgControl_SetConfig().