Gpio.h File Reference
GPIO configuration and control macros and functions.
#include <Device.h>
*
Macros
Digital I/O value control and test macros.
#define GPIO_SET(port, pin) GPIO_SET_PREP(port, (pin))
Set a GPIO pin to high.
#define GPIO_CLEAR(port, pin) GPIO_CLEAR_PREP(port, (pin))
Clear a GPIO pin to low.
#define GPIO_TOGGLE(port, pin) GPIO_TOGGLE_PREP(port, (pin))
Toggle the value of a GPIO pin.
#define GPIO_IS_HIGH(port, pin) GPIO_IS_HIGH_PREP(port, (pin))
Check if a GPIO pin is high.
#define GPIO_IS_LOW(port, pin) GPIO_IS_LOW_PREP(port, (pin))
Check if a GPIO pin is low.
#define GPIO_PORT_GET(port, pins) GPIO_PORT_GET_PREP(port, (pins))
Check the status of multiple GPIO pins on one port.
Digital I/O interrupt control and test macros.
Each pin of ports 1 and 2 have individual interrupt flag, enable, and edge select bits. These feed into two ISRs, one for port 1 and one for port 2. The individual flags must be looked at within the ISRs to determine which pin caused the interrupt.
#define GPIO_INT_ENABLE(port, pin) GPIO_INT_ENABLE_PREP(port, (pin))
Enable the interrupt for a GPIO pin.
#define GPIO_INT_DISABLE(port, pin) GPIO_INT_DISABLE_PREP(port, (pin))
Disable the interrupt for a GPIO pin.
#define GPIO_INT_CLEAR(port, pin) GPIO_INT_CLEAR_PREP(port, (pin))
Clear the interrupt flag for a GPIO pin.
#define GPIO_INT_IS_FLAG_SET(port, pin) GPIO_INT_IS_FLAG_SET_PREP(port, (pin))
Check ifi the interrupt flag for a GPIO pin is set.
#define GPIO_INT_IS_ENABLED(port, pin) GPIO_INT_IS_ENABLED_PREP(port, (pin))
Check if the interrupt for a GPIO pin is enabled.
Internal GPIO value control and test macros.
#define GPIO_SET_PREP(port, pin) (P##port##OUT = P##port##OUT | ((uint8_t) (pin)))
#define GPIO_CLEAR_PREP(port, pin) (P##port##OUT = P##port##OUT & ((uint8_t) ~(pin)))
#define GPIO_TOGGLE_PREP(port, pin) (P##port##OUT = P##port##OUT ^ ((uint8_t) (pin)))
#define GPIO_IS_HIGH_PREP(port, pin) ((((uint16_t) P##port##IN) & (pin)) > 0u)
#define GPIO_IS_LOW_PREP(port, pin) ((((uint16_t) P##port##IN) & (pin)) == 0u)
#define GPIO_PORT_GET_PREP(port, pins) (((uint16_t) P##port##IN) & (pins))
Internal GPIO interrupt control and test macros.
#define GPIO_INT_ENABLE_PREP(port, pin) (P##port##IE = P##port##IE | ((uint8_t) (pin)))
#define GPIO_INT_DISABLE_PREP(port, pin) (P##port##IE = P##port##IE & ((uint8_t) ~(pin)))
#define GPIO_INT_CLEAR_PREP(port, pin) (P##port##IFG = P##port##IFG & ((uint8_t) ~(pin)))
#define GPIO_INT_IS_FLAG_SET_PREP(port, pin) ((((uint16_t) P##port##IFG) & (pin)) > 0u)
#define GPIO_INT_IS_ENABLED_PREP(port, pin) ((((uint16_t) P##port##IE) & (pin)) > 0u)
Typedefs
typedef void(* GpioIsrPointer_t)(void)
Enumerations
enum GpioType_t {
*
GpioType_INPUT,
*
GpioType_OUTPUT,
*
GpioType_PERIPHERAL_INPUT,
*
GpioType_PERIPHERAL_OUTPUT
 }
enum GpioValue_t {
*
GpioValue_LOW = false,
*
GpioValue_HIGH = true,
*
GpioValue_DONT_CARE = GpioValue_LOW
 }
enum GpioDriveStrength_t {
*
GpioDriveStrength_REDUCED = 0,
*
GpioDriveStrength_FULL = 1,
*
GpioDriveStrength_DEFAULT = GpioDriveStrength_REDUCED
 }
enum GpioResistorType_t {
*
GpioResistorType_PULLDOWN,
*
GpioResistorType_PULLUP
 }
enum GpioEdge_t {
*
GpioEdge_RISING,
*
GpioEdge_FALLING
 }
Functions
void Gpio_Init (void)
void Gpio_Configure (int16_t port, uint8_t pinMask, GpioType_t type, GpioValue_t value, GpioDriveStrength_t driveStrength)
void Gpio_ConfigurePortJ (uint8_t pinMask, GpioType_t type, GpioValue_t value, GpioDriveStrength_t driveStrength)
void Gpio_ConfigurePortU (uint8_t pinMask, GpioType_t type, GpioValue_t value)
void Gpio_EnableResistor (int16_t port, uint8_t pinMask, GpioResistorType_t resistorType)
void Gpio_DisableResistor (int16_t port, uint8_t pinMask)
void Gpio_Set (int16_t port, uint8_t pinMask)
void Gpio_SetPortU (uint8_t pinMask)
void Gpio_SetPortJ (uint8_t pinMask)
void Gpio_Clear (int16_t port, uint8_t pinMask)
void Gpio_ClearPortU (uint8_t pinMask)
void Gpio_ClearPortJ (uint8_t pinMask)
bool Gpio_GetValue (int16_t port, uint8_t pinMask)
bool Gpio_GetValuePortU (uint8_t pinMask)
bool Gpio_GetValuePortJ (uint8_t pinMask)
void Gpio_RegisterIsr (int16_t port, uint8_t pinMask, GpioIsrPointer_t isr, GpioEdge_t edge)
void Gpio_UnregisterIsr (int16_t port, uint8_t pinMask)
void Gpio_SelectInterruptEdge (int16_t port, uint8_t pinMask, GpioEdge_t edge)
GpioEdge_t Gpio_GetInterruptEdge (int16_t port, uint8_t pinMask)
Detailed Description
GPIO configuration and control macros and functions. Project 1814 IOLab Remote Sensor Application
Description The functions and macros defined in this file provide access to the configuration and control registers for the GPIO pins on the MSP430. This includes access to the interrupt control registers for ports 1 and 2.
Definition in file Gpio.h.
Macro Definition Documentation
#define GPIO_CLEAR(port, pin) GPIO_CLEAR_PREP(port, (pin))
Clear a GPIO pin to low.
Assumes the GPIO pin is already configured as an output. Should only be used with the port and pin definitions in Board.h.
Parameters
in port - Port number of pin
in pin - Pin mask
Definition at line 99 of file Gpio.h.
Referenced by AdcManager_PoweredChannelControl(), and UltrasoundStartTransmit().
#define GPIO_INT_CLEAR(port, pin) GPIO_INT_CLEAR_PREP(port, (pin))
Clear the interrupt flag for a GPIO pin.
Only valid for ports 1 and 2. Should only be used with the port and pin definitions in Board.h.
Parameters
in port - Port number of pin
in pin - Pin mask
Definition at line 189 of file Gpio.h.
#define GPIO_INT_DISABLE(port, pin) GPIO_INT_DISABLE_PREP(port, (pin))
Disable the interrupt for a GPIO pin.
Only valid for ports 1 and 2. Should only be used with the port and pin definitions in Board.h.
Parameters
in port - Port number of pin
in pin - Pin mask
Definition at line 178 of file Gpio.h.
Referenced by Accelerometer_Stop(), Gyroscope_Stop(), and Magnetometer_Stop().
#define GPIO_INT_ENABLE(port, pin) GPIO_INT_ENABLE_PREP(port, (pin))
Enable the interrupt for a GPIO pin.
Only valid for ports 1 and 2. Should only be used with the port and pin definitions in Board.h.
Parameters
in port - Port number of pin
in pin - Pin mask
Definition at line 167 of file Gpio.h.
Referenced by Accelerometer_Start(), Gyroscope_Start(), and Magnetometer_Start().
#define GPIO_INT_IS_ENABLED(port, pin) GPIO_INT_IS_ENABLED_PREP(port, (pin))
Check if the interrupt for a GPIO pin is enabled.
Only valid for ports 1 and 2. Should only be used with the port and pin definitions in Board.h.
Parameters
in port - Port number of pin
in pin - Pin mask
Returns
True if the interrupt is enabled, false otherwise.
Definition at line 215 of file Gpio.h.
#define GPIO_INT_IS_FLAG_SET(port, pin) GPIO_INT_IS_FLAG_SET_PREP(port, (pin))
Check ifi the interrupt flag for a GPIO pin is set.
Only valid for ports 1 and 2. Should only be used with the port and pin definitions in Board.h.
Parameters
in port - Port number of pin
in pin - Pin mask
Returns
True if flag is set, false otherwise.
Definition at line 202 of file Gpio.h.
#define GPIO_IS_HIGH(port, pin) GPIO_IS_HIGH_PREP(port, (pin))
Check if a GPIO pin is high.
Should only be used with the port and pin definitions in Board.h.
Parameters
in port - Port number of pin
in pin - Pin mask
Returns
True if the pin is high, false otherwise.
Definition at line 122 of file Gpio.h.
Referenced by _ReadPins().
#define GPIO_IS_LOW(port, pin) GPIO_IS_LOW_PREP(port, (pin))
Check if a GPIO pin is low.
Should only be used with the port and pin definitions in Board.h.
Parameters
in port - Port number of pin
in pin - Pin mask
Returns
True if the pin is low, false otherwise.
Definition at line 134 of file Gpio.h.
Referenced by _ProcessPushButtons(), and PushButtonControl_Init().
#define GPIO_PORT_GET(port, pins) GPIO_PORT_GET_PREP(port, (pins))
Check the status of multiple GPIO pins on one port.
Should only be used with the port and pin definitions in Board.h.
Parameters
in port - Port number of pin
in pins - Pin(s) mask
Returns
Current state of the requested pins.
Definition at line 146 of file Gpio.h.
#define GPIO_SET(port, pin) GPIO_SET_PREP(port, (pin))
Set a GPIO pin to high.
Assumes the GPIO pin is already configured as an output. Should only be used with the port and pin definitions in Board.h.
Parameters
in port - Port number of pin
in pin - Pin mask
Definition at line 88 of file Gpio.h.
Referenced by AdcManager_PoweredChannelControl(), main(), and UltrasoundStartTransmit().
#define GPIO_TOGGLE(port, pin) GPIO_TOGGLE_PREP(port, (pin))
Toggle the value of a GPIO pin.
Assumes the GPIO pin is already configured as an output. Should only be used with the port and pin definitions in Board.h.
Parameters
in port - Port number of pin
in pin - Pin mask
Definition at line 110 of file Gpio.h.
Referenced by Assert().
Typedef Documentation
typedef void(* GpioIsrPointer_t)(void)
Defines a GPIO ISR function pointer
Definition at line 70 of file Gpio.h.
Enumeration Type Documentation
enum GpioDriveStrength_t
Defines the possible GPIO drive strengths.
Definition at line 48 of file Gpio.h.
enum GpioEdge_t
Defines the possible interrupt edges.
Definition at line 63 of file Gpio.h.
enum GpioResistorType_t
Defines the possible resistor types.
Definition at line 56 of file Gpio.h.
enum GpioType_t
Defines the possible GPIO types.
Definition at line 31 of file Gpio.h.
enum GpioValue_t
Defines the possible GPIO values.
Definition at line 40 of file Gpio.h.
Function Documentation
void Gpio_Clear (int16_t port, uint8_t pinMask)
Clear a GPIO pin to low. Allows the port parameter to be a variable, as compared to the GPIO_CLEAR macro that does not.
Note
Use the GPIO_CLEAR macro if possible for better performance.
Parameters
in port - Port number of pin.
in pinMask - Mask of pin.
Definition at line 632 of file Gpio.c.
Referenced by _Led_ProcessStates().
void Gpio_ClearPortJ (uint8_t pinMask)
Clear a Port J GPIO pin to low.
Parameters
in pinMask - Mask of pin.
Definition at line 668 of file Gpio.c.
void Gpio_ClearPortU (uint8_t pinMask)
Clear a Port U GPIO pin to low.
Parameters
in pinMask - Mask of pin.
Definition at line 650 of file Gpio.c.
Referenced by Encoder_Stop(), and System_PowerOff().
void Gpio_Configure (int16_t port, uint8_t pinMask, GpioType_t type, GpioValue_t value, GpioDriveStrength_t driveStrength)
Configures GPIO pins.
Parameters
in port - Port number of pins.
in pinMask - Mask of pins.
in type - Type to set the GPIO to.
in value - Value to set the GPIO to.
in driveStrength - Drive strength to set the GPIO to.
Definition at line 289 of file Gpio.c.
Referenced by _HandleHumanBslCommand(), _HandleHumanGpiCommand(), _HandleHumanGpoCommand(), Clock_Init(), Gpio_Init(), Header1Control_SetConfig(), Header2Control_SetConfig(), Header3Control_SetConfig(), Header4Control_SetConfig(), Header5Control_SetConfig(), Header6Control_SetConfig(), I2c_Close(), I2c_Open(), Pwm_Disable(), Pwm_Enable(), Spi_Init(), SpiSlave_Init(), Uart_Close(), and Uart_Open().
void Gpio_ConfigurePortJ (uint8_t pinMask, GpioType_t type, GpioValue_t value, GpioDriveStrength_t driveStrength)
Configures GPIO pins for Port J.
Parameters
in pinMask - Mask of pins.
in type - Type to set the GPIO to.
in value - Value to set the GPIO to.
in driveStrength - Drive strength to set the GPIO to.
Definition at line 407 of file Gpio.c.
Referenced by _HandleHumanGpiCommand(), and _HandleHumanGpoCommand().
void Gpio_ConfigurePortU (uint8_t pinMask, GpioType_t type, GpioValue_t value)
Configures GPIO pins for Port U.
Parameters
in pinMask - Mask of pins.
in type - Type to set the GPIO to.
in value - Value to set the GPIO to.
Definition at line 469 of file Gpio.c.
Referenced by _HandleHumanGpiCommand(), _HandleHumanGpoCommand(), and Gpio_Init().
void Gpio_DisableResistor (int16_t port, uint8_t pinMask)
Disable the pull-up/pull-down resistor of GPIO pins.
Parameters
in port - Port number of pins.
in pinMask - Mask of pins.
Definition at line 559 of file Gpio.c.
Referenced by Uart_Close().
void Gpio_EnableResistor (int16_t port, uint8_t pinMask, GpioResistorType_t resistorType)
Enable the pull-up/pull-down resistor of GPIO pins.
Parameters
in port - Port number of pins.
in pinMask - Mask of pins.
in resistorType - Type of resistor to enable.
Definition at line 528 of file Gpio.c.
Referenced by Gpio_Init(), and Uart_Open().
GpioEdge_t Gpio_GetInterruptEdge (int16_t port, uint8_t pinMask)
Get the selected interrupt edge for a GPIO pin.
Parameters
in port - Port number of pin.
in pinMask - Mask of pin.
Returns
The selected interrupt edge.
Definition at line 910 of file Gpio.c.
bool Gpio_GetValue (int16_t port, uint8_t pinMask)
Read the value of a GPIO pin. Allows the port parameter to be a variable, as compared to the GPIO_IS_HIGH macro that does not.
Note
Use the GPIO_IS_HIGH macro if possible for better performance.
Parameters
in port - Port number of pin.
in pinMask - Mask of pin.
Definition at line 683 of file Gpio.c.
Referenced by _HandleHumanGpiCommand().
bool Gpio_GetValuePortJ (uint8_t pinMask)
Read the value of a GPIO pin on Port J.
Parameters
in pinMask - Mask of pin.
Definition at line 743 of file Gpio.c.
Referenced by _HandleHumanGpiCommand().
bool Gpio_GetValuePortU (uint8_t pinMask)
Read the value of a GPIO pin on Port U.
Parameters
in pinMask - Mask of pin.
Definition at line 711 of file Gpio.c.
Referenced by _HandleHumanGpiCommand().
void Gpio_Init (void)
Initializes the digital I/O pins.
Definition at line 124 of file Gpio.c.
Referenced by Board_Init().
void Gpio_RegisterIsr (int16_t port, uint8_t pinMask, GpioIsrPointer_t isr, GpioEdge_t edge)
Register an ISR for the given GPIO pin.
Parameters
in port - Port number of pin.
in pinMask - Mask of pin.
in isr - Pointer to GPIO ISR.
in edge - Edge to select.
Definition at line 768 of file Gpio.c.
Referenced by Accelerometer_Init(), Gyroscope_Init(), and Magnetometer_Init().
void Gpio_SelectInterruptEdge (int16_t port, uint8_t pinMask, GpioEdge_t edge)
Select the interrupt edge for GPIO pins.
Parameters
in port - Port number of pins.
in pinMask - Mask of pins.
in edge - Edge to select.
Definition at line 881 of file Gpio.c.
void Gpio_Set (int16_t port, uint8_t pinMask)
Set a GPIO pin to high. Allows the port parameter to be a variable, as compared to the GPIO_SET macro that does not.
Note
Use the GPIO_SET macro if possible for better performance.
Parameters
in port - Port number of pin.
in pinMask - Mask of pin.
Definition at line 581 of file Gpio.c.
Referenced by _Led_ProcessStates().
void Gpio_SetPortJ (uint8_t pinMask)
Set a GPIO pin On port J to high.
Parameters
in pinMask - Mask of pin.
Definition at line 617 of file Gpio.c.
void Gpio_SetPortU (uint8_t pinMask)
Set a GPIO pin On port U to high.
Parameters
in pinMask - Mask of pin.
Definition at line 599 of file Gpio.c.
Referenced by Encoder_Start(), and System_PowerOn().
void Gpio_UnregisterIsr (int16_t port, uint8_t pinMask)
Unregister an ISR for the given GPIO pin.
Parameters
in port - Port number of pin.
in pinMask - Mask of pin.
Definition at line 833 of file Gpio.c.