Gpio.c File Reference
GPIO configuration and control macros and functions.
#include <ProjectTypes.h>
*
#include <Device.h>
*
#include `Gpio.h`
*
#include <Assert.h>
*
#include <Debug.h>
*
#include <Serial.h>
*
#include <Board.h>
*
Macros
#define PORT_MIN (1)
#define PORT_MAX (8)
#define PORT_INT_MIN (1)
#define PORT_INT_MAX (2)
#define PINS_PER_PORT (8u)
#define INPUT_BIT_SHIFT 2
Functions
__interrupt void _GpioPortOneIsr (void)
__interrupt void _GpioPortTwoIsr (void)
static void _UnlockPortU (void)
static void _LockPortU (void)
void Gpio_Init (void)
void Gpio_Configure (int16_t port, uint8_t pinMask, GpioType_t type, GpioValue_t value, GpioDriveStrength_t driveStrength)
void Gpio_ConfigurePortJ (uint8_t pinMask, GpioType_t type, GpioValue_t value, GpioDriveStrength_t driveStrength)
void Gpio_ConfigurePortU (uint8_t pinMask, GpioType_t type, GpioValue_t value)
void Gpio_EnableResistor (int16_t port, uint8_t pinMask, GpioResistorType_t resistorType)
void Gpio_DisableResistor (int16_t port, uint8_t pinMask)
void Gpio_Set (int16_t port, uint8_t pinMask)
void Gpio_SetPortU (uint8_t pinMask)
void Gpio_SetPortJ (uint8_t pinMask)
void Gpio_Clear (int16_t port, uint8_t pinMask)
void Gpio_ClearPortU (uint8_t pinMask)
void Gpio_ClearPortJ (uint8_t pinMask)
bool Gpio_GetValue (int16_t port, uint8_t pinMask)
bool Gpio_GetValuePortU (uint8_t pinMask)
bool Gpio_GetValuePortJ (uint8_t pinMask)
void Gpio_RegisterIsr (int16_t port, uint8_t pinMask, GpioIsrPointer_t isr, GpioEdge_t edge)
void Gpio_UnregisterIsr (int16_t port, uint8_t pinMask)
void Gpio_SelectInterruptEdge (int16_t port, uint8_t pinMask, GpioEdge_t edge)
GpioEdge_t Gpio_GetInterruptEdge (int16_t port, uint8_t pinMask)
Variables
static volatile uint8_t *const _gpioOutputRegisters [PORT_MAX+1]
static volatile uint8_t *const _gpioInputRegisters [PORT_MAX+1]
static volatile uint8_t *const _gpioResistorEnableRegisters [PORT_MAX+1]
static volatile uint8_t *const _gpioInterruptEnableRegisters [PORT_INT_MAX+1]
static volatile uint8_t *const _gpioInterruptEdgeSelectRegisters [PORT_INT_MAX+1]
static GpioIsrPointer_t _gpioIsrListPortOne [PINS_PER_PORT] = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL}
static GpioIsrPointer_t _gpioIsrListPortTwo [PINS_PER_PORT] = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL}
Detailed Description
GPIO configuration and control macros and functions. Project 1814 IOLab Remote Sensor Application
Description The routines in this file are used to initialize or configure the GPIO pins on the MSP430.
Definition in file Gpio.c.
Macro Definition Documentation
#define PINS_PER_PORT (8u)
Number of pins per port
Definition at line 42 of file Gpio.c.
Referenced by Gpio_RegisterIsr(), and Gpio_UnregisterIsr().
#define PORT_INT_MAX (2)
Maximum port number that supports interrupts.
Definition at line 39 of file Gpio.c.
Referenced by Gpio_GetInterruptEdge(), Gpio_RegisterIsr(), Gpio_SelectInterruptEdge(), and Gpio_UnregisterIsr().
#define PORT_INT_MIN (1)
Minimum port number that supports interrupts.
Definition at line 37 of file Gpio.c.
Referenced by Gpio_GetInterruptEdge(), Gpio_RegisterIsr(), Gpio_SelectInterruptEdge(), and Gpio_UnregisterIsr().
#define PORT_MAX (8)
Maximum port number.
Definition at line 34 of file Gpio.c.
Referenced by Gpio_Clear(), Gpio_Configure(), Gpio_DisableResistor(), Gpio_EnableResistor(), Gpio_GetValue(), and Gpio_Set().
#define PORT_MIN (1)
Minimum port number.
Definition at line 32 of file Gpio.c.
Referenced by Gpio_Clear(), Gpio_Configure(), Gpio_DisableResistor(), Gpio_EnableResistor(), Gpio_GetValue(), and Gpio_Set().
Function Documentation
__interrupt void _GpioPortOneIsr (void)
Interrupt service routine for the port 1 GPIO interrupts. The interrupt flag of the interrupt specified in P1IV is cleared when P1IV is read.
Definition at line 938 of file Gpio.c.
__interrupt void _GpioPortTwoIsr (void)
Interrupt service routine for the port 2 GPIO interrupts. The interrupt flag of the interrupt specified in P2IV is cleared when P2IV is read.
Definition at line 1020 of file Gpio.c.
static void _LockPortU (void) [static]
Relocks the port U registers to prevent changing them.
Definition at line 1108 of file Gpio.c.
Referenced by Gpio_ClearPortU(), Gpio_ConfigurePortU(), and Gpio_SetPortU().
static void _UnlockPortU (void) [static]
Unlocks the port U registers for for changing
Definition at line 1100 of file Gpio.c.
Referenced by Gpio_ClearPortU(), Gpio_ConfigurePortU(), and Gpio_SetPortU().
void Gpio_Clear (int16_t port, uint8_t pinMask)
Clear a GPIO pin to low. Allows the port parameter to be a variable, as compared to the GPIO_CLEAR macro that does not.
Note
Use the GPIO_CLEAR macro if possible for better performance.
Parameters
in port - Port number of pin.
in pinMask - Mask of pin.
Definition at line 632 of file Gpio.c.
Referenced by _Led_ProcessStates().
void Gpio_ClearPortJ (uint8_t pinMask)
Clear a Port J GPIO pin to low.
Parameters
in pinMask - Mask of pin.
Definition at line 668 of file Gpio.c.
void Gpio_ClearPortU (uint8_t pinMask)
Clear a Port U GPIO pin to low.
Parameters
in pinMask - Mask of pin.
Definition at line 650 of file Gpio.c.
Referenced by Encoder_Stop(), and System_PowerOff().
void Gpio_Configure (int16_t port, uint8_t pinMask, GpioType_t type, GpioValue_t value, GpioDriveStrength_t driveStrength)
Configures GPIO pins.
Parameters
in port - Port number of pins.
in pinMask - Mask of pins.
in type - Type to set the GPIO to.
in value - Value to set the GPIO to.
in driveStrength - Drive strength to set the GPIO to.
Definition at line 289 of file Gpio.c.
Referenced by _HandleHumanBslCommand(), _HandleHumanGpiCommand(), _HandleHumanGpoCommand(), Clock_Init(), Gpio_Init(), Header1Control_SetConfig(), Header2Control_SetConfig(), Header3Control_SetConfig(), Header4Control_SetConfig(), Header5Control_SetConfig(), Header6Control_SetConfig(), I2c_Close(), I2c_Open(), Pwm_Disable(), Pwm_Enable(), Spi_Init(), SpiSlave_Init(), Uart_Close(), and Uart_Open().
void Gpio_ConfigurePortJ (uint8_t pinMask, GpioType_t type, GpioValue_t value, GpioDriveStrength_t driveStrength)
Configures GPIO pins for Port J.
Parameters
in pinMask - Mask of pins.
in type - Type to set the GPIO to.
in value - Value to set the GPIO to.
in driveStrength - Drive strength to set the GPIO to.
Definition at line 407 of file Gpio.c.
Referenced by _HandleHumanGpiCommand(), and _HandleHumanGpoCommand().
void Gpio_ConfigurePortU (uint8_t pinMask, GpioType_t type, GpioValue_t value)
Configures GPIO pins for Port U.
Parameters
in pinMask - Mask of pins.
in type - Type to set the GPIO to.
in value - Value to set the GPIO to.
Definition at line 469 of file Gpio.c.
Referenced by _HandleHumanGpiCommand(), _HandleHumanGpoCommand(), and Gpio_Init().
void Gpio_DisableResistor (int16_t port, uint8_t pinMask)
Disable the pull-up/pull-down resistor of GPIO pins.
Parameters
in port - Port number of pins.
in pinMask - Mask of pins.
Definition at line 559 of file Gpio.c.
Referenced by Uart_Close().
void Gpio_EnableResistor (int16_t port, uint8_t pinMask, GpioResistorType_t resistorType)
Enable the pull-up/pull-down resistor of GPIO pins.
Parameters
in port - Port number of pins.
in pinMask - Mask of pins.
in resistorType - Type of resistor to enable.
Definition at line 528 of file Gpio.c.
Referenced by Gpio_Init(), and Uart_Open().
GpioEdge_t Gpio_GetInterruptEdge (int16_t port, uint8_t pinMask)
Get the selected interrupt edge for a GPIO pin.
Parameters
in port - Port number of pin.
in pinMask - Mask of pin.
Returns
The selected interrupt edge.
Definition at line 910 of file Gpio.c.
bool Gpio_GetValue (int16_t port, uint8_t pinMask)
Read the value of a GPIO pin. Allows the port parameter to be a variable, as compared to the GPIO_IS_HIGH macro that does not.
Note
Use the GPIO_IS_HIGH macro if possible for better performance.
Parameters
in port - Port number of pin.
in pinMask - Mask of pin.
Definition at line 683 of file Gpio.c.
Referenced by _HandleHumanGpiCommand().
bool Gpio_GetValuePortJ (uint8_t pinMask)
Read the value of a GPIO pin on Port J.
Parameters
in pinMask - Mask of pin.
Definition at line 743 of file Gpio.c.
Referenced by _HandleHumanGpiCommand().
bool Gpio_GetValuePortU (uint8_t pinMask)
Read the value of a GPIO pin on Port U.
Parameters
in pinMask - Mask of pin.
Definition at line 711 of file Gpio.c.
Referenced by _HandleHumanGpiCommand().
void Gpio_Init (void)
Initializes the digital I/O pins.
Definition at line 124 of file Gpio.c.
Referenced by Board_Init().
void Gpio_RegisterIsr (int16_t port, uint8_t pinMask, GpioIsrPointer_t isr, GpioEdge_t edge)
Register an ISR for the given GPIO pin.
Parameters
in port - Port number of pin.
in pinMask - Mask of pin.
in isr - Pointer to GPIO ISR.
in edge - Edge to select.
Definition at line 768 of file Gpio.c.
Referenced by Accelerometer_Init(), Gyroscope_Init(), and Magnetometer_Init().
void Gpio_SelectInterruptEdge (int16_t port, uint8_t pinMask, GpioEdge_t edge)
Select the interrupt edge for GPIO pins.
Parameters
in port - Port number of pins.
in pinMask - Mask of pins.
in edge - Edge to select.
Definition at line 881 of file Gpio.c.
void Gpio_Set (int16_t port, uint8_t pinMask)
Set a GPIO pin to high. Allows the port parameter to be a variable, as compared to the GPIO_SET macro that does not.
Note
Use the GPIO_SET macro if possible for better performance.
Parameters
in port - Port number of pin.
in pinMask - Mask of pin.
Definition at line 581 of file Gpio.c.
Referenced by _Led_ProcessStates().
void Gpio_SetPortJ (uint8_t pinMask)
Set a GPIO pin On port J to high.
Parameters
in pinMask - Mask of pin.
Definition at line 617 of file Gpio.c.
void Gpio_SetPortU (uint8_t pinMask)
Set a GPIO pin On port U to high.
Parameters
in pinMask - Mask of pin.
Definition at line 599 of file Gpio.c.
Referenced by Encoder_Start(), and System_PowerOn().
void Gpio_UnregisterIsr (int16_t port, uint8_t pinMask)
Unregister an ISR for the given GPIO pin.
Parameters
in port - Port number of pin.
in pinMask - Mask of pin.
Definition at line 833 of file Gpio.c.
Variable Documentation
volatile uint8_t* const _gpioInputRegisters[PORT_MAX+1] [static]
Initial value:
=
{
    NULL,
    &P1IN,
    &P2IN,
    &P3IN,
    &P4IN,
    &P5IN,
    &P6IN,
    &P7IN,
    &P8IN,
}
Pointers to the GPIO input registers
Definition at line 62 of file Gpio.c.
Referenced by Gpio_GetValue().
volatile uint8_t* const _gpioInterruptEdgeSelectRegisters[PORT_INT_MAX+1] [static]
Initial value:
=
{
    NULL,
    &P1IES,
    &P2IES
}
Pointers to GPIO interrupt edge select registers.
Definition at line 102 of file Gpio.c.
Referenced by Gpio_GetInterruptEdge(), Gpio_RegisterIsr(), and Gpio_SelectInterruptEdge().
volatile uint8_t* const _gpioInterruptEnableRegisters[PORT_INT_MAX+1] [static]
Initial value:
=
{
    NULL,
    &P1IE,
    &P2IE
}
Pointers to GPIO interrupt enable registers.
Definition at line 94 of file Gpio.c.
Referenced by Gpio_RegisterIsr(), and Gpio_UnregisterIsr().
GpioIsrPointer_t _gpioIsrListPortOne[PINS_PER_PORT] = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} [static]
Stores the port one GPIO ISR pointers
Definition at line 111 of file Gpio.c.
Referenced by _GpioPortOneIsr(), Gpio_RegisterIsr(), and Gpio_UnregisterIsr().
GpioIsrPointer_t _gpioIsrListPortTwo[PINS_PER_PORT] = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} [static]
Stores the port two GPIO ISR pointers
Definition at line 113 of file Gpio.c.
Referenced by _GpioPortTwoIsr(), Gpio_RegisterIsr(), and Gpio_UnregisterIsr().
volatile uint8_t* const _gpioOutputRegisters[PORT_MAX+1] [static]
Initial value:
=
{
    NULL,
    &P1OUT,
    &P2OUT,
    &P3OUT,
    &P4OUT,
    &P5OUT,
    &P6OUT,
    &P7OUT,
    &P8OUT,
}
Pointers to GPIO output registers.
Definition at line 46 of file Gpio.c.
Referenced by Gpio_Clear(), Gpio_Configure(), Gpio_EnableResistor(), and Gpio_Set().
volatile uint8_t* const _gpioResistorEnableRegisters[PORT_MAX+1] [static]
Initial value:
=
{
    NULL,
    &P1REN,
    &P2REN,
    &P3REN,
    &P4REN,
    &P5REN,
    &P6REN,
    &P7REN,
    &P8REN,
}
Pointers to GPIO resistor enable registers.
Definition at line 78 of file Gpio.c.
Referenced by Gpio_DisableResistor(), and Gpio_EnableResistor().