GyroscopeControl.h File Reference
Controls the gyroscope driver.
Functions
void GyroControl_Init (void)
void GyroControl_SetConfig (uint8_t value)
void GyroControl_ReadGyro (void)
Detailed Description
Controls the gyroscope driver. Project 1814 IOLab Remote Sensor Application
Description Controls the gyroscope driver and controls the configuration for it.
Definition in file GyroscopeControl.h.
Function Documentation
void GyroControl_Init (void)
Initializes the accelerometer controller.
Definition at line 57 of file GyroscopeControl.c.
Referenced by ConMan_Init().
void GyroControl_ReadGyro (void)
Gets a reading from the accelerometer.
Definition at line 157 of file GyroscopeControl.c.
Referenced by _ProcessEvents_DEFAULT().
void GyroControl_SetConfig (uint8_t keyValue)
Sets a configuration value to the accelerometer
Parameters
in keyValue - the key/value pair with the configuration information
Definition at line 70 of file GyroscopeControl.c.
Referenced by ConMan_SetSensorConfig().