Gyroscope.h File Reference
Header file for Gyroscope sensor driver.
Data Structures
struct GyroConfig_t
struct GyroSample_t
Typedefs
typedef void(* GyroIsrPointer_t)(void)
Enumerations
enum GyroOdr_t {
*
GyroOdr_760,
*
GyroOdr_380,
*
GyroOdr_190,
*
GyroOdr_95
 }
enum GyroResolution_t {
*
GyroResolution_2000,
*
GyroResolution_500,
*
GyroResolution_250
 }
enum GyroBandwidth_t {
*
GyroBandwidth_0,
*
GyroBandwidth_1,
*
GyroBandwidth_2,
*
GyroBandwidth_3
 }
Functions
void Gyroscope_Init (void)
void Gyroscope_Config (const GyroConfig_t *config)
void Gyroscope_Start (void)
void Gyroscope_Stop (void)
bool Gyroscope_ReadSample (GyroSample_t *sample)
void Gyroscope_ReadSampleArray (uint16_t maxLength, uint16_t *actualLength, uint8_t data[])
int8_t Gyroscope_ReadTemperature (void)
void Gyroscope_RegisterIsr (GyroIsrPointer_t isr)
void Gyroscope_UnregisterIsr (void)
Detailed Description
Header file for Gyroscope sensor driver. Project 1814 IOLab Remote Sensor Application
Description The gyroscope sensor driver accesses the 3-axis readings from the gyroscope sensor.
Definition in file Gyroscope.h.
Data Structure Documentation
struct GyroConfig_t
Defines a structure to hold the gyroscope configuration data in.
Definition at line 70 of file Gyroscope.h.
Data Fields
GyroOdr_t
odr
GyroResolution_t
resolution
struct GyroSample_t
Defines a structure to hold the gyroscope sample data in
Definition at line 79 of file Gyroscope.h.
Data Fields
uint16_t
xData
uint16_t
yData
uint16_t
zData
Typedef Documentation
typedef void(* GyroIsrPointer_t)(void)
Defines an gyroscope ISR function pointer
Definition at line 25 of file Gyroscope.h.
Enumeration Type Documentation
enum GyroBandwidth_t
Defines the Bandwidth setting for the gyroscope. The cutoff value depends on the output data rate.
Definition at line 61 of file Gyroscope.h.
enum GyroOdr_t
Defines the options for the gyroscope sample rates in Hz Defines a structure to hold the gyroscope configuration settings Defines the output data rates that the gyroscope can run at.
Definition at line 40 of file Gyroscope.h.
enum GyroResolution_t
Defines the resolution setting for the gyroscope in degrees per second.
Definition at line 51 of file Gyroscope.h.
Function Documentation
void Gyroscope_Config (const GyroConfig_t * config)
Reads in the value of the data from the gyroscope
Parameters
in sample- the location to store the sample data.
Definition at line 368 of file Gyroscope.c.
Referenced by GyroControl_SetConfig().
void Gyroscope_Init (void)
Initializes the gyroscope, but does not configure or start sampling
Definition at line 341 of file Gyroscope.c.
Referenced by GyroControl_Init().
bool Gyroscope_ReadSample (GyroSample_t * sample)
Reads in the value of the data from the gyroscope
Parameters
in sample- the location to store the sample data.
Definition at line 487 of file Gyroscope.c.
Referenced by _HandleHumanGyroCommand(), and GyroControl_ReadGyro().
void Gyroscope_ReadSampleArray (uint16_t maxLength, uint16_t * actualLength, uint8_t data[])
Reads a sample from the gyroscope if a sample was ready.
Parameters
in maxLength - the maximum length of bytes data[] can hold
out actualLength - the actual number of bytes written to data[]
in data - an array to hold the data from the accelerometer reading
Definition at line 513 of file Gyroscope.c.
Referenced by GyroControl_ReadGyro().
int8_t Gyroscope_ReadTemperature (void)
Reads a temperature sample from the gyroscope
Returns
Temperature in °C as a signed 8-bit integer number
Definition at line 544 of file Gyroscope.c.
void Gyroscope_RegisterIsr (GyroIsrPointer_t isr)
Sets a function that will be ran when the data ready interrupt occurs.
Parameters
in isr - pointer to the gyroscope data ready ISR
Definition at line 557 of file Gyroscope.c.
Referenced by GyroControl_Init().
void Gyroscope_Start (void)
Starts the gyroscope sampling at its configured data rate.
Definition at line 441 of file Gyroscope.c.
Referenced by GyroControl_SetConfig(), and ThermometerControl_SetConfig().
void Gyroscope_Stop (void)
Stops the data collecting of the gyroscope.
Definition at line 468 of file Gyroscope.c.
Referenced by GyroControl_SetConfig(), and ThermometerControl_SetConfig().
void Gyroscope_UnregisterIsr (void)
Clears the custom ISR for the gyroscope.
Definition at line 567 of file Gyroscope.c.