Gyroscope.c File Reference
Driver for the gyroscope sensor.
#include <ProjectTypes.h>
*
#include `Gyroscope.h`
*
#include <Clock.h>
*
#include <Gpio.h>
*
#include <Device.h>
*
#include <Board.h>
*
#include <SpiMaster.h>
*
#include <Assert.h>
*
Macros
#define GYROSCOPE_START_SPI_XFER GPIO_CLEAR(CS_GYRO_PORT, CS_GYRO_PIN);
#define GYROSCOPE_END_SPI_XFER GPIO_SET(CS_GYRO_PORT, CS_GYRO_PIN);
#define SPI_CS_DELAY_US 1u
#define BYTES_PER_SAMPLE 6u
#define WHO_AM_I ((uint8_t)0xD4)
Enumerations
enum GyroscopeReg_t {
*
GyroscopeReg_WHO_AM_I = 0x0F,
*
GyroscopeReg_CTRL_REG1 = 0x20,
*
GyroscopeReg_CTRL_REG2 = 0x21,
*
GyroscopeReg_CTRL_REG3 = 0x22,
*
GyroscopeReg_CTRL_REG4 = 0x23,
*
GyroscopeReg_CTRL_REG5 = 0x24,
*
GyroscopeReg_REFERENCE = 0x25,
*
GyroscopeReg_OUT_TEMP = 0x26,
*
GyroscopeReg_STATUS_REG = 0x27,
*
GyroscopeReg_OUT_X_L = 0x28,
*
GyroscopeReg_OUT_X_H = 0x29,
*
GyroscopeReg_OUT_Y_L = 0x2A,
*
GyroscopeReg_OUT_Y_H = 0x2B,
*
GyroscopeReg_OUT_Z_L = 0x2C,
*
GyroscopeReg_OUT_Z_H = 0x2D,
*
GyroscopeReg_FIFO_CTRL_REG = 0x2E,
*
GyroscopeReg_FIFO_SRC_REG = 0x2F,
*
GyroscopeReg_INT1_CFG = 0x30,
*
GyroscopeReg_INT1_SRC = 0x31,
*
GyroscopeReg_INT1_TSH_XH = 0x32,
*
GyroscopeReg_INT1_TSH_XL = 0x33,
*
GyroscopeReg_INT1_TSH_YH = 0x34,
*
GyroscopeReg_INT1_TSH_YL = 0x35,
*
GyroscopeReg_INT1_TSH_ZH = 0x36,
*
GyroscopeReg_INT1_TSH_ZL = 0x37,
*
GyroscopeReg_INT1_DURATION = 0x38
 }
enum CtrlRegOne_t {
*
CtrlRegOne_ASLP_RATE1 = 0x80,
*
CtrlRegOne_ASLP_RATE0 = 0x40,
*
CtrlRegOne_ASLP_RATE = CtrlRegOne_ASLP_RATE1 | CtrlRegOne_ASLP_RATE0,
*
CtrlRegOne_ODR2 = 0x20,
*
CtrlRegOne_ODR1 = 0x10,
*
CtrlRegOne_ODR0 = 0x08,
*
CtrlRegOne_ODR = CtrlRegOne_ODR2 | CtrlRegOne_ODR1 | CtrlRegOne_ODR0,
*
CtrlRegOne_LNOISE = 0x04,
*
CtrlRegOne_F_READ = 0x02,
*
CtrlRegOne_ACTIVE = 0x01,
*
CtrlRegOne_ODR_800 = 0x00,
*
CtrlRegOne_ODR_400 = CtrlRegOne_ODR0,
*
CtrlRegOne_ODR_200 = CtrlRegOne_ODR1,
*
CtrlRegOne_ODR_100 = CtrlRegOne_ODR1 | CtrlRegOne_ODR0,
*
CtrlRegOne_ODR_50 = CtrlRegOne_ODR2,
*
CtrlRegOne_ODR_12_5 = CtrlRegOne_ODR2 | CtrlRegOne_ODR0,
*
CtrlRegOne_ODR_6_25 = CtrlRegOne_ODR2 | CtrlRegOne_ODR1,
*
CtrlRegOne_ODR_1_56 = CtrlRegOne_ODR2 | CtrlRegOne_ODR1 | CtrlRegOne_ODR0,
*
CtrlRegOne_ODR1 = 0x80,
*
CtrlRegOne_ODR0 = 0x40,
*
CtrlRegOne_ODR = CtrlRegOne_ODR1 | CtrlRegOne_ODR0,
*
CtrlRegOne_BW1 = 0x20,
*
CtrlRegOne_BW0 = 0x10,
*
CtrlRegOne_BW = CtrlRegOne_BW1 | CtrlRegOne_BW0,
*
CtrlRegOne_PD = 0x08,
*
CtrlRegOne_Zen = 0x04,
*
CtrlRegOne_Yen = 0x02,
*
CtrlRegOne_Xen = 0x01,
*
CtrlRegOne_ODR_760 = CtrlRegOne_ODR1 | CtrlRegOne_ODR0,
*
CtrlRegOne_ODR_380 = CtrlRegOne_ODR1,
*
CtrlRegOne_ODR_190 = CtrlRegOne_ODR0,
*
CtrlRegOne_ODR_95 = 0x00
 }
enum CtrlRegTwo_t {
*
CtrlRegTwo_ST_EN = 0x80,
*
CtrlRegTwo_RST = 0x40,
*
CtrlRegTwo_SMODS1 = 0x10,
*
CtrlRegTwo_SMODS0 = 0x08,
*
CtrlRegTwo_SMODS = CtrlRegTwo_SMODS1 | CtrlRegTwo_SMODS0,
*
CtrlRegTwo_SMODS_NRML = 0x00,
*
CtrlRegTwo_SMODS_LNLP = CtrlRegTwo_SMODS0,
*
CtrlRegTwo_SMODS_HRES = CtrlRegTwo_SMODS1,
*
CtrlRegTwo_SMODS_LPWR = CtrlRegTwo_SMODS1 | CtrlRegTwo_SMODS0,
*
CtrlRegTwo_SLPE = 0x04,
*
CtrlRegTwo_MODS1 = 0x02,
*
CtrlRegTwo_MODS0 = 0x01,
*
CtrlRegTwo_MODS = CtrlRegTwo_MODS1 | CtrlRegTwo_MODS0,
*
CtrlRegTwo_MODS_NRML = 0x00,
*
CtrlRegTwo_MODS_LNLP = CtrlRegTwo_MODS0,
*
CtrlRegTwo_MODS_HRES = CtrlRegTwo_MODS1,
*
CtrlRegTwo_MODS_LPWR = CtrlRegTwo_MODS1 | CtrlRegTwo_MODS0,
*
CtrlRegTwo_HPM1 = 0x20,
*
CtrlRegTwo_HPM0 = 0x10,
*
CtrlRegTwo_HPM = CtrlRegTwo_HPM1 | CtrlRegTwo_HPM0,
*
CtrlRegTwo_HPCF3 = 0x08,
*
CtrlRegTwo_HPCF2 = 0x04,
*
CtrlRegTwo_HPCF1 = 0x02,
*
CtrlRegTwo_HPCF0 = 0x01,
*
CtrlRegTwo_HPCF = CtrlRegTwo_HPCF3 | CtrlRegTwo_HPCF3 | CtrlRegTwo_HPCF1 | CtrlRegTwo_HPCF0
 }
enum CtrlRegThree_t {
*
CtrlRegThree_FIFO_GATE = 0x80,
*
CtrlRegThree_WAKE_TRANS = 0x40,
*
CtrlRegThree_WAKE_LNDPRT = 0x20,
*
CtrlRegThree_WAKE_PULSE = 0x10,
*
CtrlRegThree_WAKE_FF_MT = 0x08,
*
CtrlRegThree_IPOL = 0x02,
*
CtrlRegThree_PP_OD = 0x01,
*
CtrlRegThree_I1_Int1 = 0x80,
*
CtrlRegThree_I1_Boot = 0x40,
*
CtrlRegThree_H_Lactive = 0x20,
*
CtrlRegThree_PP_OD = 0x10,
*
CtrlRegThree_I2_DRDY = 0x08,
*
CtrlRegThree_I2_WTM = 0x04,
*
CtrlRegThree_I2_ORun = 0x02,
*
CtrlRegThree_I2_Empty = 0x01
 }
enum CtrlRegFour_t {
*
CtrlRegFour_INT_EN_ASLP = 0x80,
*
CtrlRegFour_INT_EN_FIFO = 0x40,
*
CtrlRegFour_INT_EN_TRANS = 0x20,
*
CtrlRegFour_INT_EN_LNDPRT = 0x10,
*
CtrlRegFour_INT_EN_PULSE = 0x80,
*
CtrlRegFour_INT_EN_FF_MT = 0x40,
*
CtrlRegFour_INT_EN_DRDY = 0x01,
*
CtrlRegFour_BDU = 0x80,
*
CtrlRegFour_BLE = 0x40,
*
CtrlRegFour_FS1 = 0x20,
*
CtrlRegFour_FS0 = 0x10,
*
CtrlRegFour_FS = CtrlRegFour_FS1 | CtrlRegFour_FS0,
*
CtrlRegFour_SIM = 0x01,
*
CtrlRegFour_RES_250 = 0x00,
*
CtrlRegFour_RES_500 = CtrlRegFour_FS0,
*
CtrlRegFour_RES_2000 = CtrlRegFour_FS1
 }
enum CtrlRegFive_t {
*
CtrlRegFive_INT_CFG_ASLP = 0x80,
*
CtrlRegFive_INT_CFG_FIFO = 0x40,
*
CtrlRegFive_INT_CFG_TRANS = 0x20,
*
CtrlRegFive_INT_CFG_LNDPRT = 0x10,
*
CtrlRegFive_INT_CFG_PULSE = 0x08,
*
CtrlRegFive_INT_CFG_FF_MT = 0x04,
*
CtrlRegFive_INT_CFG_DRDY = 0x01,
*
CtrlRegFive_BOOT = 0x80,
*
CtrlRegFive_FIFO_EN = 0x40,
*
CtrlRegFive_HPen = 0x10,
*
CtrlRegFive_INT1_Sel1 = 0x08,
*
CtrlRegFive_INT1_Sel0 = 0x04,
*
CtrlRegFive_INT1_Sel = CtrlRegFive_INT1_Sel1 | CtrlRegFive_INT1_Sel0,
*
CtrlRegFive_Out_Sel1 = 0x02,
*
CtrlRegFive_Out_Sel0 = 0x01,
*
CtrlRegFive_Out_Sel = CtrlRegFive_INT1_Sel1 | CtrlRegFive_INT1_Sel0
 }
enum StatusReg_t {
*
StatusReg_ZYXOR = 0x80,
*
StatusReg_ZOR = 0x40,
*
StatusReg_YOR = 0x20,
*
StatusReg_XOR = 0x10,
*
StatusReg_ZYXDA = 0x08,
*
StatusReg_ZDA = 0x04,
*
StatusReg_YDA = 0x02,
*
StatusReg_XDA = 0x01
 }
enum FifoCtrlReg_t {
*
FifoCtrlReg_FM2 = 0x80,
*
FifoCtrlReg_FM1 = 0x40,
*
FifoCtrlReg_FM0 = 0x20,
*
FifoCtrlReg_FM = FifoCtrlReg_FM2 | FifoCtrlReg_FM1 | FifoCtrlReg_FM0,
*
FifoCtrlReg_WTM4 = 0x10,
*
FifoCtrlReg_WTM3 = 0x08,
*
FifoCtrlReg_WTM2 = 0x04,
*
FifoCtrlReg_WTM1 = 0x02,
*
FifoCtrlReg_WTM0 = 0x01,
*
FifoCtrlReg_WTM = FifoCtrlReg_WTM4 | FifoCtrlReg_WTM3 | FifoCtrlReg_WTM2 | FifoCtrlReg_WTM1 | FifoCtrlReg_WTM0
 }
enum FifoSrcReg_t {
*
FifoSrcReg_WTM = 0x80,
*
FifoSrcReg_OVRN = 0x40,
*
FifoSrcReg_EMPTY = 0x20,
*
FifoSrcReg_FSS4 = 0x10,
*
FifoSrcReg_FSS3 = 0x08,
*
FifoSrcReg_FSS2 = 0x04,
*
FifoSrcReg_FSS1 = 0x02,
*
FifoSrcReg_FSS0 = 0x01,
*
FifoSrcReg_FSS = FifoSrcReg_FSS4 | FifoSrcReg_FSS3 | FifoSrcReg_FSS2 | FifoSrcReg_FSS1 | FifoSrcReg_FSS0
 }
enum Int1Cfg_t {
*
Int1Cfg_AND_OR = 0x80,
*
Int1Cfg_LIR = 0x40,
*
Int1Cfg_ZHIE = 0x20,
*
Int1Cfg_ZLIE = 0x10,
*
Int1Cfg_YHIE = 0x08,
*
Int1Cfg_YLIE = 0x04,
*
Int1Cfg_XHIE = 0x02,
*
Int1Cfg_XLIE = 0x01
 }
enum Int1Src_t {
*
Int1Src_IA = 0x40,
*
Int1Src_ZH = 0x20,
*
Int1Src_ZL = 0x10,
*
Int1Src_YH = 0x08,
*
Int1Src_YL = 0x04,
*
Int1Src_XH = 0x02,
*
Int1Src_XL = 0x01
 }
enum Int1Duration_t {
*
Int1Duration_WAIT = 0x80,
*
Int1Duration_D6 = 0x40,
*
Int1Duration_D5 = 0x20,
*
Int1Duration_D4 = 0x10,
*
Int1Duration_D3 = 0x08,
*
Int1Duration_D2 = 0x04,
*
Int1Duration_D1 = 0x02,
*
Int1Duration_D0 = 0x01,
*
Int1Duration_D = Int1Duration_D6 | Int1Duration_D5 | Int1Duration_D4 | Int1Duration_D3 | Int1Duration_D2 | Int1Duration_D1 | Int1Duration_D0
 }
Functions
uint8_t _GyroReadSingleRegister (GyroscopeReg_t regAddress)
void _GyroWriteRegister (GyroscopeReg_t regAddress, uint8_t regValue)
void _GyroReadMultipleRegisters (GyroscopeReg_t regStartAddress, uint8_t numberOfRegisters, uint8_t values[])
static void _HandleDataReadyInterrupt (void)
void _HandleOtherInterrupt (void)
void Gyroscope_Init (void)
void Gyroscope_Config (const GyroConfig_t *config)
void Gyroscope_Start (void)
void Gyroscope_Stop (void)
bool Gyroscope_ReadSample (GyroSample_t *sample)
void Gyroscope_ReadSampleArray (uint16_t maxLength, uint16_t *actualLength, uint8_t data[])
int8_t Gyroscope_ReadTemperature (void)
void Gyroscope_RegisterIsr (GyroIsrPointer_t isr)
void Gyroscope_UnregisterIsr (void)
Variables
static bool _initialized = false
static GyroIsrPointer_t _gyroIsrPointer = NULL
static volatile uint8_t _ctrlRegOne = 0u
static volatile uint8_t _ctrlRegTwo = 0u
static volatile uint8_t _ctrlRegThree = 0u
static volatile uint8_t _ctrlRegFour = 0u
static volatile uint8_t _ctrlRegFive = 0u
static volatile bool _dataReady = false
Detailed Description
Driver for the gyroscope sensor. Project 1814 IOLab Remote Sensor Application
Description This module interfaces to a SPI gyroscope sensor to read the 3-axis data. This driver is designed to work with a ST Micro L3GD20 SPI Gyroscope.
Definition in file Gyroscope.c.
Macro Definition Documentation
#define BYTES_PER_SAMPLE 6u
Defines the number of registers to read a sample
Definition at line 80 of file Gyroscope.c.
Referenced by Gyroscope_ReadSample(), Gyroscope_ReadSampleArray(), and Gyroscope_Start().
#define GYROSCOPE_START_SPI_XFER GPIO_CLEAR(CS_GYRO_PORT, CS_GYRO_PIN);
Defines the chip select enable and disable for the gyroscope
Definition at line 71 of file Gyroscope.c.
Referenced by _GyroReadMultipleRegisters(), _GyroReadSingleRegister(), and _GyroWriteRegister().
#define SPI_CS_DELAY_US 1u
Defines the number of microseconds to delay between de/asserting the chip select line and ending/starting the SPI communication to allow the chip to become ready
Definition at line 77 of file Gyroscope.c.
Referenced by _GyroReadMultipleRegisters(), _GyroReadSingleRegister(), and _GyroWriteRegister().
#define WHO_AM_I ((uint8_t)0xD4)
Define the expected value of the WHO_AM_I query
Definition at line 83 of file Gyroscope.c.
Referenced by Gyroscope_Init().
Enumeration Type Documentation
enum CtrlRegFive_t
Defines the bitmask for the control register GyroscopeReg_CTRL_REG5 of the GyroscopeReg_t.
Enumerator
CtrlRegFive_INT_CFG_FIFO
 auto sleep/wake interrupt routing
CtrlRegFive_INT_CFG_TRANS
 FIFO interrupt routing.
CtrlRegFive_INT_CFG_LNDPRT
 Transient interrupt routing.
CtrlRegFive_INT_CFG_PULSE
 Landscape/portrait interrupt routing.
CtrlRegFive_INT_CFG_FF_MT
 Pulse interrupt routing.
CtrlRegFive_INT_CFG_DRDY
 Freefall/motion interrupt routing.
CtrlRegFive_FIFO_EN
 reboot memory content
CtrlRegFive_HPen
 FIFO enable.
CtrlRegFive_INT1_Sel1
 high-pass filter enable
CtrlRegFive_Out_Sel1
 INT1 selection configuration.
Definition at line 196 of file Gyroscope.c.
enum CtrlRegFour_t
Defines the bitmask for the control register GyroscopeReg_CTRL_REG4 of the GyroscopeReg_t.
Enumerator
CtrlRegFour_INT_EN_FIFO
 auto sleep/wake interrupt enable
CtrlRegFour_INT_EN_TRANS
 FIFO interrupt enable.
CtrlRegFour_INT_EN_LNDPRT
 Transient interrupt enable.
CtrlRegFour_INT_EN_PULSE
 Landscape/portrait interrupt enable.
CtrlRegFour_INT_EN_FF_MT
 Pulse detection interrupt enable.
CtrlRegFour_INT_EN_DRDY
 Freefall/motion interrupt enable.
CtrlRegFour_BLE
 block data update
CtrlRegFour_FS1
 big/little endian data selection
CtrlRegFour_SIM
 full scale selection
CtrlRegFour_RES_250
 SPI serial interface mode selection.
Definition at line 180 of file Gyroscope.c.
enum CtrlRegOne_t
Defines the bitmask for the control register one GyroscopeReg_CTRL_REG1 of the GyroscopeReg_t.
DATA_RATE - 00: 95 Hz 01: 190 Hz 10: 380 Hz 11: 760 Hz
OD BW ODR(Hz) Cut-Off 00 00 95 12.5 00 01 95 25 00 10 95 25 00 11 95 25 01 00 190 12_5 01 01 190 25 01 10 190 50 01 11 190 70 10 00 380 20 10 01 380 25 10 10 380 50 10 11 380 100 11 00 760 30 11 01 760 35 11 10 760 50 11 11 760 100
Enumerator
CtrlRegOne_ASLP_RATE0
 bit 1 of the autowake sample frequency
CtrlRegOne_ASLP_RATE
 bit 0 of the autowake sample frequency
CtrlRegOne_ODR2
 Configures the autowake sample frequency.
CtrlRegOne_LNOISE
 output data rate selection
CtrlRegOne_F_READ
 reduced noise enabled
CtrlRegOne_ACTIVE
 fast read mode enable
CtrlRegOne_ODR_800
 active mode enable
CtrlRegOne_BW1
 output data rate selection
CtrlRegOne_PD
 bandwidth selection
CtrlRegOne_Zen
 power-down mode enable
CtrlRegOne_Yen
 Z axis enable.
CtrlRegOne_Xen
 Y axis enable.
CtrlRegOne_ODR_760
 X axis enable.
Definition at line 110 of file Gyroscope.c.
enum CtrlRegThree_t
Defines the bitmask for the control register GyroscopeReg_CTRL_REG3 of the GyroscopeReg_t.
Enumerator
CtrlRegThree_WAKE_TRANS
 Enable the gate to block the FIFO once full.
CtrlRegThree_WAKE_LNDPRT
 Transient function interrupt can wake up system.
CtrlRegThree_WAKE_PULSE
 Orientation interrupt can wake system.
CtrlRegThree_WAKE_FF_MT
 Pulse interrupt can wake system.
CtrlRegThree_IPOL
 Freefall/motion interrupt can wake system.
CtrlRegThree_PP_OD
 Interrupt polarity active high enable.
CtrlRegThree_I1_Boot
 interrupt enable on INT1 pin
CtrlRegThree_H_Lactive
 boot status available on INT1
CtrlRegThree_PP_OD
 interrupt active configuration on INT1
CtrlRegThree_I2_DRDY
 push-pull/ open drain
CtrlRegThree_I2_WTM
 data ready on DRDY/INT2
CtrlRegThree_I2_ORun
 FIFO watermark interrupt on DRDY/INT2.
CtrlRegThree_I2_Empty
 FIFO overrun interrupt on DRDY/INT2.
Definition at line 164 of file Gyroscope.c.
enum CtrlRegTwo_t
Defines the bitmask for the control register GyroscopeReg_CTRL_REG2 of the GyroscopeReg_t.
HPM[1:0] High-pass filter mode 00 Normal mode (reset reading HP_RESET_FILTER) 01 Reference signal for filtering 10 Normal mode 11 Autoreset on interrupt event
HPCF3-0 ODR=95Hz ODR=190Hz ODR=380Hz ODR=760Hz 0000 7.2 13.5 27 51.4 0001 3.5 7.2 13.5 27 0010 1.8 3.5 7.2 13.5 0011 0.9 1.8 3.5 7.2 0100 0.45 0.9 1.8 3.5 0101 0.18 0.45 0.9 1.8 0110 0.09 0.18 0.45 0.9 0111 0.045 0.09 0.18 0.45 1000 0.018 0.045 0.09 0.18 1001 0.009 0.018 0.045 0.09
Enumerator
CtrlRegTwo_RST
 Self test enable.
CtrlRegTwo_SMODS1
 Software Reset enable.
CtrlRegTwo_SMODS0
 Sleep mode power scheme bit 1.
CtrlRegTwo_SMODS
 Sleep mode power scheme bit 0.
CtrlRegTwo_SMODS_NRML
 Sleep mode power scheme selection.
CtrlRegTwo_MODS1
 Auto sleep mode enable.
CtrlRegTwo_MODS0
 Active mode power scheme bit 1.
CtrlRegTwo_MODS
 Active mode power scheme bit 0.
CtrlRegTwo_MODS_NRML
 Active mode power scheme selection.
CtrlRegTwo_HPCF3
 high-pass filter mode selection
Definition at line 149 of file Gyroscope.c.
enum FifoCtrlReg_t
Defines the bitmask for the control register FIFO_CTRL_REG of the GyroscopeReg_t.
FM2 FM1 FM0 FIFO mode 0 0 0 Bypass mode 0 0 1 FIFO mode 0 1 0 Stream mode 0 1 1 Stream-to-FIFO mode 1 0 0 Bypass-to-Stream mode
Enumerator
FifoCtrlReg_WTM4
 FIFO mode selection.
Definition at line 234 of file Gyroscope.c.
enum FifoSrcReg_t
Defines the bitmask for the control register FIFO_SRC_REG of the GyroscopeReg_t.
Enumerator
FifoSrcReg_OVRN
 Watermark status. (0: FIFO filling is lower than WTM level; 1: FIFO filling is equal or higher than WTM level)
FifoSrcReg_EMPTY
 Overrun bit status.
FifoSrcReg_FSS4
 FIFO empty bit.
Definition at line 251 of file Gyroscope.c.
enum GyroscopeReg_t
Defines the valid register addresses for the gyroscope registers
Enumerator
GyroscopeReg_CTRL_REG1
 Device identification register.
GyroscopeReg_OUT_TEMP
 Reference/DataCapture.
GyroscopeReg_STATUS_REG
 Temperature data.
GyroscopeReg_OUT_X_H
 X-axis angular rate data, low address.
GyroscopeReg_OUT_Y_L
 X-axis angular rate data, high address.
GyroscopeReg_OUT_Y_H
 Y-axis angular rate data, low address.
GyroscopeReg_OUT_Z_L
 Y-axis angular rate data, high address.
GyroscopeReg_OUT_Z_H
 Z-axis angular rate data, low address.
GyroscopeReg_FIFO_CTRL_REG
 Z-axis angular rate data, high address.
GyroscopeReg_INT1_TSH_XL
 Interrupt threshold.
GyroscopeReg_INT1_TSH_YH
 Interrupt threshold.
GyroscopeReg_INT1_TSH_YL
 Interrupt threshold.
GyroscopeReg_INT1_TSH_ZH
 Interrupt threshold.
GyroscopeReg_INT1_TSH_ZL
 Interrupt threshold.
GyroscopeReg_INT1_DURATION
 Interrupt threshold.
Definition at line 38 of file Gyroscope.c.
enum Int1Cfg_t
Defines the bitmask for the control register INT1_CFG of the GyroscopeReg_t.
Enumerator
Int1Cfg_LIR
 AND/OR combination of interrupt events. (0: OR combination of interrupt events 1: AND combination of interrupt events)
Int1Cfg_ZHIE
 Latch interrupt request. (0: interrupt request not latched; 1: interrupt request latched)
Int1Cfg_ZLIE
 Enable interrupt generation on Z high event.
Int1Cfg_YHIE
 Enable interrupt generation on Z low event.
Int1Cfg_YLIE
 Enable interrupt generation on Y high event.
Int1Cfg_XHIE
 Enable interrupt generation on Y low event.
Int1Cfg_XLIE
 Enable interrupt generation on X high event.
Definition at line 267 of file Gyroscope.c.
enum Int1Duration_t
Defines the bitmask for the control register INT1_DURATION of the GyroscopeReg_t.
Enumerator
Int1Duration_D6
 Wait enable.
Definition at line 296 of file Gyroscope.c.
enum Int1Src_t
Defines the bitmask for the control register INT1_SRC of the GyroscopeReg_t.
Enumerator
Int1Src_ZH
 Interrupt active.
Int1Src_ZL
 Z high.
Int1Src_YH
 Z low.
Int1Src_YL
 Y high.
Int1Src_XH
 Y low.
Int1Src_XL
 X high.
Definition at line 282 of file Gyroscope.c.
enum StatusReg_t
Defines the bitmask for the control register STATUS_REG of the GyroscopeReg_t.
Enumerator
StatusReg_ZOR
 X, Y, Z -axis data overrun.
StatusReg_YOR
 Z axis data overrun.
StatusReg_XOR
 Y axis data overrun.
StatusReg_ZYXDA
 X axis data overrun.
StatusReg_ZDA
 X, Y, Z -axis new data available.
StatusReg_YDA
 Z axis new data available.
StatusReg_XDA
 Y axis new data available.
Definition at line 212 of file Gyroscope.c.
Function Documentation
void _GyroReadMultipleRegisters (GyroscopeReg_t regStartAddress, uint8_t numberOfRegisters, uint8_t values[])
Reads from consecutive registers using the SPI port.
Parameters
in regStartAddress - the register address to read from the device
in numberOfRegisters - the number of consecutive registers to read
in values[] - the location to store the register values
Note
The length of values >= numberOfRegisters
Definition at line 640 of file Gyroscope.c.
Referenced by Gyroscope_ReadSample(), Gyroscope_ReadSampleArray(), and Gyroscope_Start().
uint8_t _GyroReadSingleRegister (GyroscopeReg_t regAddress)
Reads from a specific register using the SPI port.
Parameters
in regAddress - the register address to read from the device
Returns
The value read from the register.
Definition at line 602 of file Gyroscope.c.
Referenced by Gyroscope_Init(), and Gyroscope_ReadTemperature().
void _GyroWriteRegister (GyroscopeReg_t regAddress, uint8_t regValue)
Writes a value to a specific register using the SPI port.
Parameters
in regAddress - the register address to write at on device
in regValue - the value at regAddress
Definition at line 621 of file Gyroscope.c.
Referenced by Gyroscope_Config(), Gyroscope_Start(), and Gyroscope_Stop().
static void _HandleDataReadyInterrupt (void) [static]
Handles the GPIO event that indicates that data is ready on the gyroscope.
Definition at line 575 of file Gyroscope.c.
Referenced by Gyroscope_Init().
void _HandleOtherInterrupt (void)
Handles the GPIO event that indicates that a special event on the gyroscope.
Definition at line 590 of file Gyroscope.c.
Referenced by Gyroscope_Init().
void Gyroscope_Config (const GyroConfig_t * config)
Reads in the value of the data from the gyroscope
Parameters
in sample- the location to store the sample data.
Definition at line 368 of file Gyroscope.c.
Referenced by GyroControl_SetConfig().
void Gyroscope_Init (void)
Initializes the gyroscope, but does not configure or start sampling
Definition at line 341 of file Gyroscope.c.
Referenced by GyroControl_Init().
bool Gyroscope_ReadSample (GyroSample_t * sample)
Reads in the value of the data from the gyroscope
Parameters
in sample- the location to store the sample data.
Definition at line 487 of file Gyroscope.c.
Referenced by _HandleHumanGyroCommand(), and GyroControl_ReadGyro().
void Gyroscope_ReadSampleArray (uint16_t maxLength, uint16_t * actualLength, uint8_t data[])
Reads a sample from the gyroscope if a sample was ready.
Parameters
in maxLength - the maximum length of bytes data[] can hold
out actualLength - the actual number of bytes written to data[]
in data - an array to hold the data from the accelerometer reading
Definition at line 513 of file Gyroscope.c.
Referenced by GyroControl_ReadGyro().
int8_t Gyroscope_ReadTemperature (void)
Reads a temperature sample from the gyroscope
Returns
Temperature in C as a signed 8-bit integer number
Definition at line 544 of file Gyroscope.c.
void Gyroscope_RegisterIsr (GyroIsrPointer_t isr)
Sets a function that will be ran when the data ready interrupt occurs.
Parameters
in isr - pointer to the gyroscope data ready ISR
Definition at line 557 of file Gyroscope.c.
Referenced by GyroControl_Init().
void Gyroscope_Start (void)
Starts the gyroscope sampling at its configured data rate.
Definition at line 441 of file Gyroscope.c.
Referenced by GyroControl_SetConfig(), and ThermometerControl_SetConfig().
void Gyroscope_Stop (void)
Stops the data collecting of the gyroscope.
Definition at line 468 of file Gyroscope.c.
Referenced by GyroControl_SetConfig(), and ThermometerControl_SetConfig().
void Gyroscope_UnregisterIsr (void)
Clears the custom ISR for the gyroscope.
Definition at line 567 of file Gyroscope.c.
Variable Documentation
volatile uint8_t _ctrlRegOne = 0u [static]
Store the values written to the control registers so they don't have to be read back.
Definition at line 319 of file Gyroscope.c.
Referenced by Gyroscope_Config(), Gyroscope_Start(), and Gyroscope_Stop().
volatile bool _dataReady = false [static]
Tracks if data is ready to be read from the gyroscope
Definition at line 326 of file Gyroscope.c.
Referenced by _HandleDataReadyInterrupt(), and Gyroscope_ReadSampleArray().
GyroIsrPointer_t _gyroIsrPointer = NULL [static]
Stores the ISR pointer
Definition at line 314 of file Gyroscope.c.
Referenced by _HandleDataReadyInterrupt(), Gyroscope_RegisterIsr(), and Gyroscope_UnregisterIsr().
bool _initialized = false [static]
Tracks if the gyroscope has been initialized.
Definition at line 311 of file Gyroscope.c.