GyroscopeControl.c File Reference
Controls the gyroscope driver.
#include <ProjectTypes.h>
*
#include `GyroscopeControl.h`
*
#include <Gyroscope.h>
*
#include <EventQueue.h>
*
#include <DataBuffer.h>
*
#include <SensorId.h>
*
#include <KeyValue.h>
*
#include <Assert.h>
*
#include <Serial.h>
*
#include <Debug.h>
*
Functions
static void _GyroDataReadyIsr (void)
void GyroControl_Init (void)
void GyroControl_SetConfig (uint8_t keyValue)
void GyroControl_ReadGyro (void)
Variables
static bool _initialized = false
static GyroConfig_t _gyroConfig
Detailed Description
Controls the gyroscope driver. Project 1814 IOLab Remote Sensor Application
Description Controls the gyroscope driver and controls the configuration for it.
Definition in file GyroscopeControl.c.
Function Documentation
static void _GyroDataReadyIsr (void) [static]
The data ready ISR handles the gyroscope data ready interrupt and will add an event to the event queue to notify the system to read the gyroscope.
Definition at line 191 of file GyroscopeControl.c.
Referenced by GyroControl_Init().
void GyroControl_Init (void)
Initializes the accelerometer controller.
Definition at line 57 of file GyroscopeControl.c.
Referenced by ConMan_Init().
void GyroControl_ReadGyro (void)
Gets a reading from the accelerometer.
Definition at line 157 of file GyroscopeControl.c.
Referenced by _ProcessEvents_DEFAULT().
void GyroControl_SetConfig (uint8_t keyValue)
Sets a configuration value to the accelerometer
Parameters
in keyValue - the key/value pair with the configuration information
Definition at line 70 of file GyroscopeControl.c.
Referenced by ConMan_SetSensorConfig().
Variable Documentation
GyroConfig_t _gyroConfig [static]
Initial value:
=
{
    GyroOdr_95,
    GyroResolution_250,
}
Stores the settings for the gyroscope
Definition at line 45 of file GyroscopeControl.c.
Referenced by ConMan_StartData().
bool _initialized = false [static]
tracks if the controller has been initialized
Definition at line 42 of file GyroscopeControl.c.