Header6Control.c File Reference
Controls header pin 6.
#include <ProjectTypes.h>
*
#include <KeyValue.h>
*
#include <Assert.h>
*
#include <Serial.h>
*
#include <Debug.h>
*
#include <Gpio.h>
*
#include <Board.h>
*
#include <Device.h>
*
#include <Header6Control.h>
*
Functions
static void _Header6Control_SetPinOutput (void)
void Header6Control_Init ()
void Header6Control_SetConfig (uint8_t config)
Variables
static Header6Mode_t _header6Mode = Header6Mode_INVALID
static Header6OutputValue_t _headerOutputValue = DEFAULT_HEADER6_OUTPUT_VALUE
Detailed Description
Controls header pin 6. Project 1814 IOLab Remote Sensor Application
Description Controls and manages the settings for header pin 6.
Definition in file Header6Control.c.
Function Documentation
void Header6Control_Init ()
Initialize header pin 6.
Definition at line 50 of file Header6Control.c.
Referenced by ConMan_Init().
void Header6Control_SetConfig (uint8_t config)
Sets a configuration value to header pin 6
Parameters
in config - the key/value pair with the configuration information
Definition at line 61 of file Header6Control.c.
Referenced by ConMan_SetOutputConfig(), and ConMan_SetSensorConfig().
Variable Documentation
Header6Mode_t _header6Mode = Header6Mode_INVALID [static]
Tracks what mode header pin 6 is in
Definition at line 39 of file Header6Control.c.
Referenced by Header6Control_SetConfig().
Header6OutputValue_t _headerOutputValue = DEFAULT_HEADER6_OUTPUT_VALUE [static]
Tracks what output value header pin 6 was last set to
Definition at line 42 of file Header6Control.c.
Referenced by Header6Control_SetConfig().