Header4Control.h File Reference
Controls the settings of header pin 4.
Functions
void Header4Control_Init ()
void Header4Control_SetConfig (uint8_t config)
Detailed Description
Controls the settings of header pin 4. Project 1814 IOLab Remote Sensor Application
Description Controls and manages the settings for header pin 4
Definition in file Header4Control.h.
Function Documentation
void Header4Control_Init ()
Initialized the Buzzer and PWM driver.
Definition at line 75 of file Header4Control.c.
Referenced by ConMan_Init().
void Header4Control_SetConfig (uint8_t config)
Sets a configuration value to header pin 4
Parameters
in config - the key/value pair with the configuration information
Definition at line 85 of file Header4Control.c.
Referenced by ConMan_SetOutputConfig(), and ConMan_SetSensorConfig().