Header1Control.c File Reference
Controls header pin 1.
#include <ProjectTypes.h>
*
#include <KeyValue.h>
*
#include <Assert.h>
*
#include <Serial.h>
*
#include <Debug.h>
*
#include <Gpio.h>
*
#include <Board.h>
*
#include <Device.h>
*
#include <Header1Control.h>
*
Functions
static void _Header1Control_SetPinOutput (void)
void Header1Control_Init ()
void Header1Control_SetConfig (uint8_t config)
Variables
static Header1Mode_t _header1Mode = Header1Mode_INVALID
static Header1OutputValue_t _headerOutputValue = DEFAULT_HEADER1_OUTPUT_VALUE
Detailed Description
Controls header pin 1. Project 1814 IOLab Remote Sensor Application
Description Controls and manages the settings for header pin 1.
Definition in file Header1Control.c.
Function Documentation
void Header1Control_Init ()
Initialize header pin 1.
Definition at line 50 of file Header1Control.c.
Referenced by ConMan_Init().
void Header1Control_SetConfig (uint8_t config)
Sets a configuration value to header pin 1
Parameters
in config - the key/value pair with the configuration information
Definition at line 61 of file Header1Control.c.
Referenced by ConMan_SetOutputConfig(), and ConMan_SetSensorConfig().
Variable Documentation
Header1Mode_t _header1Mode = Header1Mode_INVALID [static]
Tracks what mode header pin 1 is in
Definition at line 39 of file Header1Control.c.
Referenced by Header1Control_SetConfig().
Header1OutputValue_t _headerOutputValue = DEFAULT_HEADER1_OUTPUT_VALUE [static]
Tracks what output value header pin 1 was last set to
Definition at line 42 of file Header1Control.c.
Referenced by Header1Control_SetConfig().