Header3Control.c File Reference
Controls header pin 3.
#include <ProjectTypes.h>
*
#include <KeyValue.h>
*
#include <Assert.h>
*
#include <Serial.h>
*
#include <Debug.h>
*
#include <Gpio.h>
*
#include <Board.h>
*
#include <Device.h>
*
#include <Header3Control.h>
*
Functions
static void _Header3Control_SetPinOutput (void)
void Header3Control_Init ()
void Header3Control_SetConfig (uint8_t config)
Variables
static Header3Mode_t _header3Mode = Header3Mode_INVALID
static Header3OutputValue_t _headerOutputValue = DEFAULT_HEADER3_OUTPUT_VALUE
Detailed Description
Controls header pin 3. Project 1814 IOLab Remote Sensor Application
Description Controls and manages the settings for header pin 3.
Definition in file Header3Control.c.
Function Documentation
void Header3Control_Init ()
Initialize header pin 3.
Definition at line 50 of file Header3Control.c.
Referenced by ConMan_Init().
void Header3Control_SetConfig (uint8_t config)
Sets a configuration value to header pin 3
Parameters
in config - the key/value pair with the configuration information
Definition at line 61 of file Header3Control.c.
Referenced by ConMan_SetOutputConfig(), and ConMan_SetSensorConfig().
Variable Documentation
Header3Mode_t _header3Mode = Header3Mode_INVALID [static]
Tracks what mode header pin 3 is in
Definition at line 39 of file Header3Control.c.
Referenced by Header3Control_SetConfig().
Header3OutputValue_t _headerOutputValue = DEFAULT_HEADER3_OUTPUT_VALUE [static]
Tracks what output value header pin 3 was last set to
Definition at line 42 of file Header3Control.c.
Referenced by Header3Control_SetConfig().