Header5Control.h File Reference
Controls the settings of header pin 5.
Functions
void Header5Control_Init ()
void Header5Control_SetConfig (uint8_t config)
Detailed Description
Controls the settings of header pin 5. Project 1814 IOLab Remote Sensor Application
Description Controls and manages the settings for header pin 5
Definition in file Header5Control.h.
Function Documentation
void Header5Control_Init ()
Initialized the Buzzer and PWM driver.
Definition at line 75 of file Header5Control.c.
Referenced by ConMan_Init().
void Header5Control_SetConfig (uint8_t config)
Sets a configuration value to header pin 5
Parameters
in config - the key/value pair with the configuration information
Definition at line 87 of file Header5Control.c.
Referenced by ConMan_SetOutputConfig(), and ConMan_SetSensorConfig().