Header6Control.h File Reference
Controls the settings of header pin 6.
Functions
void Header6Control_Init ()
void Header6Control_SetConfig (uint8_t config)
Detailed Description
Controls the settings of header pin 6. Project 1814 IOLab Remote Sensor Application
Description Controls and manages the settings for header pin 6
Definition in file Header6Control.h.
Function Documentation
void Header6Control_Init ()
Initialize header pin 6.
Definition at line 50 of file Header6Control.c.
Referenced by ConMan_Init().
void Header6Control_SetConfig (uint8_t config)
Sets a configuration value to header pin 6
Parameters
in config - the key/value pair with the configuration information
Definition at line 61 of file Header6Control.c.
Referenced by ConMan_SetOutputConfig(), and ConMan_SetSensorConfig().