Header2Control.c File Reference
Controls header pin 2.
#include <ProjectTypes.h>
*
#include <KeyValue.h>
*
#include <Assert.h>
*
#include <Serial.h>
*
#include <Debug.h>
*
#include <Gpio.h>
*
#include <Board.h>
*
#include <Device.h>
*
#include <Header2Control.h>
*
Functions
static void _Header2Control_SetPinOutput (void)
void Header2Control_Init ()
void Header2Control_SetConfig (uint8_t config)
Variables
static Header2Mode_t _header2Mode = Header2Mode_INVALID
static Header2OutputValue_t _headerOutputValue = DEFAULT_HEADER2_OUTPUT_VALUE
Detailed Description
Controls header pin 2. Project 1814 IOLab Remote Sensor Application
Description Controls and manages the settings for header pin 2.
Definition in file Header2Control.c.
Function Documentation
void Header2Control_Init ()
Initialize header pin 2.
Definition at line 50 of file Header2Control.c.
Referenced by ConMan_Init().
void Header2Control_SetConfig (uint8_t config)
Sets a configuration value to header pin 2
Parameters
in config - the key/value pair with the configuration information
Definition at line 61 of file Header2Control.c.
Referenced by ConMan_SetOutputConfig(), and ConMan_SetSensorConfig().
Variable Documentation
Header2Mode_t _header2Mode = Header2Mode_INVALID [static]
Tracks what mode header pin 2 is in
Definition at line 39 of file Header2Control.c.
Referenced by Header2Control_SetConfig().
Header2OutputValue_t _headerOutputValue = DEFAULT_HEADER2_OUTPUT_VALUE [static]
Tracks what output value header pin 2 was last set to
Definition at line 42 of file Header2Control.c.
Referenced by Header2Control_SetConfig().