Header3Control.h File Reference
Controls the settings of header pin 3.
Functions
void Header3Control_Init ()
void Header3Control_SetConfig (uint8_t config)
Detailed Description
Controls the settings of header pin 3. Project 1814 IOLab Remote Sensor Application
Description Controls and manages the settings for header pin 3
Definition in file Header3Control.h.
Function Documentation
void Header3Control_Init ()
Initialize header pin 3.
Definition at line 50 of file Header3Control.c.
Referenced by ConMan_Init().
void Header3Control_SetConfig (uint8_t config)
Sets a configuration value to header pin 3
Parameters
in config - the key/value pair with the configuration information
Definition at line 61 of file Header3Control.c.
Referenced by ConMan_SetOutputConfig(), and ConMan_SetSensorConfig().