Header1Control.h File Reference
Controls the settings of header pin 1.
Functions
void Header1Control_Init ()
void Header1Control_SetConfig (uint8_t config)
Detailed Description
Controls the settings of header pin 1. Controls the settings of header pin 2.
Project 1814 IOLab Remote Sensor Application
Description Controls and manages the settings for header pin 1
Project 1814 IOLab Remote Sensor Application
Description Controls and manages the settings for header pin 2
Definition in file Header1Control.h.
Function Documentation
void Header1Control_Init ()
Initialize header pin 1.
Definition at line 50 of file Header1Control.c.
Referenced by ConMan_Init().
void Header1Control_SetConfig (uint8_t config)
Sets a configuration value to header pin 1
Parameters
in config - the key/value pair with the configuration information
Definition at line 61 of file Header1Control.c.
Referenced by ConMan_SetOutputConfig(), and ConMan_SetSensorConfig().