HighGainControl.c File Reference
Controls reading the high gain input.
#include <ProjectTypes.h>
*
#include `HighGainControl.h`
*
#include <SensorId.h>
*
#include <DataBuffer.h>
*
#include <KeyValue.h>
*
#include <AdcManager.h>
*
#include <Board.h>
*
#include <Gpio.h>
*
#include <Device.h>
*
#include <Assert.h>
*
#include <Serial.h>
*
Functions
static void _HighGainDataCallback (uint16_t data)
void HighGainControl_Init (void)
void HighGainControl_SetConfig (uint8_t config)
Variables
static bool _initialized = false
static HighGainSampleRate_t _sampleRate = DEFAULT_HIGH_GAIN_SAMPLE_RATE
Detailed Description
Controls reading the high gain input. Project 1814 IOLab Remote Sensor Application
Description Controls the high gain input and manages the configurations and settings associated with the high gain input.
Definition in file HighGainControl.c.
Function Documentation
static void _HighGainDataCallback (uint16_t data) [static]
Takes the high gain input data and stores it in the proper location. This function is designed to be called every time there is data for the high gain input.
Parameters
in data - The sample from the high gain input that should be stored in the proper location.
Definition at line 167 of file HighGainControl.c.
Referenced by HighGainControl_SetConfig().
void HighGainControl_Init (void)
Initializes the high gain input reading control.
Definition at line 54 of file HighGainControl.c.
Referenced by ConMan_Init().
void HighGainControl_SetConfig (uint8_t config)
Takes a configuration and sets it for the high gain input reading.
Parameters
in config - the KeyValue configuration setting for the high gain input reading.
Definition at line 66 of file HighGainControl.c.
Referenced by ConMan_SetSensorConfig().
Variable Documentation
bool _initialized = false [static]
Tracks if the module has been initialized
Definition at line 42 of file HighGainControl.c.
HighGainSampleRate_t _sampleRate = DEFAULT_HIGH_GAIN_SAMPLE_RATE [static]
Stores the desired sample rate of the high gain input reading
Definition at line 45 of file HighGainControl.c.
Referenced by HighGainControl_SetConfig().