I2c.c File Reference
I2C Module.
#include <ProjectTypes.h>
*
#include `I2c.h`
*
#include <Assert.h>
*
#include <Device.h>
*
#include <Gpio.h>
*
Macros
#define I2C_NUM_PORTS (2)
Functions
void I2c_Init (I2cPort_t port, const I2cPortConfig_t *config)
void I2c_Open (I2cPort_t port)
void I2c_Close (I2cPort_t port)
I2cError_t I2c_TransmitStart (I2cPort_t port, uint8_t address, I2cOperation_t operation)
I2cError_t I2c_TransmitByte (I2cPort_t port, uint8_t byte)
I2cError_t I2c_TransmitByteEnd (I2cPort_t port, uint8_t byte)
void I2c_ReceiveByte (I2cPort_t port, uint8_t *byte)
void I2c_ReceiveByteEnd (I2cPort_t port, uint8_t *byte)
void I2c_WaitUntilBusIdle (I2cPort_t port)
Variables
static volatile uint8_t *const _i2cControlOneRegisters [I2C_NUM_PORTS]
static volatile uint8_t *const _i2cTransmitBufferRegisters [I2C_NUM_PORTS]
static volatile const uint8_t
*
*const _i2cReceiveBufferRegisters [I2C_NUM_PORTS]
static volatile uint8_t *const _i2cInterruptFlagRegisters [I2C_NUM_PORTS]
static const int16_t _i2cGpioSCLPorts [I2C_NUM_PORTS] = {3, 4}
static const int16_t _i2cGpioSDAPorts [I2C_NUM_PORTS] = {3, 4}
static const uint8_t _i2cGpioSCLPinmasks [I2C_NUM_PORTS]
static const uint8_t _i2cGpioSDAPinmasks [I2C_NUM_PORTS]
static bool _i2cPortInitialized [I2C_NUM_PORTS] = {false, false}
static bool _i2cPortOpen [I2C_NUM_PORTS] = {false, false}
Detailed Description
I2C Module. Project 1814 IOLab Remote Sensor Application
Description This module provides functions to configure an I2C port to communicate to various peripheral devices.
Definition in file I2c.c.
Macro Definition Documentation
#define I2C_NUM_PORTS (2)
Number of possible I2C ports
Definition at line 33 of file I2c.c.
Referenced by I2c_Init(), I2c_TransmitStart(), and I2c_WaitUntilBusIdle().
Function Documentation
void I2c_Close (I2cPort_t port)
Close the I2C port.
Parameters
in port - Selected I2C port.
Definition at line 249 of file I2c.c.
void I2c_Init (I2cPort_t port, const I2cPortConfig_t * config)
Initialize the I2C hardware.
Parameters
in port - Selection of which I2C hardware port to initialize.
in config - Structure of selected I2C HW settings.
Definition at line 98 of file I2c.c.
Referenced by main().
void I2c_Open (I2cPort_t port)
Open the I2C port.
Parameters
in port - Selected I2C port.
Definition at line 220 of file I2c.c.
Referenced by main().
void I2c_ReceiveByte (I2cPort_t port, uint8_t * byte)
Receives a byte via I2C.
This assumes that the I2C port has been configured as a MASTER device.
Parameters
in port - Selected I2C port.
in byte - Pointer to where received byte should be stored.
Definition at line 457 of file I2c.c.
Referenced by _AccReadMultipleRegisters(), and _ReadMultipleRegisters().
void I2c_ReceiveByteEnd (I2cPort_t port, uint8_t * byte)
Receives a byte via I2C, then send the I2C Stop bit. This is required to end the transaction with the slave device.
This assumes that the I2C port has been configured as a MASTER device.
Parameters
in port - Selected I2C port.
in byte - Pointer to where received byte should be stored.
Definition at line 489 of file I2c.c.
Referenced by _AccReadMultipleRegisters(), _AccReadSingleRegister(), _ReadMultipleRegisters(), and _ReadSingleRegister().
I2cError_t I2c_TransmitByte (I2cPort_t port, uint8_t byte)
Transmits a byte via I2C. This is used to send multiple bytes on I2C, as the Stop Bit is NOT sent.
This assumes that the I2C port has been configured as a MASTER device.
Parameters
in port - Selected I2C port.
in byte - Data byte to send out over I2C.
Returns
True if the byte was sent OK. Otherwise, false.
Definition at line 347 of file I2c.c.
Referenced by _AccReadMultipleRegisters(), _AccReadSingleRegister(), _AccWriteSingleRegister(), _ReadMultipleRegisters(), _ReadSingleRegister(), and _WriteSingleRegister().
I2cError_t I2c_TransmitByteEnd (I2cPort_t port, uint8_t byte)
Transmits a byte via I2C, then send the I2C Stop bit. This is required to end the transaction with the slave device.
This assumes that the I2C port has been configured as a MASTER device.
Parameters
in port - Selected I2C port.
in byte - Data byte to send out over I2C.
Returns
True if the byte and Stop Bit was sent OK. Otherwise, false.
Definition at line 392 of file I2c.c.
Referenced by _AccWriteSingleRegister(), and _WriteSingleRegister().
I2cError_t I2c_TransmitStart (I2cPort_t port, uint8_t address, I2cOperation_t operation)
Transmit the Start Bit on the I2C port, immediately followed by sending the selected Slave Address out to the I2C port.
This assumes that the I2C port has been configured as a MASTER device. Slave devices do not send out the Start bit.
Parameters
in port - Selected I2C port.
in address - Slave address to communicate with.
in operation - Select I2C Write or I2C Read.
Returns
True if the Start Bit and address were sent OK. Otherwise, false.
Definition at line 281 of file I2c.c.
Referenced by _AccReadMultipleRegisters(), _AccReadSingleRegister(), _AccWriteSingleRegister(), _ReadMultipleRegisters(), _ReadSingleRegister(), and _WriteSingleRegister().
void I2c_WaitUntilBusIdle (I2cPort_t port)
Delays until the I2C bus becomes idle. This is useful to ensure that the I2C bus is available between rapid bus accesses.
Parameters
in port - Selected I2C port.
Definition at line 547 of file I2c.c.
Referenced by _AccReadMultipleRegisters(), _AccReadSingleRegister(), _AccWriteSingleRegister(), _ReadMultipleRegisters(), _ReadSingleRegister(), and _WriteSingleRegister().
Variable Documentation
volatile uint8_t* const _i2cControlOneRegisters[I2C_NUM_PORTS] [static]
Initial value:
=
{
    &UCB0CTL1,
    &UCB1CTL1
}
Look-up table for I2C control 1 registers.
Definition at line 37 of file I2c.c.
Referenced by I2c_Close(), I2c_Init(), I2c_Open(), I2c_ReceiveByteEnd(), I2c_TransmitByte(), I2c_TransmitByteEnd(), and I2c_TransmitStart().
const uint8_t _i2cGpioSCLPinmasks[I2C_NUM_PORTS] [static]
Initial value:
=
{
    (uint8_t)(1u << 1),
    (uint8_t)(1u << 2)
}
Look-up table for GPIO pinmask of I2C SCL ports.
Definition at line 71 of file I2c.c.
Referenced by I2c_Close(), and I2c_Open().
const int16_t _i2cGpioSCLPorts[I2C_NUM_PORTS] = {3, 4} [static]
Look-up table for GPIO port number of I2C SCL ports.
Definition at line 65 of file I2c.c.
Referenced by I2c_Close(), and I2c_Open().
const uint8_t _i2cGpioSDAPinmasks[I2C_NUM_PORTS] [static]
Initial value:
=
{
    (uint8_t)(1u << 0),
    (uint8_t)(1u << 1)
}
Look-up table for GPIO pinmask of I2C SDA ports.
Definition at line 78 of file I2c.c.
Referenced by I2c_Close(), and I2c_Open().
const int16_t _i2cGpioSDAPorts[I2C_NUM_PORTS] = {3, 4} [static]
Look-up table for GPIO port number of I2C SDA ports.
Definition at line 68 of file I2c.c.
Referenced by I2c_Close(), and I2c_Open().
volatile uint8_t* const _i2cInterruptFlagRegisters[I2C_NUM_PORTS] [static]
Initial value:
=
{
    &UCB0IFG,
    &UCB1IFG
}
Look-up table for I2C interrupt flag registers.
Definition at line 58 of file I2c.c.
Referenced by I2c_ReceiveByte(), I2c_ReceiveByteEnd(), I2c_TransmitByte(), I2c_TransmitByteEnd(), and I2c_TransmitStart().
bool _i2cPortInitialized[I2C_NUM_PORTS] = {false, false} [static]
Tracks if a I2C port is initialized.
Definition at line 86 of file I2c.c.
Referenced by I2c_Init(), and I2c_Open().
bool _i2cPortOpen[I2C_NUM_PORTS] = {false, false} [static]
Tracks if a I2C port is open.
Definition at line 89 of file I2c.c.
Referenced by I2c_Close(), I2c_Open(), I2c_ReceiveByte(), I2c_ReceiveByteEnd(), I2c_TransmitByte(), I2c_TransmitByteEnd(), and I2c_TransmitStart().
volatile const uint8_t* const _i2cReceiveBufferRegisters[I2C_NUM_PORTS] [static]
Initial value:
=
{
    &UCB0RXBUF,
    &UCB1RXBUF
}
Look-up table for I2C receive buffer registers.
Definition at line 51 of file I2c.c.
Referenced by I2c_ReceiveByte(), and I2c_ReceiveByteEnd().
volatile uint8_t* const _i2cTransmitBufferRegisters[I2C_NUM_PORTS] [static]
Initial value:
=
{
    &UCB0TXBUF,
    &UCB1TXBUF
}
Look-up table for I2C transmit buffer registers.
Definition at line 44 of file I2c.c.
Referenced by I2c_TransmitByte(), and I2c_TransmitByteEnd().