I2c.h File Reference
I2C Module header file.
Data Structures
struct I2cPortConfig_t
Macros
#define I2C_ENABLE_PORT_0
Enumerations
enum I2cError_t {
*
I2cError_OK,
*
I2cError_NACK,
*
I2cError_STOP
 }
enum I2cPort_t { I2cPort_0 = 0u
 }
enum I2cOperation_t {
*
I2cOperation_WRITE,
*
I2cOperation_READ
 }
enum I2cMode_t {
*
I2cMode_SLAVE,
*
I2cMode_MASTER
 }
enum I2cAddressing_t {
*
I2cAddressing_7_bits,
*
I2cAddressing_10_bits
 }
enum I2cBaudRate_t {
*
I2cBaudRate_100000,
*
I2cBaudRate_400000
 }
Functions
void I2c_Init (I2cPort_t port, const I2cPortConfig_t *config)
void I2c_Open (I2cPort_t port)
void I2c_Close (I2cPort_t port)
I2cError_t I2c_TransmitStart (I2cPort_t port, uint8_t address, I2cOperation_t operation)
I2cError_t I2c_TransmitByte (I2cPort_t port, uint8_t byte)
I2cError_t I2c_TransmitByteEnd (I2cPort_t port, uint8_t byte)
void I2c_ReceiveByte (I2cPort_t port, uint8_t *byte)
void I2c_ReceiveByteEnd (I2cPort_t port, uint8_t *byte)
void I2c_WaitUntilBusIdle (I2cPort_t port)
Detailed Description
I2C Module header file. Project 1814 IOLab Remote Sensor Application
Description This module provides functions to configure an I2C port to communicate to various peripheral devices.
Definition in file I2c.h.
Data Structure Documentation
struct I2cPortConfig_t
Defines the I2C port configuration structure
Definition at line 85 of file I2c.h.
Data Fields
I2cAddressing_t
addressing
I2cBaudRate_t
baudRate
I2cMode_t
modeType
Macro Definition Documentation
#define I2C_ENABLE_PORT_0
If defined, I2C port 0 is enabled.
Definition at line 28 of file I2c.h.
Enumeration Type Documentation
enum I2cAddressing_t
The possible addressing modes when configuring a I2C port
Definition at line 71 of file I2c.h.
enum I2cBaudRate_t
The possible baud rates when configuring a I2C port
Definition at line 78 of file I2c.h.
enum I2cError_t
Enumeration type for I2C module errors.
Definition at line 38 of file I2c.h.
enum I2cMode_t
The possible Modes when configuring a I2C port
Definition at line 64 of file I2c.h.
enum I2cOperation_t
The possible operations when using the I2C port
Definition at line 57 of file I2c.h.
enum I2cPort_t
The available I2C ports
Definition at line 46 of file I2c.h.
Function Documentation
void I2c_Close (I2cPort_t port)
Close the I2C port.
Parameters
in port - Selected I2C port.
Definition at line 249 of file I2c.c.
void I2c_Init (I2cPort_t port, const I2cPortConfig_t * config)
Initialize the I2C hardware.
Parameters
in port - Selection of which I2C hardware port to initialize.
in config - Structure of selected I2C HW settings.
Definition at line 98 of file I2c.c.
Referenced by main().
void I2c_Open (I2cPort_t port)
Open the I2C port.
Parameters
in port - Selected I2C port.
Definition at line 220 of file I2c.c.
Referenced by main().
void I2c_ReceiveByte (I2cPort_t port, uint8_t * byte)
Receives a byte via I2C.
This assumes that the I2C port has been configured as a MASTER device.
Parameters
in port - Selected I2C port.
in byte - Pointer to where received byte should be stored.
Definition at line 457 of file I2c.c.
Referenced by _AccReadMultipleRegisters(), and _ReadMultipleRegisters().
void I2c_ReceiveByteEnd (I2cPort_t port, uint8_t * byte)
Receives a byte via I2C, then send the I2C Stop bit. This is required to end the transaction with the slave device.
This assumes that the I2C port has been configured as a MASTER device.
Parameters
in port - Selected I2C port.
in byte - Pointer to where received byte should be stored.
Definition at line 489 of file I2c.c.
Referenced by _AccReadMultipleRegisters(), _AccReadSingleRegister(), _ReadMultipleRegisters(), and _ReadSingleRegister().
I2cError_t I2c_TransmitByte (I2cPort_t port, uint8_t byte)
Transmits a byte via I2C. This is used to send multiple bytes on I2C, as the Stop Bit is NOT sent.
This assumes that the I2C port has been configured as a MASTER device.
Parameters
in port - Selected I2C port.
in byte - Data byte to send out over I2C.
Returns
True if the byte was sent OK. Otherwise, false.
Definition at line 347 of file I2c.c.
Referenced by _AccReadMultipleRegisters(), _AccReadSingleRegister(), _AccWriteSingleRegister(), _ReadMultipleRegisters(), _ReadSingleRegister(), and _WriteSingleRegister().
I2cError_t I2c_TransmitByteEnd (I2cPort_t port, uint8_t byte)
Transmits a byte via I2C, then send the I2C Stop bit. This is required to end the transaction with the slave device.
This assumes that the I2C port has been configured as a MASTER device.
Parameters
in port - Selected I2C port.
in byte - Data byte to send out over I2C.
Returns
True if the byte and Stop Bit was sent OK. Otherwise, false.
Definition at line 392 of file I2c.c.
Referenced by _AccWriteSingleRegister(), and _WriteSingleRegister().
I2cError_t I2c_TransmitStart (I2cPort_t port, uint8_t address, I2cOperation_t operation)
Transmit the Start Bit on the I2C port, immediately followed by sending the selected Slave Address out to the I2C port.
This assumes that the I2C port has been configured as a MASTER device. Slave devices do not send out the Start bit.
Parameters
in port - Selected I2C port.
in address - Slave address to communicate with.
in operation - Select I2C Write or I2C Read.
Returns
True if the Start Bit and address were sent OK. Otherwise, false.
Definition at line 281 of file I2c.c.
Referenced by _AccReadMultipleRegisters(), _AccReadSingleRegister(), _AccWriteSingleRegister(), _ReadMultipleRegisters(), _ReadSingleRegister(), and _WriteSingleRegister().
void I2c_WaitUntilBusIdle (I2cPort_t port)
Delays until the I2C bus becomes idle. This is useful to ensure that the I2C bus is available between rapid bus accesses.
Parameters
in port - Selected I2C port.
Definition at line 547 of file I2c.c.
Referenced by _AccReadMultipleRegisters(), _AccReadSingleRegister(), _AccWriteSingleRegister(), _ReadMultipleRegisters(), _ReadSingleRegister(), and _WriteSingleRegister().