KeyValue.c File Reference
Contains the definitions of the Key-Value pairs.
#include <ProjectTypes.h>
*
#include `KeyValue.h`
*
#include <Assert.h>
*
Macros
#define VALUE_BIT_MASK (0x1F)
Functions
void KeyValue_Separate (uint8_t keyValue, Key_t *key, Value_t *value)
KeyValue_t KeyValue_Combine (Key_t key, Value_t value)
Detailed Description
Contains the definitions of the Key-Value pairs. Project 1814 IOLab Remote Sensor Application
Description Contains the definitions of the Key-Value pairs used for configuring the different sensors in the IOLab system. The keys and values defined in this module are based on the document 1814F08 Data Protocol Key-Value table.
Definition in file KeyValue.c.
Macro Definition Documentation
#define VALUE_BIT_MASK (0x1F)
Defines the bit mask for the value portion of the key-value
Definition at line 34 of file KeyValue.c.
Referenced by KeyValue_Combine(), and KeyValue_Separate().
Function Documentation
KeyValue_t KeyValue_Combine (Key_t key, Value_t value)
Combine the key and the value to form the KeyValue pair.
Parameters
out key - the key from the key value pair
out value - the value from the key value pair
Returns
The key-value pair made from the input key and value
Definition at line 65 of file KeyValue.c.
void KeyValue_Separate (uint8_t keyValue, Key_t * key, Value_t * value)
Separate the key and the value from the KeyValue pair.
Parameters
in keyValue - The key-value pair
out key - the key from the key value pair
out value - the value from the key value pair
Definition at line 48 of file KeyValue.c.
Referenced by AccControl_SetConfig(), AmbientLightControl_SetConfig(), Analog7Control_SetConfig(), Analog8Control_SetConfig(), Analog9Control_SetConfig(), BarometerControl_SetConfig(), BatteryControl_SetConfig(), BuzzerControl_SetConfig(), DacControl_SetConfig(), DigitalInputControl_SetConfig(), EcgControl_SetConfig(), EncControl_SetConfig(), FgControl_SetConfig(), GyroControl_SetConfig(), Header1Control_SetConfig(), Header2Control_SetConfig(), Header3Control_SetConfig(), Header4Control_SetConfig(), Header5Control_SetConfig(), Header6Control_SetConfig(), HighGainControl_SetConfig(), MagControl_SetConfig(), MicrophoneControl_SetConfig(), and ThermometerControl_SetConfig().