LedControl.c File Reference
LED Controller.
#include <ProjectTypes.h>
*
#include `LedControl.h`
*
#include <Gpio.h>
*
#include <Board.h>
*
#include <TimerTick.h>
*
#include <Assert.h>
*
Macros
#define LED_COUNTER_START (0x0001u)
#define LED_COUNTER_END (0x0200u)
#define LED_TIME_MSEC (100u)
Functions
static void _Led_ProcessStates (void)
void LedControl_Init (void)
void LedControl_SetLed (Led_t led, LedState_t state)
Variables
static uint16_t _ledCounter = LED_COUNTER_START
static uint16_t _ledState [Led_LAST]
Detailed Description
LED Controller. Project 1814 IOLab Remote Sensor Application
Description LED controller that manages the LEDs and their state
Definition in file LedControl.c.
Macro Definition Documentation
#define LED_COUNTER_END (0x0200u)
Led counter ending value
Definition at line 34 of file LedControl.c.
Referenced by _Led_ProcessStates().
#define LED_COUNTER_START (0x0001u)
Led counter starting value
Definition at line 32 of file LedControl.c.
Referenced by _Led_ProcessStates().
#define LED_TIME_MSEC (100u)
Time between Led states
Definition at line 36 of file LedControl.c.
Referenced by LedControl_Init().
Function Documentation
static void _Led_ProcessStates (void) [static]
Increments the led state counter and sets the state of the leds.
Definition at line 87 of file LedControl.c.
Referenced by LedControl_Init().
void LedControl_Init (void)
Initializes the Led Controller and sets up the timeout and callback for controlling the Led state.
Definition at line 61 of file LedControl.c.
Referenced by main().
void LedControl_SetLed (Led_t led, LedState_t state)
Sets the specified Led to blink for the appropriate state.
Parameters
in led - which led to set
in state - the state to set led to
Definition at line 77 of file LedControl.c.
Referenced by _ClearStartup(), _HandlePowerOffRequest(), _HandleStatusPacket(), main(), and SelfTest_Start().
Variable Documentation
uint16_t _ledCounter = LED_COUNTER_START [static]
The counter for the led state.
Definition at line 42 of file LedControl.c.
Referenced by _Led_ProcessStates().
uint16_t _ledState[Led_LAST] [static]
Initial value:
=
{
    LedState_OFF,
    LedState_OFF,
    LedState_OFF,
    LedState_OFF
}
Stores the setting for each led
Definition at line 45 of file LedControl.c.
Referenced by _Led_ProcessStates(), and LedControl_SetLed().