LedControl.h File Reference
LED Controller header.
Enumerations
enum LedState_t {
*
LedState_INVALID = -1,
*
LedState_OFF = 0x0000u,
*
LedState_BLINK_1 = 0x0200u,
*
LedState_BLINK_2 = 0x0280u,
*
LedState_BLINK_3 = 0x02A0u,
*
LedState_BLINK_4 = 0x02A8u,
*
LedState_BLINK_FAST_EVEN = 0x0155u,
*
LedState_BLINK_FAST_ODD = 0x02AAu,
*
LedState_BLINK_SLOW_EVEN = 0x001Fu,
*
LedState_BLINK_SLOW_ODD = 0x03E0u,
*
LedState_WINK_1 = 0x03FEu,
*
LedState_WINK_2 = 0x03FAu,
*
LedState_WINK_3 = 0x03EAu,
*
LedState_WINK_4 = 0x03AAu,
*
LedState_ON = 0x03FFu
 }
enum Led_t {
*
Led_INVALID = -1,
*
Led_FIRST = 0,
*
Led_0_RED = Led_FIRST,
*
Led_0_GREEN,
*
Led_1_RED,
*
Led_1_GREEN,
*
Led_LAST
 }
Functions
void LedControl_Init (void)
void LedControl_SetLed (Led_t led, LedState_t state)
Detailed Description
LED Controller header. Project 1814 IOLab Remote Sensor Application
Description LED controller that manages the LEDs and their state
Definition in file LedControl.h.
Enumeration Type Documentation
enum Led_t
Defines the LEDs available in the control.
Definition at line 46 of file LedControl.h.
enum LedState_t
Defines the LED states that are possible
Enumerator
LedState_BLINK_2
 Blink is mostly off then on for a short period of time. Opposite of wink
LedState_WINK_2
 Wink is mostly on then off for short period of time. Opposite of blink
Definition at line 26 of file LedControl.h.
Function Documentation
void LedControl_Init (void)
Initializes the Led Controller and sets up the timeout and callback for controlling the Led state.
Definition at line 61 of file LedControl.c.
Referenced by main().
void LedControl_SetLed (Led_t led, LedState_t state)
Sets the specified Led to blink for the appropriate state.
Parameters
in led - which led to set
in state - the state to set led to
Definition at line 77 of file LedControl.c.
Referenced by _ClearStartup(), _HandlePowerOffRequest(), _HandleStatusPacket(), main(), and SelfTest_Start().