MagnetometerControl.c File Reference
Magnetometer control module.
#include <ProjectTypes.h>
*
#include `MagnetometerControl.h`
*
#include <Magnetometer.h>
*
#include <EventQueue.h>
*
#include <SensorId.h>
*
#include <KeyValue.h>
*
#include <DataBuffer.h>
*
#include <Assert.h>
*
#include <Serial.h>
*
#include <Debug.h>
*
Functions
static void _MagDataReadyIsr (void)
void MagControl_Init (void)
void MagControl_SetConfig (uint8_t keyValue)
void MagControl_ReadMag (void)
Variables
static bool _initialized = false
static MagConfig_t _magConfig
Detailed Description
Magnetometer control module. Project 1814 IOLab Remote Sensor Application
Description Interfaces to the magnetometer driver to control and configure the magnetometer with the proper settings and handle the data coming from the magnetometer.
Definition in file MagnetometerControl.c.
Function Documentation
static void _MagDataReadyIsr (void) [static]
The data ready ISR handles the magnetometer data ready interrupt and will add an event to the event queue to notify the system to read the magnetometer.
Definition at line 195 of file MagnetometerControl.c.
Referenced by MagControl_Init().
void MagControl_Init (void)
Initializes the magnetometer controller.
Definition at line 60 of file MagnetometerControl.c.
Referenced by ConMan_Init().
void MagControl_ReadMag (void)
Gets a reading from the magnetometer.
Definition at line 163 of file MagnetometerControl.c.
Referenced by _ProcessEvents_DEFAULT().
void MagControl_SetConfig (uint8_t keyValue)
Sets a configuration value to the accelerometer
Parameters
in keyValue - the key/value pair with the configuration information
Definition at line 74 of file MagnetometerControl.c.
Referenced by ConMan_SetSensorConfig().
Variable Documentation
bool _initialized = false [static]
tracks if the controller has been initialized
Definition at line 41 of file MagnetometerControl.c.
MagConfig_t _magConfig [static]
Initial value:
=
{
        MagSampleRate_1280,
        MagOverSampleRatio_16,
        MagDataScaling_RAW,
        MagAutoReset_ENABLED,
        MagSampling_Auto,
        MagResolution_16BIT
}
Stores the configuration settings for the magnetometer
Definition at line 44 of file MagnetometerControl.c.