Magnetometer.h File Reference
Magnetometer Interface Header.
Data Structures
struct MagConfig_t
struct MagSample_t
Typedefs
typedef void(* MagIsrPointer_t)(void)
Enumerations
enum MagSampleRate_t {
*
MagSampleRate_1280,
*
MagSampleRate_640,
*
MagSampleRate_320,
*
MagSampleRate_160,
*
MagSampleRate_80,
*
MagSampleRate_40,
*
MagSampleRate_20,
*
MagSampleRate_10
 }
enum MagOverSampleRatio_t {
*
MagOverSampleRatio_16,
*
MagOverSampleRatio_32,
*
MagOverSampleRatio_64,
*
MagOverSampleRatio_128
 }
enum MagDataScaling_t {
*
MagDataScaling_RAW,
*
MagDataScaling_SCALED
 }
enum MagAutoReset_t {
*
MagAutoReset_DISABLED,
*
MagAutoReset_ENABLED
 }
enum MagSamplingMode_t {
*
MagSampling_Auto,
*
MagSampling_Triggered
 }
enum MagResolution_t {
*
MagResolution_16BIT,
*
MagResolution_8BIT
 }
Functions
void Magnetometer_Init (void)
bool Magnetometer_Config (const MagConfig_t *config)
void Magnetometer_Start (void)
void Magnetometer_Stop (void)
bool Magnetometer_TriggerSampleBlocking (MagSample_t *sample)
void Magnetometer_ResetSensorBlocking (void)
void Magnetometer_SetCalibration (const MagSample_t *calibration)
bool Magnetometer_ReadSample (MagSample_t *sample)
void Magnetometer_ReadSampleArray (uint16_t maxLength, uint16_t *actualLength, uint8_t data[])
int8_t Magnetometer_ReadTemp (void)
void Magnetometer_RegisterIsr (MagIsrPointer_t isr)
void Magnetometer_UnregisterIsr (void)
Detailed Description
Magnetometer Interface Header. Project 1814 IOLab Remote Sensor Application
Description Header file for the magnetometer (3-axis Hall effect) sensor interface logic.
Definition in file Magnetometer.h.
Data Structure Documentation
struct MagConfig_t
Defines the magnetometer configuration structure
Definition at line 92 of file Magnetometer.h.
Data Fields
MagAutoReset_t
autoReset
MagDataScaling_t
dataScaling
MagOverSampleRatio_t
overSampleRatio
MagResolution_t
resolution
MagSampleRate_t
sampleRate
MagSamplingMode_t
samplingMode
struct MagSample_t
Defines the structure that will hold the sample data from a magnetometer reading.
Definition at line 105 of file Magnetometer.h.
Data Fields
int16_t
xData
int16_t
yData
int16_t
zData
Typedef Documentation
typedef void(* MagIsrPointer_t)(void)
Defines an magnetometer ISR function pointer
Definition at line 113 of file Magnetometer.h.
Enumeration Type Documentation
enum MagAutoReset_t
Selects if the magnetometer should reset its sensor before each reading. Resetting is necessary after being exposed to a large magnetic field.
Note
Auto-reset is recommended.
Definition at line 66 of file Magnetometer.h.
enum MagDataScaling_t
Defines the scaling mode for the output data.
Enumerator
MagDataScaling_SCALED
 Outputs raw data from the ADC. Scales the ADC data by the user set scaling values
Definition at line 55 of file Magnetometer.h.
enum MagOverSampleRatio_t
Defines the oversampling ratio of the magnetometer. The higher the oversampling ratio the lower the noise in the measurement, but the slower the output data rate. Output Data Rate = MagSampleRate / MagOverSampleRatio
Definition at line 46 of file Magnetometer.h.
enum MagResolution_t
Defines what resolution the sensor readings will be. 8-bit resolution return the MSB only from a 16-bit value. This will allow for lower data rates when lower resolution data is acceptable.
Definition at line 85 of file Magnetometer.h.
enum MagSampleRate_t
Defines the ADC sample rate in Hz that the magnetometer will run at. Lower sample rates consume less power. Output Data Rate = MagSampleRate / MagOverSampleRatio
Definition at line 30 of file Magnetometer.h.
enum MagSamplingMode_t
Defines how the sensor will gather samples Auto mode will collect samples at the configured rate determined by the sample rate and over sampling mode.
Definition at line 75 of file Magnetometer.h.
Function Documentation
bool Magnetometer_Config (const MagConfig_t * config)
Configures the magnetometer, but does not start the sampling.
Parameters
in config - Structure of selected magnetometer settings.
Returns
True if the configuration was successful, false otherwise. The configuration will fail if the magnetometer is not in standby when configured.
Definition at line 193 of file Magnetometer.c.
Referenced by MagControl_SetConfig().
void Magnetometer_Init (void)
Initializes the magnetometer, but does not configure or start the sampling.
Definition at line 159 of file Magnetometer.c.
Referenced by MagControl_Init().
bool Magnetometer_ReadSample (MagSample_t * sample)
Reads a sample from the magnetometer if a sample was ready.
Parameters
in sample - structure to hold the sample data once it is collected
Returns
True if the sample was ready, false otherwise
Definition at line 526 of file Magnetometer.c.
Referenced by MagControl_ReadMag().
void Magnetometer_ReadSampleArray (uint16_t maxLength, uint16_t * actualLength, uint8_t data[])
Reads a sample from the magnetometer if a sample was ready.
Parameters
in maxLength - the maximum number of items that can be written to data[]
out actuaLength - the actual number of items written to data[]
out data - the array that the data will be stored in.
Definition at line 560 of file Magnetometer.c.
Referenced by MagControl_ReadMag().
int8_t Magnetometer_ReadTemp (void)
Reads the die temperature of the device.
Returns
Temperature in °C as a signed 8-bit integer number
Definition at line 590 of file Magnetometer.c.
void Magnetometer_RegisterIsr (MagIsrPointer_t isr)
Sets a function that will be ran when the data ready interrupt occurs.
Parameters
in isr - pointer to the accelerometer data ready ISR
Definition at line 603 of file Magnetometer.c.
Referenced by MagControl_Init().
void Magnetometer_ResetSensorBlocking (void)
Resets the sensor in the magnetometer and blocks until the sensor is reset.
Definition at line 460 of file Magnetometer.c.
void Magnetometer_SetCalibration (const MagSample_t * calibration)
Writes the sensor calibration data to the magnetometer.
Parameters
in calibration - structure to hold the calibration data to be written
Definition at line 487 of file Magnetometer.c.
void Magnetometer_Start (void)
Starts the magnetometer sampling at its configured data rate.
Definition at line 368 of file Magnetometer.c.
Referenced by MagControl_SetConfig(), and ThermometerControl_SetConfig().
void Magnetometer_Stop (void)
Stops the data collecting of the magnetometer.
Definition at line 399 of file Magnetometer.c.
Referenced by MagControl_SetConfig(), and ThermometerControl_SetConfig().
bool Magnetometer_TriggerSampleBlocking (MagSample_t * sample)
Triggers a sample from the magnetometer and blocks until the sample is returned.
Parameters
in sample - structure to hold the sample data once it is collected
Returns
True if the sample was aquired, false otherwise
Definition at line 419 of file Magnetometer.c.
Referenced by _HandleHumanMagCommand().