MagnetometerControl.h File Reference
Header for the magnetometer control module.
Functions
void MagControl_Init (void)
void MagControl_SetConfig (uint8_t keyValue)
void MagControl_ReadMag (void)
Detailed Description
Header for the magnetometer control module. Project 1814 IOLab Remote Sensor Application
Description Header for the magnetometer control module. This will interface to the magnetometer driver to configure and and retrieve data.
Definition in file MagnetometerControl.h.
Function Documentation
void MagControl_Init (void)
Initializes the magnetometer controller.
Definition at line 60 of file MagnetometerControl.c.
Referenced by ConMan_Init().
void MagControl_ReadMag (void)
Gets a reading from the magnetometer.
Definition at line 163 of file MagnetometerControl.c.
Referenced by _ProcessEvents_DEFAULT().
void MagControl_SetConfig (uint8_t keyValue)
Sets a configuration value to the accelerometer
Parameters
in keyValue - the key/value pair with the configuration information
Definition at line 74 of file MagnetometerControl.c.
Referenced by ConMan_SetSensorConfig().