Magnetometer.c File Reference
Magnetometer sensor interface module.
#include <ProjectTypes.h>
*
#include `Magnetometer.h`
*
#include <Assert.h>
*
#include <Debug.h>
*
#include <Serial.h>
*
#include <I2c.h>
*
#include <Gpio.h>
*
#include <Board.h>
*
#include <Device.h>
*
Macros
#define WHO_AM_I ((uint8_t)0xC4)
#define MAG_PORT I2cPort_0
#define MAG_ADDRESS ((uint8_t)0x0E)
#define BYTES_IN_SAMPLE 6u
Enumerations
enum MagReg_t {
*
MagReg_DR_STATUS = 0x00,
*
MagReg_OUT_X_MSB = 0x01,
*
MagReg_OUT_X_LSB = 0x02,
*
MagReg_OUT_Y_MSB = 0x03,
*
MagReg_OUT_Y_LSB = 0x04,
*
MagReg_OUT_Z_MSB = 0x05,
*
MagReg_OUT_Z_LSB = 0x06,
*
MagReg_WHO_AM_I = 0x07,
*
MagReg_SYSMOD = 0x08,
*
MagReg_OFF_X_MSB = 0x09,
*
MagReg_OFF_X_LSB = 0x0A,
*
MagReg_OFF_Y_MSB = 0x0B,
*
MagReg_OFF_Y_LSB = 0x0C,
*
MagReg_OFF_Z_MSB = 0x0D,
*
MagReg_OFF_Z_LSB = 0x0E,
*
MagReg_DIE_TEMP = 0x0F,
*
MagReg_CTRL_REG1 = 0x10,
*
MagReg_CTRL_REG2 = 0x11
 }
enum DataReadyStatus {
*
DataReadyStatus_XDR = 0x01,
*
DataReadyStatus_YDR = 0x02,
*
DataReadyStatus_ZDR = 0x04,
*
DataReadyStatus_ZYXDR = 0x08,
*
DataReadyStatus_XOW = 0x10,
*
DataReadyStatus_YOW = 0x20,
*
DataReadyStatus_ZOW = 0x40,
*
DataReadyStatus_ZYXOW = 0x80
 }
enum SysMod {
*
SysMod_STANDBY = 0x00,
*
SysMod_ACTIVE_RAW_DATA = 0x01,
*
SysMod_ACTIVE_SCALED_DATA = 0x02
 }
enum CtrlRegOne {
*
ADC_RATE_1280 = 0x00,
*
ADC_RATE_640 = 0x20,
*
ADC_RATE_320 = 0x40,
*
ADC_RATE_160 = 0x60,
*
ADC_RATE_80 = 0x80,
*
ADC_RATE_40 = 0xA0,
*
ADC_RATE_20 = 0xC0,
*
ADC_RATE_10 = 0xE0,
*
OSR_16 = 0x00,
*
OSR_32 = 0x08,
*
OSR_64 = 0x10,
*
OSR_128 = 0x18,
*
FAST_READ_ENABLE = 0x04,
*
TRIGGER_MEASUREMENT = 0x02,
*
ACTIVE_MODE_ENABLE = 0x01
 }
enum CtrlRegTwo {
*
Mag_RST = 0x10,
*
RAW_ENABLE = 0x20,
*
AUTO_MRST_EN = 0x80
 }
Functions
static void _HandleDataReadyInterrupt (void)
static uint8_t _ReadSingleRegister (MagReg_t reg)
static void _ReadMultipleRegisters (MagReg_t startReg, uint8_t numRegisters, uint8_t registers[])
static I2cError_t _WriteSingleRegister (MagReg_t reg, uint8_t value)
void Magnetometer_Init (void)
bool Magnetometer_Config (const MagConfig_t *config)
void Magnetometer_Start (void)
void Magnetometer_Stop (void)
bool Magnetometer_TriggerSampleBlocking (MagSample_t *sample)
void Magnetometer_ResetSensorBlocking (void)
void Magnetometer_SetCalibration (const MagSample_t *calibration)
bool Magnetometer_ReadSample (MagSample_t *sample)
void Magnetometer_ReadSampleArray (uint16_t maxLength, uint16_t *actualLength, uint8_t data[])
int8_t Magnetometer_ReadTemp (void)
void Magnetometer_RegisterIsr (MagIsrPointer_t isr)
void Magnetomter_UnregisterIsr (void)
Variables
static bool _initialized = false
static MagIsrPointer_t _magIsrPointer = NULL
static MagConfig_t _parameters
static volatile uint8_t _controlRegOne = 0u
static volatile uint8_t _controlRegTwo = 0u
static volatile bool _dataReady = false
Detailed Description
Magnetometer sensor interface module. Project 1814 IOLab Remote Sensor Application
Description This module provides logic to interface with the magnetometer (3-axis Hall effect sensor). This logic assumes that the magnetometer in use is the Freescale MAG3110 I2C Digital Magnetometer.
Link to Product Webpage
Link to Datasheet
Definition in file Magnetometer.c.
Macro Definition Documentation
#define MAG_ADDRESS ((uint8_t)0x0E)
defines the magnetometer's I2C address
Definition at line 126 of file Magnetometer.c.
Referenced by _ReadMultipleRegisters(), _ReadSingleRegister(), and _WriteSingleRegister().
#define MAG_PORT I2cPort_0
defines the port the magnetometer is attached to
Definition at line 123 of file Magnetometer.c.
Referenced by _ReadMultipleRegisters(), _ReadSingleRegister(), and _WriteSingleRegister().
#define WHO_AM_I ((uint8_t)0xC4)
Define the expected value of the WHO_AM_I query
Definition at line 83 of file Magnetometer.c.
Referenced by Magnetometer_Init().
Enumeration Type Documentation
enum CtrlRegOne
Defines the settings for control register one. The output data rate (ODR) is equal to the ADC_RATE/OSR. E.g. ADC_RATE_1280/OSR_16 = 80 Hz ODR
Enumerator
ADC_RATE_640
 analog sample rate in Hz
OSR_32
 over sampling ratio
Definition at line 96 of file Magnetometer.c.
enum CtrlRegTwo
Enumerator
RAW_ENABLE
 resets the magnetic sensor after exposure to large magnetic field
AUTO_MRST_EN
 if enabled, sensor will output raw data not scaled by user offset
Definition at line 115 of file Magnetometer.c.
enum DataReadyStatus
Defines the bitmask for the data ready status register
Definition at line 70 of file Magnetometer.c.
enum MagReg_t
Defines the possible registers that can be read from or written to on the magnetometer.
Enumerator
MagReg_OUT_X_MSB
 Data Ready Status (r)
MagReg_OUT_X_LSB
 Sensor data (r)
MagReg_OUT_Y_MSB
 (r)
MagReg_OUT_Y_LSB
 (r)
MagReg_OUT_Z_MSB
 (r)
MagReg_OUT_Z_LSB
 (r)
MagReg_WHO_AM_I
 (r)
MagReg_SYSMOD
 chip identifier byte (r)
MagReg_OFF_X_MSB
 system mode (r)
MagReg_OFF_X_LSB
 (r/w)
MagReg_OFF_Y_MSB
 (r/w)
MagReg_OFF_Y_LSB
 (r/w)
MagReg_OFF_Z_MSB
 (r/w)
MagReg_OFF_Z_LSB
 (r/w)
MagReg_DIE_TEMP
 (r/w)
MagReg_CTRL_REG1
 (r)
MagReg_CTRL_REG2
 (r/w)
Definition at line 47 of file Magnetometer.c.
enum SysMod
Defines the states of the system mode register
Definition at line 86 of file Magnetometer.c.
Function Documentation
static void _HandleDataReadyInterrupt (void) [static]
Handles the GPIO event that indicates that data is ready on the magnetometer.
Definition at line 620 of file Magnetometer.c.
Referenced by Magnetometer_Init().
static void _ReadMultipleRegisters (MagReg_t startReg, uint8_t numRegisters, uint8_t registers[]) [static]
Reads a multiple consecutive registers from the magnetometer.
Parameters
in startReg - the first register to read of the consecutive registers
in numRegisters - The number of consecutive registers to read
in registers[] - the array in which the register values will be stored.
Note
Make sure that registers[] has at least numRegisters elements to hold the register data.
Definition at line 668 of file Magnetometer.c.
Referenced by Magnetometer_ReadSample(), Magnetometer_ReadSampleArray(), and Magnetometer_TriggerSampleBlocking().
static uint8_t _ReadSingleRegister (MagReg_t reg) [static]
Reads a single register from the magnetometer.
Parameters
in reg- the register to read
Returns
The value read from the magnetometer register
Definition at line 638 of file Magnetometer.c.
Referenced by Magnetometer_Config(), Magnetometer_Init(), Magnetometer_ReadTemp(), Magnetometer_ResetSensorBlocking(), Magnetometer_Start(), and Magnetometer_TriggerSampleBlocking().
static I2cError_t _WriteSingleRegister (MagReg_t reg, uint8_t value) [static]
Writes a single register to the magnetometer.
Parameters
in reg - the register to write to
in value - The value to write to the register
Returns
I2cError_OK if the register could be written successfully. Otherwise return an I2cError.
Definition at line 708 of file Magnetometer.c.
Referenced by Magnetometer_Config(), Magnetometer_Init(), Magnetometer_ResetSensorBlocking(), Magnetometer_SetCalibration(), Magnetometer_Start(), Magnetometer_Stop(), and Magnetometer_TriggerSampleBlocking().
bool Magnetometer_Config (const MagConfig_t * config)
Configures the magnetometer, but does not start the sampling.
Parameters
in config - Structure of selected magnetometer settings.
Returns
True if the configuration was successful, false otherwise. The configuration will fail if the magnetometer is not in standby when configured.
Definition at line 193 of file Magnetometer.c.
Referenced by MagControl_SetConfig().
void Magnetometer_Init (void)
Initializes the magnetometer, but does not configure or start the sampling.
Definition at line 159 of file Magnetometer.c.
Referenced by MagControl_Init().
bool Magnetometer_ReadSample (MagSample_t * sample)
Reads a sample from the magnetometer if a sample was ready.
Parameters
in sample - structure to hold the sample data once it is collected
Returns
True if the sample was ready, false otherwise
Definition at line 526 of file Magnetometer.c.
Referenced by MagControl_ReadMag().
void Magnetometer_ReadSampleArray (uint16_t maxLength, uint16_t * actualLength, uint8_t data[])
Reads a sample from the magnetometer if a sample was ready.
Parameters
in maxLength - the maximum number of items that can be written to data[]
out actuaLength - the actual number of items written to data[]
out data - the array that the data will be stored in.
Definition at line 560 of file Magnetometer.c.
Referenced by MagControl_ReadMag().
int8_t Magnetometer_ReadTemp (void)
Reads the die temperature of the device.
Returns
Temperature in °C as a signed 8-bit integer number
Definition at line 590 of file Magnetometer.c.
void Magnetometer_RegisterIsr (MagIsrPointer_t isr)
Sets a function that will be ran when the data ready interrupt occurs.
Parameters
in isr - pointer to the accelerometer data ready ISR
Definition at line 603 of file Magnetometer.c.
Referenced by MagControl_Init().
void Magnetometer_ResetSensorBlocking (void)
Resets the sensor in the magnetometer and blocks until the sensor is reset.
Definition at line 460 of file Magnetometer.c.
void Magnetometer_SetCalibration (const MagSample_t * calibration)
Writes the sensor calibration data to the magnetometer.
Parameters
in calibration - structure to hold the calibration data to be written
Definition at line 487 of file Magnetometer.c.
void Magnetometer_Start (void)
Starts the magnetometer sampling at its configured data rate.
Definition at line 368 of file Magnetometer.c.
Referenced by MagControl_SetConfig(), and ThermometerControl_SetConfig().
void Magnetometer_Stop (void)
Stops the data collecting of the magnetometer.
Definition at line 399 of file Magnetometer.c.
Referenced by MagControl_SetConfig(), and ThermometerControl_SetConfig().
bool Magnetometer_TriggerSampleBlocking (MagSample_t * sample)
Triggers a sample from the magnetometer and blocks until the sample is returned.
Parameters
in sample - structure to hold the sample data once it is collected
Returns
True if the sample was aquired, false otherwise
Definition at line 419 of file Magnetometer.c.
Referenced by _HandleHumanMagCommand().
void Magnetomter_UnregisterIsr (void)
Clears the custom ISR for the magnetometer.
Definition at line 612 of file Magnetometer.c.
Variable Documentation
volatile uint8_t _controlRegOne = 0u [static]
Stores the values written to the control registers because the chip always reads back 0x00 when reading the register.
Definition at line 142 of file Magnetometer.c.
Referenced by Magnetometer_Config(), Magnetometer_Init(), Magnetometer_Start(), and Magnetometer_Stop().
volatile bool _dataReady = false [static]
Tracks if data is ready to be read from the magnetometer
Definition at line 146 of file Magnetometer.c.
Referenced by _HandleDataReadyInterrupt(), Magnetometer_ReadSample(), and Magnetometer_ReadSampleArray().
bool _initialized = false [static]
Tracks if the magnetometer is initialized
Definition at line 130 of file Magnetometer.c.
MagIsrPointer_t _magIsrPointer = NULL [static]
Stores the ISR pointer
Definition at line 134 of file Magnetometer.c.
Referenced by _HandleDataReadyInterrupt(), Magnetometer_RegisterIsr(), and Magnetomter_UnregisterIsr().
MagConfig_t _parameters [static]
Initial value:
= {MagSampleRate_1280, MagOverSampleRatio_16, MagDataScaling_RAW, MagAutoReset_ENABLED,
                                  MagSampling_Auto, MagResolution_16BIT}
Stores the configuration parameters for the _initialized port
Definition at line 137 of file Magnetometer.c.