MicrophoneControl.c File Reference
Controls reading the microphone.
#include <ProjectTypes.h>
*
#include `MicrophoneControl.h`
*
#include <SensorId.h>
*
#include <DataBuffer.h>
*
#include <KeyValue.h>
*
#include <AdcManager.h>
*
#include <Assert.h>
*
#include <Serial.h>
*
Functions
static void _MicrophoneDataCallback (uint16_t data)
void MicrophoneControl_Init (void)
void MicrophoneControl_SetConfig (uint8_t config)
Variables
static bool _initialized = false
static MicrophoneSampleRate_t _sampleRate = DEFAULT_MICROPHONE_SAMPLE_RATE
Detailed Description
Controls reading the microphone. Project 1814 IOLab Remote Sensor Application
Description Controls the microphone and manages the configurations and settings associated with the microphone
Definition in file MicrophoneControl.c.
Function Documentation
static void _MicrophoneDataCallback (uint16_t data) [static]
Takes the microphone data and stores it in the proper location. This function is designed to be called every time there is data for the microphone.
Parameters
in data - The sample from the microphone that should be stored in the proper location.
Definition at line 162 of file MicrophoneControl.c.
Referenced by MicrophoneControl_SetConfig().
void MicrophoneControl_Init (void)
Initializes the ambient light sensor reading control.
Definition at line 50 of file MicrophoneControl.c.
Referenced by ConMan_Init().
void MicrophoneControl_SetConfig (uint8_t config)
Takes a configuration and sets it for the microphone.
Parameters
in config - the KeyValue configuration setting for the microphone.
Definition at line 61 of file MicrophoneControl.c.
Referenced by ConMan_SetSensorConfig().
Variable Documentation
bool _initialized = false [static]
Tracks if the module has been initialized
Definition at line 38 of file MicrophoneControl.c.
MicrophoneSampleRate_t _sampleRate = DEFAULT_MICROPHONE_SAMPLE_RATE [static]
Stores the desired sample rate of the microphone
Definition at line 41 of file MicrophoneControl.c.
Referenced by MicrophoneControl_SetConfig().