Pmm.c File Reference
Power management module driver.
#include <ProjectTypes.h>
*
#include `Pmm.h`
*
#include <Assert.h>
*
#include <Debug.h>
*
#include <Serial.h>
*
#include <Device.h>
*
Macros
#define PMM_MAX_VCORE_LEVEL (3u)
#define PMM_PASSWORD (0xA5u)
Enumerations
enum PmmStatus_t {
*
PmmStatus_OKAY,
*
PmmStatus_ERROR
 }
Functions
static PmmStatus_t _SetVCore (uint8_t level)
static PmmStatus_t _SetVCoreUp (uint8_t level)
static PmmStatus_t _SetVCoreDown (uint8_t level)
void Pmm_Init (void)
Detailed Description
Power management module driver. Project 1814 IOLab Remote Sensor Application
Description The power management module driver will interact with the microcontroller registers that control the power modes of the micro and peripherals.
Definition in file Pmm.c.
Macro Definition Documentation
#define PMM_MAX_VCORE_LEVEL (3u)
Maximum level that Vcore can be set to
Definition at line 36 of file Pmm.c.
Referenced by _SetVCore(), _SetVCoreDown(), and _SetVCoreUp().
#define PMM_PASSWORD (0xA5u)
Password required to access PMM registers
Definition at line 39 of file Pmm.c.
Referenced by _SetVCoreDown(), _SetVCoreUp(), and Pmm_Init().
Enumeration Type Documentation
enum PmmStatus_t
Possible results of setting Vcore
Definition at line 42 of file Pmm.c.
Function Documentation
static PmmStatus_t _SetVCore (uint8_t level) [static]
Set Vcore to given level.
Parameters
in level - Level to which Vcore needs to be set
Returns
PmmStatus_OKAY if successful, otherwise PmmStatus_ERROR
Definition at line 120 of file Pmm.c.
Referenced by Pmm_Init().
static PmmStatus_t _SetVCoreDown (uint8_t level) [static]
Decrease Vcore by one level
Parameters
in level - Level to which Vcore needs to be decreased
Returns
PmmStatus_OKAY if successful, otherwise PmmStatus_ERROR
Definition at line 298 of file Pmm.c.
Referenced by _SetVCore().
static PmmStatus_t _SetVCoreUp (uint8_t level) [static]
Increase Vcore by one level
Parameters
in level - Level to which Vcore needs to be increased
Returns
PmmStatus_OKAY if successful, otherwise PmmStatus_ERROR
Definition at line 155 of file Pmm.c.
Referenced by _SetVCore().
void Pmm_Init (void)
Initialize the power management module.
Note that high-side refers to Vcc and low-side refers to Vcore.
Definition at line 59 of file Pmm.c.
Referenced by Board_Init().