PushButtonControl.c File Reference
Control for the push buttons.
#include <ProjectTypes.h>
*
#include `PushButtonControl.h`
*
#include <Gpio.h>
*
#include <Board.h>
*
#include <EventQueue.h>
*
#include <TimerTick.h>
*
Data Structures
struct PushButtonInfo_t
Macros
#define BUTTON_DEBOUNCE_MS (80u)
Functions
static void _ProcessPushButtons (void)
void PushButtonControl_Init (void)
bool PushButtonControl_isButtonPressed (PushButtons_t button)
uint16_t PushButtonControl_ButtonPressedDuration (PushButtons_t button)
Variables
static TickIsrHandle_t _processButtonsIsrHandle
static PushButtonInfo_t _buttonInfo [PushButton_LAST]
Detailed Description
Control for the push buttons. Project 1814 IOLab Remote Sensor Application
Description The push button control will control the push buttons and manage the debouncing of them.
Definition in file PushButtonControl.c.
Data Structure Documentation
struct PushButtonInfo_t
Definition at line 37 of file PushButtonControl.c.
Data Fields
uint16_t
buttonPressedDuration
uint16_t
previousButtonPressedDuration
Macro Definition Documentation
#define BUTTON_DEBOUNCE_MS (80u)
The number of milliseconds that must have elapsed for the button to be debounced.
Definition at line 35 of file PushButtonControl.c.
Referenced by _ProcessPushButtons(), PushButtonControl_Init(), and PushButtonControl_isButtonPressed().
Function Documentation
static void _ProcessPushButtons (void) [static]
Processes the push buttons by looking at the state of the buttons and generating the appropriate events based on the button state and how long the button has been in that state.
Debounce the press only. This sort of debounces the release as well (i.e. press won't happen from a bounce on release).
Note
function assumes it is called every system timer tick.
Definition at line 145 of file PushButtonControl.c.
Referenced by PushButtonControl_Init().
uint16_t PushButtonControl_ButtonPressedDuration (PushButtons_t button)
Gets the duration (in ms) that the button has been pressed.
Parameters
in button - The button enum value for the button of interest
Returns
The number of milliseconds which the button has been depressed.
The resolution of the duration depends on the period of the system tick.The pressed duration does not account for the debounce time. Example, if the button debounce time is 50 ms and the button has been pressed for 40 ms, this function will still return that the button has been `pressed` for 40 ms even though the debounce time hasn't occured.
Definition at line 119 of file PushButtonControl.c.
void PushButtonControl_Init (void)
Initializes the push button controller and regisisters the push button callback.
Definition at line 59 of file PushButtonControl.c.
Referenced by main().
bool PushButtonControl_isButtonPressed (PushButtons_t button)
Returns true if the button is pressed, false otherwise. This takes into account the button debounce time.
Parameters
in button - The button enum value for the button of interest
Returns
True if the button is pressed, false otherwise
Definition at line 89 of file PushButtonControl.c.
Referenced by _ProcessEvents_RUN().
Variable Documentation
PushButtonInfo_t _buttonInfo[PushButton_LAST] [static]
Stores how long the push buttons have been pressed
Definition at line 50 of file PushButtonControl.c.
TickIsrHandle_t _processButtonsIsrHandle [static]
Define a variable to store the handle to the ISR to process the push buttons.
Definition at line 47 of file PushButtonControl.c.
Referenced by PushButtonControl_Init().