Pwm.c File Reference
Pulse width modulation module driver.
#include <ProjectTypes.h>
*
#include `Pwm.h`
*
#include <Assert.h>
*
#include <Debug.h>
*
#include <Serial.h>
*
#include <Device.h>
*
#include <Timer.h>
*
#include <Board.h>
*
#include <Gpio.h>
*
#include <Clock.h>
*
Macros
#define PWM_CLK (1200000ul)
#define NUM_CHANNELS 7
#define MAX_DUTY 100
#define DEFAULT_MAX_COUNT 1200
Functions
static uint16_t _DutyToCount (uint8_t duty)
static bool _AnyChannelsEnabled (void)
void Pwm_Init (void)
void Pwm_SetFrequency (uint32_t freq)
bool Pwm_SetDuty (PwmChannel_t channel, uint8_t duty)
uint8_t Pwm_GetDuty (PwmChannel_t channel)
bool Pwm_Enable (PwmChannel_t channel, uint8_t duty)
void Pwm_Disable (PwmChannel_t channel)
Variables
static volatile TimerB0CC_t const _ccModules [NUM_CHANNELS]
static uint16_t _maxCount = DEFAULT_MAX_COUNT
static uint8_t _dutyCycles [NUM_CHANNELS] = {0}
static bool _openChannels [NUM_CHANNELS] = {false}
static bool _initialized = false
Detailed Description
Pulse width modulation module driver. Project 1814 IOLab Remote Sensor Application
Description The pulse width modulation module contains functions definitions and macros that set up and control the MSP430 timer B peripheral used to generate pulse width modulated signals.
Definition in file Pwm.c.
Macro Definition Documentation
#define DEFAULT_MAX_COUNT 1200
define the default frequency during initialization to be 1kHz, which corresponds to a maxCount of 1200.
Definition at line 53 of file Pwm.c.
#define MAX_DUTY 100
maximum duty cycle that can be specified for a PWM channel
Definition at line 48 of file Pwm.c.
Referenced by Pwm_Enable(), and Pwm_SetDuty().
#define NUM_CHANNELS 7
number of PWM channels
Definition at line 45 of file Pwm.c.
Referenced by _AnyChannelsEnabled(), and Pwm_SetFrequency().
#define PWM_CLK (1200000ul)
The PWM clock is the PWM timer source divided by the timer divider. the SMCLK divided by 20. The timer source is defined in the init to be SMCLK, which is 24MHz. The divider is defined in the init to be 20. Change this define if the init is changed.
Definition at line 42 of file Pwm.c.
Referenced by Pwm_SetFrequency().
Function Documentation
static bool _AnyChannelsEnabled (void) [static]
Determines if any channels are enabled
Definition at line 331 of file Pwm.c.
Referenced by Pwm_Disable(), Pwm_Enable(), and Pwm_SetFrequency().
static uint16_t _DutyToCount (uint8_t duty) [static]
Converts the specified duty cycle to counts to be loaded into the register
Parameters
in duty - Duty cycle for PWM.
Definition at line 316 of file Pwm.c.
Referenced by Pwm_Enable(), and Pwm_SetDuty().
void Pwm_Disable (PwmChannel_t channel)
Disable a channel of the PWM.
Parameters
in channel - PWM channel to disable
Definition at line 259 of file Pwm.c.
Referenced by Buzzer_Disable(), BuzzerControl_SetConfig(), Header4Control_SetConfig(), and Header5Control_SetConfig().
bool Pwm_Enable (PwmChannel_t channel, uint8_t duty)
Enable a channel of the PWM.
Parameters
in channel - PWM channel to enable
in duty - duty cycle for specified channel, should be between 0 and 100
Definition at line 185 of file Pwm.c.
Referenced by _BuzzerControl_SetOutput(), _HandleHumanPwmCommand(), and Buzzer_Enable().
uint8_t Pwm_GetDuty (PwmChannel_t channel)
Gets the duty cycle for a specific channel of the PWM.
Parameters
in channel - Channel to get the duty cycle of
Returns
The duty cycle setting of that PWM channel
Definition at line 167 of file Pwm.c.
Referenced by Buzzer_Enable().
void Pwm_Init (void)
Initialize the PWM with default settings:
Definition at line 92 of file Pwm.c.
Referenced by Buzzer_Init(), BuzzerControl_Init(), Header5Control_Init(), and main().
bool Pwm_SetDuty (PwmChannel_t channel, uint8_t duty)
Set the duty cycle for a specific channel of the PWM.
Parameters
in channel - Channel to configure
in duty - Duty cycle to set the channel to
Definition at line 141 of file Pwm.c.
Referenced by _BuzzerControl_SetDutyCycle(), Buzzer_Init(), Buzzer_SetDuty(), and Pwm_SetFrequency().
void Pwm_SetFrequency (uint32_t freq)
Set the frequency of the PWM in fixed point tenths of Hertz.
Parameters
in freq - Fixed point frequency at which to set the PWM. Uses a x10 fixed point, so 123.4Hz = 1234.
Note
With TimerSource = SMCLK = 24MHz, and TimerDivider = 20, the frequency range is 18 to 37500 Hz
Definition at line 110 of file Pwm.c.
Referenced by _BuzzerControl_SetOutput(), _HandleHumanPwmCommand(), Buzzer_Init(), and Buzzer_SetFrequency().
Variable Documentation
volatile TimerB0CC_t const _ccModules[NUM_CHANNELS] [static]
Initial value:
=
{
    TimerB0CC_0,
    TimerB0CC_1,
    TimerB0CC_2,
    TimerB0CC_3,
    TimerB0CC_4,
    TimerB0CC_5,
    TimerB0CC_6
}
Array of Timer B0 compare/capture (CC) modules
Definition at line 57 of file Pwm.c.
Referenced by Pwm_Enable(), and Pwm_SetDuty().
uint8_t _dutyCycles[NUM_CHANNELS] = {0} [static]
Array to keep track of the duty cycles of channels
Definition at line 75 of file Pwm.c.
Referenced by _BuzzerControl_SetDutyCycle(), _BuzzerControl_SetOutput(), Pwm_Enable(), Pwm_GetDuty(), Pwm_SetDuty(), and Pwm_SetFrequency().
bool _initialized = false [static]
tracks if the PWM driver has been initialized
Definition at line 82 of file Pwm.c.
uint16_t _maxCount = DEFAULT_MAX_COUNT [static]
Stores the maximum number the timer will count up to before resetting, which defines the period of the PWM signal.
Definition at line 72 of file Pwm.c.
Referenced by _DutyToCount(), Pwm_Init(), and Pwm_SetFrequency().
bool _openChannels[NUM_CHANNELS] = {false} [static]
Array to keep track of what PWM channels are in use
Definition at line 79 of file Pwm.c.
Referenced by _AnyChannelsEnabled(), Pwm_Disable(), Pwm_Enable(), and Pwm_SetFrequency().