Pwm.h File Reference
Pulse width modulation module.
Enumerations
enum PwmChannel_t {
*
PwmChannel_0 = 0,
*
PwmChannel_1 = 1,
*
PwmChannel_2 = 2,
*
PwmChannel_3 = 3,
*
PwmChannel_4 = 4,
*
PwmChannel_5 = 5,
*
PwmChannel_6 = 6
 }
Functions
void Pwm_Init (void)
void Pwm_SetFrequency (uint32_t freq)
bool Pwm_SetDuty (PwmChannel_t channel, uint8_t duty)
uint8_t Pwm_GetDuty (PwmChannel_t channel)
bool Pwm_Enable (PwmChannel_t channel, uint8_t duty)
void Pwm_Disable (PwmChannel_t channel)
Detailed Description
Pulse width modulation module. Project 1814 IOLab Remote Sensor Application
Description Contains functions and macros for the pulse width modulation module.
Definition in file Pwm.h.
Enumeration Type Documentation
enum PwmChannel_t
PWM channels
Definition at line 27 of file Pwm.h.
Function Documentation
void Pwm_Disable (PwmChannel_t channel)
Disable a channel of the PWM.
Parameters
in channel - PWM channel to disable
Definition at line 259 of file Pwm.c.
Referenced by Buzzer_Disable(), BuzzerControl_SetConfig(), Header4Control_SetConfig(), and Header5Control_SetConfig().
bool Pwm_Enable (PwmChannel_t channel, uint8_t duty)
Enable a channel of the PWM.
Parameters
in channel - PWM channel to enable
in duty - duty cycle for specified channel, should be between 0 and 100
Definition at line 185 of file Pwm.c.
Referenced by _BuzzerControl_SetOutput(), _HandleHumanPwmCommand(), and Buzzer_Enable().
uint8_t Pwm_GetDuty (PwmChannel_t channel)
Gets the duty cycle for a specific channel of the PWM.
Parameters
in channel - Channel to get the duty cycle of
Returns
The duty cycle setting of that PWM channel
Definition at line 167 of file Pwm.c.
Referenced by Buzzer_Enable().
void Pwm_Init (void)
Initialize the PWM with default settings:
Definition at line 92 of file Pwm.c.
Referenced by Buzzer_Init(), BuzzerControl_Init(), Header5Control_Init(), and main().
bool Pwm_SetDuty (PwmChannel_t channel, uint8_t duty)
Set the duty cycle for a specific channel of the PWM.
Parameters
in channel - Channel to configure
in duty - Duty cycle to set the channel to
Definition at line 141 of file Pwm.c.
Referenced by _BuzzerControl_SetDutyCycle(), Buzzer_Init(), Buzzer_SetDuty(), and Pwm_SetFrequency().
void Pwm_SetFrequency (uint32_t freq)
Set the frequency of the PWM in fixed point tenths of Hertz.
Parameters
in freq - Fixed point frequency at which to set the PWM. Uses a x10 fixed point, so 123.4Hz = 1234.
Note
With TimerSource = SMCLK = 24MHz, and TimerDivider = 20, the frequency range is 18 to 37500 Hz
Definition at line 110 of file Pwm.c.
Referenced by _BuzzerControl_SetOutput(), _HandleHumanPwmCommand(), Buzzer_Init(), and Buzzer_SetFrequency().