SelfTest.h File Reference
Manages the self test mode.
Functions
void SelfTest_Init (void)
void SelfTest_Start (void)
void SelfTest_Process (void)
Detailed Description
Manages the self test mode. Description Handles the sequencing, configuration, and data management for the self test mode.
Definition in file SelfTest.h.
Function Documentation
void SelfTest_Init (void)
Initializes the self-test module.
Definition at line 231 of file SelfTest.c.
Referenced by main().
void SelfTest_Process (void)
Processes the data received during the self test.
Definition at line 261 of file SelfTest.c.
Referenced by _ProcessEvents_SELF_TEST().
void SelfTest_Start (void)
Starts the self-test. Sets all of the necessary configurations for the test to begin.
Definition at line 240 of file SelfTest.c.
Referenced by _ProcessEvents_SELF_TEST().