Serial.h File Reference
Serial interface module header.
Data Structures
struct SerialBuffer_t
Macros
#define SERIAL_PAYLOAD_MAX_LENGTH (50u)
#define SERIAL_PAYLOAD_MAX_LENGTH_HUMAN (SERIAL_PAYLOAD_MAX_LENGTH - 1u)
Enumerations
enum SerialStatus_t {
*
SerialStatus_SUCCESS,
*
SerialStatus_RECEIVE_DISABLED,
*
SerialStatus_NO_PACKET,
*
SerialStatus_TX_BUFFER_FULL
 }
enum SerialMode_t {
*
SerialMode_TRANSMIT_ONLY,
*
SerialMode_TRANSMIT_AND_RECEIVE
 }
Functions
void Serial_Init (void)
void Serial_Open (SerialMode_t mode)
void Serial_Close (void)
void Serial_ProcessReceivedBytes (void)
SerialStatus_t Serial_GetPacket (SerialBuffer_t **payloadReceived)
SerialStatus_t Serial_SendPacket (const SerialBuffer_t *payloadToTransmit)
void Serial_SendString (const char_t *string)
void Serial_SendStringNumber (const char_t *string, uint16_t number)
void Serial_SendStringNumberU32 (const char_t *string, uint32_t number)
void Serial_SendString3Numbers (const char_t *string, uint16_t number1, uint16_t number2, uint16_t number3)
void Serial_SendStringBlocking (const char_t *string)
void Serial_SendStringBlockingNoAssert (const char_t *string)
Detailed Description
Serial interface module header. Project 1814 IOLab Remote Sensor Application
Description The serial interface is used to transmit serial data over a serial port.
Definition in file Serial.h.
Data Structure Documentation
struct SerialBuffer_t
Defines a struct used to store serial payloads.
Definition at line 54 of file Serial.h.
Data Fields
uint8_t
buffer[SERIAL_PAYLOAD_MAX_LENGTH]
Stores the serial payload.
bool
inUse
Tracks if the buffer is currently in use.
bool
isBinary
Specifies if the buffer contains a binary payload.
uint16_t
length
Specifies the length of the payload in the buffer.
Macro Definition Documentation
#define SERIAL_PAYLOAD_MAX_LENGTH (50u)
The maximum length in bytes of the payload field.
Definition at line 30 of file Serial.h.
Referenced by Assert(), and Serial_SendPacket().
#define SERIAL_PAYLOAD_MAX_LENGTH_HUMAN (SERIAL_PAYLOAD_MAX_LENGTH - 1u)
The maximum length in bytes of the payload field for a human readable packet. The length is reduced by one to make space for a NULL character at the end of the payload, making it a valid string.
Definition at line 35 of file Serial.h.
Referenced by _HandleHumanAccCommand(), _HandleHumanAdc1Command(), _HandleHumanBarcCommand(), _HandleHumanBarCommand(), _HandleHumanEncoderCommand(), _HandleHumanGpiCommand(), _HandleHumanGyroCommand(), _HandleHumanMagCommand(), _HandleHumanRfCommand(), _HandleHumanVerCommand(), _SendAckHuman(), _SendNakHuman(), Assert(), Serial_ProcessReceivedBytes(), Serial_SendString(), Serial_SendString3Numbers(), Serial_SendStringBlocking(), Serial_SendStringBlockingNoAssert(), Serial_SendStringNumber(), and Serial_SendStringNumberU32().
Enumeration Type Documentation
enum SerialMode_t
Possible serial interface modes.
Definition at line 47 of file Serial.h.
enum SerialStatus_t
Possible results of serial operations.
Definition at line 38 of file Serial.h.
Function Documentation
void Serial_Close (void)
Closes the serial interface.
Definition at line 172 of file Serial.c.
SerialStatus_t Serial_GetPacket (SerialBuffer_t ** payloadReceived)
Attempts to get a serial packet.
Parameters
out payloadReceived - Pointer to the received serial payload.
Return values
SerialStatus_SUCCESS if a valid packet was received.
SerialStatus_RECEIVE_DISABLED if not in receive mode.
SerialStatus_NO_PACKET if no packet was available.
Definition at line 310 of file Serial.c.
Referenced by TestProtocol_HandleReceivedPacket().
void Serial_Init (void)
Initializes the received serial payload buffer and the UART.
Definition at line 132 of file Serial.c.
Referenced by main().
void Serial_Open (SerialMode_t mode)
Opens the serial interface.
Parameters
in mode - Selected mode for the serial interface.
Definition at line 146 of file Serial.c.
Referenced by main().
void Serial_ProcessReceivedBytes (void)
Processes bytes received from the UART, searching for a valid packet.
Definition at line 182 of file Serial.c.
Referenced by main().
SerialStatus_t Serial_SendPacket (const SerialBuffer_t * payloadToTransmit)
Attempts to send a serial packet.
Parameters
in payloadToTransmit - Pointer to the serial payload to transmit.
Return values
SerialStatus_SUCCESS if packet sent successfully.
SerialStatus_TX_BUFFER_FULL if transmit buffer is full.
Definition at line 345 of file Serial.c.
Referenced by _HandleHumanAccCommand(), _HandleHumanAdc1Command(), _HandleHumanBarcCommand(), _HandleHumanBarCommand(), _HandleHumanEncoderCommand(), _HandleHumanGpiCommand(), _HandleHumanGyroCommand(), _HandleHumanMagCommand(), _HandleHumanRfCommand(), _HandleHumanVerCommand(), _SendAckHuman(), and _SendNakHuman().
void Serial_SendString (const char_t * string)
Attempts to send a string as a human-readable serial packet. If a UART error occurs, the entire packet may not be written.
Parameters
in string - Pointer to the string to transmit.
Definition at line 415 of file Serial.c.
Referenced by _PrintResetReason(), EncControl_ReadEnc(), and GyroControl_ReadGyro().
void Serial_SendString3Numbers (const char_t * string, uint16_t number1, uint16_t number2, uint16_t number3)
Attempts to send a string and number as a human-readable serial packet. If a UART error occurs, the entire packet may not be written. The number will always be printed at the end of the string in hex format.
Parameters
in string - Pointer to the string to transmit.
in number1 - number to print at the end of the string.
in number2 - number to print at the end of the string.
in number3 - number to print at the end of the string.
Definition at line 572 of file Serial.c.
Referenced by AccControl_ReadAcc(), BarometerControl_ReadBar(), GyroControl_ReadGyro(), and MagControl_ReadMag().
void Serial_SendStringBlocking (const char_t * string)
Attempts to send a string as a human-readable serial packet and blocks until the send is complete.
Parameters
in string - Pointer to the string to transmit.
Definition at line 679 of file Serial.c.
void Serial_SendStringBlockingNoAssert (const char_t * string)
Attempts to send a string as a human-readable serial packet and blocks until the send is complete.
Note
This function does not use an assert for safety checking so that it can be used in the assert handler.
Parameters
in string - Pointer to the string to transmit.
Definition at line 708 of file Serial.c.
Referenced by Assert().
void Serial_SendStringNumber (const char_t * string, uint16_t number)
Attempts to send a string and number as a human-readable serial packet. If a UART error occurs, the entire packet may not be written. The number will always be printed at the end of the string in hex format.
Parameters
in string - Pointer to the string to transmit.
in number - number to print at the end of the string.
Definition at line 456 of file Serial.c.
Referenced by _AmbientLightDataCallback(), _Analog7DataCallback(), _Analog8DataCallback(), _Analog9DataCallback(), _BatteryVoltageDataCallback(), _EcgAddToDataBuffer(), _ForceGaugeDataCallback(), _HighGainDataCallback(), _MicrophoneDataCallback(), _ReadPins(), _thermometerDataCallBack(), AdcManager_ProcessConversion(), CommProtocol_RxHandler(), ConMan_SetFixedConfig(), EncControl_ReadEnc(), SelfTest_Process(), and UiManager_PlaySequence().
void Serial_SendStringNumberU32 (const char_t * string, uint32_t number)
Attempts to send a string and number as a human-readable serial packet. If a UART error occurs, the entire packet may not be written. The number will always be printed at the end of the string in hex format.
Parameters
in string - Pointer to the string to transmit.
in number - number to print at the end of the string.
Definition at line 508 of file Serial.c.
Referenced by _thermometerDataCallBack().