Serial.c File Reference
Serial communication module.
#include <ProjectTypes.h>
*
#include `Serial.h`
*
#include <EventQueue.h>
*
#include <Assert.h>
*
#include <Debug.h>
*
#include <Uart.h>
*
#include <string.h>
*
Macros
#define SERIAL_UART_PORT (UartPort_1)
#define SERIAL_CHECKSUM_LENGTH (2u)
#define SERIAL_HEADER_LENGTH (7u)
#define FOOTER_HUMAN_LENGTH (2u)
Serial Protocol Field Indexes
#define SERIAL_SOP_INDEX (0u)
#define SERIAL_LENGTH_MSB_INDEX (1u)
#define SERIAL_LENGTH_LSB_INDEX (2u)
#define SERIAL_DCS_MSB_INDEX (3u)
#define SERIAL_DCS_LSB_INDEX (4u)
#define SERIAL_HCS_MSB_INDEX (5u)
#define SERIAL_HCS_LSB_INDEX (6u)
#define SERIAL_PAYLOAD_INDEX (7u)
Serial protocol start- and end-of-packet byte definitions.
#define SERIAL_SOP_BINARY (0x7Cu)
#define SERIAL_SOP_HUMAN (0x3Cu)
#define SERIAL_EOP (0x0Du)
Serial protocol acknowledgment and negative-acknowledgment definitions.
#define SERIAL_ACK (0x41u)
#define SERIAL_NAK (0x4Eu)
Functions
void Serial_Init (void)
void Serial_Open (SerialMode_t mode)
void Serial_Close (void)
void Serial_ProcessReceivedBytes (void)
SerialStatus_t Serial_GetPacket (SerialBuffer_t **payloadReceived)
SerialStatus_t Serial_SendPacket (const SerialBuffer_t *payloadToTransmit)
void Serial_SendString (const char_t *string)
void Serial_SendStringNumber (const char_t *string, uint16_t number)
void Serial_SendStringNumberU32 (const char_t *string, uint32_t number)
void Serial_SendString3Numbers (const char_t *string, uint16_t number1, uint16_t number2, uint16_t number3)
void Serial_SendStringBlocking (const char_t *string)
void Serial_SendStringBlockingNoAssert (const char_t *string)
Variables
static const uint8_t _footerHuman [FOOTER_HUMAN_LENGTH] = {0x0Au, SERIAL_EOP}
static SerialBuffer_t _serialPayloadRx
static bool _isSerialInterfaceOpen = false
static SerialMode_t _currentMode = SerialMode_TRANSMIT_ONLY
static uint16_t _currentRxIndex = SERIAL_SOP_INDEX
Detailed Description
Serial communication module. Project 1814 IOLab Remote Sensor Application
Description This module implements a serial communication interface that supports both a binary and human readable output.
Definition in file Serial.c.
Macro Definition Documentation
#define FOOTER_HUMAN_LENGTH (2u)
Length in bytes of the footer used for human-readable packets
Definition at line 96 of file Serial.c.
Referenced by Serial_SendPacket(), Serial_SendString(), Serial_SendString3Numbers(), Serial_SendStringBlocking(), Serial_SendStringBlockingNoAssert(), Serial_SendStringNumber(), and Serial_SendStringNumberU32().
#define SERIAL_ACK (0x41u)
Equal to 'A' in ASCII.
Definition at line 90 of file Serial.c.
#define SERIAL_CHECKSUM_LENGTH (2u)
Length of a checksum field in bytes.
Definition at line 71 of file Serial.c.
#define SERIAL_EOP (0x0Du)
Equal to '
' (newline) in ASCII.
Definition at line 83 of file Serial.c.
Referenced by Serial_ProcessReceivedBytes().
#define SERIAL_HEADER_LENGTH (7u)
Length of an entire header (includes SOP) of a binary packet.
Definition at line 73 of file Serial.c.
#define SERIAL_NAK (0x4Eu)
Equal to 'N' in ASCII.
Definition at line 92 of file Serial.c.
#define SERIAL_SOP_BINARY (0x7Cu)
Equal to '|' in ASCII.
Definition at line 79 of file Serial.c.
Referenced by Serial_ProcessReceivedBytes().
#define SERIAL_SOP_HUMAN (0x3Cu)
Equal to '<' in ASCII.
Definition at line 81 of file Serial.c.
Referenced by Serial_ProcessReceivedBytes(), Serial_SendPacket(), Serial_SendString(), Serial_SendString3Numbers(), Serial_SendStringBlocking(), Serial_SendStringBlockingNoAssert(), Serial_SendStringNumber(), and Serial_SendStringNumberU32().
#define SERIAL_UART_PORT (UartPort_1)
Defines the selected UART port used by the serial interface
Definition at line 41 of file Serial.c.
Referenced by Serial_Close(), Serial_Init(), Serial_Open(), Serial_ProcessReceivedBytes(), Serial_SendPacket(), Serial_SendString(), Serial_SendString3Numbers(), Serial_SendStringBlocking(), Serial_SendStringBlockingNoAssert(), Serial_SendStringNumber(), and Serial_SendStringNumberU32().
Function Documentation
void Serial_Close (void)
Closes the serial interface.
Definition at line 172 of file Serial.c.
SerialStatus_t Serial_GetPacket (SerialBuffer_t ** payloadReceived)
Attempts to get a serial packet.
Parameters
out payloadReceived - Pointer to the received serial payload.
Return values
SerialStatus_SUCCESS if a valid packet was received.
SerialStatus_RECEIVE_DISABLED if not in receive mode.
SerialStatus_NO_PACKET if no packet was available.
Definition at line 310 of file Serial.c.
Referenced by TestProtocol_HandleReceivedPacket().
void Serial_Init (void)
Initializes the received serial payload buffer and the UART.
Definition at line 132 of file Serial.c.
Referenced by main().
void Serial_Open (SerialMode_t mode)
Opens the serial interface.
Parameters
in mode - Selected mode for the serial interface.
Definition at line 146 of file Serial.c.
Referenced by main().
void Serial_ProcessReceivedBytes (void)
Processes bytes received from the UART, searching for a valid packet.
Definition at line 182 of file Serial.c.
Referenced by main().
SerialStatus_t Serial_SendPacket (const SerialBuffer_t * payloadToTransmit)
Attempts to send a serial packet.
Parameters
in payloadToTransmit - Pointer to the serial payload to transmit.
Return values
SerialStatus_SUCCESS if packet sent successfully.
SerialStatus_TX_BUFFER_FULL if transmit buffer is full.
Definition at line 345 of file Serial.c.
Referenced by _HandleHumanAccCommand(), _HandleHumanAdc1Command(), _HandleHumanBarcCommand(), _HandleHumanBarCommand(), _HandleHumanEncoderCommand(), _HandleHumanGpiCommand(), _HandleHumanGyroCommand(), _HandleHumanMagCommand(), _HandleHumanRfCommand(), _HandleHumanVerCommand(), _SendAckHuman(), and _SendNakHuman().
void Serial_SendString (const char_t * string)
Attempts to send a string as a human-readable serial packet. If a UART error occurs, the entire packet may not be written.
Parameters
in string - Pointer to the string to transmit.
Definition at line 415 of file Serial.c.
Referenced by _PrintResetReason(), EncControl_ReadEnc(), and GyroControl_ReadGyro().
void Serial_SendString3Numbers (const char_t * string, uint16_t number1, uint16_t number2, uint16_t number3)
Attempts to send a string and number as a human-readable serial packet. If a UART error occurs, the entire packet may not be written. The number will always be printed at the end of the string in hex format.
Parameters
in string - Pointer to the string to transmit.
in number1 - number to print at the end of the string.
in number2 - number to print at the end of the string.
in number3 - number to print at the end of the string.
Definition at line 572 of file Serial.c.
Referenced by AccControl_ReadAcc(), BarometerControl_ReadBar(), GyroControl_ReadGyro(), and MagControl_ReadMag().
void Serial_SendStringBlocking (const char_t * string)
Attempts to send a string as a human-readable serial packet and blocks until the send is complete.
Parameters
in string - Pointer to the string to transmit.
Definition at line 679 of file Serial.c.
void Serial_SendStringBlockingNoAssert (const char_t * string)
Attempts to send a string as a human-readable serial packet and blocks until the send is complete.
Note
This function does not use an assert for safety checking so that it can be used in the assert handler.
Parameters
in string - Pointer to the string to transmit.
Definition at line 708 of file Serial.c.
Referenced by Assert().
void Serial_SendStringNumber (const char_t * string, uint16_t number)
Attempts to send a string and number as a human-readable serial packet. If a UART error occurs, the entire packet may not be written. The number will always be printed at the end of the string in hex format.
Parameters
in string - Pointer to the string to transmit.
in number - number to print at the end of the string.
Definition at line 456 of file Serial.c.
Referenced by _AmbientLightDataCallback(), _Analog7DataCallback(), _Analog8DataCallback(), _Analog9DataCallback(), _BatteryVoltageDataCallback(), _EcgAddToDataBuffer(), _ForceGaugeDataCallback(), _HighGainDataCallback(), _MicrophoneDataCallback(), _ReadPins(), _thermometerDataCallBack(), AdcManager_ProcessConversion(), CommProtocol_RxHandler(), ConMan_SetFixedConfig(), EncControl_ReadEnc(), SelfTest_Process(), and UiManager_PlaySequence().
void Serial_SendStringNumberU32 (const char_t * string, uint32_t number)
Attempts to send a string and number as a human-readable serial packet. If a UART error occurs, the entire packet may not be written. The number will always be printed at the end of the string in hex format.
Parameters
in string - Pointer to the string to transmit.
in number - number to print at the end of the string.
Definition at line 508 of file Serial.c.
Referenced by _thermometerDataCallBack().
Variable Documentation
SerialMode_t _currentMode = SerialMode_TRANSMIT_ONLY [static]
Tracks the current mode of the serial interface
Definition at line 113 of file Serial.c.
Referenced by Serial_GetPacket(), Serial_Open(), and Serial_ProcessReceivedBytes().
uint16_t _currentRxIndex = SERIAL_SOP_INDEX [static]
Tracks the current index of a packet being received
Definition at line 116 of file Serial.c.
Referenced by Serial_Open(), and Serial_ProcessReceivedBytes().
const uint8_t _footerHuman[FOOTER_HUMAN_LENGTH] = {0x0Au, SERIAL_EOP} [static]
Footer used for human-readable packets. While the protocol does not require the carriage return (0x0D), adding it ensures that human-readable packets display correctly on a terminal.
Definition at line 103 of file Serial.c.
Referenced by Serial_SendPacket(), Serial_SendString(), Serial_SendString3Numbers(), Serial_SendStringBlocking(), Serial_SendStringBlockingNoAssert(), Serial_SendStringNumber(), and Serial_SendStringNumberU32().
bool _isSerialInterfaceOpen = false [static]
Tracks if the serial interface is open
Definition at line 110 of file Serial.c.
Referenced by Serial_Close(), Serial_Open(), Serial_ProcessReceivedBytes(), Serial_SendPacket(), Serial_SendString(), Serial_SendString3Numbers(), Serial_SendStringBlocking(), Serial_SendStringNumber(), and Serial_SendStringNumberU32().
SerialBuffer_t _serialPayloadRx [static]
Stores the most recently received serial payload.
Definition at line 107 of file Serial.c.
Referenced by Serial_GetPacket().