SpiSlave.h File Reference
SPI module using this device as a SPI slave.
Enumerations
enum SpiSlaveError_t {
*
SpiSlaveError_OK,
*
SpiSlaveError_BUFFER_IN_USE,
*
SpiSlaveError_PACKET_TOO_LONG,
*
SpiSlaveError_NO_PACKET,
*
SpiSlaveError_WRITE_IN_PROGRESS
 }
Functions
void SpiSlave_Init (void)
SpiSlaveError_t SpiSlave_LoadPacket (uint16_t packetLength, const uint8_t packet[])
void SpiSlave_UnloadPacket (void)
bool SpiSlave_PacketLoaded (void)
SpiSlaveError_t SpiSlave_ReadPacket (uint16_t packetLength, uint8_t packet[])
void SpiSlave_FlushRead (void)
bool SpiSlave_PacketAvailable (void)
Detailed Description
SPI module using this device as a SPI slave. Project 1814 IOLab Remote Sensor Application
Description This module provides functions to configure the SPI port to be a SPI slave device.
Definition in file SpiSlave.h.
Enumeration Type Documentation
enum SpiSlaveError_t
Enumeration type for SPI slave module errors.
Definition at line 27 of file SpiSlave.h.
Function Documentation
void SpiSlave_FlushRead (void)
Disarms the SPI port from accepting new data. Disables the DMA so that received bytes won't be transferred into the memory.
Definition at line 223 of file SpiSlave.c.
Referenced by CommProtocol_RxHandler().
void SpiSlave_Init (void)
Initialize the SPI slave module.
Definition at line 79 of file SpiSlave.c.
Referenced by main().
SpiSlaveError_t SpiSlave_LoadPacket (uint16_t packetLength, const uint8_t packet[])
Transmit a packet over the SPI slave port. The data will not be transmitted until the SPI master device clocks the data out. This function will store the pointer and size of the packet to be transmitted when the master asks for the data.
Parameters
in packetLength - number of bytes in packet.
in packet - packet to transmit.
Return values
SpiSlaveError_OK - Success
SpiSlaveError_BUFFER_IN_USE - a packet is already waiting to be transmitted.
Note
The packet must be > 1 bytes (at least 2 bytes) to transmit.
Definition at line 129 of file SpiSlave.c.
Referenced by CommProtocol_Init(), and CommProtocol_TxHandler().
bool SpiSlave_PacketAvailable (void)
Determine if a packet is available.
Returns
True if a packet is available, otherwise false.
Definition at line 235 of file SpiSlave.c.
bool SpiSlave_PacketLoaded (void)
Disarms the SPI port transmit by disabling the DMA
Definition at line 174 of file SpiSlave.c.
SpiSlaveError_t SpiSlave_ReadPacket (uint16_t packetLength, uint8_t packet[])
Read a packet received over the SPI slave port into a buffer when it arrives. The buffer will be used to store the received SPI information after it arrives. The function will store the pointer and size to the buffer and return but the SpiSlave_PacketAvailable will tell when the data in the buffer becomes valid.
Parameters
in packetLength - number of bytes in packet to receive.
out packet - Received packet.
Return values
SpiSlaveError_OK - Success
SpiSlaveError_BUFFER_IN_USE - There is already a read buffer waiting to be filled.
Definition at line 192 of file SpiSlave.c.
Referenced by CommProtocol_Init(), and CommProtocol_RxHandler().
void SpiSlave_UnloadPacket (void)
Disarms the SPI port transmit by disabling the DMA
Definition at line 163 of file SpiSlave.c.
Referenced by CommProtocol_TxHandler().