SpiMaster.h File Reference
SPI Master Module.
Functions
void Spi_Init (void)
void Spi_WriteRegister (uint8_t writeRegister, uint8_t dataByte)
void Spi_ReadRegister (uint8_t readRegister, uint8_t *dataByte)
void Spi_WriteByte (uint8_t byte)
Detailed Description
SPI Master Module. Project 1814 IOLab Remote Sensor Application
Description The SPI master module controls the SPI port and interfaces to other SPI slave devices.
Definition in file SpiMaster.h.
Function Documentation
void Spi_Init (void)
Initialize the SPI hardware.
Definition at line 47 of file SpiMaster.c.
Referenced by main().
void Spi_ReadRegister (uint8_t readRegister, uint8_t * dataByte)
Reads a register via SPI.
Parameters
in readRegister - Selected control register.
in dataByte - Pointer to where received byte should be stored.
Definition at line 132 of file SpiMaster.c.
Referenced by _BarReadMultipleRegisters(), _BarReadRegister(), _GyroReadMultipleRegisters(), and _GyroReadSingleRegister().
void Spi_WriteByte (uint8_t byte)
Reads a byte via SPI.
Parameters
in byte - The value written out the spi port
Definition at line 167 of file SpiMaster.c.
Referenced by _BarReadMultipleRegisters(), and DacSetVoltage().
void Spi_WriteRegister (uint8_t writeRegister, uint8_t dataByte)
Transmits a register address and value via SPI.
Parameters
in writeRegister - Selected control register.
in dataByte - Data byte to send out over SPI.
Note: This assumes that the SPI port has been configured as a MASTER device.
Definition at line 96 of file SpiMaster.c.
Referenced by _BarWriteRegister(), and _GyroWriteRegister().