SpiSlave.c File Reference
SPI Slave Module.
#include <ProjectTypes.h>
*
#include `SpiSlave.h`
*
#include <Device.h>
*
#include <Dma.h>
*
#include <Assert.h>
*
#include <Gpio.h>
*
#include <Board.h>
*
#include <EventQueue.h>
*
Functions
static void _HandleDmaRxIsr (void)
static void _HandleDmaTxIsr (void)
void SpiSlave_Init (void)
SpiSlaveError_t SpiSlave_LoadPacket (uint16_t packetLength, const uint8_t packet[])
void SpiSlave_UnloadPacket (void)
bool SpiSlave_PacketLoaded (void)
SpiSlaveError_t SpiSlave_ReadPacket (uint16_t packetLength, uint8_t packet[])
void SpiSlave_FlushRead (void)
bool SpiSlave_PacketAvailable (void)
Variables
static const DmaConfig_t _dmaConfigRx
static const DmaChannel_t _dmaChannelRx = DmaChannel_0
static const DmaConfig_t _dmaConfigTx
static const DmaChannel_t _dmaChannelTx = DmaChannel_1
static volatile bool _bufferTxInUse = false
static volatile bool _bufferTxComplete = false
static volatile bool _bufferRxInUse = false
static volatile bool _bufferRxComplete = false
static volatile bool _initialized = false
Detailed Description
SPI Slave Module. Project 1814 IOLab Remote Sensor Application
Description This module is used when this device is a SPI slave device. The functions and macros defined in the module can be used to communicate with a SPI master device.
Definition in file SpiSlave.c.
Function Documentation
static void _HandleDmaRxIsr (void) [static]
Handles the interrupt generated by the DMA when the receive transfer is complete.
Definition at line 244 of file SpiSlave.c.
Referenced by SpiSlave_Init().
static void _HandleDmaTxIsr (void) [static]
Handles the interrupt generated by the DMA when the transmit transfer is complete.
Definition at line 256 of file SpiSlave.c.
Referenced by SpiSlave_Init().
void SpiSlave_FlushRead (void)
Disarms the SPI port from accepting new data. Disables the DMA so that received bytes won't be transferred into the memory.
Definition at line 223 of file SpiSlave.c.
Referenced by CommProtocol_RxHandler().
void SpiSlave_Init (void)
Initialize the SPI slave module.
Definition at line 79 of file SpiSlave.c.
Referenced by main().
SpiSlaveError_t SpiSlave_LoadPacket (uint16_t packetLength, const uint8_t packet[])
Transmit a packet over the SPI slave port. The data will not be transmitted until the SPI master device clocks the data out. This function will store the pointer and size of the packet to be transmitted when the master asks for the data.
Parameters
in packetLength - number of bytes in packet.
in packet - packet to transmit.
Return values
SpiSlaveError_OK - Success
SpiSlaveError_BUFFER_IN_USE - a packet is already waiting to be transmitted.
Note
The packet must be > 1 bytes (at least 2 bytes) to transmit.
Definition at line 129 of file SpiSlave.c.
Referenced by CommProtocol_Init(), and CommProtocol_TxHandler().
bool SpiSlave_PacketAvailable (void)
Determine if a packet is available.
Returns
True if a packet is available, otherwise false.
Definition at line 235 of file SpiSlave.c.
bool SpiSlave_PacketLoaded (void)
Disarms the SPI port transmit by disabling the DMA
Definition at line 174 of file SpiSlave.c.
SpiSlaveError_t SpiSlave_ReadPacket (uint16_t packetLength, uint8_t packet[])
Read a packet received over the SPI slave port into a buffer when it arrives. The buffer will be used to store the received SPI information after it arrives. The function will store the pointer and size to the buffer and return but the SpiSlave_PacketAvailable will tell when the data in the buffer becomes valid.
Parameters
in packetLength - number of bytes in packet to receive.
out packet - Received packet.
Return values
SpiSlaveError_OK - Success
SpiSlaveError_BUFFER_IN_USE - There is already a read buffer waiting to be filled.
Definition at line 192 of file SpiSlave.c.
Referenced by CommProtocol_Init(), and CommProtocol_RxHandler().
void SpiSlave_UnloadPacket (void)
Disarms the SPI port transmit by disabling the DMA
Definition at line 163 of file SpiSlave.c.
Referenced by CommProtocol_TxHandler().
Variable Documentation
volatile bool _bufferRxComplete = false [static]
Tracks if the DMA is finished with the receive buffer or not
Definition at line 66 of file SpiSlave.c.
Referenced by _HandleDmaRxIsr(), SpiSlave_FlushRead(), SpiSlave_PacketAvailable(), and SpiSlave_ReadPacket().
volatile bool _bufferRxInUse = false [static]
Tracks if the receive buffer is being used
Definition at line 64 of file SpiSlave.c.
Referenced by SpiSlave_FlushRead(), SpiSlave_PacketAvailable(), and SpiSlave_ReadPacket().
volatile bool _bufferTxComplete = false [static]
Tracks if the DMA is finished with transmit buffer or not
Definition at line 61 of file SpiSlave.c.
Referenced by _HandleDmaTxIsr(), SpiSlave_LoadPacket(), SpiSlave_PacketLoaded(), and SpiSlave_UnloadPacket().
volatile bool _bufferTxInUse = false [static]
Tracks if the transmit buffer is being used
Definition at line 59 of file SpiSlave.c.
Referenced by SpiSlave_LoadPacket(), SpiSlave_PacketLoaded(), and SpiSlave_UnloadPacket().
const DmaConfig_t _dmaConfigRx [static]
Initial value:
= { DmaMode_SINGLE,
                                          DmaTrigger_UCB1RXIFG,
                                          DmaIncr_NONE,
                                          DmaIncr_INCREMENT,
                                          DmaBitWidth_BYTE,
                                          DmaBitWidth_BYTE
                                        }
Defines the settings for using the DMA to receive data
Definition at line 38 of file SpiSlave.c.
const DmaConfig_t _dmaConfigTx [static]
Initial value:
= { DmaMode_SINGLE,
                                          DmaTrigger_UCB1TXIFG,
                                          DmaIncr_INCREMENT,
                                          DmaIncr_NONE,
                                          DmaBitWidth_BYTE,
                                          DmaBitWidth_BYTE
                                         }
Defines the settings for using the DMA to transmit data
Definition at line 48 of file SpiSlave.c.
volatile bool _initialized = false [static]
Tracks if the module has been initialized
Definition at line 69 of file SpiSlave.c.