SpiMaster.c File Reference
SPI Master Module.
#include <ProjectTypes.h>
*
#include `SpiMaster.h`
*
#include <Assert.h>
*
#include <Debug.h>
*
#include <Serial.h>
*
#include <Gpio.h>
*
#include <Board.h>
*
#include <Device.h>
*
Macros
#define READ_BIT (0x80u)
Functions
void Spi_Init (void)
void Spi_WriteRegister (uint8_t writeRegister, uint8_t dataByte)
void Spi_ReadRegister (uint8_t readRegister, uint8_t *dataByte)
void Spi_WriteByte (uint8_t byte)
Variables
static volatile bool _initialized = false
Detailed Description
SPI Master Module. Project 1814 IOLab Remote Sensor Application
Description The SPI master module controls the SPI port and interfaces to other SPI slave devices.
Definition in file SpiMaster.c.
Macro Definition Documentation
#define READ_BIT (0x80u)
Bit assignment in the transmit register for reading a byte
Definition at line 37 of file SpiMaster.c.
Referenced by Spi_ReadRegister().
Function Documentation
void Spi_Init (void)
Initialize the SPI hardware.
Definition at line 47 of file SpiMaster.c.
Referenced by main().
void Spi_ReadRegister (uint8_t readRegister, uint8_t * dataByte)
Reads a register via SPI.
Parameters
in readRegister - Selected control register.
in dataByte - Pointer to where received byte should be stored.
Definition at line 132 of file SpiMaster.c.
Referenced by _BarReadMultipleRegisters(), _BarReadRegister(), _GyroReadMultipleRegisters(), and _GyroReadSingleRegister().
void Spi_WriteByte (uint8_t byte)
Reads a byte via SPI.
Parameters
in byte - The value written out the spi port
Definition at line 167 of file SpiMaster.c.
Referenced by _BarReadMultipleRegisters(), and DacSetVoltage().
void Spi_WriteRegister (uint8_t writeRegister, uint8_t dataByte)
Transmits a register address and value via SPI.
Parameters
in writeRegister - Selected control register.
in dataByte - Data byte to send out over SPI.
Note: This assumes that the SPI port has been configured as a MASTER device.
Definition at line 96 of file SpiMaster.c.
Referenced by _BarWriteRegister(), and _GyroWriteRegister().
Variable Documentation
volatile bool _initialized = false [static]
Tracks if the module is initialized
Definition at line 41 of file SpiMaster.c.