StateMachine.c File Reference
State logic handling.
#include <ProjectTypes.h>
*
#include `StateMachine.h`
*
#include <EventQueue.h>
*
#include <CommProtocol.h>
*
#include <TestProtocol.h>
*
#include <AccelerometerControl.h>
*
#include <MagnetometerControl.h>
*
#include <GyroscopeControl.h>
*
#include <PushButtonControl.h>
*
#include <LedControl.h>
*
#include <TimerTick.h>
*
#include <AdcManager.h>
*
#include <SelfTest.h>
*
#include <System.h>
*
#include <Debug.h>
*
Macros
#define POWER_OFF_MSEC (1000u)
Enumerations
enum State_t {
*
State_INVALID = -1,
*
State_FIRST = 0,
*
State_RUN = State_FIRST,
*
State_SELF_TEST,
*
State_LAST
 }
Functions
static bool _ProcessEvents_RUN (Event_t event)
static bool _ProcessEvents_SELF_TEST (Event_t event)
static bool _ProcessEvents_DEFAULT (Event_t event)
static __inline void _UnlatchPower (void)
static void _HandlePowerOffRequest (void)
void StateMachine_ProcessEvents (void)
Variables
static State_t _currentState = State_RUN
static bool _buttonOnePressed = false
static TickTimeoutHandle_t _powerOffTimeoutHandle
static bool _powerOffTimeoutInUse = false
Detailed Description
State logic handling. Project IOLabRemoteSensorApplication
Description Handles the state logic and transition between states.
Definition in file StateMachine.c.
Macro Definition Documentation
#define POWER_OFF_MSEC (1000u)
The number of milliseconds that the button must be pressed before the power will be shut off.
Definition at line 53 of file StateMachine.c.
Referenced by _ProcessEvents_DEFAULT().
Enumeration Type Documentation
enum State_t
Possible states for the sensor micro to be in
Definition at line 41 of file StateMachine.c.
Function Documentation
static void _HandlePowerOffRequest (void) [static]
Handles the request for power off based on the power button.
Definition at line 282 of file StateMachine.c.
Referenced by _ProcessEvents_DEFAULT().
static bool _ProcessEvents_DEFAULT (Event_t event) [static]
Process events default handler. Processes events the same, regardless of state.
Parameters
in event - Pending event
Returns
True if the event should be further processed, false otherwise
Definition at line 191 of file StateMachine.c.
Referenced by _ProcessEvents_RUN(), _ProcessEvents_SELF_TEST(), and StateMachine_ProcessEvents().
static bool _ProcessEvents_RUN (Event_t event) [static]
Process events while in RUN state
Parameters
in event - Pending event
Returns
True if the event should be further processed, false otherwise
Definition at line 119 of file StateMachine.c.
Referenced by StateMachine_ProcessEvents().
static bool _ProcessEvents_SELF_TEST (Event_t event) [static]
Process events while in SELF_TEST state
Parameters
in event - Pending event
Returns
True if the event should be further processed, false otherwise
Definition at line 156 of file StateMachine.c.
Referenced by StateMachine_ProcessEvents().
static __inline void _UnlatchPower (void) [static]
Should be called to turn the system off. Turns power off by unlatching the power supply. The system might still remain on after this is called if the user continues holding the power button.
Definition at line 273 of file StateMachine.c.
Referenced by _HandlePowerOffRequest(), _ProcessEvents_RUN(), and _ProcessEvents_SELF_TEST().
void StateMachine_ProcessEvents (void)
State machine logic that will process all the events from the event queue and manage the states of the system
Definition at line 79 of file StateMachine.c.
Referenced by main().
Variable Documentation
bool _buttonOnePressed = false [static]
Stores if button one has been pressed or not. This makes sure that the button has been pressed before it was released, and was not pressed before power on (in which case the firmware wouldn't see the press event) then released.
Definition at line 61 of file StateMachine.c.
Referenced by _ProcessEvents_DEFAULT(), and _ProcessEvents_RUN().
State_t _currentState = State_RUN [static]
Current system state
Definition at line 56 of file StateMachine.c.
Referenced by _ProcessEvents_RUN(), and StateMachine_ProcessEvents().
TickTimeoutHandle_t _powerOffTimeoutHandle [static]
Handle for the system power off timeout
Definition at line 64 of file StateMachine.c.
Referenced by _ProcessEvents_DEFAULT().
bool _powerOffTimeoutInUse = false [static]
Tracks if the power off timeout is in use
Definition at line 66 of file StateMachine.c.
Referenced by _ProcessEvents_DEFAULT().