System.h File Reference
System module driver.
Enumerations
enum SystemResetReason_t {
*
SystemResetReason_INVALID = 0x00u,
*
SystemResetReason_BROWNOUT = 0x02u,
*
SystemResetReason_RESET_PIN = 0x04u,
*
SystemResetReason_PMM_SW_BOR = 0x06u,
*
SystemResetReason_WAKEUP_FROM_LPMXd5 = 0x08u,
*
SystemResetReason_SECURITY_VIOLATION = 0x0Au,
*
SystemResetReason_SVSL = 0x0Cu,
*
SystemResetReason_SVSH = 0x0Eu,
*
SystemResetReason_SVML_OVP = 0x10u,
*
SystemResetReason_SVMH_OVP = 0x12u,
*
SystemResetReason_PMM_SW_POR = 0x14u,
*
SystemResetReason_WATCHDOG = 0x16u,
*
SystemResetReason_WDT_PASSWORD_VIOLATION = 0x18u,
*
SystemResetReason_FLASH_PASSWORD_VIOLATION = 0x1Au,
*
SystemResetReason_PLL_UNLOCK = 0x1Cu,
*
SystemResetReason_PERF = 0x1Eu,
*
SystemResetReason_PMM_PASSWORD_VIOLATION = 0x20u
 }
Functions
void System_Init (void)
void System_PowerOn (void)
void System_PowerOff (void)
SystemResetReason_t System_GetResetReason (void)
const char_t * System_ConvertResetReasonToString (SystemResetReason_t reason)
Detailed Description
System module driver. Project 1814 IOLab Remote Sensor Application
Description This header file provides functions to configure the system control module on MSP430x5xx microcontrollers.
Definition in file System.h.
Enumeration Type Documentation
enum SystemResetReason_t
Possible system reset reasons
Definition at line 27 of file System.h.
Function Documentation
const char_t* System_ConvertResetReasonToString (SystemResetReason_t reason)
Convert a reset reason to a human-readable string.
Parameters
in reason - Reset reason to convert.
Returns
Pointer to the string describing the reset reason.
Definition at line 106 of file System.c.
Referenced by _PrintResetReason().
SystemResetReason_t System_GetResetReason (void)
Returns
The reason for the most recent reset of the micro.
Definition at line 88 of file System.c.
Referenced by main().
void System_Init (void)
Initializes the system by enabling a few safety features.
Definition at line 43 of file System.c.
Referenced by Board_Init().
void System_PowerOff (void)
Disables the power latch for the system.
Definition at line 80 of file System.c.
Referenced by _ProcessEvents_DEFAULT().
void System_PowerOn (void)
Enables the power latch for the system.
Definition at line 72 of file System.c.