System.c File Reference
System module.
#include <ProjectTypes.h>
*
#include <Device.h>
*
#include `System.h`
*
#include <Board.h>
*
#include <Gpio.h>
*
#include <Assert.h>
*
Macros
#define DISABLE_BSL
#define NUM_RESET_REASON_STRINGS (17u)
Functions
void System_Init (void)
void System_PowerOn (void)
void System_PowerOff (void)
SystemResetReason_t System_GetResetReason (void)
const char_t * System_ConvertResetReasonToString (SystemResetReason_t reason)
Detailed Description
System module. Project 1814 IOLab Remote Sensor Application
Description This file provides functions to configure the system control module on MSP430x5xx microcontrollers.
Definition in file System.c.
Macro Definition Documentation
#define DISABLE_BSL
This will disable the boot strap loader. Some instances might want the bootstrap loader enabled so that the memory can be reprogrammed over the BSL
Definition at line 35 of file System.c.
Function Documentation
const char_t* System_ConvertResetReasonToString (SystemResetReason_t reason)
Convert a reset reason to a human-readable string.
Parameters
in reason - Reset reason to convert.
Returns
Pointer to the string describing the reset reason.
Definition at line 106 of file System.c.
Referenced by _PrintResetReason().
SystemResetReason_t System_GetResetReason (void)
Returns
The reason for the most recent reset of the micro.
Definition at line 88 of file System.c.
Referenced by main().
void System_Init (void)
Initializes the system by enabling a few safety features.
Definition at line 43 of file System.c.
Referenced by Board_Init().
void System_PowerOff (void)
Disables the power latch for the system.
Definition at line 80 of file System.c.
Referenced by _ProcessEvents_DEFAULT().
void System_PowerOn (void)
Enables the power latch for the system.
Definition at line 72 of file System.c.