TestProtocol.c File Reference
Manages the self-test protocol.
#include <ProjectTypes.h>
*
#include `TestProtocol.h`
*
#include <string.h>
*
#include <Assert.h>
*
#include <Debug.h>
*
#include <Serial.h>
*
#include <Conversion.h>
*
#include <Gpio.h>
*
#include <Pwm.h>
*
#include <Barometer.h>
*
#include <Accelerometer.h>
*
#include <Magnetometer.h>
*
#include <Gyroscope.h>
*
#include <Encoder.h>
*
#include <DAC.h>
*
#include <AdcManager.h>
*
#include <Ultrasound.h>
*
#include <Version.h>
*
#include <CommProtocol.h>
*
#include <stdio.h>
*
#include <Interrupt.h>
*
#include <Device.h>
*
#include <Board.h>
*
#include <Watchdog.h>
*
#include <Clock.h>
*
Data Structures
struct HumanCommand_t
Macros
#define HUMAN_PARAM_SEPARATORS (` _\r\n`)
#define NUM_HUMAN_COMMANDS (17u)
#define HUMAN_COMMAND_MAX_LENGTH (4u)
#define HELP_STRING_MAX_LENGTH (25u)
#define PORT_J_UINT (99u)
#define PORT_U_UINT (98u)
#define PORT_J_UINT (99u)
#define PORT_U_UINT (98u)
#define NUM_ENC_ITEMS (2u)
#define NUMBER_ADC_USED 1u
Enumerations
enum NakErrorCode_t {
*
NakErrorCode_NO_COMMAND = 1,
*
NakErrorCode_INVALID_COMMAND = 2,
*
NakErrorCode_INVALID_DATA_LENGTH = 3,
*
NakErrorCode_INVALID_DATA = 4,
*
NakErrorCode_CANNOT_PERFORM = 5,
*
NakErrorCode_ERROR = 6
 }
Functions
static void _HandleHumanPackets (SerialBuffer_t *packetReceived)
static void _HandleHumanGpoCommand (void)
static void _HandleHumanGpiCommand (void)
static void _HandleHumanAdc1Command (void)
static void _HandleHumanAdcCommand (void)
static void _HandleHumanPwmCommand (void)
static void _HandleHumanAccCommand (void)
static void _HandleHumanMagCommand (void)
static void _HandleHumanBarcCommand (void)
static void _HandleHumanBarCommand (void)
static void _HandleHumanGyroCommand (void)
static void _HandleHumanEncoderCommand (void)
static void _HandleHumanDacCommand (void)
static void _HandleHumanUsGoCommand (void)
static void _HandleHumanStopCommand (void)
static void _HandleHumanVerCommand (void)
static void _HandleHumanRfCommand (void)
static void _HandleHumanBslCommand (void)
static void _SendAckHuman (void)
static void _SendNakHuman (NakErrorCode_t errorCode)
void TestProtocol_Init (void)
void TestProtocol_HandleReceivedPacket (void)
Variables
static SerialBuffer_t _packetTx
static const HumanCommand_t _humanCommands [NUM_HUMAN_COMMANDS]
Detailed Description
Manages the self-test protocol. Project 1814 IOLab Remote Sensor Application
Description The test protocol module manages the tests that are performed using a PC via the serial interface.
Definition in file TestProtocol.c.
Macro Definition Documentation
#define HELP_STRING_MAX_LENGTH (25u)
Maximum length of a command help string
Definition at line 90 of file TestProtocol.c.
#define HUMAN_COMMAND_MAX_LENGTH (4u)
Maximum length of a human command string
Definition at line 87 of file TestProtocol.c.
Referenced by _HandleHumanPackets().
#define HUMAN_PARAM_SEPARATORS (` _\r\n`)
Defines the characters used to separate parameters in human-readable commands.
Definition at line 81 of file TestProtocol.c.
Referenced by _HandleHumanAdc1Command(), _HandleHumanDacCommand(), _HandleHumanGpiCommand(), _HandleHumanGpoCommand(), _HandleHumanPackets(), and _HandleHumanPwmCommand().
#define NUM_HUMAN_COMMANDS (17u)
Number of defined human-readable commands
Definition at line 84 of file TestProtocol.c.
Referenced by _HandleHumanPackets().
Enumeration Type Documentation
enum NakErrorCode_t
Possible NAK error codes. The values are fixed to match the protocol document.
Definition at line 55 of file TestProtocol.c.
Function Documentation
static void _HandleHumanAccCommand (void) [static]
Enables the accelerometer and starts taking samples of the accelerometer.
Definition at line 606 of file TestProtocol.c.
static void _HandleHumanAdc1Command (void) [static]
Sets a selected analog input and takes a single sample of that ADC channel.
Definition at line 465 of file TestProtocol.c.
static void _HandleHumanAdcCommand (void) [static]
Sets a selected analog input and takes repeating samples of that ADC channel
Definition at line 517 of file TestProtocol.c.
static void _HandleHumanBarcCommand (void) [static]
Enables the barometer and reads the barometer coefficients.
Definition at line 669 of file TestProtocol.c.
static void _HandleHumanBarCommand (void) [static]
Enables the barometer and starts taking samples of the barometer.
Definition at line 696 of file TestProtocol.c.
static void _HandleHumanBslCommand (void) [static]
Puts the device in the serial bootloader mode
Definition at line 985 of file TestProtocol.c.
static void _HandleHumanDacCommand (void) [static]
Enables the DAC and sets voltage.
Definition at line 825 of file TestProtocol.c.
static void _HandleHumanEncoderCommand (void) [static]
Enables the gyroscope and starts taking samples of the gyroscope.
Definition at line 750 of file TestProtocol.c.
static void _HandleHumanGpiCommand (void) [static]
Sets a selected port and pin to a digital input and reads the logic level of that pin.
Definition at line 348 of file TestProtocol.c.
static void _HandleHumanGpoCommand (void) [static]
Sets a selected port and pin to a digital output and sets the logic level of the output.
Definition at line 229 of file TestProtocol.c.
static void _HandleHumanGyroCommand (void) [static]
Enables the gyroscope and starts taking samples of the gyroscope.
Definition at line 723 of file TestProtocol.c.
static void _HandleHumanMagCommand (void) [static]
Enables the magnetometer and starts taking samples of the magnetometer.
Definition at line 637 of file TestProtocol.c.
static void _HandleHumanPackets (SerialBuffer_t * packetReceived) [static]
Handles any of the human-readable packets received.
Parameters
in packetReceived - Pointer to the received packet.
Definition at line 180 of file TestProtocol.c.
Referenced by TestProtocol_HandleReceivedPacket().
static void _HandleHumanPwmCommand (void) [static]
Sets a selected PWM output and enables it
Definition at line 526 of file TestProtocol.c.
static void _HandleHumanRfCommand (void) [static]
Prints the current RF information
Definition at line 922 of file TestProtocol.c.
static void _HandleHumanStopCommand (void) [static]
Stops the currently running command.
Definition at line 882 of file TestProtocol.c.
static void _HandleHumanVerCommand (void) [static]
Prints the current version numbers of the system
Definition at line 891 of file TestProtocol.c.
static void _SendAckHuman (void) [static]
Attempts to send a human-readable acknowledgement packet. An assert will occur if the send fails.
Definition at line 1009 of file TestProtocol.c.
Referenced by _HandleHumanAccCommand(), _HandleHumanAdc1Command(), _HandleHumanBarcCommand(), _HandleHumanBarCommand(), _HandleHumanDacCommand(), _HandleHumanEncoderCommand(), _HandleHumanGpiCommand(), _HandleHumanGpoCommand(), _HandleHumanGyroCommand(), _HandleHumanMagCommand(), _HandleHumanPwmCommand(), _HandleHumanRfCommand(), and _HandleHumanVerCommand().
static void _SendNakHuman (NakErrorCode_t errorCode) [static]
Attempts to send a human-readable negative-acknowledgement packet with the given error code. An assert will occur if the send fails.
Parameters
in errorCode - Error code to include in the packet.
Definition at line 1032 of file TestProtocol.c.
Referenced by _HandleHumanAdc1Command(), _HandleHumanAdcCommand(), _HandleHumanDacCommand(), _HandleHumanGpiCommand(), _HandleHumanGpoCommand(), _HandleHumanPackets(), _HandleHumanPwmCommand(), and _HandleHumanStopCommand().
void TestProtocol_HandleReceivedPacket (void)
Directs any received packets to the correct handler.
Definition at line 158 of file TestProtocol.c.
Referenced by _ProcessEvents_DEFAULT().
void TestProtocol_Init (void)
Initializes all the variables and settings for the test protocol module.
Definition at line 150 of file TestProtocol.c.
Referenced by main().
Variable Documentation
const HumanCommand_t _humanCommands[NUM_HUMAN_COMMANDS] [static]
Initial value:
=
{
    {"gpo", " gpo [port] [pin] [1|0]", &_HandleHumanGpoCommand},
    {"gpi", " gpi [port] [pin]", &_HandleHumanGpiCommand},
    {"adc1", " adc1 [channel]", &_HandleHumanAdc1Command},
    {"adc", " adc [channel]", &_HandleHumanAdcCommand},
    {"pwm", " pwm [chan] [%] [f]", &_HandleHumanPwmCommand},
    {"acc", " acc", &_HandleHumanAccCommand},
    {"mag", " mag", &_HandleHumanMagCommand},
    {"barc", " barc", &_HandleHumanBarcCommand},
    {"bar", " bar", &_HandleHumanBarCommand},
    {"gyro", " gyro", & _HandleHumanGyroCommand},
    {"enc", " enc", &_HandleHumanEncoderCommand},
    {"dac", " dac [d]", & _HandleHumanDacCommand},
    {"ugo", " ugo", & _HandleHumanUsGoCommand},
    {"stop", " stop", &_HandleHumanStopCommand},
    {"ver", " ver", &_HandleHumanVerCommand},
    {"rf", " rf", &_HandleHumanRfCommand},
    {"bsl", "bsl", &_HandleHumanBslCommand}
}
Look-up table for human-readable commands
Definition at line 126 of file TestProtocol.c.
SerialBuffer_t _packetTx [static]
Stores the most recently sent packet
Definition at line 95 of file TestProtocol.c.