ThermometerControl.h File Reference
Controls the Thermometer driver.
Functions
void ThermometerControl_Init (void)
void ThermometerControl_SetConfig (uint8_t value)
void ThermometerControl_ReadCalibration (uint16_t maxCalibrationLength, uint16_t *actualCalibrationLength, uint8_t calibration[])
Detailed Description
Controls the Thermometer driver. Project 1814 IOLab Remote Sensor Application
Description Controls the Thermometer driver and controls the configuration for it.
Definition in file ThermometerControl.h.
Function Documentation
void ThermometerControl_Init (void)
Initializes the thermometer controller.
Definition at line 95 of file ThermometerControl.c.
Referenced by ConMan_Init().
void ThermometerControl_ReadCalibration (uint16_t maxCalibrationLength, uint16_t * actualCalibrationLength, uint8_t calibration[])
Reads the calibration values from the thermometer.
Parameters
in maxCalibrationLength - the maximum number of bytes allocated for calibration[]
out actualCalibrationLength - the number of bytes of calibration data placed in calibration[]
out calibration[] - the calibration data from the battery.
Definition at line 302 of file ThermometerControl.c.
Referenced by ConMan_GetCalibration().
void ThermometerControl_SetConfig (uint8_t keyValue)
Sets a configuration value to the Thermometer
Parameters
in keyValue - the key/value pair with the configuration information
Definition at line 108 of file ThermometerControl.c.
Referenced by ConMan_SetSensorConfig().