ThermometerControl.c File Reference
Controls the thermometer driver.
#include <ProjectTypes.h>
*
#include `ThermometerControl.h`
*
#include <AdcManager.h>
*
#include <TimerTick.h>
*
#include <DataBuffer.h>
*
#include <SensorId.h>
*
#include <KeyValue.h>
*
#include <Assert.h>
*
Macros
#define THERMOMETER_USE_ADC
#define TIMEOUT_50HZ (20u)
#define TIMEOUT_10HZ (100u)
#define TIMEOUT_1HZ (1000u)
#define NUM_TEMP_CALIBRATION_BYTES (4u)
Functions
static void _thermometerDataCallBack (uint16_t data)
static __inline void _SetOverampling (void)
void ThermometerControl_Init (void)
void ThermometerControl_SetConfig (uint8_t keyValue)
void ThermometerControl_ReadCalibration (uint16_t maxCalibrationLength, uint16_t *actualCalibrationLength, uint8_t calibration[])
Variables
static bool _initialized = false
static ThermometerSampleRate_t _sampleRate = DEFAULT_THERMOMETER_SAMPLE_RATE
static ThermometerOversample_t _oversample = DEFAULT_THERMOMETER_OVERSAMPLE
static uint32_t _data = 0u
static uint16_t _numberAccumulated
static uint16_t _numberToAccumulate
Detailed Description
Controls the thermometer driver. Project 1814 IOLab Remote Sensor Application
Description Controls the thermometer driver and controls the configuration for it. This uses the thermometer from the Gyroscope IC.
Definition in file ThermometerControl.c.
Macro Definition Documentation
#define TIMEOUT_10HZ (100u)
defines how many milliseconds to wait between samples for a 10 Hz rate
Definition at line 56 of file ThermometerControl.c.
Referenced by ThermometerControl_SetConfig().
#define TIMEOUT_1HZ (1000u)
defines how many milliseconds to wait between samples for a 1 Hz rate
Definition at line 59 of file ThermometerControl.c.
Referenced by ThermometerControl_SetConfig().
#define TIMEOUT_50HZ (20u)
defines how many milliseconds to wait between samples for a 50 Hz rate
Definition at line 53 of file ThermometerControl.c.
Referenced by ThermometerControl_SetConfig().
Function Documentation
static __inline void _SetOverampling (void) [static]
Sets all the registers appropriately for the current oversampling or not- oversampling settings.
Definition at line 397 of file ThermometerControl.c.
Referenced by ThermometerControl_SetConfig().
static void _thermometerDataCallBack (uint16_t data) [static]
Takes the analog input data from internal thermometer and stores it in the proper location. This function is designed to be called every time there is data for the thermometer.
Parameters
in data - The sample from header pin 7 that should be stored in the proper location.
Definition at line 363 of file ThermometerControl.c.
Referenced by ThermometerControl_SetConfig().
void ThermometerControl_Init (void)
Initializes the thermometer controller.
Definition at line 95 of file ThermometerControl.c.
Referenced by ConMan_Init().
void ThermometerControl_ReadCalibration (uint16_t maxCalibrationLength, uint16_t * actualCalibrationLength, uint8_t calibration[])
Reads the calibration values from the thermometer.
Parameters
in maxCalibrationLength - the maximum number of bytes allocated for calibration[]
out actualCalibrationLength - the number of bytes of calibration data placed in calibration[]
out calibration[] - the calibration data from the battery.
Definition at line 302 of file ThermometerControl.c.
Referenced by ConMan_GetCalibration().
void ThermometerControl_SetConfig (uint8_t keyValue)
Sets a configuration value to the Thermometer
Parameters
in keyValue - the key/value pair with the configuration information
Definition at line 108 of file ThermometerControl.c.
Referenced by ConMan_SetSensorConfig().
Variable Documentation
uint32_t _data = 0u [static]
Stores the oversampled thermometer data
Definition at line 80 of file ThermometerControl.c.
Referenced by _thermometerDataCallBack().
bool _initialized = false [static]
tracks if the controller has been initialized
Definition at line 65 of file ThermometerControl.c.
ThermometerOversample_t _oversample = DEFAULT_THERMOMETER_OVERSAMPLE [static]
Stores the thermometer oversample setting
Definition at line 77 of file ThermometerControl.c.
Referenced by _SetOverampling(), and ThermometerControl_SetConfig().
ThermometerSampleRate_t _sampleRate = DEFAULT_THERMOMETER_SAMPLE_RATE [static]
Stores the thermometer sample rate setting
Definition at line 75 of file ThermometerControl.c.
Referenced by _SetOverampling(), and ThermometerControl_SetConfig().