TimerTick.c File Reference
The system tick.
#include <ProjectTypes.h>
*
#include <Device.h>
*
#include `TimerTick.h`
*
#include <Timer.h>
*
#include <EventQueue.h>
*
#include <Assert.h>
*
Data Structures
struct Timeout_t
Macros
#define MAX_NUM_TIMEOUTS (10u)
#define MAX_NUM_TICK_ISR (3u)
#define TIMER_SOURCE_FREQ_HZ (6000000ul)
#define TIMER_SOURCE_PERIODS_PER_TICK (((TIMER_SOURCE_FREQ_HZ * TIMERTICK_MSEC_PER_TICK) + 500u) / 1000u)
#define TIMER_COMPARE_VALUE (TIMER_SOURCE_PERIODS_PER_TICK - 1u)
Functions
static void _InsertTimeout (Timeout_t *const newTimeout)
__interrupt void _TimerA1CC0Isr (void)
void TimerTick_Init (void)
void TimerTick_ProcessTimeouts (void)
TickTimeoutHandle_t TimerTick_RequestTimeout (TickTimeoutType_t type, uint16_t milliseconds, TickTimeoutCallback_t callback)
void TimerTick_CancelTimeout (TickTimeoutHandle_t handle)
void TimerTick_CancelTimeoutFromCallback (void)
bool TimerTick_IsTimerActive (void)
uint16_t TimerTick_GetMaxActiveTimeouts (void)
TickIsrHandle_t TimerTick_RegisterTickIsr (TickIsrPointer_t tickIsr)
void TimerTick_UnregisterTickIsr (TickIsrHandle_t handle)
void TimerTick_EnableTickIsr (TickIsrHandle_t handle)
void TimerTick_DisableTickIsr (TickIsrHandle_t handle)
Variables
static volatile bool _timerActive = false
static uint16_t _tickCounter = 0u
static Timeout_t _timeoutList [MAX_NUM_TIMEOUTS]
static Timeout_t * _startOfList = NULL
static bool _isCallbackRunning = false
static TickIsrPointer_t _tickIsrList [MAX_NUM_TICK_ISR] = {NULL, NULL, NULL}
static bool _tickIsrActive [MAX_NUM_TICK_ISR] = {false, false, false}
static uint16_t _maxActiveTimeouts = 0u
Detailed Description
The system tick. Project 1814 IOLab Remote Sensor Application
Description The timer tick will provide a system tick for triggering periodic events.This module provides an interface to register an ISR that will be called every `tick` or to request a timeout after a given number of ticks.
Definition in file TimerTick.c.
Data Structure Documentation
struct Timeout_t
Structure used to store a timeout
Definition at line 49 of file TimerTick.c.
Data Fields
TickTimeoutCallback_t
callback
bool
isActive
struct Timeout *
next
uint16_t
periodTicks
uint16_t
tickCount
TickTimeoutType_t
type
Macro Definition Documentation
#define MAX_NUM_TICK_ISR (3u)
The maximum number of timer tick ISRs
Definition at line 37 of file TimerTick.c.
Referenced by TimerTick_DisableTickIsr(), TimerTick_EnableTickIsr(), TimerTick_RegisterTickIsr(), and TimerTick_UnregisterTickIsr().
#define MAX_NUM_TIMEOUTS (10u)
The maximum number of active timeouts
Definition at line 34 of file TimerTick.c.
Referenced by TimerTick_CancelTimeout(), TimerTick_Init(), and TimerTick_RequestTimeout().
#define TIMER_COMPARE_VALUE (TIMER_SOURCE_PERIODS_PER_TICK - 1u)
The value of the source clock compare module for the compare to occur at
Definition at line 46 of file TimerTick.c.
Referenced by _TimerA1CC0Isr(), and TimerTick_Init().
#define TIMER_SOURCE_FREQ_HZ (6000000ul)
Frequency (in Hz) of the timer source. Depends on the timer configuration performed in TimerTick_Init()
Definition at line 42 of file TimerTick.c.
#define TIMER_SOURCE_PERIODS_PER_TICK (((TIMER_SOURCE_FREQ_HZ * TIMERTICK_MSEC_PER_TICK) + 500u) / 1000u)
Number of timer source clock periods per timer tick (add 500 before /1000 to prevent fixed point rounding errors)
Definition at line 44 of file TimerTick.c.
Function Documentation
static void _InsertTimeout (Timeout_t *const newTimeout) [static]
Insert a new timeout structure into the list. List is sorted from smallest (earliest expiration time) to largest (latest expiration time).
Parameters
in newTimeout - New timeout to insert into the list.
Definition at line 415 of file TimerTick.c.
Referenced by TimerTick_ProcessTimeouts(), and TimerTick_RequestTimeout().
__interrupt void _TimerA1CC0Isr (void)
Interrupt service routine for the timer A1 compare/capture 0 interrupt. The interrupt flag is cleared in hardware when the ISR is called.
Increment tick counter and check timeout list for expired timeouts.
Note
Worst case ISR length depends on the time spent in the callbacks.
Definition at line 517 of file TimerTick.c.
void TimerTick_CancelTimeout (TickTimeoutHandle_t handle)
Cancel the given timeout. The timeout structure is deleted from the list.
Note
This function should not be called from within a timeout's callback function, as this could cause erros in the timeout list. Use TimerTick_CancelTimeoutFromCallback() instead.
Parameters
in handle - Handle of timeout to cancel
Definition at line 246 of file TimerTick.c.
Referenced by _PlaySequence(), _ProcessEvents_DEFAULT(), BarometerControl_SetConfig(), DigitalInputControl_SetConfig(), EncControl_SetConfig(), ThermometerControl_SetConfig(), and UiManager_StopSequence().
void TimerTick_CancelTimeoutFromCallback (void)
Cancel the timeout running this callback. The timeout structure is deleted from the list.
Definition at line 301 of file TimerTick.c.
Referenced by _PlaySequence(), and UiManager_StopSequence().
void TimerTick_DisableTickIsr (TickIsrHandle_t handle)
Disables the tick ISR with the given handle.
Parameters
in handle - Handle of tick ISR
Definition at line 402 of file TimerTick.c.
Referenced by TimerTick_RegisterTickIsr(), and TimerTick_UnregisterTickIsr().
void TimerTick_EnableTickIsr (TickIsrHandle_t handle)
Enables the tick ISR with the given handle. The timer interrupt flag is cleared first, so the ISR will not be called for up to one tick period.
Parameters
in handle - Handle of tick ISR
Definition at line 390 of file TimerTick.c.
Referenced by CommProtocol_Init(), and PushButtonControl_Init().
uint16_t TimerTick_GetMaxActiveTimeouts (void)
Returns
The maximum number of timeouts that are active at one time.
Definition at line 330 of file TimerTick.c.
void TimerTick_Init (void)
Initializes the timer tick module. Uses Timer A1 CC0 with timer in continuous mode.
Definition at line 91 of file TimerTick.c.
Referenced by main().
bool TimerTick_IsTimerActive (void)
Get timer active status and reset status.
Returns
The timer interrupt is active or not.
Definition at line 318 of file TimerTick.c.
Referenced by main().
void TimerTick_ProcessTimeouts (void)
Processes the timeouts. This function must be called at a regular rate to process the timer tick timeouts.
Definition at line 116 of file TimerTick.c.
Referenced by _ProcessEvents_DEFAULT().
TickIsrHandle_t TimerTick_RegisterTickIsr (TickIsrPointer_t tickIsr)
Register a tick ISR, that is an ISR that fires once every tick.
Parameters
in tickIsr - ISR to register.
Returns
Handle of tick ISR. If handle is negative, registration failed.
Definition at line 342 of file TimerTick.c.
Referenced by CommProtocol_Init(), and PushButtonControl_Init().
TickTimeoutHandle_t TimerTick_RequestTimeout (TickTimeoutType_t type, uint16_t milliseconds, TickTimeoutCallback_t callback)
Request a timeout. Adds a timeout structure to a sorted list. List is sorted from smallest (earliest expiration time) to largest (latest expiration time).
Note
The resolution is equal to TIMERTICK_RESOLUTION_MSEC.
Parameters
in type - Type of timeout
in milliseconds - Length of timeout in milliseconds
in callback - Pointer to the function called when the timeout expires
Returns
A handle to the requested timeout.
Definition at line 174 of file TimerTick.c.
Referenced by _ProcessEvents_DEFAULT(), _ProcessEvents_SELF_TEST(), BarometerControl_SetConfig(), DigitalInputControl_SetConfig(), EncControl_SetConfig(), LedControl_Init(), main(), SelfTest_Process(), ThermometerControl_SetConfig(), and UiManager_PlaySequence().
void TimerTick_UnregisterTickIsr (TickIsrHandle_t handle)
Unregister the tick ISR with the given handle.
Parameters
in handle - Handle of tick ISR
Definition at line 376 of file TimerTick.c.
Variable Documentation
bool _isCallbackRunning = false [static]
Tracks if a callback is currently being run
Definition at line 73 of file TimerTick.c.
Referenced by TimerTick_CancelTimeout(), TimerTick_CancelTimeoutFromCallback(), and TimerTick_ProcessTimeouts().
uint16_t _maxActiveTimeouts = 0u [static]
Tracks the maximum number of timeouts that are active at one time
Definition at line 81 of file TimerTick.c.
Referenced by TimerTick_GetMaxActiveTimeouts(), and TimerTick_RequestTimeout().
Timeout_t* _startOfList = NULL [static]
Tracks the first item in the timeout list
Definition at line 71 of file TimerTick.c.
Referenced by _InsertTimeout(), TimerTick_CancelTimeout(), and TimerTick_ProcessTimeouts().
uint16_t _tickCounter = 0u [static]
Counts each tick that occurs. Does not need to be volatile as the timer tick interrupt is always disabled when it is accessed.
Definition at line 66 of file TimerTick.c.
Referenced by _InsertTimeout(), and TimerTick_ProcessTimeouts().
bool _tickIsrActive[MAX_NUM_TICK_ISR] = {false, false, false} [static]
Stores the active state of the ISR function pointers
Definition at line 78 of file TimerTick.c.
Referenced by _TimerA1CC0Isr(), TimerTick_DisableTickIsr(), and TimerTick_EnableTickIsr().
TickIsrPointer_t _tickIsrList[MAX_NUM_TICK_ISR] = {NULL, NULL, NULL} [static]
Stores the tick ISR function pointers
Definition at line 76 of file TimerTick.c.
Referenced by _TimerA1CC0Isr(), TimerTick_RegisterTickIsr(), and TimerTick_UnregisterTickIsr().
Timeout_t _timeoutList[MAX_NUM_TIMEOUTS] [static]
Storage for the timeout structure list
Definition at line 69 of file TimerTick.c.
volatile bool _timerActive = false [static]
Indicates a timer interrupt is running
Definition at line 61 of file TimerTick.c.
Referenced by _TimerA1CC0Isr(), and TimerTick_IsTimerActive().