TimerTick.h File Reference
Timer Tick utility header file.
Macros
#define TIMERTICK_MSEC_PER_TICK (10u)
#define TIMERTICK_RESOLUTION_MSEC (TIMERTICK_MSEC_PER_TICK)
Typedefs
typedef uint16_t TickTimeoutHandle_t
typedef void(* TickTimeoutCallback_t)(void)
typedef int16_t TickIsrHandle_t
typedef void(* TickIsrPointer_t)(void)
Enumerations
enum TickTimeoutType_t {
*
TickTimeoutType_SINGLE,
*
TickTimeoutType_REPEAT
 }
Functions
void TimerTick_Init (void)
void TimerTick_ProcessTimeouts (void)
TickTimeoutHandle_t TimerTick_RequestTimeout (TickTimeoutType_t type, uint16_t milliseconds, TickTimeoutCallback_t callback)
void TimerTick_CancelTimeout (TickTimeoutHandle_t handle)
void TimerTick_CancelTimeoutFromCallback (void)
bool TimerTick_IsTimerActive (void)
uint16_t TimerTick_GetMaxActiveTimeouts (void)
TickIsrHandle_t TimerTick_RegisterTickIsr (TickIsrPointer_t tickIsr)
void TimerTick_UnregisterTickIsr (TickIsrHandle_t handle)
void TimerTick_EnableTickIsr (TickIsrHandle_t handle)
void TimerTick_DisableTickIsr (TickIsrHandle_t handle)
Detailed Description
Timer Tick utility header file. Project 1814 IOLab Remote Sensor Application
Description The timer tick will provide a system tick for triggering periodic events.
Definition in file TimerTick.h.
Macro Definition Documentation
#define TIMERTICK_MSEC_PER_TICK (10u)
Defines the number of milliseconds per timer tick. Value based on timer setup. Must be greater than 2 to convert from milliseconds to ticks without overflowing.
Definition at line 30 of file TimerTick.h.
Referenced by _HandleRfStatusISR(), _ProcessPushButtons(), and TimerTick_RequestTimeout().
#define TIMERTICK_RESOLUTION_MSEC (TIMERTICK_MSEC_PER_TICK)
Defines the resolution (in milliseconds) of the timer tick timeout values.
Definition at line 32 of file TimerTick.h.
Referenced by TimerTick_RequestTimeout().
Typedef Documentation
typedef int16_t TickIsrHandle_t
Definition of a tick ISR handle
Definition at line 47 of file TimerTick.h.
typedef void(* TickIsrPointer_t)(void)
Defines a tick ISR function pointer
Definition at line 49 of file TimerTick.h.
typedef void(* TickTimeoutCallback_t)(void)
Defines a tick timeout callback function pointer
Definition at line 44 of file TimerTick.h.
typedef uint16_t TickTimeoutHandle_t
Definition of a tick timeout handle
Definition at line 42 of file TimerTick.h.
Enumeration Type Documentation
enum TickTimeoutType_t
Defines the possible types of timeouts
Definition at line 35 of file TimerTick.h.
Function Documentation
void TimerTick_CancelTimeout (TickTimeoutHandle_t handle)
Cancel the given timeout. The timeout structure is deleted from the list.
Note
This function should not be called from within a timeout's callback function, as this could cause erros in the timeout list. Use TimerTick_CancelTimeoutFromCallback() instead.
Parameters
in handle - Handle of timeout to cancel
Definition at line 246 of file TimerTick.c.
Referenced by _PlaySequence(), _ProcessEvents_DEFAULT(), BarometerControl_SetConfig(), DigitalInputControl_SetConfig(), EncControl_SetConfig(), ThermometerControl_SetConfig(), and UiManager_StopSequence().
void TimerTick_CancelTimeoutFromCallback (void)
Cancel the timeout running this callback. The timeout structure is deleted from the list.
Definition at line 301 of file TimerTick.c.
Referenced by _PlaySequence(), and UiManager_StopSequence().
void TimerTick_DisableTickIsr (TickIsrHandle_t handle)
Disables the tick ISR with the given handle.
Parameters
in handle - Handle of tick ISR
Definition at line 402 of file TimerTick.c.
Referenced by TimerTick_RegisterTickIsr(), and TimerTick_UnregisterTickIsr().
void TimerTick_EnableTickIsr (TickIsrHandle_t handle)
Enables the tick ISR with the given handle. The timer interrupt flag is cleared first, so the ISR will not be called for up to one tick period.
Parameters
in handle - Handle of tick ISR
Definition at line 390 of file TimerTick.c.
Referenced by CommProtocol_Init(), and PushButtonControl_Init().
uint16_t TimerTick_GetMaxActiveTimeouts (void)
Returns
The maximum number of timeouts that are active at one time.
Definition at line 330 of file TimerTick.c.
void TimerTick_Init (void)
Initializes the timer tick module. Uses Timer A1 CC0 with timer in continuous mode.
Definition at line 91 of file TimerTick.c.
Referenced by main().
bool TimerTick_IsTimerActive (void)
Get timer active status and reset status.
Returns
The timer interrupt is active or not.
Definition at line 318 of file TimerTick.c.
Referenced by main().
void TimerTick_ProcessTimeouts (void)
Processes the timeouts. This function must be called at a regular rate to process the timer tick timeouts.
Definition at line 116 of file TimerTick.c.
Referenced by _ProcessEvents_DEFAULT().
TickIsrHandle_t TimerTick_RegisterTickIsr (TickIsrPointer_t tickIsr)
Register a tick ISR, that is an ISR that fires once every tick.
Parameters
in tickIsr - ISR to register.
Returns
Handle of tick ISR. If handle is negative, registration failed.
Definition at line 342 of file TimerTick.c.
Referenced by CommProtocol_Init(), and PushButtonControl_Init().
TickTimeoutHandle_t TimerTick_RequestTimeout (TickTimeoutType_t type, uint16_t milliseconds, TickTimeoutCallback_t callback)
Request a timeout. Adds a timeout structure to a sorted list. List is sorted from smallest (earliest expiration time) to largest (latest expiration time).
Note
The resolution is equal to TIMERTICK_RESOLUTION_MSEC.
Parameters
in type - Type of timeout
in milliseconds - Length of timeout in milliseconds
in callback - Pointer to the function called when the timeout expires
Returns
A handle to the requested timeout.
Definition at line 174 of file TimerTick.c.
Referenced by _ProcessEvents_DEFAULT(), _ProcessEvents_SELF_TEST(), BarometerControl_SetConfig(), DigitalInputControl_SetConfig(), EncControl_SetConfig(), LedControl_Init(), main(), SelfTest_Process(), ThermometerControl_SetConfig(), and UiManager_PlaySequence().
void TimerTick_UnregisterTickIsr (TickIsrHandle_t handle)
Unregister the tick ISR with the given handle.
Parameters
in handle - Handle of tick ISR
Definition at line 376 of file TimerTick.c.