Timer.c File Reference
Hardware timer module.
#include <ProjectTypes.h>
*
#include <Device.h>
*
#include `Timer.h`
*
#include <Assert.h>
*
#include <Debug.h>
*
#include <Serial.h>
*
Macros
#define TIMER_A0_NUM_CC_MODULES (5u)
#define TIMER_A1_NUM_CC_MODULES (3u)
#define TIMER_A2_NUM_CC_MODULES (3u)
#define TIMER_B0_NUM_CC_MODULES (7u)
Functions
void Timer_A0_Configure (TimerSource_t source, TimerDivider_t divider, TimerRunMode_t runMode, uint16_t value)
void Timer_A0CCX_Configure (TimerA0CC_t module, uint16_t config, uint16_t value)
void Timer_A1_Configure (TimerSource_t source, TimerDivider_t divider, TimerRunMode_t runMode, uint16_t value)
void Timer_A1CCX_Configure (TimerA1CC_t module, uint16_t config, uint16_t value)
void Timer_A2_Configure (TimerSource_t source, TimerDivider_t divider, TimerRunMode_t runMode, uint16_t value)
void Timer_A2CCX_Configure (TimerA2CC_t module, uint16_t config, uint16_t value)
void Timer_B0_Configure (TimerSource_t source, TimerDivider_t divider, TimerCounterLength_t counterLength, TimerRunMode_t runMode, uint16_t value)
void Timer_B0CCX_Configure (TimerB0CC_t module, uint16_t config, uint16_t value)
Detailed Description
Hardware timer module. Project 1814 IOLab Remote Sensor Application
Description Provides functions to setup the hardware timers. The control of the timers and their interrupts are handled using the macros defined in the header file.
Definition in file Timer.c.
Macro Definition Documentation
#define TIMER_A0_NUM_CC_MODULES (5u)
Number of compare/capture modules within timer A0
Definition at line 35 of file Timer.c.
Referenced by Timer_A0CCX_Configure().
#define TIMER_A1_NUM_CC_MODULES (3u)
Number of compare/capture modules within timer A1
Definition at line 37 of file Timer.c.
Referenced by Timer_A1CCX_Configure().
#define TIMER_A2_NUM_CC_MODULES (3u)
Number of compare/capture modules within timer A2
Definition at line 39 of file Timer.c.
Referenced by Timer_A2CCX_Configure().
#define TIMER_B0_NUM_CC_MODULES (7u)
Number of compare/capture modules within timer B0
Definition at line 41 of file Timer.c.
Referenced by Timer_B0CCX_Configure().
Function Documentation
void Timer_A0_Configure (TimerSource_t source, TimerDivider_t divider, TimerRunMode_t runMode, uint16_t value)
Configure timer A0 using the given parameters. If the selected run mode is either Up or Up/Down, the compare/capture 0 module is also configured and the timer counts to value. If the selected run mode is Continuous, the timer counts up to 2^16-1. The timer is not started.
Parameters
in source - Timer source
in divider - Timer divider
in runMode - Timer mode
in value - Value for timer to count up to
Definition at line 57 of file Timer.c.
Referenced by _SetupTimerConfig().
void Timer_A0CCX_Configure (TimerA0CC_t module, uint16_t config, uint16_t value)
Configure a timer A0 compare/capture (CC) module.
Parameters
in module - Compare/capture module to configure
in config - Configuration value to set control register to
in value - Initial compare/capture value
Definition at line 125 of file Timer.c.
Referenced by _SetupTimerConfig().
void Timer_A1_Configure (TimerSource_t source, TimerDivider_t divider, TimerRunMode_t runMode, uint16_t value)
Configure timer A1 using the given parameters. If the selected run mode is either Up or Up/Down, the compare/capture 0 module is also configured and the timer counts to value. If the selected run mode is Continuous, the timer counts up to 2^16-1. The timer is not started.
Parameters
in source - Timer source
in divider - Timer divider
in runMode - Timer mode
in value - Value for timer to count up to
Definition at line 167 of file Timer.c.
Referenced by TimerTick_Init().
void Timer_A1CCX_Configure (TimerA1CC_t module, uint16_t config, uint16_t value)
Configure a timer A1 compare/capture (CC) module.
Parameters
in module - Compare/capture module to configure
in config - Configuration value to set control register to
in value - Initial compare/capture value
Definition at line 235 of file Timer.c.
void Timer_A2_Configure (TimerSource_t source, TimerDivider_t divider, TimerRunMode_t runMode, uint16_t value)
Configure timer A2 using the given parameters. If the selected run mode is either Up or Up/Down, the compare/capture 0 module is also configured and the timer counts to value. If the selected run mode is Continuous, the timer counts up to 2^16-1. The timer is not started.
Parameters
in source - Timer source
in divider - Timer divider
in runMode - Timer mode
in value - Value for timer to count up to
Definition at line 273 of file Timer.c.
Referenced by Encoder_Init().
void Timer_A2CCX_Configure (TimerA2CC_t module, uint16_t config, uint16_t value)
Configure a timer A2 compare/capture (CC) module.
Parameters
in module - Compare/capture module to configure
in config - Configuration value to set control register to
in value - Initial compare/capture value
Definition at line 341 of file Timer.c.
Referenced by Encoder_Init().
void Timer_B0_Configure (TimerSource_t source, TimerDivider_t divider, TimerCounterLength_t counterLength, TimerRunMode_t runMode, uint16_t value)
Configure timer B0 using the given parameters. If the selected run mode is either Up or Up/Down, the compare/capture 0 module is also configured and the timer counts to value. If the selected run mode is Continuous, a range of either 16, 12, 10, or 8 bits is selected. The timer is not started.
Parameters
in source - Timer source
in divider - Timer divider
in counterLength - Length of timer counter
in runMode - Timer mode
in value - Value for timer to count up to
Definition at line 381 of file Timer.c.
Referenced by Pwm_Init(), and Pwm_SetFrequency().
void Timer_B0CCX_Configure (TimerB0CC_t module, uint16_t config, uint16_t value)
Configure a timer B0 compare/capture (CC) module.
Parameters
in module - Compare/capture module to configure
in config - Configuration value to set control register to
in value - Initial compare/capture value
Definition at line 453 of file Timer.c.
Referenced by Pwm_Enable(), and Pwm_SetDuty().