Uart.h File Reference
UART module header.
Data Structures
struct UartPortConfig_t
Macros
#define UART_ENABLE_PORT_0
#define UART_ENABLE_PORT_1
Enumerations
enum UartError_t {
*
UartError_OK,
*
UartError_NO_DATA,
*
UartError_BUFFER_FULL
 }
enum UartPort_t {
*
UartPort_0 = 0u,
*
UartPort_1 = 1u
 }
enum UartBaudRate_t {
*
UartBaudRate_9600,
*
UartBaudRate_19200,
*
UartBaudRate_38400,
*
UartBaudRate_57600,
*
UartBaudRate_115200,
*
UartBaudRate_230400
 }
enum UartParity_t {
*
UartParity_NONE,
*
UartParity_ODD,
*
UartParity_EVEN
 }
enum UartEndieness_t {
*
UartEndieness_MsbFirst,
*
UartEndieness_LsbFirst
 }
enum UartStopBit_t {
*
UartStopBit_ONE,
*
UartStopBit_TWO
 }
Functions
void Uart_Init (UartPort_t port, const UartPortConfig_t *config)
void Uart_Open (UartPort_t port)
void Uart_Close (UartPort_t port)
bool Uart_IsPortOpen (UartPort_t port)
void Uart_EnableReceive (UartPort_t port)
void Uart_DisableReceive (UartPort_t port)
void Uart_WriteByteBlocking (UartPort_t port, uint8_t byte)
void Uart_WriteByteBlockingNoAssert (UartPort_t port, uint8_t byte)
void Uart_WriteByteArrayBlocking (UartPort_t port, uint16_t numToWrite, const uint8_t source[])
void Uart_WriteByteArrayBlockingNoAssert (UartPort_t port, uint16_t numToWrite, const uint8_t source[])
void Uart_WriteByteHexBlocking (UartPort_t port, uint8_t byte)
void Uart_WriteByteArrayHexBlocking (UartPort_t port, uint16_t numToWrite, const uint8_t source[])
void Uart_WriteStringBlocking (UartPort_t port, const char_t string[])
UartError_t Uart_WriteByte (UartPort_t port, uint8_t byte)
UartError_t Uart_WriteByteArray (UartPort_t port, uint16_t numToWrite, const uint8_t source[])
UartError_t Uart_WriteByteHex (UartPort_t port, uint8_t byte)
void Uart_WriteString (UartPort_t port, const char_t string[])
UartError_t Uart_ReadByte (UartPort_t port, uint8_t *destinationByte)
UartError_t Uart_ReadByteArray (UartPort_t port, uint16_t numToRead, uint8_t destination[], uint16_t *numRead)
bool Uart_AreBytesAvailable (UartPort_t port)
bool Uart_AreBytesAvailableAnyOpenPort (void)
Detailed Description
UART module header. Project 1814 IOLab Remote Sensor Application
Description This module provides functions and macros for configuring the UART and transmitting and receiving data over that port.
Definition in file Uart.h.
Data Structure Documentation
struct UartPortConfig_t
Defines the UART port configuration structure
Definition at line 90 of file Uart.h.
Data Fields
UartBaudRate_t
baudRate
bool
enableIrda
UartEndieness_t
endieness
UartParity_t
parity
UartStopBit_t
stopBits
Macro Definition Documentation
#define UART_ENABLE_PORT_0
If defined, UART port 0 is enabled.
Definition at line 29 of file Uart.h.
#define UART_ENABLE_PORT_1
If defined, UART port 1 is enabled.
Definition at line 34 of file Uart.h.
Enumeration Type Documentation
enum UartBaudRate_t
The possible baud rates when configuring a UART port
Definition at line 57 of file Uart.h.
enum UartEndieness_t
The possible endieness options for a UART port
Definition at line 76 of file Uart.h.
enum UartError_t
Enumeration type for UART module errors.
Definition at line 38 of file Uart.h.
enum UartParity_t
The possible parity options when configuring a UART port
Definition at line 68 of file Uart.h.
enum UartPort_t
The available UART ports
Definition at line 46 of file Uart.h.
enum UartStopBit_t
The possible stop bit options for a UART port
Definition at line 83 of file Uart.h.
Function Documentation
bool Uart_AreBytesAvailable (UartPort_t port)
Determines if bytes are available in the UART receive buffer.
Parameters
in port - Selected UART port.
Returns
True if bytes are available, False is the receive buffer is empty.
Definition at line 1161 of file Uart.c.
Referenced by Serial_ProcessReceivedBytes().
bool Uart_AreBytesAvailableAnyOpenPort (void)
Determines if bytes are available in the UART receive buffer for any of the open UART ports.
Returns
True if bytes are available, False is the receive buffers are empty.
Definition at line 1185 of file Uart.c.
Referenced by main().
void Uart_Close (UartPort_t port)
Close the UART port.
Parameters
in port - Selected UART port.
Definition at line 364 of file Uart.c.
Referenced by Serial_Close().
void Uart_DisableReceive (UartPort_t port)
Disable the receive interrupt for the UART port.
Parameters
in port - Selected UART port.
Note
Port must be open before disabling the receives.
Definition at line 424 of file Uart.c.
void Uart_EnableReceive (UartPort_t port)
Enable the receive interrupt for the UART port.
Parameters
in port - Selected UART port.
Note
Port must be open before enabling the receives.
Definition at line 400 of file Uart.c.
Referenced by Serial_Open().
void Uart_Init (UartPort_t port, const UartPortConfig_t * config)
Initialize the selected UART module.
Parameters
in port - Selected UART port.
in config - Pointer to the configuration information for the port.
Definition at line 140 of file Uart.c.
Referenced by Serial_Init().
bool Uart_IsPortOpen (UartPort_t port)
Determines if a UART port is open.
Parameters
in port - Selected UART port.
Returns
True if the port is open. Otherwise, false.
Definition at line 388 of file Uart.c.
Referenced by Serial_Open().
void Uart_Open (UartPort_t port)
Open the UART port. You should not open the same UART port more than once.
Parameters
in port - Selected UART port.
Definition at line 329 of file Uart.c.
Referenced by Serial_Open().
UartError_t Uart_ReadByte (UartPort_t port, uint8_t * destinationByte)
Reads one byte out of the receive buffer if available.
Parameters
in port - Selected UART port.
out destinationByte - Pointer to where the read byte should be stored.
Returns
If no bytes are available, UartError_NO_DATA. Otherwise, UartError_OK.
Definition at line 1073 of file Uart.c.
Referenced by Serial_ProcessReceivedBytes().
UartError_t Uart_ReadByteArray (UartPort_t port, uint16_t numToRead, uint8_t destination[], uint16_t * numRead)
Read bytes out of the receive buffer.
Parameters
in port - Selected UART port.
in numToRead - Number of bytes to read if available.
out destination - Pointer to where the read bytes should be stored.
out numRead - Pointer where the number of bytes read out of the receive buffer should be stored.
Returns
If no bytes are available, UartError_NO_DATA. Otherwise, UartError_OK.
Definition at line 1111 of file Uart.c.
UartError_t Uart_WriteByte (UartPort_t port, uint8_t byte)
Transmit a byte via the UART. The byte is loaded into the transmit buffer to be transmitted using the UART Tx interrupt.
Parameters
in port - Selected UART port.
in byte - Byte to transmit.
Returns
If the buffer does not have enough space available, UartError_BUFFER_FULL. Otherwise, UartError_OK.
Definition at line 817 of file Uart.c.
Referenced by Serial_SendPacket(), Serial_SendString(), Serial_SendString3Numbers(), Serial_SendStringNumber(), and Serial_SendStringNumberU32().
UartError_t Uart_WriteByteArray (UartPort_t port, uint16_t numToWrite, const uint8_t source[])
Transmit a byte array via the UART. The byte array is loaded into the transmit buffer to be transmitted using the UART Tx interrupt.
Parameters
in port - Selected UART port.
in numToWrite - Number of bytes to transmit.
in source - Pointer to byte array to transmit.
Returns
If the buffer does not have enough space available, UartError_BUFFER_FULL. Otherwise, UartError_OK.
Definition at line 861 of file Uart.c.
Referenced by Serial_SendPacket(), Serial_SendString(), Serial_SendString3Numbers(), Serial_SendStringNumber(), and Serial_SendStringNumberU32().
void Uart_WriteByteArrayBlocking (UartPort_t port, uint16_t numToWrite, const uint8_t source[])
Transmit a byte array via the UART. This function blocks until the entire buffer has been written to the UART.
Parameters
in port - Selected UART port.
in numToWrite - Number of bytes to transmit.
in source - Pointer to byte array to transmit.
Definition at line 510 of file Uart.c.
Referenced by Serial_SendStringBlocking(), and Serial_SendStringBlockingNoAssert().
void Uart_WriteByteArrayBlockingNoAssert (UartPort_t port, uint16_t numToWrite, const uint8_t source[])
Transmit a byte array via the UART. This function blocks until the entire buffer has been written to the UART.
Note
No asserts are used.
Parameters
in port - Selected UART port.
in numToWrite - Number of bytes to transmit.
in source - Pointer to byte array to transmit.
Definition at line 533 of file Uart.c.
Referenced by Uart_WriteByteArrayBlocking().
void Uart_WriteByteArrayHexBlocking (UartPort_t port, uint16_t numToWrite, const uint8_t source[])
Transmit a byte array via the UART as a hex string. A hyphen is inserted between each byte. This function blocks until the entire hex string has been written to the UART.
Parameters
in port - Selected UART port.
in numToWrite - Number of bytes to transmit.
in source - Pointer to byte array to transmit as a hex string
Definition at line 661 of file Uart.c.
void Uart_WriteByteBlocking (UartPort_t port, uint8_t byte)
Transmit a byte via the UART. This function blocks until the byte has been written to the UART.
Parameters
in port - Selected UART port.
in byte - Byte to transmit.
Definition at line 441 of file Uart.c.
Referenced by Serial_SendStringBlocking(), and Serial_SendStringBlockingNoAssert().
void Uart_WriteByteBlockingNoAssert (UartPort_t port, uint8_t byte)
Transmit a byte via the UART. This function blocks until the byte has been written to the UART.
Note
No asserts are used.
Parameters
in port - Selected UART port.
in byte - Byte to transmit.
Definition at line 461 of file Uart.c.
Referenced by Uart_WriteByteBlocking().
UartError_t Uart_WriteByteHex (UartPort_t port, uint8_t byte)
Transmit a byte via the UART in hex format. The byte (in hex format) is loaded into the transmit buffer to be transmitted using the UART Tx interrupt.
Parameters
in port - Selected UART port.
in byte - Byte to transmit in hex.
Returns
If the buffer does not have enough space available, UartError_BUFFER_FULL. Otherwise, UartError_OK.
Definition at line 923 of file Uart.c.
Referenced by Serial_SendString3Numbers(), Serial_SendStringNumber(), and Serial_SendStringNumberU32().
void Uart_WriteByteHexBlocking (UartPort_t port, uint8_t byte)
Transmit a byte via the UART as a hex string. This function blocks until the entire hex string has been written to the UART.
Parameters
in port - Selected UART port.
in byte - Byte to transmit as a hex string.
Definition at line 586 of file Uart.c.
void Uart_WriteString (UartPort_t port, const char_t string[])
Transmit a null-terminated string via the UART. The string is loaded into the transmit buffer to be transmitted using the UART Tx interrupt.
Only the number of characters that will fit into the buffer will be loaded. All other characters in the string will be discarded. This means that the string may not be sent if the buffer is full.
Parameters
in port - Selected UART port.
in string - String to transmit
Definition at line 1004 of file Uart.c.
void Uart_WriteStringBlocking (UartPort_t port, const char_t string[])
Transmit a null-terminated string via the UART. This function blocks until the entire string has been written to the UART.
Parameters
in port - Selected UART port.
in string - String to transmit.
Definition at line 755 of file Uart.c.