Version.c File Reference
Version information about the device and firmware.
#include <ProjectTypes.h>
*
#include `Version.h`
*
#include <Device.h>
*
#include <Assert.h>
*
Macros
#define VERSION_MAJOR (VERSION_ARRAY[6u])
#define VERSION_MINOR (VERSION_ARRAY[7u])
Functions
uint32_t WaferId (void)
uint16_t WaferXPosition (void)
uint16_t WaferYPosition (void)
uint16_t DeviceId (void)
uint8_t HardwareRevisionMicro (void)
uint8_t FirmwareRevisionMicro (void)
uint16_t UserFirmwareVersion (void)
const char * UserFirmwareVersionString (void)
uint16_t UserHardwareVersion (void)
Variables
static const uint8_t VERSION_ARRAY [8u] = { 0xAA, 0xBB, 0xCC, 0xDD, 0xEE, 0xFF, USER_FIRMWARE_MAJOR, USER_FIRMWARE_MINOR }
Detailed Description
Version information about the device and firmware. Project 1814 IOLab Remote Sensor Application
Description The version module stores version information about the device and the firmware.
Definition in file Version.c.
Macro Definition Documentation
#define VERSION_MAJOR (VERSION_ARRAY[6u])
define macros to use the version number from the version number array so that the array doesn't get left out by the linker
Definition at line 38 of file Version.c.
Function Documentation
uint16_t DeviceId (void)
Reads the 2 byte Device Id from the microcontroller.
MSP430F5329 should be 0x811B MSP430F5328 should be 0x811A MSP430F5327 should be 0x8119 MSP430F5326 should be 0x8118 MSP430F5325 should be 0x8117 MSP430F5324 should be 0x8116
Returns
The 2-byte Device Id of the microcontroller.
Definition at line 89 of file Version.c.
Referenced by _HandleHumanVerCommand().
uint8_t FirmwareRevisionMicro (void)
Reads the microcontroller firmware revision.
Returns
The 1-byte firmware revision.
Definition at line 111 of file Version.c.
Referenced by _HandleHumanVerCommand().
uint8_t HardwareRevisionMicro (void)
Reads the microcontroller hardware revision.
Returns
The 1-byte hardware revision.
Definition at line 100 of file Version.c.
Referenced by _HandleHumanVerCommand().
uint16_t UserFirmwareVersion (void)
Reads the 2 byte firmware version of the code. The high byte is the major revision version and the low byte is the minor revision version.
Returns
The 2-byte firmware version.
Definition at line 123 of file Version.c.
uint16_t UserHardwareVersion (void)
Reads the 2 byte hardware version of the PCB. The high byte is the major revision version and the low byte is the minor revision version.
Returns
The 2-byte hardware version.
Definition at line 146 of file Version.c.
uint32_t WaferId (void)
Reads the 4 byte Wafer Id from the microcontroller.
Returns
The 4-byte Wafer Id of the microcontroller.
Definition at line 49 of file Version.c.
Referenced by _HandleHumanVerCommand().
uint16_t WaferXPosition (void)
Reads the 2 byte Wafer X Position from the microcontroller.
Returns
The 2-byte Wafer X Position of the microcontroller.
Definition at line 60 of file Version.c.
uint16_t WaferYPosition (void)
Reads the 2 byte Wafer Y position from the microcontroller.
Returns
The 2-byte Wafer Y position from the microcontroller.
Definition at line 71 of file Version.c.
Variable Documentation
const uint8_t VERSION_ARRAY[8u] = { 0xAA, 0xBB, 0xCC, 0xDD, 0xEE, 0xFF, USER_FIRMWARE_MAJOR, USER_FIRMWARE_MINOR } [static]
Define a local array that has a fixed sequence of bytes before the version number so that the version number can be located in the binary code image
Definition at line 33 of file Version.c.