Version.h File Reference
Version header.
Macros
#define USER_FIRMWARE_MAJOR (0x01u)
#define USER_FIRMWARE_MINOR (0x10u)
#define USER_FIRMWARE_VERSION ((USER_FIRMWARE_MAJOR<<8)+USER_FIRMWARE_MINOR)
#define USER_HARDWARE_VERSION (0x0003u)
Functions
uint32_t WaferId (void)
uint16_t WaferXPosition (void)
uint16_t WaferYPosition (void)
uint16_t DeviceId (void)
uint8_t HardwareRevisionMicro (void)
uint8_t FirmwareRevisionMicro (void)
uint16_t UserFirmwareVersion (void)
const char * UserFirmwareVersionString (void)
uint16_t UserHardwareVersion (void)
Detailed Description
Version header. Project 1814 IOLab Remote Sensor Application
Description The version module provides access to version information such as the firmware revision number and the DIE ID.
Definition in file Version.h.
Macro Definition Documentation
#define USER_FIRMWARE_MAJOR (0x01u)
Defines the major version of the firmware
Definition at line 27 of file Version.h.
Referenced by _HandleGetStatusPacket().
#define USER_FIRMWARE_MINOR (0x10u)
Defines the minor version of the firmware
Definition at line 29 of file Version.h.
Referenced by _HandleGetStatusPacket().
#define USER_FIRMWARE_VERSION ((USER_FIRMWARE_MAJOR<<8)+USER_FIRMWARE_MINOR)
Defines the user firmware version with the high byte the major release and the low byte the minor release.
Definition at line 33 of file Version.h.
Referenced by UserFirmwareVersion().
#define USER_HARDWARE_VERSION (0x0003u)
Defines the user hardware version with the high byte the major release and the low byte the minor release.
Definition at line 38 of file Version.h.
Referenced by _HandleHumanVerCommand(), and UserHardwareVersion().
Function Documentation
uint16_t DeviceId (void)
Reads the 2 byte Device Id from the microcontroller.
MSP430F5329 should be 0x811B MSP430F5328 should be 0x811A MSP430F5327 should be 0x8119 MSP430F5326 should be 0x8118 MSP430F5325 should be 0x8117 MSP430F5324 should be 0x8116
Returns
The 2-byte Device Id of the microcontroller.
Definition at line 89 of file Version.c.
Referenced by _HandleHumanVerCommand().
uint8_t FirmwareRevisionMicro (void)
Reads the microcontroller firmware revision.
Returns
The 1-byte firmware revision.
Definition at line 111 of file Version.c.
Referenced by _HandleHumanVerCommand().
uint8_t HardwareRevisionMicro (void)
Reads the microcontroller hardware revision.
Returns
The 1-byte hardware revision.
Definition at line 100 of file Version.c.
Referenced by _HandleHumanVerCommand().
uint16_t UserFirmwareVersion (void)
Reads the 2 byte firmware version of the code. The high byte is the major revision version and the low byte is the minor revision version.
Returns
The 2-byte firmware version.
Definition at line 123 of file Version.c.
uint16_t UserHardwareVersion (void)
Reads the 2 byte hardware version of the PCB. The high byte is the major revision version and the low byte is the minor revision version.
Returns
The 2-byte hardware version.
Definition at line 146 of file Version.c.
uint32_t WaferId (void)
Reads the 4 byte Wafer Id from the microcontroller.
Returns
The 4-byte Wafer Id of the microcontroller.
Definition at line 49 of file Version.c.
Referenced by _HandleHumanVerCommand().
uint16_t WaferXPosition (void)
Reads the 2 byte Wafer X Position from the microcontroller.
Returns
The 2-byte Wafer X Position of the microcontroller.
Definition at line 60 of file Version.c.
uint16_t WaferYPosition (void)
Reads the 2 byte Wafer Y position from the microcontroller.
Returns
The 2-byte Wafer Y position from the microcontroller.
Definition at line 71 of file Version.c.